### ISSUE TITLE
Add “Combining reducers” recipe

### ISSUE THREAD

**Issue by gaearon** [reactjs/redux#1018]
Anybody wants to write this?

It should explain:

1. You don't have to use `combineReducers()`, and you can write top-level reducer by hand
2. If you like it, you can use `combineReducers()` multiple times, like in `shopping-cart` example
3. The result of `combineReducer()` doesn't have to be top level reducer. You can tweak how it works, e.g. https://github.com/rackt/redux/pull/658#issuecomment-136478950

**Comment by IwanKaramazow** [comment]
I'll take a crack at this over the weekend, if no one is currently writing this.

**Comment by IwanKaramazow** [comment]
Started working on this over weekend, will probably take me at least two weeks due to my heavy academic workload. I'll report back when I have something of more substance.

**Comment by sai-prasanna** [comment]
@gaearon  I can write this. Which file should I update in the docs with the contents?

**Comment by markerikson** [comment]
@IwanKaramazow , @sai-prasanna : I'm looking at trying to put together a more comprehensive doc on organizing reducer logic.  See https://github.com/reactjs/redux/issues/1784.  Would appreciate any thoughts, comments, or help :)

**Comment by timdorr** [comment]
Closing out in favor of the effort's Mark is championing over at #1930.
