### ISSUE TITLE
Update TodoMVC example to be more in line with other examples

### ISSUE THREAD

**Issue by gaearon** [reactjs/redux#1354]
This is up for grabs.

TodoMVC hasn’t received much love over the last few months. We should update it to store `visibilityFilter` in the state, split it into presentational and container components, and update the reducer code to use composition.

It might even be easier to take the new vanilla `todos` example and tweak it until it looks and acts as TodoMVC. Bonus: add Reselect into it as described in “Computing Derived Data”!

If you want to do it, please write in this thread!

**Comment by julianusti** [comment]
I'd love to contribute.

**Comment by montogeek** [comment]
I can contribute!

**Comment by gaearon** [comment]
Cool, @julianusti grabbed the task first.

@julianusti Please post your work in progress in a PR as it goes so we can discuss the work as it happens. If you feel like you don’t have time to finish it let us know so others can pick it up.

Thanks!

**Comment by julianusti** [comment]
@gaearon cool, thx.

**Comment by jontewks** [comment]
@julianusti is this underway? I would also like to contribute but there aren't many `help wanted` tags available.

**Comment by urbanvikingr** [comment]
@jontewks If you like, I am looking for someone to pair with on adding tests to `todos` example. I would like to have some container and component tests added. Mocha has been used the other tests, and I am open to Jasmine and/or Jest. I'll create a new issue for this.

**Comment by julianusti** [comment]
@jontewks hey, I've started but haven't chance to accomplish it yet. I would do my best to do it the next two-three days, otherwise I'll let u know and u can pick it up.

**Comment by gaearon** [comment]
Ping :wink:

**Comment by montogeek** [comment]
I can ping too to help ;) ;)

**Comment by jontewks** [comment]
@gaearon @urbanvikingr and I were going to pair on this, but my wife had our son sooner than thought, so we decided to split it. I completed about half the tests and passed it along to @urbanvikingr but he let me know there was some things going on for him that were taking up most of his time and I haven't heard from him for 4 days. I'll try to contact him and see if he can still take care of the other half, and if not I'll finish it up by Friday.

**Comment by gaearon** [comment]
@julianusti Let us know if you’re busy. If you are, @montogeek can pick it up.

**Comment by julianusti** [comment]
@gaearon @montogeek hey guys, sorry for late respons, haven't chance to finish it yet, so, please @montogeek pick it up.

**Comment by montogeek** [comment]
I will work on it today :)

**Comment by mjw56** [comment]
I gave this a try here #1480

**Comment by Huanzhang89** [comment]
is this still up for grabs? Saw quite a few people already saying they are working on it

**Comment by timdorr** [comment]
Go for it! :)

**Comment by Huanzhang89** [comment]
Thanks @timdorr will have a crack at it today.

@gaearon could you elaborate a bit on the `Computing Derived Data` part please?

**Comment by tomipaul** [comment]
@gaearon @timdorr @Huanzhang89  Is this still open? I would like to work on it

**Comment by timdorr** [comment]
Yes, it's open for anyone to take on. Otherwise the issue would be closed :)

**Comment by tomipaul** [comment]
Thanks @timdorr I will take on the task

**Comment by tomipaul** [comment]
Hi @timdorr I attempted this here #2757 
I would love feedback if there's any

**Comment by phsantiago** [comment]
@timdorr, still up to grab or @tomipaul solved that?

**Comment by timdorr** [comment]
It looks like there's a PR open, but if you want to make your own or build on theirs, go right ahead. It's whatever code is best, not first.

**Comment by JosephMart** [comment]
Is this still yet to be completed or just not closed?

**Comment by timdorr** [comment]
There is #2757 open for it.

**Comment by JoeDuncko** [comment]
https://github.com/reactjs/redux/pull/2757 seems to be merged. Should this be closed?

**Comment by timdorr** [comment]
Yup!
