### ISSUE TITLE
Remove lodash

### ISSUE THREAD

**Issue by paulmillr** [reactjs/redux#1393]
e7295c33776be6199b826817934dadad5d0f9bb1 brought lodash dependency in.

It is not useful to add the whole 20KB (gzipped!) library just to make Redux work. Would you still consider redux lightweight after the bloated dependency is in?

Can I make a pull request reverting the change?

**Comment by tyscorp** [comment]
It [does not](https://github.com/reactjs/redux/pull/611#issuecomment-177354583) add 20KB.

**Comment by paulmillr** [comment]
My bad then.

**Comment by jdalton** [comment]
![](https://cloud.githubusercontent.com/assets/4303/13090750/5c90d7dc-d4ac-11e5-8536-577f801fc6c8.png)

**Comment by paulmillr** [comment]
<img width="498" alt="screen shot 2016-02-16 at 11 51 05 pm" src="https://cloud.githubusercontent.com/assets/574696/13092360/2f68849c-d508-11e5-8b56-3bffe3a896f5.png">
