### ISSUE TITLE
Limiting / purging history

### ISSUE THREAD

**Issue by born2net** [reactjs/redux#1396]
Sorry for opening an issue, just no other way to ask a Q on github.
How can I limit the total history the store keeps...
In other words I never need over 100+ entries for time travel, is there a store property for that?
or purging I guess would be good as well...

P.S. Dan, nice talk on with Victor and the rest of the ng2 team...

regards

Sean.

**Comment by gaearon** [comment]
Vanilla Redux doesn’t keep any history. This is what you’d use in production.

Redux, when enhanced with [DevTools](https://github.com/gaearon/redux-devtools/), will keep the history until you press “Commit” (at least, with the [Log Monitor](https://github.com/gaearon/redux-devtools-log-monitor)). **You should never enable Redux DevTools in production.**

I believe that [Redux DevTools Chrome extension](https://github.com/zalmoxisus/redux-devtools-extension) lets you specify how many actions you care about. Regardless of whether this is the case, we plan to [allow you to configure how many actions you want to see until they get auto-committed](https://github.com/gaearon/redux-devtools/pull/241).

**Comment by born2net** [comment]
got it... tx for the quick support
