### ISSUE TITLE
Add Tests to `todos` Example

### ISSUE THREAD

**Issue by urbanvikingr** [reactjs/redux#1397]
I'm looking for somebody to pair with on adding tests to the `todos` example. I would like to add container and component tests. Mocha has been used to the other tests, but I am open to use Jasmine and/or Jest.

**Comment by jontewks** [comment]
I'd love to pair with you on this!

**Comment by gaearon** [comment]
Let’s use Mocha everywhere for consistency. You can look at `todomvc` examples for inspiration.

**Comment by urbanvikingr** [comment]
Awesome. That's deal. Let's coordinate outside GitHub. My email is dj@fitbird.com.

**Comment by urbanvikingr** [comment]
@gaearon Got it. Thanks.

**Comment by gaearon** [comment]
Coordinating on GitHub would be better so everybody can keep track of what’s happening.

**Comment by urbanvikingr** [comment]
We'll use email to coordinate time for pairing etc. However, we will create a pull request and push changes as we go. This way, community can follow process.

**Comment by weicheng113** [comment]
How about the unit tests i did in #1458? I think organizing it to be easier unit testable is more important.

Cheers, Cheng

**Comment by gaearon** [comment]
Superseded by #1471 and #1493.
