### ISSUE TITLE
Global async error handler with an override possibility

### ISSUE THREAD

**Issue by smolyakoff** [reactjs/redux#1406]
I'm thinking about error handling in redux. Imagine a situation of handling form submit which can return different errors: 400, 401, 500.
When 400 is returned, I want to show a message in top of the form (override the default behavior). 
For other (unhandled) error codes, the default (global) error handler should be invoked (which shows notification toast). Just don't want to duplicate this code for every single action

I dispatch async actions using redux-thunk middleware
```js
// Pseudo code
const action = (dispatch) => {
	
	const onSuccess = (result) => dispatch({type: 'OPERATION_SUCCESS', payload: resuly});
	const onError = (error) => dispatch({type: 'OPERATION_ERROR', error: true, payload: error});

	return promise.then(onSuccess, onError);

};
dispatch(action);
```

I can create a reducer which handles all {error: true} actions and show some popup-notification (probably without using redux state, directly invoking some toast.show() method)
But how to determine if this special error was already handled somewhere in the state tree?

**Comment by gaearon** [comment]
Hi, thanks for coming by.

Please use StackOverflow for usage questions. This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it. (Github search is pretty much useless.)

Sorry we couldn’t answer your question here. Please feel free to post a link to the StackOverflow question, and I’ll be happy to try to answer it.

**Comment by smolyakoff** [comment]
@gaearon, thanks for your attention, posted [question on stackoverflow](http://stackoverflow.com/questions/35417507/how-to-make-a-global-error-handler-in-redux-react-and-override-it-when-needed)

**Comment by sompylasar** [comment]
Looks related: https://github.com/reactjs/redux/issues/1400#issuecomment-184355106
