### ISSUE TITLE
Put action after state with default value in reducer will cause jshint to complain

### ISSUE THREAD

**Issue by anianj** [reactjs/redux#1410]
JSHint will report: 
Regular parameters should not come after default parameters. W138

**Comment by gaearon** [comment]
Well, we don’t agree with this particular rule. You can either disable it, or not use optional parameters and write something like

```js
function counter(state, action) {
  if (typeof state === 'undefined) {
    return 0
  }

  switch (action.type) {
    // ...
  }
}
```
