### ISSUE TITLE
How to use createStore second argument for initial state with combined reducers? 

### ISSUE THREAD

**Issue by mohsen1** [reactjs/redux#1431]
Why [`assertReducerSanity`](https://github.com/reactjs/redux/blob/master/src/combineReducers.js#L49) in `combineReducers` passes `undefined` to reducers to check if they are "sane"?

In my app I want to send the initial state when I'm making the store in the [second argument of `createStore`](https://github.com/reactjs/redux/blob/master/src/createStore.js#L38)?

**Comment by gaearon** [comment]
In general we consider `initialState` argument to `createStore` an optimization. It is handy for persistence and rehydrating the store when rendering on the server, but your app is supposed to be able to “boot up” without that argument.

The reducer sanity check verifies that your reducers can handle empty state and initialize themselves if necessary. Preparing a single “initial state tree” outside the reducers is an anti-pattern because it makes them less reusable and easier to break during a refactoring. If you don’t agree with our opinion you can always write the root reducer by hand instead of using the stock `combineReducers()`.

**Comment by mohsen1** [comment]
Thanks for explanation. Having an initial state in each reducer helped me re-use a reducer in my code actually! 

https://github.com/contacts-mvc/redux-react/blob/9b98792f1b6d8a731f220fc8c66263c7a9611f81/reducers/selectedContactId.ts#L13

**Comment by pke** [comment]
Any sample code how reducers init themselves?

**Comment by sompylasar** [comment]
@pke Reducers are stateless, they do not init themselves, rather they return the initial value of the piece of application state they are responsible for.

If the state passed to the reducer is undefined, the initial value should be returned:
https://github.com/reactjs/redux/blob/master/examples/todomvc/reducers/todos.js#L11
https://github.com/reactjs/redux/blob/master/examples/todomvc/reducers/todos.js#L3-L9

**Comment by pke** [comment]
I see. I was merely using @gaearon words
> your reducers can handle empty state and initialize themselves if necessary

How would a reducer initialize itself with a remote list of items?

**Comment by sompylasar** [comment]
@pke Any state change is done solely via actions, even the state initialization (Redux calls the reducer with an empty state and an INIT action to get the very first state from the reducer). The very first state can be empty if you have no data right away. Then, to change the state from empty to full (e.g. after asynchronously receiving data from remote location), you'd have an action with a payload required to fill the state.

**Comment by gaearon** [comment]
Yep. I was referring to synchronous initialization, by which I meant that reducer should return some initial state if it receives `undefined` as first argument. Any further changes in state much come through actions.

**Comment by pke** [comment]
And the action to load the remote data should be initiated in the reducers `default` handler?

**Comment by gaearon** [comment]
No, reducers cannot initiate actions. They are passive and only react to actions.
The actions can be initiated by components.

Check out http://redux.js.org/docs/advanced/AsyncActions.html.

To be fair there *are* approaches where reducers initiate actions but they are experimental. See https://github.com/raisemarketplace/redux-loop for an example.
