### ISSUE TITLE
I set NODE_ENV=production but dev_tool still exists in real-world

### ISSUE THREAD

**Issue by ibufu** [reactjs/redux#1432]
I run 'set NODE_ENV=production && npm start', 
but in root.js 
`if (process.env.NODE_ENV === 'production') {
  module.exports = require('./Root.prod')
} else {
  module.exports = require('./Root.dev')
}`
it select Root.dev and process.env.NODE_ENV is undefined

**Comment by ibufu** [comment]
sorry,
I should write `new webpack.DefinePlugin({ "process.env": { NODE_ENV: JSON.stringify("production") } })`
at webpack.config.js.

**Comment by gaearon** [comment]
Yep, you need to evify the code for `NODE_ENV` to take effect. It doesn’t rewrite your code automatically unless you do the envification.

**Comment by wmertens** [comment]
Also, if you use bash or zsh you should write `NODE_ENV=production npm
start`. In fact, `env NODE_ENV=production npm start` should work in all
shells.

> --

Wout.
(typed on mobile, excuse terseness)

**Comment by gaearon** [comment]
`set NODE_ENV=production && stuff` is a Windows thing.
