### ISSUE TITLE
Strange delay/lag in reducer output

### ISSUE THREAD

**Issue by ffxsam** [reactjs/redux#1438]
Is there any reason there would be a slight lag in Redux's reducer output? The action fires off immediately, as I can see in the browser console. See GIF below.

![licecap](https://cloud.githubusercontent.com/assets/12532733/13263158/49e21198-da1d-11e5-9b86-2cdf0fd40399.gif)

**Comment by ffxsam** [comment]
The action and reducer in question:

Action:
```
export const PLAY_URL = 'PLAY_URL';
export function playUrl(id) {
  return {
    type: PLAY_URL,
    id,
  }
}
```

Reducer:
```
export default function (state = initialState, action) {
  switch (action.type) {
    case PLAY_URL:
      return Object.assign({}, state, {playingId: action.id});
    default:
      return state;
  }
}
```

**Comment by ffxsam** [comment]
Never mind, my own dumb mistake! :)

**Comment by club9822** [comment]
i have save issue. could you say your fault and solution
