### ISSUE TITLE
Infinite recursion when calling "dispatch" from middleware

### ISSUE THREAD

**Issue by mananvpanchal** [reactjs/redux#1446]
Hello,

When I call "next(action)" from middleware, it works well and calls next middleware.

```export const middleware = ({ dispatch, getState }) => {
	return (next) => {
		return (action) => {
			return next(action);
		};
	};
};```

But, if I call "dispatch(action)" from middleware, it starts calling first middleware and eventually goes into infinite recursion call.

```export const middleware = ({ dispatch, getState }) => {
	return (next) => {
		return (action) => {
			return dispatch(action);
		};
	};
};```

Why we are not providing "dispatch" directly from store which takes us to the reducer? This way we can provide a functionality like if "someAction" doesn't want to go though remaining middleware chain then we can just call "dispatch(someAction)". Please give me explanation if "dispatch" from store doesn't need in middleware.

Thank you very much #1445

**Comment by johanneslumpe** [comment]
This is the desired behavior. You should be able to start a new dispatch at the top of the chain. Your example is overly simplified. In a real world condition you'd have a condition whether you want to dispatch an action in your middleware or not.

Each action should go through the whole middleware stack in order for everything to be easy to reason about in my opinion.

What is your use case here?

**Comment by mananvpanchal** [comment]
Sorry, but no use case here. It's just general discussion that if each action should go through the whole middleware chain then the dispatch get encountered again and causes infinite recursion.To Prevent this we need to specify some conditions to not to call that dispatch again. Putting this kind of conditions would be very hard in real world situation. And if it still needed we can change middleware signature as below.

`export const middleware = ({ dispatchFirst, dispatchLast, getState }) => {`

"dispatchFist" starts from first middleware, whereas "dispatchLast" calls reducer and bypass middleware chain. We can rename "dispatchFist" and "dispatchLast" to some other, if the name doesn't represents its finctionality

**Comment by johanneslumpe** [comment]
I strongly disagree that it is hard to add conditions to your middleware. It is not for the middleware to decide whether to skip other middlewares or not. Think about this: You add a few middlewares to your stack which you want to always be used. Then you add a third party one after those and you expect that if it dispatches actions those actions will hit your middlewares too. But if that middleware decides to use your proposed `dispatchLast`, your functionality breaks in a very confusing way.

I think introducing something like this will make the api less straight forward and cause all kinds of headaches. If no valid use case is provided, then I'd err on the side of this being just like writing `while (true) {}` - you can do it, but you are aware of the fact that it will cause an infinite loop. To me it is common sense that if you infinitely recurse, your application will break. I don't see this as anything that has to or should change.

Furthermore, take a look at https://github.com/acdlite/redux-promise/blob/master/src/index.js and see how the library uses the dispatch. This is a very common pattern and it also shows you how to use conditions to make your problem regarding the infinite dispatch loop go away.

**Comment by mananvpanchal** [comment]
Yes that is my point that infinite while loop is provided already and now I need to write some conditions to avoid being it infinite. And thunk is always there to handle complex scenario. If someone calls "disapatchLast" by mistake and face strange situation then he is in even stranger situation if they forger to write or write wrong condition to avoid recursion.

**Comment by gaearon** [comment]
Thank you for the discussion!

Here’s my thoughts on this. Much more people use the middleware than write it. The API is optimized for the users rather than the writers.

The users don’t want to debug “incompatible” middleware. If any middleware has the ability to dispatch actions directly to the reducer, the system becomes much less useful. For example you can’t put a logger middleware at the end of the chain and still expect it to log every action and the next state.

The expectation is that you use `next()` most of the time unless you really know what you’re doing with `dispatch()`. There may be ways to improve this but I don’t intend to make breaking changes to API just for middleware authors. Stability is more important than middleware authors’ convenience at this point.

And we definitely *need to* provide a way to restart the middleware chain. It’s essential for middleware like thunk.

I will close as I don’t see how we can improve things without breaking changes. Please feel free to continue the discussion or contribute to the documentation to better describe this pitfall. 

Thanks!

**Comment by slashhuang** [comment]
great explanation, Thank you guys

**Comment by sktguha** [comment]
Hi, 
I know this is an old thread. My apologies in advance if this is the wrong place to put this.

But I just want to bring up something related to this. 
Is it a good idea for redux to detect an infinite loop of dispatches happening from middleware and show error like
React shows error if setstate is called repeatedly, i.e
"Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops"
So could redux detect and show a similiar message ? It seems the limit of setstates is 50 as per [https://github.com/facebook/react/blob/1992d973068d031083f507558d89ad91c0015709/packages/react-reconciler/src/ReactFiberWorkLoop.old.js#L341](nested update limit)

**Comment by markerikson** [comment]
This would require adding an extra middleware or enhancer to the store.  This is a fairly rare use case - I can only remember seeing a handful of folks reporting this over the years (as evidenced by how quiet this thread has been).  As such, I'm not terribly concerned about it.

**Comment by sktguha** [comment]
Thanks for your reply @markerikson 
>This is a fairly rare use case
Got it. Ya I guess, then its not worth putting much effort then

If its not too much trouble, can you point me to such an extra middleware or enhancer . seems interesting.

**Comment by markerikson** [comment]
I can't remember seeing a middleware that actually implements this idea.  But, hypothetically, you'd probably want to keep track of the latest dispatched action type and how many times in a row you've seen it, and you could maybe do some call stack introspection or a stack of times the middleware has run without returning, and do the logic that way.

**Comment by sktguha** [comment]
oh I see. Understood. but it won't handle non serialisable values . 


By the way I wanted to know your opinion on something else I am facing at my work at Salesforce , if you wish to answer. so I want to make a generic form HOC component . so the user can call some functuon like getForm('someId') and it returns a object with a reducer and form component. They can use that reducer in combineReducer. 

Is that the best approach ?

**Comment by sktguha** [comment]
Hi @markerikson , a bit unrelated question, but is there any good eslint for redux, preferably with autofixes . Looking for class based components only for now ? 
As me and my team are sometimes bike shedding over some things. so eslint would be good to fix that.

**Comment by markerikson** [comment]
No idea, sorry - I haven't looked.

**Comment by sktguha** [comment]
Oh I see. No worries, thanks for reply 🙂.
