### ISSUE TITLE
Failed npm install, rimraf lib

### ISSUE THREAD

**Issue by benpetersen** [reactjs/redux#1448]
Is there a way around this without updating node? My corporate environment is slightly behind the times and has slightly older versions of whitelisted apps, below is the most up-to-date they allow.

Failed at redux@3.3.1 clean script 'rimraf lib dist es coverage'.

Below is the section of npm-debug that could be useful.

2 info using npm@3.7.1
3 info using node@v4.1.0
4 verbose run-script [ 'preclean', 'clean', 'postclean' ]
5 info lifecycle redux@3.3.1~preclean: redux@3.3.1
6 silly lifecycle redux@3.3.1~preclean: no script for preclean, continuing
7 info lifecycle redux@3.3.1~clean: redux@3.3.1
8 verbose lifecycle redux@3.3.1~clean: unsafe-perm in lifecycle true
9 verbose lifecycle redux@3.3.1~clean: PATH: 
10 verbose lifecycle redux@3.3.1~clean: CWD: C:\Users\benjamin.petersen\Documents\GitHub\redux
11 silly lifecycle redux@3.3.1~clean: Args: [ '/d /s /c', 'rimraf lib dist es coverage' ]
12 silly lifecycle redux@3.3.1~clean: Returned: code: 1  signal: null
13 info lifecycle redux@3.3.1~clean: Failed to exec clean script
14 verbose stack Error: redux@3.3.1 clean: `rimraf lib dist es coverage`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\benjamin.petersen\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\benjamin.petersen\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:817:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by gaearon** [comment]
>My corporate environment is slightly behind the times and has slightly older versions of whitelisted apps, below is the most up-to-date they allow.

I’m not sure I’m following. What whitelisted apps?

>Failed at redux@3.3.1 clean script 'rimraf lib dist es coverage'.

Are you installing Redux for usage or development? `npm install redux` should not be running `clean`.

**Comment by gaearon** [comment]
Closing as lacking the necessary information.
