### ISSUE TITLE
Support the next generation code bins

### ISSUE THREAD

**Issue by christianalfoni** [reactjs/redux#1449]
Services like JSBin, JSFiddle, Plunkr etc. has provided us with great experiences to explore and share code for a long time now, and they will continue to do so for a very long time. That said, the way we write code also changes. We are heavily dependent on build tools and Webpack is one of the more popular build tools. There is a small movement going on now to make this better.

I am working on a project like this, currently in alpha, called [WebpackBin](http://webpackbin.herokuapp.com/E1YY7Odoe). It is a code bin service that runs with webpack. It is highly optimized and lets you easily grab any NPM package, play around with code and share it with others. Since it lets you bundle NPM packages and Webpack loaders it really takes it to the next level. You can watch an earlier version being introduced [here (youtube)](https://www.youtube.com/watch?v=beatnbs34Aw).

But there is a problem. And I share this problem with other modern code bins like [esnextb.in](http://esnextb.in). We can not install **redux**. The reason is that redux does not provide the "transpiled" files in the NPM registry. That means the backend service needs to install all dependencies and then build the project. This is a process that just takes too much time and has a risk of crashing and give other issues.

So I am asking an open question here. Would it be possible for Redux to make an example out of this? We need NPM registry packages to provide a "transpiled" version to allow services like WebpackBin and EsNextBin to grow and be useful.

Thanks for your attention :)

**Comment by emmenko** [comment]
@christianalfoni wow, really nice idea and impressive work so far! Thanks!

**Comment by gaearon** [comment]
>The reason is that redux does not provide the "transpiled" files in the NPM registry. 

It provides a transpiled UMD build as `redux/dist/redux.min.js`. It is included in the NPM package.

>That means the backend service needs to install all dependencies and then build the project.

I understand this takes much time, but what would be the point of supporting npm without supporting nested dependencies? If you only plan to support UMD builds, you might as well let user map library names to URLs and encourage people to use npmcdn.com URLs like http://npmcdn.com/redux@latest/dist/redux.min.js for libraries hosted on NPM that happen to have UMD builds.

Great effort though! And thanks for starting the discussion.

**Comment by christianalfoni** [comment]
@gaearon Sorry, I was a bit tired yesterday after hacking an my explanation was not very good :) I really ment that that the `main` path in `package.json` does not exist, which means I have to guess what the entry point is. I do not really want the distributed version, I just want the entry point to exist.

That said, I woke up this morning thinking about it and I could of course just search for it. So:

1. Find `main` entry
2. If not exists find `dist/{packageName}.js`
3. If not exists find `src/index.js`

And so on... I think I will manage with that actually. Will put something together and let you know. Thanks for the feedback guys :-)

**Comment by christianalfoni** [comment]
You know, I think this might be an issue in WebpackBin. I see now that NPM registry actually TARS up a built version, not the github repo. Which is great :)

Though very strange that redux acts so different than other libs... hm... closing this for now and will reopen if it is related to redux project.

**Comment by christianalfoni** [comment]
Okay, I found the issue.

Redux exports a property of `exports.__esModule = true`. This makes Webpack misbehave. So will be able to fix it.

Anyone know what this property does? Searched all of Webpack source code but can not find any reference.

**Comment by johanneslumpe** [comment]
@christianalfoni The is a property set by `babel` in order for it to identify when to check for a `defaults` prop on the exported module. It it being used to differentiate between transpiled ES6 modules and normal commonjs modules.

**Comment by christianalfoni** [comment]
Ah, I see. Though I suppose this is a redux issue then?

```js
'use strict';

exports.__esModule = true;
exports.compose = exports.applyMiddleware = exports.bindActionCreators = exports.combineReducers = exports.createStore = undefined;

var _createStore = require('./createStore');

var _createStore2 = _interopRequireDefault(_createStore);

var _combineReducers = require('./combineReducers');

var _combineReducers2 = _interopRequireDefault(_combineReducers);

var _bindActionCreators = require('./bindActionCreators');

var _bindActionCreators2 = _interopRequireDefault(_bindActionCreators);

var _applyMiddleware = require('./applyMiddleware');

var _applyMiddleware2 = _interopRequireDefault(_applyMiddleware);

var _compose = require('./compose');

var _compose2 = _interopRequireDefault(_compose);

var _warning = require('./utils/warning');

var _warning2 = _interopRequireDefault(_warning);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { "default": obj }; }

/*
* This is a dummy function to check if the function name has been altered by minification.
* If the function has been minified and NODE_ENV !== 'production', warn the user.
*/
function isCrushed() {}

if (process.env.NODE_ENV !== 'production' && typeof isCrushed.name === 'string' && isCrushed.name !== 'isCrushed') {
  (0, _warning2["default"])('You are currently using minified code outside of NODE_ENV === \'production\'. ' + 'This means that you are running a slower development build of Redux. ' + 'You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify ' + 'or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) ' + 'to ensure you have the correct code for your production build.');
}

exports.createStore = _createStore2["default"];
exports.combineReducers = _combineReducers2["default"];
exports.bindActionCreators = _bindActionCreators2["default"];
exports.applyMiddleware = _applyMiddleware2["default"];
exports.compose = _compose2["default"];
```

Since it is `__esModule = true` it should not export directly, but export on a "default" property?

**Comment by emmenko** [comment]
Can I ask exactly why webpack has a problem with it? Just want to understand :)

**Comment by christianalfoni** [comment]
@emmenko It might be scoped only to the DLLPlugin, which extracts webpack bundles to work as externals that other webpack bundles can require from.

So not sure if it is a bug there, or redux is exporting it wrong? Since redux works normally I would suspect a problem in DLLPlugin, but @johanneslumpe comment made me a bit unsure again ;-)

**Comment by johanneslumpe** [comment]
@christianalfoni No, it works as expected. I think the issue you are running into is the fact that redux does not export a default export at all. In https://github.com/reactjs/redux/blob/master/src/index.js#L28 you can see that redux exports multiple named exports.

And maybe I didn't explain it properly: the `__esModule` flag just means that the module is actually transpiled from an ES6 module. It does not mean that it must have a `default` property.

Example:

```js
import test from 'myModule'
```
To process this properly babel needs to know whether `myModule` is a transpiled ES6 module or a raw commonjs module.

This is the method babel uses:

```js
function _interopRequireDefault(obj) {
  return obj && obj.__esModule ? obj : { 'default': obj };
}
```
It uses that flag so it can determine whether to just return the module or whether to wrap the commonjs module with in a new object with a valid `default` property.

**Comment by christianalfoni** [comment]
Okay, cool, thanks for taking the time to explain it :)

I conclude that this is a DLLPlugin issue then, since Webpack normally handles this scenario. Thanks a bunch!

Deploying a temporary fix until it is fixed.

**Comment by johanneslumpe** [comment]
@christianalfoni you've very welcome

**Comment by emmenko** [comment]
:+1:
