### ISSUE TITLE
Allowing nested action creators in bindActionCreators

### ISSUE THREAD

**Issue by lmuntaner** [reactjs/redux#1452]
I think it would be a nice feature to be able to pass a nested object of action creators to the bindActionCreators.

Rather than only binding the first level of actionCreators, bind all the leafs of the actionCreators object.

I have already submitted the [Pull Request](https://github.com/reactjs/redux/pull/1451)

**Comment by gaearon** [comment]
Thank you for raising the issue. Please see my reply in https://github.com/reactjs/redux/pull/1451#issuecomment-189671109.
