### ISSUE TITLE
App.js location in todos example

### ISSUE THREAD

**Issue by xuefengwang** [reactjs/redux#1466]
In todos example, App.js is in the components folder. This seems a little confusing to me. In other examples, App.js is in the containers folder which makes more sense. 

Thanks,
William

**Comment by xuefengwang** [comment]
Created pull request; https://github.com/reactjs/redux/pull/1467

**Comment by gaearon** [comment]
It is there for a reason. In some examples, `App` is `connect()`ed to Redux store and acts as a container. In other examples, it’s a purely presentational component that isn’t aware of Redux store.

I would like to convert more examples to make `App` presentational. For example, see #1354.

**Comment by xuefengwang** [comment]
Ah, thanks for clarification.
