### ISSUE TITLE
Optimize TravisCI runs

### ISSUE THREAD

**Issue by zpao** [reactjs/redux#1469]
If you look at https://travis-ci.org/reactjs/redux/builds, it's taking > 40 minutes to run TravisCI tests. This is incredibly long and it's making me fatigued.

Can we do something to optimize these runs?

**Comment by gaearon** [comment]
Maybe it’s worth removing `build:examples` and `test:examples` from the CI. Examples are taking most of the time, especially their independent `npm install`s.

**Comment by naw** [comment]
I'm not very familiar with TravisCI, but if you're using their container-based infrastructure, you should be able to cache the node_modules folder for each separate example.

https://docs.travis-ci.com/user/workers/container-based-infrastructure/

https://docs.travis-ci.com/user/caching

**Comment by zpao** [comment]
I agree that caching could help out here, but be careful of how cache invalidation is done (or not done, which is where it hurts). I've seen cases where CI continued fine but a patch version upgrade of a npm package broke things so we didn't know for a while. I think the top-level caching of node_modules is supposed to work and get invalidated when your deps change but that might be wrong.

**Comment by naw** [comment]
If I'm understanding correctly, you could prevent such a scenario by having CI execute `npm update` instead of `npm install` on top of the (potentially stale) cached packages. 

This would result in the _exact_ package versions that would be installed by `npm install` when there is no cache, wouldn't it?

**Comment by gaearon** [comment]
I haven’t looked into those links yet but I think we should, if possible,

* *not* cache the root `node_modules` for extra safety
* cache `node_modules` for examples, as they are not critical

**Comment by timdorr** [comment]
> not cache the root node_modules for extra safety

It shouldn't be caching `node_modules` by default, just the `~/.npm`. That gives a boost to the download and native code build times for everything, which is about 164MB on my current system. As new modules are released within the semver restrictions set up within `package.json`, they will be downloaded fresh and added to the cache for the next build. 

Plus, we've gotten on with this in place all this time with no issues that I can remember :smile:

**Comment by timdorr** [comment]
OR what if we move the examples out to another repo? There are fairly regular additions, so a monorepo format for a `redux-examples` repo would scale well without affecting the core project's builds.

**Comment by gaearon** [comment]
I’d rather keep the examples here.

@timdorr Can you look into optimizing the speed of Travis? Maybe enabling caching for `node_modules` inside examples would be enough but I don’t know.

**Comment by timdorr** [comment]
Got the `node_modules` cached, but noticed a huge slowdown with eslint. Our ignores weren't globbing right. Fixed in 80d11be4.

**Comment by timdorr** [comment]
Well, that made it faster-ish: https://travis-ci.org/reactjs/redux/jobs/115188363

But of that 9:28 build time, 3:50 was spent unpacking and re-packing/updating the cache because the package.json's get touched by `npm install`. We can shave of some more time if that can get fixed, I believe.

**Comment by gaearon** [comment]
10 minutes is much better than 40 minutes :+1: 
Further improvements are welcome but I’m closing as solved-ish.
