### ISSUE TITLE
Improve `mapStateToProps` invariant validation error message

### ISSUE THREAD

**Issue by pke** [reactjs/redux#1474]
During refactoring of my stores I more than once hit an invariant violation like this:

```
Uncaught Invariant Violation: `mapStateToProps` must return an object. Instead received "A string".
Uncaught Invariant Violation: `mapStateToProps` must return an object. Instead received .
```

It would be nice of the name of the connected component would also be part of the error message

The latter error message above is from an "undefined" return I guess, so it should print that in the error message:
`Uncaught Invariant Violation: 'ComponentName mapStateToProps' must return an object. Instead received undefined`

**Comment by SimenB** [comment]
react-redux issue, not redux.

https://github.com/reactjs/react-redux/blob/1da657e0e0207090a307c35d09d407e5d65d52f9/src/components/connect.js#L21

**Comment by pke** [comment]
You right, sorry. Filed over there: https://github.com/reactjs/react-redux/issues/309
