### ISSUE TITLE
is it ok to update state too frequently?

### ISSUE THREAD

**Issue by Guro** [reactjs/redux#1496]
Example:
I have a component which plays video and i want to update another components based on video playback time.

Is it a good practice to fire an action "onplaybacktimechange"? which will update state?
as i know Redux keeps all versions of states so it means that i will consume too much memory too soon? 
what are your suggestions, how i can handle this kind of scenario?

**Comment by gaearon** [comment]
>as i know Redux keeps all versions of states 

This is **absolutely** not the case.

To be clear, [Redux DevTools](https://github.com/gaearon/redux-devtools) keeps state history for a while (until you commit or reset it) but you should never use it in production.

>Is it a good practice to fire an action "onplaybacktimechange"?

I would not suggest to fire actions *way* too often but once a second seems fine to me. As with any technological decision, you should write a stress test that models your use case reasonably accurately, and see whether the performance is acceptable.

**Comment by Guro** [comment]
> as i know Redux keeps all versions of states
**This is absolutely not the case.**

Thanks, that's what i wanted to know :)
