### ISSUE TITLE
Middleware, timeoutScheduler canceling the timer

### ISSUE THREAD

**Issue by Vivekbhusal** [reactjs/redux#1501]
In the documentation, on Middleware section, there is an example of [`timeoutScheduler`](http://redux.js.org/docs/advanced/Middleware.html#seven-examples). 
I am working on something on my project and I believe this example middleware could be helpful to me. 

The middleware returns cancel function but I am not sure who can I make use of that. 

In more detail, I have a project that lists an item. I want have a feature of UNDO on delete.

1. List of Items
![image](https://cloud.githubusercontent.com/assets/1974260/13625245/a3c40cd2-e609-11e5-81f9-dcceaa59a00e.png)

2. Action to delete item
![image](https://cloud.githubusercontent.com/assets/1974260/13625255/c5084f16-e609-11e5-8ee8-095238691add.png)

3. After delete
![image](https://cloud.githubusercontent.com/assets/1974260/13625627/c05809f8-e60d-11e5-9a74-a077cb7ba9e3.png)

Now the problem is, if I dispatch the delete action, and if it calls api to delete item from server, undo feature would be useless. So I can't delete from server (we could have flag option implemented on server , but wanna go there as last option).

So instead I thought, I could just flag the item on current state `to be deleted` then wait for  5 seconds and call api to delete the item. 

Coming back to middleware, I think probably timeoutScheduler would be helpful. if the action is 'DELETE ITEM' I could wait before distpaching the action/calling the api. 

```
export default function timeoutScheduler(store) {
    return (next) =>
        (action) =>  {
            if (action.type != DELETE_CLIPPING) {
                return next(action);
            }

            let timeoutID = setTimeout(
                () => next(action),
                5000
            );

            return function cancel() {
                clearTimeout(timeoutID);
            }
        };
};
```

I am not sure what would be the perfect solution to implement this. Also there is option to implement [redux-undo](https://github.com/omnidan/redux-undo) but not sure it would be helpful for asyncronous nature.

**Comment by gaearon** [comment]
I don’t think middleware is a good way to solve the problem you describe. Undoing needs to be a first-class concept in your server API. Redux can’t help you here. What you want is something like `deleteItem()` async API and `restoreDeletedItem()` async API.
