### ISSUE TITLE
Redux: Default parameters are injected as object?

### ISSUE THREAD

**Issue by bboysathish** [reactjs/redux#1502]
Hi,

I am facing an issue, when running a simple counter example using redux. 

May I know why redux is injecting the default parameter as Object {}, as shown in the below screen shot.

![injected_code](https://cloud.githubusercontent.com/assets/8023447/13627323/a2a76386-e5ef-11e5-9e93-4b398ab3eb23.PNG)

For More details, please see the SO.
http://stackoverflow.com/questions/35873520/default-parameters-are-injected-as-object-in-babeljs-reactjs

**Comment by taurose** [comment]
I think it's your `configureStore` method that's injecting the state when`window.__INITIAL_STATE__` is undefined.

`export default function configureStore(initialState = {}) {`

Change it to

`export default function configureStore(initialState) {`

**Comment by bboysathish** [comment]
@taurose , it worked like a charm. Thanks.. I forgot initially reducers arguments are injected from the configureStore. Am i right ?

**Comment by taurose** [comment]
Yes, the way you set it up, your `configureStore` essentially calls `createStore(reducer, window.__INITIAL_STATE__ || {})` (null and other edge cases aside), i.e. your initial state will never be undefined, so your reducer default value will never be used.

**Comment by bboysathish** [comment]
@taurose  Thanks.
