### ISSUE TITLE
At todos example, What does the second parameter "ownProps" in container component FilterLink for?

### ISSUE THREAD

**Issue by AlexCao2016** [reactjs/redux#1507]
Hi, team,
     when I tried to study Redux example, I found that as following:
const mapStateToProps = (state, **ownProps**) => {
  return {
    active: ownProps.filter === state.visibilityFilter
  }
}

const mapDispatchToProps = (dispatch, ownProps) => {
  return {
    onClick: () => {
      dispatch(setVisibilityFilter(ownProps.filter))
    }
  }
}

const FilterLink = connect(
  mapStateToProps,
  mapDispatchToProps
)(Link)

export default FilterLink

I have one question in my issue title? what is it for? Is it related to presentational component "Link" because of has parameter "children"?

**Comment by codenostic** [comment]
@timdorr i did not understand the statement this.state = props.state . what does it do? and what is props.state? Is this coming from store ? 
And also, thanks for putting this up as this is easier to understand than using connect.
