### ISSUE TITLE
Where is repo for eslint-config-rackt exists now?

### ISSUE THREAD

**Issue by vtambourine** [reactjs/redux#1509]
Suddenly all repos for ESLint presets `eslint-config-rackt`/`eslint-config-reactjs` responds 404. Where are they now? Does they exists?

**Comment by timdorr** [comment]
I believe @mjackson removed it, as we're going to start centralizing on `eslint-config-airbnb`. [`history` already made the switch](https://github.com/mjackson/history/blob/master/package.json#L45), so we should probably do that too at some point. I don't think the NPM module is going to get yanked any time soon, but I would avoid using it.

**Comment by mjackson** [comment]
:+1: Ya, I removed the repo because nobody was maintaining it. Linting is up to individual package maintainers now. Semi-colons!!!1!!

**Comment by vtambourine** [comment]
Great, thanks for clarification!

So, semicolon are now in favour? I am confused. All of the `redux` official examples are written in semicolonless style (more like standard, I guess). I thought this is the style most contributors prefer :)

**Comment by gaearon** [comment]
>I thought this is the style most contributors prefer :)

It’s a style Ryan and Michael chose for `rackt` at the time, and since Redux was a part of it, we went with it. I never cared too much either way :smile: . I’ll be happy to get back to `airbnb` style. In fact I think maybe we should just show semicolons of no semicolons randomly every day so people stop paying attention to them :wink: .

**Comment by knowbody** [comment]
![](http://i.giphy.com/CradU0oCOmHrq.gif)

**Comment by vtambourine** [comment]
@gaearon I am happy not worrying about style at all. I like adopting code style from projects I am contributing to or grabbing code from. By this way, having preset like `eslint-rackt` or `eslint-reactjs` is wonderful, since all I need to do is just install appropriate package and go back writing clean code. It's great to have `eslint-config-airbnb`, but what is great even more is to have some agreed community convention on it :)

**Comment by gaearon** [comment]
We were using `airbnb` before joining `rackt` and I’m happy to get back to it now that `rackt` dissolved into `reactjs`. I don’t think we want a separate `reactjs` config.

**Comment by sompylasar** [comment]
@gaearon I remember you saying you don't use semicolons because of some team coding style, but `airbnb` enforces their presence: https://github.com/airbnb/javascript#semicolons -- what has changed?

**Comment by gaearon** [comment]
I think I just clarified this above: https://github.com/reactjs/redux/issues/1509#issuecomment-195358849
We were part of `rackt`. They used no semicolons. Now `rackt` has morphed into `reactjs` and the consensus seems to be `airbnb`. We could do that too if somebody has time to prepare a PR. I don’t care much about this. :smile:

**Comment by sompylasar** [comment]
@gaearon I see, great, thank you for clarification. :+1:

**Comment by battaile** [comment]
Is there any chance of turning the choices from something like react-quick-start into a reactjs maintained style guide?  Airbnb seems like a good place to start, but they're committed to doing their own thing, not necessarily going where the community is going.

> "what's common" isn't the primary motivator for this guide, it's "what we use at Airbnb". 
https://github.com/airbnb/javascript/issues/982#issuecomment-236979901

**Comment by mjackson** [comment]
FWIW I just use [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react)'s "recommended" settings these days and go from there. You can see how I do it based on some of my more recent work:

- [react-point](https://github.com/mjackson/react-point)'s [.eslintrc](https://github.com/mjackson/react-point/blob/master/.eslintrc)
- [react-media](https://github.com/mjackson/react-media)'s [.eslintrc](https://github.com/mjackson/react-media/blob/master/.eslintrc)

**Comment by ljharb** [comment]
@battaile if there's anything (besides the jsx thing, which has been discussed at length) you think the community is doing differently than the airbnb guide, please feel free to contribute at https://github.com/airbnb/javascript/issues/1089
