### ISSUE TITLE
Sever rendering docs have outdated template string information

### ISSUE THREAD

**Issue by Aweary** [reactjs/redux#1510]
>Note on String Interpolation Syntax
In the example above, we use ES6 template strings syntax. It lets us write multiline strings and interpolate values, but it requires ES6 support. If you’d like to write your Node code using ES6, check out Babel require hook documentation. Or you can just keep writing ES5 code.

Template strings are supported natively in Node `4.x` and newer. This should likely be updated to mention that.

**Comment by gaearon** [comment]
You are welcome to send a pull request fixing this!

**Comment by Aweary** [comment]
I'm out on vacation, just saw it and wanted to note it before I forgot, so if someone else wants to do it, go for it! Otherwise I'll do it next week or so :tada:
