### ISSUE TITLE
Pass state to listeners as an argument?

### ISSUE THREAD

**Issue by Lucretiel** [reactjs/redux#1513]
This seems so straightforward and obvious I feel like I'm missing some reason it isn't done this way. Why don't listeners accept the new state as an argument?

```js
let unsubscribe = store.subscribe(state => {
    ...
});
```

**Comment by merk** [comment]
Just use getState on the store.

```js
let unsubscribe = store.subscribe(() => {
   const state = store.getState()

// ...
})
```

**Comment by Lucretiel** [comment]
I know, but why require the extra step?

**Comment by gaearon** [comment]
This has been discussed before: https://github.com/reactjs/redux/issues/303. `subscribe()` and `getState()` are orthogonal on purpose so if you “override” one in a store enhancer, you don’t need to override the other.

In any case, having just the new `state` is not very useful. You’ll probably want the previous `state` too. And not just the previous state—probably a specific part you care about. At which point you might as well write your own helper to do this.

See https://github.com/reactjs/redux/issues/303#issuecomment-125184409 for more details.
