### ISSUE TITLE
deprecated graceful-fs@2.0.3

### ISSUE THREAD

**Issue by JinxiuLee** [reactjs/redux#1522]
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

**Comment by billyjanitsch** [comment]
Redux [doesn't depend on `graceful-fs`](https://github.com/reactjs/redux/blob/master/package.json#L62), so I don't think this is a Redux issue.

**Comment by johnsoftek** [comment]
@JinxiuLee Are you using Flow? flow-bin may need updated dependencies.

**Comment by JinxiuLee** [comment]
I cloned repository yesterday and when I was installing the npm packages redux required(npm install), I got the warning in my terminal. So that's why I published it here as an issue.

**Comment by kouhin** [comment]
@JinxiuLee Maybe mocha https://github.com/mochajs/mocha/issues/2121#issuecomment-187367807

**Comment by TrySound** [comment]
@JinxiuLee When you install something npm still checks all deps.

**Comment by johnsoftek** [comment]
@kouhin Yes, the Mocha team are on it: https://github.com/mochajs/mocha/pull/2129/files.

Also, Redux repo includes an old version of gitbook-cli: 0.3.6. Latest version is 2.1.2.
