### ISSUE TITLE
Add Redux Dash docs

### ISSUE THREAD

**Issue by afang** [reactjs/redux#1523]
Any plans on adding the Redux docs to Dash? If not I can do it.

**Comment by timdorr** [comment]
Dash?

**Comment by Aweary** [comment]
I believe @afang is referring to: https://kapeli.com/dash

**Comment by timdorr** [comment]
Ah, that Dash! Well, I'm not sure of the process to get a project added. Do we need to do anything here, or is it done on their side?

**Comment by afang** [comment]
There are user contributed docs that are handled on their side. I've just opened a request: https://github.com/Kapeli/Dash-User-Contributions/issues/861

**Comment by timdorr** [comment]
Thanks!
