### ISSUE TITLE
ES7 decorator

### ISSUE THREAD

**Issue by nmaves** [reactjs/redux#1529]
I am really new to the JS world so this is me just thinking out loud.

From the start the connect()() really threw me for a loop.  Mix that with connect(mSTP, mDTP)(Radium(component)) etc... the uglyness continues.

Would it be possible to come up with something like this?

```
@Redux({
  mapStateToProps: (state) => {
  },
  mapDispatchToProps: (state) => {
  },
})
class App extends Component {
  ...
}
```

Where they were optional just like the connect?

**Comment by BerkeleyTrue** [comment]
You can use the connect as a decorator.

```
@connect(...)
class App extends Component...
```

In fact that is all class decorators are, functions that take in a class and return a class.

**Comment by gaearon** [comment]
We don’t suggest using decorators though until the spec advances and Babel officially supports it.
Why not use `compose` for this?

```js
import { compose } from 'redux'

class MyComponent extends Component {
  // ...
}

const enhance = compose(
  connect(mapStateToProps, mapDispatchToProps),
  Radium,
  // anything else
)

export default enhance(MyComponent)
```

**Comment by jaspersorrio** [comment]
Hi @gaearon, thank you for this library. +1 for your solution.

I am also new to redux and came across this similar problem.
I cant seem to find much about using connect with es6 classes in the docs, hence google brought me here.

Would like to check if decorators are ready to use?
 
And i realised that none of the examples were using es6 classes, is there a specific reason? Am i going in the wrong way with incorporating code that uses es6 classes?

**Comment by gaearon** [comment]
>I cant seem to find much about using connect with es6 classes in the docs, hence google brought me here.

You’d use `connect()` with ES6 classes exactly like you’d use it with functional components.
There is no difference.

Functions:

```js
function Foo() {
  return <div />
}

function mapStateToProps() {
  // ...
}

export default connect(
  mapStateToProps
)(Foo)
```  

Classes:

```js
class Foo extends React.Component {
  render() {
    return <div />
  }
}

function mapStateToProps() {
  // ...
}

export default connect(
  mapStateToProps
)(Foo)
```

Use classes when you need `this.setState()` or lifecycle hooks like `componentDidMount()`. Use functions when you don’t need either. Example **do** use classes in such cases, [for example `RepoPage`](https://github.com/reactjs/redux/blob/master/examples/real-world/src/containers/RepoPage.js).

Neither approach has any relation to decorators. Decorators are an unstable feature that is not officially supported by Babel at the moment, and their specification is undergoing a change now. So I don’t recommend using them. In terms of `connect`, there is nothing you can do with decorators that you can’t do without them.

**Comment by jaspersorrio** [comment]
Thank you for the prompt reply.

However this begs the question, when do I use compose? Instead of using your latest solution?

Thank you.

**Comment by markerikson** [comment]
`compose` is used to combine multiple wrappers together into a pipeline.  For example, with store enhancers, you'd do:

```js
const composedStoreEnhancer = compose(
    applyMiddleware(thunk, saga),
    DevTools.instrument()
);

const store = createStore(rootReducer, composedStoreEnhancer);
```

Similarly, if I wanted to create a single wrapper that combined Redux setup and Redium setup, I could do:

```js
const combinedWrapperComponents = compose(
    connect(mapState, mapDispatch),
    Radium(radiumArgs)
);

export default combinedWrapperComponents(MyComponent);
```

**Comment by markerikson** [comment]
And, uh, that's basically what Dan wrote already :)
