### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by missinglink** [reactjs/redux#1531]
Is node >12 required? I couldn't find a reference to it in the readme or an 'engines' section in package.json

```
$ npm i

...
> cross-env BABEL_ENV=es babel src --out-dir es

/redux/build/use-lodash-es.js:4
      ImportDeclaration(path) {
                       ^
SyntaxError: Unexpected token (
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:177:20
    at Array.map (native)
    at Function.normalisePlugins (/redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:155:20)
...
```

```
$ node --version
v0.12.12

$ npm --version
2.14.9
```

```
$ git log -1
commit 175f32a99368980e24a4277ad9a3b2a4d012331f
Merge: 80d11be 74b1188
Author: Tim Dorr <timdorr@timdorr.com>
Date:   Fri Mar 11 13:16:20 2016 -0500

    Merge pull request #1515 from arnaudbenard/update-redux-mock-store-docs
    
    update redux-mock-store documentation
```

**Comment by timdorr** [comment]
[We only test Node 4.x.x and v5.x.x](https://github.com/reactjs/redux/blob/master/.travis.yml#L3-L4). You will need one of those versions to build Redux.

**Comment by missinglink** [comment]
Adding an [engines section](https://docs.npmjs.com/files/package.json#engines) to your npm will emit a warning to old-schooler like me :)

**Comment by timdorr** [comment]
Could you submit a PR to add that? Seems like low-hanging fruit if you want to make a contribution :smile: I would do it, but I'm mobile.

**Comment by missinglink** [comment]
no problem, here you go https://github.com/reactjs/redux/pull/1532

on closer inspection it might be better handled with an entry to the readme since the way npm handles that flag is inconsistent.

**Comment by gaearon** [comment]
It is required for contributing. We should add this information to https://github.com/reactjs/redux/blob/master/CONTRIBUTING.md.

It is, however, not required for using Redux. `npm install redux` will work fine.
