### ISSUE TITLE
Problem with NODE_ENV=production in browser

### ISSUE THREAD

**Issue by AntiCZ** [reactjs/redux#1540]
Hello,
I dont know is this right place but I try. 

My app is build from react-transform-boilerplate.git. For developing I use nodejs and webpack and all is ok. But for production I dont use Nodejs. App loads via classic script tag in html 
`<div id="app"></div><scipt src="js/react-app.js"></script>`
like other frontends js libraries. I dont need index for Google and app is part of classic PHP web.

App works but in console I get message:

You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.

I really dont know how to solve this. Is there some workaround?

**Comment by AntiCZ** [comment]
Ok, so I am only stupid https://github.com/tj/frontend-boilerplate/pull/16

**Comment by gaearon** [comment]
It's a common source of confusion, no worries! Envifying is important for React anyway so we just followed the convention most people were already using.
