### ISSUE TITLE
mapstatetoprops for a list item

### ISSUE THREAD

**Issue by caranicas** [reactjs/redux#1542]
I have a list item that I am trying to map state to, however when I inspect the `ownProps` value that is being passed in to `mapstatetoprops` the key isn't part of the object. 

Maybe this is a misunderstanding of React at the core, but I assumed that the key would come through. 

It was easy to solve because I just attached my key to a new prop, but it isn't nearly as clean or satisfying this way. Any help would be greatly appreciated.

**Comment by Aweary** [comment]
This isn't related to Redux, but React uses the `key` prop internally to maintain the order of child elements. Accessing `this.props.key` was [removed in React v0.12 RC-1](https://facebook.github.io/react/blog/2014/10/16/react-v0.12-rc1.html#breaking-change-key-and-ref-removed-from-this.props)

>You can no longer access this.props.ref and this.props.key from inside the Component instance itself. So you need to use a different name for those props.

So setting it as another `prop` is the correct way to do it.

**Comment by caranicas** [comment]
Thanks for the quick answer. Its a bummer that I have to duplicate data, but I'll live.
