### ISSUE TITLE
Please consider making non-npm dependent standalone releases of redux and react bindings available

### ISSUE THREAD

**Issue by srinathh** [reactjs/redux#1546]
Given the recent left-pad controversy showcasing weaknesses on npm and the [arbitrary code execution vurnerebility]( https://www.kb.cert.org/vuls/id/319816) that was marked as won't fix by npm, could you please consider making a usable static usable version of redux and react binfings for redux available without npm dependencies for safety?

Today, react can be already used without npm but I have struggled to make redux work with react without npm.

**Comment by Aweary** [comment]
Redux and `react-redux` already provides a UMD build. For their READMEs:

>If you don’t yet use [npm](https://www.npmjs.com/) or a modern module bundler, and would rather prefer a single-file [UMD](https://github.com/umdjs/umd) build that makes `Redux` available as a global object, you can grab a pre-built version from cdnjs.

[redux](https://cdnjs.com/libraries/redux))
[react-redux](https://cdnjs.com/libraries/react-redux)

If you're having issues you may want to try StackOverflow or Discord :+1:

**Comment by srinathh** [comment]
Thanks! I found I was able to make the redux UMD work for me by manually managing subscriptions. Haven't tried react-redux yet though.
