### ISSUE TITLE
Stop using babel-eslint

### ISSUE THREAD

**Issue by gaearon** [reactjs/redux#1554]
[It is not necessary anymore.](https://twitter.com/geteslint/status/714642903482564608)
We should migrate our source and examples to not use it.

**Comment by raspo** [comment]
wrong link? https://twitter.com/geteslint/status/714642903482564608

**Comment by gaearon** [comment]
Lol yeah, that’s the one.

**Comment by kennetpostigo** [comment]
@gaearon how come it is not needed anymore?

**Comment by gaearon** [comment]
From https://twitter.com/geteslint/status/714642903482564608:

>The ESLint default parser natively supports ES2016, JSX, and object rest/spread. You don't need babel-eslint for any of that.

**Comment by kennetpostigo** [comment]
Awesome! 
thank you @gaearon

**Comment by mjw56** [comment]
@gaearon would this require an update to the ```eslint-config-rackt``` dependency? I couldn't find the repository hosted anywhere on GitHub. Looking at the installed ```eslint-config-rackt``` package though, I do see ```"parser": "babel-eslint",``` in ```index.js```.

**Comment by knowbody** [comment]
I'm working on this one, updating the rackt config to airbnb as this was requested somewhere already anyway, and eslint-config-rackt is not mainatined

**Comment by gaearon** [comment]
Yea.

**Comment by knowbody** [comment]
@gaearon do you have any preference for customizing eslint-config-airbnb? or just follow it as is? I will push WIP soon

**Comment by gaearon** [comment]
What about semicolons? I couldn't care less about whether we use them or not but I'm concerned about the amount of work it would take to convert docs back. On the other hand any changes to style would require tweaking docs anyway.

Can we just use `eslint --fix` and write a script to run Markdown embedded snippets through it as well?

**Comment by knowbody** [comment]
what about stuff like: `vars-on-top`, `no-param-reassign`?

**Comment by gaearon** [comment]
Ugh. I guess we'll have to use a custom config. vars-on-top doesn't make sense to me.

**Comment by knowbody** [comment]
same here. I would just make both of those disabled then

**Comment by knowbody** [comment]
@gaearon these (https://gist.github.com/knowbody/6a59ddbc1bbff7bfa43c731ca531d1b3) are all after the `--fix` let me know which ones should we exclude

**Comment by gaearon** [comment]
Thank goodness. What do you think about a script that `--fix`es docs? Could be useful to other libs too.

**Comment by knowbody** [comment]
I can hack something

**Comment by knowbody** [comment]
but have a look at this https://github.com/eslint/eslint-plugin-markdown

**Comment by gaearon** [comment]
Apart from `vars-on-top`, these look sensible to me.
We should also switch to using `const` (with `let` where needed).

**Comment by knowbody** [comment]
Cool will send the PR soon

**Comment by gaearon** [comment]
Ideally we should merge some hanging PRs before merging that. I haven’t had time to do that yet.

**Comment by knowbody** [comment]
@gaearon what about `react/prefer-stateless-function` this specifically touches the examples.

> Ideally we should merge some hanging PRs before merging that. I haven’t had time to do that yet.

that's totally fine, I will make a WIP PR and we can update it once you have whatever you need merged

**Comment by gaearon** [comment]
I’m good with using stateless functional components where possible

**Comment by nickuraltsev** [comment]
I submitted a PR that updates most of the examples to use functional
components several days ago.

**Comment by knowbody** [comment]
oh, shame I didn't have a look... just pushed that change to my [PR](https://github.com/reactjs/redux/pull/1559). But it doesn't matter, as @gaearon said we will probably merge some PRs before merging mine. So yours should be merged, thanks for your work @nickuraltsev !

**Comment by nickuraltsev** [comment]
You are welcome!

**Comment by guidsen** [comment]
What is the status of this issue? Any help needed?

**Comment by timdorr** [comment]
Since we're using eslint-config-react-app, it [requires it as a peer dependency](https://github.com/facebookincubator/create-react-app/blob/master/packages/eslint-config-react-app/package.json#L14). If they drop using it in the future, we can do so here. For now, we're "stuck" using it (which is fine).
