### ISSUE TITLE
Conflating actions strategy?

### ISSUE THREAD

**Issue by mycroft11** [reactjs/redux#1557]
Hi, this might be a special case, but I thought it's worth adding in here.

My application requires the use of push message from the server (i.e a player is joining a game). When a push event comes in, i dispatch an action which updates the state and in turn the UI with that user joining.

The problem I'm having is if 20 players join within a few seconds, 20 events get dispatched and the UI updates 20 times (which is not great).

Is there a way to somehow conflate the actions and dispatch a single action within a 5s interval for example.

I'm sure there's lots of other cases this functionality would be useful. Any ideas would be greatly appreciated.

**Comment by sompylasar** [comment]
https://github.com/acdlite/redux-batched-updates ?

**Comment by Aweary** [comment]
There's also: https://github.com/tappleby/redux-batched-subscribe

**Comment by mycroft11** [comment]
Thanks guys, both seem like a right fit! Much appreciated!
