### ISSUE TITLE
server is running and I include the export line its not throwing an error

### ISSUE THREAD

**Issue by js08** [reactjs/redux#1558]
- I am facing a weird error
- when the server is running and I include the export line its not throwing an error and able to see the application...even it shows webpack is valid
 export { SportsTopPortion  };
- but after including this line and start the server again I am facing the error
Error: Invariant Violation:
- i am using webpack,node and react
- since I am using webpack for build I am thinking the error will be due to webpack
- checked React code for errors there is no problem in syntax.
- can you tell me how to fix it..
- the reason I am using export is to write unit test case
- whole code and test code can be seen in gist below
- I am debugging for past four days not able to find out

**Comment by sompylasar** [comment]
Without the code and full error messages, it would be impossible to help with this error.

**Comment by sompylasar** [comment]
> whole code and test code can be seen in gist below

There is no gist below.

**Comment by js08** [comment]
@sompylasar sorry missed the gist...you can see the code here https://gist.github.com/js08/c463caab33c78edb725583e3c000310a

**Comment by gaearon** [comment]
Is there anything in the code that suggest this error is specific to Redux?
It doesn’t appear so to me, so I’m closing this issue.
If you need help, it’s best to ask it on support forums and chats.
