### ISSUE TITLE
Component not re-rendering

### ISSUE THREAD

**Issue by brandonmp** [reactjs/redux#1560]
I checked the docs & [this issue](https://github.com/reactjs/redux/issues/585), but none of the troubleshooting did the trick.

I have a sign-in component for user auth/account creation.  I display it in a side-nav menu, so to easily navigate to the first page in registration,  i have the following check in my component lifecycle:

```
 componentWillMount: function() {
            if (this.state.formIndex <= 1 && this.props.UIState.userMustRegister == true) {
                this.jumpToRegistration();
            }
        },
...
jumpToRegistration: function() {
            this.setState({formIndex: 2});
        },
```

where `formIndex` tells my render function which page to render.

Anywho, when I click 'Create account,' I see the correct actions fire in Redux DevTools, and my button turns to a spinner.  

DevTools shows that the user has account has been created, and the user is logged-in.  So, the form should move to the first page of a small questionairre, but it doesn't.  I even put a console.log statement in my componentWillMount method, but it doesn't fire when the props change (ie, those tied to redux store).  

While trouble-shooting, I also put a console.log in my mapStateToProps function to check when it was firing.  

```
function mapStateToProps(state) {
    console.log("remapping:", state.UIState.userMustRegister);
    return {
        isLoggedIn: state.userAuth.authStatus,
        userProfile: state.userProfile,
        UIState: state.UIState
    }
}

```
![image](https://cloud.githubusercontent.com/assets/14139991/14162272/756aa9a8-f6b8-11e5-9727-ef36a9c1c5df.png)

As you can see, the value I'm monitoring in that console.log _is_ changing from `undefined` to `true`.

So, my reducers all correctly use Object.assign(), my DevTools look good, and on refresh, everything works like a charm.  

just for completeness, here's the reducer that handles the last few actions fired in my account creation logic. 

  ```
//reducers/UIState.js
      case C.USER_MUST_REGISTER:
            return Object.assign({}, currentState, {userMustRegister: true});

//reducers/userProfile.js
 case C.LOAD_USER_PROFILE:
            return Object.assign({}, currentState, action.userProfile);
```

Where should I look next?

**Comment by brandonmp** [comment]
my devtools readout.  this suggests both the content _and_ shape of my state are changing

![image](https://cloud.githubusercontent.com/assets/14139991/14162402/9572c216-f6b9-11e5-9489-4fe3c0b7fd7c.png)

**Comment by sacho** [comment]
`componentWillMount` fires only once in a component's lifecycle. It seems like you want to also use `componentWillReceiveProps`.

**Comment by mxstbr** [comment]
As @sacho said, using `componentWillReceiveProps` should solve this issue!

**Comment by gaearon** [comment]
Yeah. Note that `this.props` is not yet updated by the time `componentWillReceiveProps` runs so you need to read props from its first `nextProps` argument.

**Comment by brandonmp** [comment]
gah, my newb is showing.  Thanks all!
