### ISSUE TITLE
Redux router in spa discuss

### ISSUE THREAD

**Issue by node-rookie** [reactjs/redux#1561]
This question confuse me a long time, need someone's help.
In spa, when i refresh child page, the created state tree will crash, right? So the child page can't get any data, how can i do?

**Comment by gaearon** [comment]
Please try to use StackOverflow for questions. In general, single-page apps should be resistant to missing data. Inside your components, check whether it is available, and if not, render a spinner and begin fetching data. Examples such as `async` and `real-world` demonstrate this.
