### ISSUE TITLE
createStore is not available through cdnjs?

### ISSUE THREAD

**Issue by reggi** [reactjs/redux#1580]
I'm including the script via cdn in a jsbin and it's not working, says `createStore` is undefined.

**Comment by gaearon** [comment]
You are probably looking for `Redux.createStore`. When you see examples using `createStore` directly note that they always import or restructure it beforehand.

**Comment by reggi** [comment]
Bingo! Thanks!

```js
let {createStore} = Redux
let {connect, Provider} = ReactRedux
```
