### ISSUE TITLE
Chainable asynchronous middlewares

### ISSUE THREAD

**Issue by recidive** [reactjs/redux#1584]
Hello, we are trying to create modules made of a redux reducer and/or a middleware. The modules are to be reused and distributed, mostly like [Ducks](https://github.com/erikras/ducks-modular-redux) does, but also supporting middlewares.

We are using redux actions and trying to do something useful asynchronously, like reading a file or something from the database, and also allow a chain of dependency where modules' middlewares/reducers can rely on the state/payload of the module it depends on, and use it to build and return a new state.

Something like:

module 1
  -> dispatch action to read something async
  -> query database middleware await data from database
  -> run all other modules (async/sync) middlewares
  -> reducer consumes data and build a new state
  -> then it's passed to module 2 reducer and so on...

For doing so we are trying to run through a chain of (synchronous and asynchronous) side-effects in middlewares.

We don't want to do anything other than returning the FSA object when defining actions, so we don't restrict the data gathering logic and any other business logic only to the module that creates the action and centralize them in middlewares.

```js
import {createStore, applyMiddleware} from 'redux'
import {createAction, handleActions} from 'redux-actions'
import promiseMiddleware from 'redux-promise'

const BOOT = 'BOOT'
const AFTER_BOOT = 'AFTER_BOOT'
const AFTER_AFTER_BOOT = 'AFTER_AFTER_BOOT'

const someApi = {
 get(id) {
   return Promise.resolve({
     name: 'yeah'
   })
 }
}

const bootAction = createAction(BOOT)

const afterBootAction = createAction(AFTER_BOOT, async (id) => {
 const result = await someApi.get(id)
 return result
})

const afterAfterBootAction = createAction(AFTER_AFTER_BOOT, async (id) => {
 const result = await someApi.get(id)
 return result
})

const initialState = {foo: 'bar'}

const reducer = (state = initialState, action) => {
 switch (action.type) {
   case AFTER_BOOT:
     return {
       ...state,
       foo: 'baz'
     }
     
   case AFTER_AFTER_BOOT:
     return {
       ...state,
       foo: 'rock'
     }
   default:
     return state
     break
 }
}

const middlewares = [
 function middle({getState, dispatch}) {
   // Note the async keyword.
   return next => async (action) => {

     if (action.type == BOOT) {
       const sideffectA = await dispatch(afterBootAction(2))
     }

     if (action.type == AFTER_BOOT) {
       const sideffectB = await dispatch(afterAterBootAction(3))
     }

     return next(action)
   }
 },
 promiseMiddleware
]

const store = createStore(reducer, initialState, applyMiddleware(...middlewares))

// First action, and should fire other side-effects.
store.dispatch(bootAction())

console.log(store.getState(), "It should print {foo: 'rock'}")
```

We are doing this as part of our [Choko Redux](https://github.com/choko-org/choko-redux) project.

**Comment by sebas5384** [comment]
Seems to be a long discussion about side-effects here https://github.com/reactjs/redux/issues/1528

**Comment by tihonove** [comment]
Hi everyone,

I've spent many time to find solution for side effect composition. Idea to combine 'Algebraic Effects' and Redux-loop is very impressive. Another point: i love redux-saga, because it allows to write simple imperative-like code for business logic. 
Few days ago, I write library that solves all my problems (IMHO).

The main idea: reducer should returs a pair { state, effects } like redux loop, but effects should be a generator like redux-saga. Effects generator returns plain objects exactly like actions.
Here sample code:

```javascript
function reducer(state, action)  {
    if (action == 'Action1') {
        return effected(state, function* {
            yield put({ type: 'AnotherAction' });
            yield take(x => x.type === 'AnotherAction2');
        })
    }
    return state;
}
```

In nature, effects is a stream of actions that bubbles up through composed reducers and can be transformed. For example:

```javascript
function reducer(state, action)  {
    if (action == 'Nested.Action1') {
        
        var [newState, effects] = splitEffected(nestedReducer(state, { ...action, type: action.type.replace(/^Nested\./, '') }))

        return effected[newState, effects::map(effect => {
            if (effect.type === 'PUT') {
                return { ...effect, action: { ...effect.action, type: 'Nested.' + effect.action.type } };
            }
            return effect;
        })
    }
    return state;
}
```

Another example: bubbling side effects and can be handled at any level of reducer composition:

```javascript
function nestedReducer(state, action) {
    //...
    if (action == 'Action1') {
        return effected(state, function* () {
            var randomNumber = yield { type: 'GenerateRandomNumber', min: 10, max: 100 };
            yield put({ type: 'UpdateNestedValue', value: randomNumber });
        })
    }
    //...
}

function reducer(state, action)  {
    if (action == 'Action1') {
        
        var [newState, effects] = splitEffected(nestedReducer(state, action)

        return effected[newState, effects::map(effect => {
            if (effect.type === 'GenerateRandomNumber') {
                return call(function* () {
                    return getRandomInt(effect.min, effect.max)
                });
            }
            return effect;
        })
    }
    return state;
}
```

I have spent much time to solve problem of easy to reuse 'Confirmation dialog'. This approach solves it easily:

```javascript
function nestedReducer(state, action) {
    //...
    // I want to delete item with confirmation
    if (action == 'ConfirmedDelete') {
        return effected(state, function* () {
            var confirmed = yield { type: 'Confirm', text: 'Delete item?' };
            if (confirmed)
                yield put({ type: 'Delete', id: action.itemId });
        })
    }
    //...
}


function reducer(state, action)  {
    //...
    var [newState, effects] = splitEffected(nestedReducer(state, action)
    return effected[newState, effects::map(effect => {
        if (effect.type === 'Confirm') {
            return call(function* () {
                yield put({ type: 'ConfirmDialog.Show', text: effect.text });
                var confirmOrDiscard = yield take(x => x.type === 'ConfirmDialog.Discard' || x.type === 'ConfirmDialog.Confirm');
                if (confirmOrDiscard.type === 'ConfirmDialog.Confirm')
                    return true;
                return false;
            });
        }
        return effect;
    })
    //...
}
```

I create repository with enhancer for createStore that allow to write reducers like examples above. 
https://github.com/tihonove/reelm

Plese consider this approach and say 'dead' or 'can live'. 
I'am a newbie in front-end development and spent many time to write readable code, so this approach is 'can live’, I ready to provide more examples and recipes.

**Comment by recidive** [comment]
This is resolved in [redux-boot](https://github.com/choko-org/redux-boot). This centralizes all side-effects in middlewares, despite they are sync or async.

This helps reduce boilerplate and having a uniform way for grouping reducers and middlewares.
