### ISSUE TITLE
Would it be convenient to swap out warning.js with fbjs utils? 

### ISSUE THREAD

**Issue by ev1stensberg** [reactjs/redux#1594]
# Discussion 

As Redux is a part of the reactjs community repo, would it convenient to swap out `scr/utils/warning.js` with the warning utility the fbjs repo provides? This might seem like unnecessary work, but it would be alongside with the structure of the  other Facebook/React libraries.

**What do you think?**

**Comment by gaearon** [comment]
Thanks for the suggestion! I would prefer not to depend on fbjs so we have more control here. Redux doesn’t really any other utilities from it so I don’t see the point.
