### ISSUE TITLE
Any advice about CALLBACK STYLE component with isomorphic ?

### ISSUE THREAD

**Issue by mc-zone** [reactjs/redux#1596]
Redux is almost perfect when using it on server-rendering. But there is a question troubled me: How to design, or, deal with CALLBACK STYLE component with isomorphic state ?

If say I have a reusable Dialog component like this:

```javascript
// components/Dialog.js
class Dialog extends React.Component {
  constructor(props) {
    super(props);
  }
  render(){
    const { tips } = this.props;
    if(!tips.show) return null;
    return (
      <div>
        <h1>{'Tips!' + tips.title}</h1>
        <p>{tips.content}</p>
        <a href="javascript:;" onClick={()=> tips.onConfirm && tips.onConfirm()} >OK</a>
        <a href="javascript:;" onClick={()=> tips.onCancel && tips.onCancel()} >Cancel</a>
      </div>
    )
  }
}
module.exports = connect((state)=>{
  return {
    tips:state.tips,
  }
})(Dialog);

```

A reducer for `tips` like:
```javascript
// reducer/tips.js
const initialState = {
  show:false, 
  onConfirm:null,
  onCancel:null,
  title:'',
  content:'',
};

export default function tips(state = initialState, action) {
  switch (action.type) {
    case SHOW_TIPS:
      return $.extend({}, state, action.payload, {show:true});
    //...
    default:
      return state;
  }
}

```

Then it will be used in some scenarios that are related to **user interaction**. 
For exapmle:

```javascript
// action/draw.js
export function queryDraw(userid){
  return function(dispatch){
    return dispatch( fetchDrawRecordFromServer(userid) ).then((data)=>{
      if(data && data.canDraw){
        dispatch({
          type:SHOW_TIPS,
          payload:{
            title:'You have an opportunity to Lucky Draw!',
            content:'Get it right now?',
            onConfirm:()=>{
              dispatch( getDraw(userid) )
            }
          }
        })
      }else{
        dispatch({
          type:SHOW_TIPS,
          payload:{
            title:'Sorry, your opportunity has run out'
          }
        })
      }
    })
  }
}

// pages/DrawPage.js
class DrawPage extends React.Component {
  constructor(props) {
    super(props);
  }
  static isomorphicInit(dispatch){
      return dispatch( queryDraw() );
  }
  render(){
    return (
       //...
    )
  }
}

// entry/server.js
const store = initStore();
DrawPage.isomorphicInit(store.dispatch).then(()=>{
  //...
})
```

It worked well on client-side. But  I can't keep and pass callback functions (`onConfirm`, `onCancel` and so on) at isomorphic App with `initialState`: 

```javascript 
window.__INITIAL_STATE__ = ${JSON.stringify(initialState)}
```

One way I can think of to get them only on client-rendering but not on server-rendering, but maybe it will bring a little of platform-specific codes about fetch data and inital check.

Any advice or design pattern with this  ?

**Comment by sompylasar** [comment]
You shouldn't put any non-plain objects (e.g. functions) in your store.

The callbacks should be created where you render your Dialog: `<Dialog onConfirm={...} onCancel={...} {...dialogPropsFromStore} />`.

If you want to store the actions that should be dispatched on Dialog interaction, you can do that, but this will only work if these actions are not created as thunks (functions):
```
      if(data && data.canDraw){
        dispatch({
          type:SHOW_TIPS,
          payload:{
            title:'You have an opportunity to Lucky Draw!',
            content:'Get it right now?',
            // getDraw must return plain object.
            onConfirmAction: getDraw(userid)
          }
        })
      }
```

You can also store some constant that would mean what action you will have to create:
```
      if(data && data.canDraw){
        dispatch({
          type:SHOW_TIPS,
          payload:{
            title:'You have an opportunity to Lucky Draw!',
            content:'Get it right now?',
            onConfirmActionType: actions.GET_DRAW
          }
        })
      }
```

**Comment by mc-zone** [comment]
> You can also store some constant that would mean what action you will have to create:

@sompylasar Thanks for your advice. Maybe I should encapsulate every business to actions. I will check and rewrite my code.

**Comment by sompylasar** [comment]
Moving business logic into actions is not what I advised.

I advised you don't put non-plain objects into the store. You should **describe** the state with your store structure, and **describe** transitions of your app with the reducers. Describe means you use plain values (strings, numbers), arrays, objects.

This does not mean you should move the logic of building this description somewhere, it should remain in the reducer to remain predictable and testable.
