### ISSUE TITLE
Using redux with multiple modules (discussion)

### ISSUE THREAD

**Issue by saknarak** [reactjs/redux#1598]
If i have application structure like this.

App module
-> Home, Static pages
=> Setting module
----> General setting page
----> Other setting page
=> Module1 module
----> Page1 (list) page
-------> Page1.1 (edit) page
----> Page2 page
=> Module2 module
----> Page3 page
----> Page 4 page

App module always load

Setting, Module1, Module2 modules not load at the same time
and when I switch between module, I don't want to keep state of unloaded module

Pages in modules, I also don't want to keep state when switch between pages
But for sub page, Page1 to Page1.1, I want to keep state for parent page (Page1).

Is it possible in redux?
My idea is I have to create CLEAR_SETTING_MOD action to clear module state
before I leave setting module and switch to Module2 module.
Is it will work or not? Or another solutions, please suggest

**Comment by gaearon** [comment]
Yes, I expect this would work. Generally we encourage keeping the old state around for better user experience (e.g. immediate response to Back button) but this is up to you.
