### ISSUE TITLE
Please help me understand if / how I can use Redux

### ISSUE THREAD

**Issue by dimitryvolkov** [reactjs/redux#1599]
Hello All!

I have recently discovered ReduxJS and am trying to understand,whether or not I can use it. 
I have an app where I would dispatch "actions" (invoke a function) that would use some logic to in a "reducer" (said function) to mutate some global "state" (plain JS object).
Since Redux seems like a more mature and interesting implementation (sans the mutability) for the same issue, I thought I'd give it a try.

However, in my case some of the logic in my "reducer" relies on the state of a DOM node, as far as I can see this violates the concept of a "pure function", since it relies on something outside the scope of the state. Even if I pass along that DOM node with my "action" it might violate the concept
of "replayability" of said action, since every dispatch might have a different outcome depending on the state of that DOM node.
I would be happy to know if this can somehow fit inside the Redux box.

Another thing is the issue of mutability. I fully understand the benefits of immutability in large async applications, where multiple sources might affect some global state.
In my case however, I have one synchronous source, changing one global state, which causes me to doubt the benefits of making my state immutable.
Could anyone shed some light on this matter in the context of a synchronous stream of actions?

I know Redux isn't for everyone and it might not even be a match for my case but I still would very much like to learn and expand my knowledge on these subjects and would love to hear the opinions of some of the more experienced developers here.

Thank you very much for any help you can offer.

**Comment by gaearon** [comment]
>However, in my case some of the logic in my "reducer" relies on the state of a DOM node

Can I ask why this is the case?

**Comment by dimitryvolkov** [comment]
Thank you for your prompt response!
It's is actually one of several edge cases I have.

For the most part, the state can be derived from the previous state without any external side effects, but in my case I have found that referring to the DOM state might short-circuit most of the logic of my reducer and save me some time.

I have considered extracting that code into the action creator, passing along that dom state along with that action, that would cause the reducer to be indeed a "pure function" (according to my understanding) since the same input will always produce the same output state, but I am not sure if that is not cheating, since the action creator is now not entirely a pure function (not sure if that is even a must in Redux's world).

Also, though the reducer is now "pure" it still relies on some external information passed along with the action and not only the previous state, which I am not sure is the way to go.

Can you shed some light?

**Comment by adamdonahue** [comment]
> I have found that referring to the DOM state might short-circuit most of the logic of my reducer and save me some time.

This sounds suspiciously like premature optimization.  So are you saying you _can_ use Redux as is but that you want to somehow improve rendering by accessing or manipulating the DOM directly?

**Comment by dimitryvolkov** [comment]
Thank you for your answer!

It might be a minor optimization, though it isn't premature since I have tested the effects of it and found it effective enough to use it.

Regarding your second comment, I have no intention in manipulating the DOM (directly or indirectly), but some information found on the current state of the DOM might assist me in my logic so I chose to use it instead of spare it (that and the aforementioned minor performance boost).

Could you perhaps assist me in understanding if the choice of moving said logic to the action creator fits better in the model? As far as I can see, my looking at the DOM is not different than retrieving some information asynchronously from some remote resource via fetch(), but still I am unsure if it violates some concept Redux is trying to preserve.

**Comment by markerikson** [comment]
@dimitryvolkov : action creators absolutely _do not_ have to be pure, and in fact, are usually where most of an app's "impurities" live.  

A typical Redux code flow would have a component handling any needed DOM interaction, extracting the necessary data from a DOM event or element, and calling an action creator with all that data.  The action creator usually uses something like `redux-thunk` to enable additional logic and dispatching, and would handle stuff like AJAX requests.  However, while an action creator is often not "pure" in the strict side effects sense, it usually does not deal with the DOM directly, instead relying on what raw data it needs to be passed in as parameters.

Can you give some examples of what DOM state you actually are trying to refer to, and what the specific use cases are?  Might help use advise you better.
