### ISSUE TITLE
point-free bindActionCreators

### ISSUE THREAD

**Issue by mrtnbroder** [reactjs/redux#1607]
I'm writing a lot of these lines:

```
const mapStateToProps = ({ wat }) => ({ wat })
const mapDispatchToProps = (dispatch) => bindActionCreators({ modifySomething }, dispatch)

export default connect(mapStateToProps, mapDispatchToProps)(view)
```

it would be awesome if bindActionCreators could be used like this:

```
const mapDispatchToProps = bindActionCreators({ modifySomething })
```

So it would be point-free.

**Comment by markerikson** [comment]
Actually, if you just pass an object containing action creators as the second argument to `connect`, it already does almost exactly what you want - it just doesn't include `dispatch` in the output.

You can also write your own small utility function to handle this.  I personally happen to like having all my actions pre-bound, and available as a prop named "actions", so I wrote this helper:

```js
export function prepareActions(actions) {
    return (dispatch) => ({
        actions : bindActionCreators(actions, dispatch),
    });
}
```

**Comment by mrtnbroder** [comment]
Well, **I could** do that. But first-level support right from the library is what I am looking for 😄 It's just a simple matter of curring the bindActionCreators function.

It would not even break anything as you could still use it the same way.

**Comment by gaearon** [comment]
Any reason why

>Actually, if you just pass an object containing action creators as the second argument to connect, it already does almost exactly what you want - it just doesn't include dispatch in the output.

Doesn’t help?

>It's just a simple matter of currying the bindActionCreators function.

As well as the cost of adding documentation, answering questions on StackOverflow about incorrect usage, having people forget to pass the second argument and wonder why they got a function in return, etc. :smile:

**Comment by mrtnbroder** [comment]
I totally read @markerikson comment wrong. Just passing the object is totally fine!

>As well as the cost of adding documentation, answering questions on StackOverflow about incorrect usage, having people forget to pass the second argument and wonder why they got a function in return, etc. :smile:

If you don't break existing behaviour, then I don't see where stackoverflow will be flooded with questions :D

Anyway, I'm happy now, but I'll leave the decision to close this issue to the collaborators.

**Comment by gaearon** [comment]
I’ll close this but if more people request it I’m open to adding this.
Cheers!
