### ISSUE TITLE
add the 'key' to the reducer callback

### ISSUE THREAD

**Issue by xiejunfeng** [reactjs/redux#1635]
hi, when dynamically generating reducer, the attributor of key may be used. Would you add this attributor to your source? or another better solution for this case ?

at line 129 in the combineReducers.js
```JS
//var nextStateForKey = reducer(previousStateForKey, action)
var nextStateForKey = reducer(previousStateForKey, action, key)
```

**Comment by gaearon** [comment]
We don’t plan to add use for third argument in `combineReducers` (we keep getting requests with people asking to put different things there which means we shouldn’t force either of those solutions). I would suggest just writing reducer by hand in this case:

```js
// instead of
const reducer = combineReducers({ a, b })

// write
function reducer(state = {}, action) {
  return {
    a(state.a, action, 'a'),
    b(state.b, action, 'b')
  }
}
```
