### ISSUE TITLE
jsnext:main should point to src

### ISSUE THREAD

**Issue by reggi** [reactjs/redux#1643]
This line in the package.json 

https://github.com/reactjs/redux/blob/master/package.json#L6

Shouldn't it be changed from `es/index.js` to `src/index.js`?

https://github.com/rollup/rollup/wiki/jsnext:main

**Comment by reggi** [comment]
hmmmmm I think I'm wrong again.

**Comment by markerikson** [comment]
Feedback is appreciated, but in the future it would help if you could hold off on filing issues until you're sure that there's definitely a problem.

If you have questions, you might also be able to get some feedback by asking over in the Reactiflux chat channels on Discord, which you can join at http://www.reactiflux.com.  There's a lot of developers who hang out over there that can help answer questions.
