### ISSUE TITLE
componentWillMount is called twice.

### ISSUE THREAD

**Issue by xueqingxiao** [reactjs/redux#1646]
LoginCompontent
```js
  componentWillReceiveProps(nextProps) {
    const router = this.context.router;
    const { query } = this.props.location;
    if (!nextProps.success) {
      return;
    }
    switch (nextProps.data.code) {
      case 0:
        query.next ? router.push(query.next) : router.push('/');
        break;
      case 1:
        break;
      default:
        break;
    }
  }
```
CategoryCompontent
```js
  componentWillMount() {
    const { params } = this.props;
    this.props.fetchCategories(params.id);
  }
```
Result
<img width="559" alt="screen shot 2016-04-20 at 4 56 23 pm" src="https://cloud.githubusercontent.com/assets/4010906/14668975/395c3190-0719-11e6-88e5-c3410c27a6c0.png">

**Comment by gaearon** [comment]
Hi!

Redux is a library that contains one thing: an event emitter that calls your reducer function. It can’t possibly be responsible for calling your React components. So it is not a bug here, and StackOverflow might be a better place to ask about this. 

The lifecycle books are managed by React. If you see that `componentWillMount` runs twice it means the component was unmounted between those calls for some reason. You can set a breakpoint in `componentWillIUnmount` you can check the stack trace to see what is causing the component to unmount. 

I hope this helps!

**Comment by thegourav** [comment]
componentWillUnmount typo
