### ISSUE TITLE
Warn when no state update occurs as result of an action

### ISSUE THREAD

**Issue by brigand** [reactjs/redux#1667]
I'm not sure if this is possible for redux to do, or if middleware could be written for this.

It's similar to how redux warns when an action's type is undefined, but also helps people not using constant files. It would also help to identify accidental mutations of state because they would report that nothing has changed, instead of the ui just not updating.

The "downside" to this is that you have to handle all actions, including ones you don't care about, by e.g. `case 'FOO_FAILED': return {...state}`. I think this is very positive because it forces you to think about all possibilities in your application, and makes silencing errors a deliberate act.

This probably shouldn't be enabled by default unless feedback shows it's helpful to more people than it annoys.

**Comment by markerikson** [comment]
We actually just had someone else post about this yesterday, and I linked to an existing middleware that dose this already.  See https://github.com/reactjs/redux/issues/1662.

**Comment by brigand** [comment]
Thank you! :-)
