### ISSUE TITLE
`isDispatching` really needed?

### ISSUE THREAD

**Issue by anler** [reactjs/redux#1668]
Hi! Just a comment/question about something I've seen in the `dispatch`'s code in `createStore.js` (see the code below). I was wondering why is variable `isDispatching` needed, if there are two concurrent calls to `dispatch` the `isDispatching` check is pointless because is not inside a mutex:

![image](https://cloud.githubusercontent.com/assets/83847/14812050/a1ae08d2-0b9b-11e6-891f-dc4cb0bd7bbd.png)

But as far as I know, JS' runtime can only execute one thing/function at a time so two _concurrent calls_ to dispatch will never happen and if that's the case I don't see the need for `isDispatching` right?

Can you tell me if I'm missing something? Thanks!

--

https://github.com/reactjs/redux/blob/master/src/createStore.js#L149
```js
function dispatch(action) {
  // ...
  if (isDispatching) {
    throw new Error('Reducers may not dispatch actions.')
  }

  try {
    isDispatching = true
    currentState = currentReducer(currentState, action)
  } finally {
    isDispatching = false
  }
  // ...
}
```

**Comment by brigand** [comment]
It catches this case, dispatching from within a reducer.

```js
var store = createStore((state, action) => {
  store.dispatch({type: 'ANOTHER_ACTION'});
});
```

**Comment by anler** [comment]
Oh I see, now is clear, is dispatching from within a reducer forbidden to avoid things such as loops (reducer -> dispatch -> reducer ->...) am I right?

Thanks!

**Comment by gaearon** [comment]
Yep.
