### ISSUE TITLE
Page title on redux.js.org is broken (due to the new logo)

### ISSUE THREAD

**Issue by 17cupsofcoffee** [reactjs/redux#1672]
Hey, not sure if this is the right place to raise this issue, but just something I noticed on the website - since the top-level heading of README.md is now an image, the title of the page (i.e. what comes up on the tab) is now showing the markup of the image rather than "Redux". This also shows up when you mouse over the top of the page:

![image](https://cloud.githubusercontent.com/assets/784533/14826825/98cfe0dc-0bd7-11e6-96b8-780893d064d7.png)

Does GitBook offer a way to override that?

**Comment by gaearon** [comment]
Thanks for reporting. I wonder!

**Comment by gaearon** [comment]
Fixed in 52fb47391f43530979b867ff1b6c781d9ceab661.
