### ISSUE TITLE
JavaScript 'strict mode';

### ISSUE THREAD

**Issue by giantelk** [reactjs/redux#1674]
Wondering why you aren't using JavaScript `'strict mode'; `

Any plans to use strict mode? Will it break things? I see ReactJS source uses strict mode, so wondering why Redux isn't? 

Thanks!

**Comment by acdlite** [comment]
Strict mode is implicit inside ES6 modules.

**Comment by giantelk** [comment]
OK, so what happens on the browser side with browsers that don't support ES6? Not a concern? Which browsers & versions support ES6!

**Comment by Aweary** [comment]
@giantelk babel injects `'use strict'` statements when redux is transpiled for production. Check your `node_modules/redux/dist/redux.js` if you're using `npm`, you'll see them all over the place.

**Comment by gaearon** [comment]
Yes, it's part of the compilation process before the package gets published on npm.
