### ISSUE TITLE
Wrong scope for obervables?

### ISSUE THREAD

**Issue by micha149** [reactjs/redux#1675]
I was speculating, that this may be an [issue of the redux-devtools](https://github.com/gaearon/redux-devtools/issues/274) but after studying the redux code I am not sure anymore. When the devtools chrome extension is activated, my observable transports the devtools state instead of my app state. I could imagine, getState() is called in a wrong scope, or something like this. Did anyone understand where the problem came from?

**Comment by gaearon** [comment]
I think we have to override `obervable` in DevTools now just like we do with `getState`. Feel free to send a PR!

**Comment by micha149** [comment]
Thanks for the hint. I'll have a look on this.

**Comment by micha149** [comment]
I implemented the observable in the devtools, which resolves the issue. But I'm not 100% sure if this is an elegant solution… https://github.com/gaearon/redux-devtools/pull/275

**Comment by gaearon** [comment]
Yeah, it's not very cool but does the job. I'll look at this again before cutting 4.0 because there might be a better solution.
