### ISSUE TITLE
Add Enzyme to redux testing docs

### ISSUE THREAD

**Issue by tylercollier** [reactjs/redux#1679]
In #1481, you suggested using Enzyme in tests, and I can see that people helped take this on and get the example apps set up with Enzyme testing. However, Enzyme is not used in the example in [the Redux "Writing Tests" doc](http://redux.js.org/docs/recipes/WritingTests.html).

Do you want me to add it there? I can submit a PR for you to check out. For the prose section, I plan to say something like "Facebook provides a basic helper library called [ReactTestUtils](https://facebook.github.io/react/docs/test-utils.html) for testing React components. Here we'll show how to test your component using Airbnb's [Enzyme](http://airbnb.io/enzyme/), which uses ReactTestUtils internally, and makes our job of testing easier and provides additional functionality."

PS: I read the guidelines for contributing and wasn't sure if I should add this to #1481 or start a new case. Sorry if I chose wrong. :-)

**Comment by gaearon** [comment]
Sure, please send a PR to the doc!
