### ISSUE TITLE
Priority for action dispatches

### ISSUE THREAD

**Issue by phsoul** [reactjs/redux#1680]
Hello, have been working with redux for quite a while now. Can honestly say loving it. One thing I noticed that by working with bigger applications that have multiple actions being dispatched via thunks, they always bubble to root. Is there a way to control this without altering the structure? There are some cases, when you want to order Action calls, or force that no other child invoked actions would be called before the current finishes? If its a architecture or a implementation problem, would greatly appreciate some pointers on how to deal with this.

Thanks!

**Comment by markerikson** [comment]
Can you clarify what you mean by "bubble to root", and "order actions"?  

Redux only dispatches a single action at a time.  You can technically do another dispatch in the store's subscription callback, but that has to be done conditionally or else you wind up with an infinite loop.

It might also help if you can describe your use case further.

**Comment by gaearon** [comment]
Does this help? https://github.com/reactjs/redux/issues/1676#issuecomment-215413478
If you return Promises from thunks, you can chain asynchronous operations.

**Comment by phsoul** [comment]
I will try to provide a detailed view:
The problem i was face'ing was i needed a subscriber to conditionally dispatch a couple of actions on every action made in the application. so The subscriber should go: 1,2,3 then the action that is done via the child Component 4,5,6.
The result i was getting was 1,4,2,3 etc..
Using a promise to resolve and chain did the trick.
Thank You!

**Comment by gaearon** [comment]
>i needed a subscriber to conditionally dispatch a couple of actions on every action made in the application

I'm afraid this is generally an anti pattern that we don't recommend. Can you tell more about your use case? Why did you need this?

**Comment by phsoul** [comment]
The basic functionality i need is data fetching on state initialization. No matter what route the app is in, it should populate the initial state with data from a certain API. There are cases when the data is page specific, and some where its global to the whole app, like user data on authentication, dynamic sidebar content. this generally sits in the root component and is used by multiple child components. The further expand on the problem i was face'ing, during the initial request, I would normally have a indicators in the state that would tell me if the global data is loaded or needs to be refreshed. This loads of a subscriber. Since the action was a thunk, the initial load, would dispatch a couple of actions one after a another. This would overlap. Firing one action from the subscriber, and one from the components lifecycle ComponentWillMount, this returns a error, since the state does not contain the desired data yet. One other option i could think of was rerendering when the props are present.
