### ISSUE TITLE
Real world example si stuck loading due to upper cases

### ISSUE THREAD

**Issue by Zhouzi** [reactjs/redux#1684]
Hey there!

GitHub's api is case insensitive, which means that searching for the user "zhouzi" will result in "Zhouzi" and "zhouzi/theaterjs" in "Zhouzi/TheaterJS". Right now, it's causing the UI to be stuck loading because there's no "zhouzi" user in the entities (but there's "Zhouzi").

**Comment by gaearon** [comment]
Thanks for the fix!
