### ISSUE TITLE
npm ERR! extraneous， How to fix

### ISSUE THREAD

**Issue by caojinli** [reactjs/redux#1691]
I got many error of npm, "npm ERR! extraneous" when I use command "npm ls", I don't know if it should fix necessary.

**Comment by caojinli** [comment]
npm ERR! extraneous: inline-style-prefixer@1.0.2 D:\react\react-redux-starter-kit\node_modules\inline-style-prefixer
npm ERR! extraneous: isomorphic-fetch@2.2.1 D:\react\react-redux-starter-kit\node_modules\isomorphic-fetch
npm ERR! extraneous: keycode@2.1.1 D:\react\react-redux-starter-kit\node_modules\keycode
npm ERR! extraneous: lodash.merge@4.3.2 D:\react\react-redux-starter-kit\node_modules\lodash.merge
npm ERR! extraneous: lodash.throttle@4.0.1 D:\react\react-redux-starter-kit\node_modules\lodash.throttle
npm ERR! extraneous: react-event-listener@0.1.1 D:\react\react-redux-starter-kit\node_modules\react-event-listener
npm ERR! extraneous: recompose@0.15.1 D:\react\react-redux-starter-kit\node_modules\recompose
npm ERR! extraneous: redux-logger@2.6.1 D:\react\react-redux-starter-kit\node_modules\redux-logger
npm ERR! extraneous: simple-assign@0.1.0 D:\react\react-redux-starter-kit\node_modules\simple-assign
npm ERR! extraneous: whatwg-fetch@0.9.0 D:\react\react-redux-starter-kit\node_modules\whatwg-fetch

**Comment by markerikson** [comment]
This has nothing to do with Redux, and you already posted this in the other issue.  Please stop.

**Comment by polyakoff** [comment]
_**For all the future googlers who will end up here...**_
It’s probably safe to ignore this error. But you can clean up the unnecessary packages with
`$ npm prune`

**Comment by jeffersonnnn** [comment]
i appreciate youuuuu
