### ISSUE TITLE
STICKERS

### ISSUE THREAD

**Issue by export-mike** [reactjs/redux#1695]
Love the project, love the logo, got a laptop here with some space available for a redux sticker! :D where can I get one?

**Comment by gaearon** [comment]
Haha good question. Anything we can do on our end?

**Comment by export-mike** [comment]
Hexagon shape would be pretty damn awesome!

**Comment by export-mike** [comment]
Last I read theres two standards for the correct dimensions. I think we should be compliant. I'm hunting down the spec.

**Comment by export-mike** [comment]
here's the spec being used at the London Node User Group (LNUG) and other meetups. https://github.com/terinjokes/StickerConstructorSpec

**Comment by export-mike** [comment]
potential vendors: https://github.com/terinjokes/StickerConstructorSpec/wiki/Vendors

**Comment by Aweary** [comment]
FWIW I'd like to purchase a non-hexagonal Redux sticker if possible 😄  [Something like this](http://www.redbubble.com/people/miney/works/12005581-git) with the Redux logo and name

**Comment by export-mike** [comment]
@Aweary that looks cool, yeah I think it'd be great to have an assortment

**Comment by acdlite** [comment]
Stickers are nice. I want a shirt.

**Comment by export-mike** [comment]
@acdlite thats a seperate issue :D

**Comment by mxstbr** [comment]
Yeah we definitely need hexagon and non-hexagonal stickers.

**Comment by Aweary** [comment]
@acdlite I put up a [Teespring campaign for a basic Redux shirt](https://teespring.com/redux-shirt). I figure we can donate any of the profits to a charity chosen by the community or something? As long as that's OK with @gaearon

**Comment by omnidan** [comment]
@acdlite 
![why not both?](https://media.giphy.com/media/3o85xIO33l7RlmLR4I/giphy.gif)

**Comment by gaearon** [comment]
>I figure we can donate any of the profits to a charity chosen by the community or something?

Sounds great to me.

**Comment by export-mike** [comment]
Can I suggest one charity if no body minds? It's for Huntingtons disease, my family has been affected by this horrid disease and many millions of other families, it still exists in my family today. Here is the UK charity it's a rare disease if you haven't heard of it; the symptoms are very similar to parkinsons. http://hda.org.uk

**Comment by Aweary** [comment]
@export-mike I've opened an issue here to discuss charities: https://github.com/reactjs/redux/issues/1696

Definitely post it there 👍

**Comment by kennetpostigo** [comment]
Hey guys,
Put a hexagon sticker for redux up on the stickermule market place last week:
https://www.stickermule.com/marketplace/11935-redux-sticker

**Comment by timdorr** [comment]
@Aweary I believe the TeeSpring crew can do die cut stickers now. Get it contact with them. They've been great to work with in the past.

**Comment by Aweary** [comment]
@timdorr I'll look into that, thanks. I didn't see a way to add additional items to an already launched campaign, so I'm not 100% sure I could add them to this current one but I'll look into it.

**Comment by timdorr** [comment]
Yeah, they can do all manner of fancy stuff behind the scenes. I've seen them do coffee cups and other schwag-y items too.

**Comment by Aweary** [comment]
Awesome, I sent them an email 👍

**Comment by DavidBrear** [comment]
Hey guys, I saw that the TeeSpring campaign failed to get enough people. Any update on t-shirts or stickers?

**Comment by gilbarbara** [comment]
Hey,
Plain (pure) redux sticker without the hexagon: https://www.stickermule.com/marketplace/12673-redux

**Comment by timdorr** [comment]
@gilbarbara Looks like that's not officially sanctioned, so none of the proceeds there go back to the devs here or an appropriate charity/fund.

**Comment by hpurmann** [comment]
I really like the sharp and clear stickers from unixstickers. If we [all vote on this Trello item](https://trello.com/c/xHMH0URm/442-redux-stickers), they will create a Redux Sticker for us. Please give it a vote in case you have a Trello account.

**Comment by timdorr** [comment]
I'm closing this for now only because nothing has really materialized. If someone wants to lead an effort to buy some schwag or set up a crowdfunded effort to do so (with profits going to an appropriate charity or two), please feel free to set up a new issue to track that specific project.
