### ISSUE TITLE
Select charity for Redux apparel sales

### ISSUE THREAD

**Issue by Aweary** [reactjs/redux#1696]
https://teespring.com/new-redux-apparel
https://teespring.com/redux-apparel-dark

I've setup a Teespring campaign with some basic shirts/a hoodie rocking the new Redux logo. I want all the proceeds to be donated to a charity that the community can decide on. I was hoping we could use this issue to discuss and (possibly) vote on a charity the proceeds could go to.

### Finding a Good Charity

I highly recommend Charity Navigator: http://www.charitynavigator.org/ for finding a charity that will donations effectively.

**Comment by export-mike** [comment]
Can I suggest one charity if no body minds? It's for Huntingtons disease, my family has been affected by this horrid disease and many millions of other families, it still exists in my family today. Here is the UK charity it's a rare disease if you haven't heard of it; the symptoms are very similar to parkinsons. http://hda.org.uk

**Comment by Aweary** [comment]
@timdorr @gaearon if you guys wouldn't mind spreading the word on social media that would be immensely helpful. I've got 2/15 orders required to print the shirts and I'd love to hit the goal so we can get some money to donate 😄

**Comment by Aweary** [comment]
Update: we have 7 out of the minimum 15 orders required for the shirts to ship 😄  this is up from 2 this morning, so we're getting there!

**Comment by gaearon** [comment]
Can we have a dark design? The logo has a version with light text.

**Comment by Aweary** [comment]
@gaearon I didn't have the option to add a second type of shirt (which would be required since it's a different image) but I'm going to reach out to Teespring and see if I can get another shirt type added 👍 

Otherwise I might just start a second campaign with the dark design if they can't do that for us.

**Comment by orlando** [comment]
@Aweary can we have ones just with the logo?

**Comment by export-mike** [comment]
+1 @orlando ha no emojis on mobile website

**Comment by hsrobflavorus** [comment]
I'm in to buy one if we can do one in black/navy or another dark color. I can't trust myself around light colored shirts due to my propensity to spill coffee and various hot sauces.

**Comment by Aweary** [comment]
@gaearon @hsrobflavorus Teespring hasn't gotten back to me on adding additional shirts with new art, so here's a separate campaign with the dark shirts: https://teespring.com/redux-apparel-dark

**Comment by hsrobflavorus** [comment]
@Aweary Ordered one of the black shirts, hopefully we'll meet the minimum!

**Comment by Aweary** [comment]
That reminds me, I wanted to note that the initial campaign did meet its minimum so it will ship! We have a whopping $7 in profit that can be donated so far 😄  hopefully we can get this shared on social media and get more of the community aware.

**Comment by kuy** [comment]
Cool! Can I merge my orders on both campaigns to save shipping cost? @Aweary

**Comment by kuy** [comment]
Bad news, Dark version was gone. https://teespring.com/redux-apparel-dark

**Comment by Aweary** [comment]
It ended without enough orders to ship. Unfortunately there was not enough attention/interest here so it didn't meet the goal.

**Comment by rickharrison** [comment]
I just reserved it again. I'm sure we could find 20 people who want a redux dark shirt. We just need to get the word out!

**Comment by birdwell** [comment]
I would love to reserve a dark shirt! Put me down as one person.

**Comment by timdorr** [comment]
Looks like the campaigns are over, so I'm closing this out for new. If you want to run a new one or sell via some other means, I can reopen this for you or you can start a new issue to track the effort. Thanks for the efforts organizing this, @Aweary!
