### ISSUE TITLE
Potential future bug in Redux - React docs

### ISSUE THREAD

**Issue by opensrcken** [reactjs/redux#1700]
Regarding http://redux.js.org/docs/basics/UsageWithReact.html, in the sample code for `components/Footer.js` (copied below for convenience), a container is nested in a component. `Footer` is defined as a Stateless Functional Component, and yet it "knows" about the app state via the nested container.

This may cause a bug in the future because of the following snippet from the React docs:
```
In an ideal world, most of your components would be stateless functions 
because in the future we’ll also be able to make performance optimizations
specific to these components by avoiding unnecessary checks and memory
allocations. This is the recommended pattern, when possible.
```

My reading of this is that in the future, if React detects the props have not changed, it will not re-render SFC's, which means that the sample code in the Redux docs could lead to a future bug.

``` javascript
import React from 'react'
import FilterLink from '../containers/FilterLink'

const Footer = () => (
  <p>
    Show:
    {" "}
    <FilterLink filter="SHOW_ALL">
      All
    </FilterLink>
    {", "}
    <FilterLink filter="SHOW_ACTIVE">
      Active
    </FilterLink>
    {", "}
    <FilterLink filter="SHOW_COMPLETED">
      Completed
    </FilterLink>
  </p>
)

export default Footer
```

**Comment by Aweary** [comment]
The react-redux `connect` wrapper subscribes directly the redux store, which would also be available via context. It shouldn't matter if a parent component does not update. The subscription handler will invoke the `handleChange` method on the wrapping class and update the component that it's wrapping.

**Comment by gaearon** [comment]
Yeah, `connect` uses sideways subscriptions to Redux store so it circumvents any optimizations React components above might have.

**Comment by opensrcken** [comment]
Thanks for clarifying. From a conceptual standpoint, does the example code violate the expectations that the output of an SFC will be pure in its inputs?
