### ISSUE TITLE
Update WritingTests to not use arrow functions

### ISSUE THREAD

**Issue by mlippens** [reactjs/redux#1703]
Mocha advises against using arrow functions, so it seems wrong to me to use them in WritingTests.md as an example.

**Comment by SimenB** [comment]
Why? Because of magical `this`?

**Comment by froginvasion** [comment]
That's what they say in the documentation of mocha, though myself I have not run into any issues with it so far.

**Comment by rosskevin** [comment]
Mocha doesn't want you to use arrow functions only so that you can access the mocha instance to set expirations etc, otherwise, arrow functions work just fine.  I expect Mocha will need to adapt that approach soon as since the arrow fn syntax is being adopted quickly and since node 6 is out.

**Comment by SimenB** [comment]
Node 4 supports arrow functions as well

**Comment by GGAlanSmithee** [comment]
If you need the Mocha context, only the outer most function must not be an arrow function.
