### ISSUE TITLE
Question: Where do helper and utility methods go?

### ISSUE THREAD

**Issue by ashwinputhige** [reactjs/redux#1709]
If I have a `UserInfo` component with `UserInfoActions` and `UserInfoReducer`.
The server returns user data such as
```
{
    fName: "first",
    lName: "last",
}
```
In which file do I put helper methods?
Example:  `getFormattedName()` which returns `Fname Lname` in titlecase?
Should I put the method directly in the Component file or should I create a separate `UserInfoHelper` file for such methods?

Also, if `getFormattedName()` is to be shared among multiple components, where should it go?

**Comment by gaearon** [comment]
[Redux has no opinion on the file structure of your application.](http://redux.js.org/docs/FAQ.html#structure-file-structure)

>Should I put the method directly in the Component file or should I create a separate UserInfoHelper file for such methods?

Both ways work fine.

>Also, if getFormattedName() is to be shared among multiple components, where should it go?

Anywhere you like, e.g. in the same folder as components, or in a special `utils` folder. This makes no real difference so please do as you like best.

**Comment by ashwinputhige** [comment]
Thanks @gaearon for your response.

**Comment by tylerlong** [comment]
Please check my answer: https://stackoverflow.com/a/44742666/862862

Nowadays the best practice is to put the code into 'utils/' folder:

- src/
    - components/
        - ...
    - reducers/
        - ...
    - **utils/**
        - ...
