### ISSUE TITLE
Links to markdown prompt a download

### ISSUE THREAD

**Issue by chmac** [reactjs/redux#1711]
See here http://redux.js.org/docs/advanced/index.html

This link does not render, but prompts to download the markdown file.

http://redux.js.org/docs/advanced/UsageWithReactRouter.md

Once you eventually track it down here in the repo (or download and open it), you discover it's coming soon. Would be cool if there was an easy way to flag that directly in the docs.

**Comment by gaearon** [comment]
Yeah. The real fix would be to write that document.
I’m waiting for some React Router 3.0 changes to get to it.
I’ll probably close because this is going to be irrelevant soon.
