### ISSUE TITLE
Dispatch a redux action from an external javascript module

### ISSUE THREAD

**Issue by rpnna** [reactjs/redux#1714]
Hi guys,
I'm working on a react/redux application, which makes use of an external module (written in plain javascript):

```javascript
module.exports = {
    ...
    // Some functions here..
    someFunction () {
        dispatch(setSomething());
    }
    ...
};
```
I need to dispatch an action on the existing store, previously built and linked to the React application. 
What's the best way?

Thank you

**Comment by gaearon** [comment]
This is just JavaScript, so the answer is the same as with any JavaScript code.
If you need a module to have access to a function, pass that function to that module.

```js
module.exports = {
  someFunction (dispatch) {
    dispatch(setSomething());
  }
};
```

or

```js
module.exports = function (dispatch) {
  return {
    someFunction () {
        dispatch(setSomething());
    }
  }
};
```

Finally, you can (if you really want) put a store in a separate module as a singleton, but this makes testing and universal apps considerably harder.

**Comment by rpnna** [comment]
@gaearon thanks, I also have solved this way, it was a fake problem..I really appreciate your work and this project.
