### ISSUE TITLE
Import of redux results in undefined

### ISSUE THREAD

**Issue by JacobSoderblom** [reactjs/redux#1719]
Hi!

I'm trying to setup redux for my react app, but I get some weird errors.

I import the library like this:

`import { createStore, applyMiddleware, compose } from 'redux';`

And when using applyMiddleware I get Uncaught TypeError: Cannot read property 'apply' of undefined

`const enhancer = compose(
      applyMiddleware(...middlewares)
);`

When sending the imported functions from redux to the console I just get undefined. 
I might have missed something, but this is how I done with the older versions, see below.

```javascript
import { createStore, applyMiddleware, compose } from 'redux';
import thunk from 'redux-thunk';
import createLogger from 'redux-logger';
import { Iterable } from 'immutable';
import callAPIMiddleware from './middleware/callAPIMiddleware';
import rootReducer from './reducers';
import initialState from './initialState';

export default function () {
  const middlewares = [thunk, callAPIMiddleware];
  console.log(createStore); // undefined
  console.log(applyMiddleware); // undefined
  console.log(compose); // undefined
  let store;
  if (__DEVELOPMENT__) {
    const stateTransformer = (state) => {
      if (Iterable.isIterable(state)) return state.toJS();
      return state;
    };
    const logger = createLogger({
      stateTransformer,
    });
    middlewares.push(logger);
    const enhancer = compose(
      applyMiddleware(...middlewares) // Uncaught TypeError: Cannot read property 'apply' of undefined
    );
    store = createStore(rootReducer, initialState, enhancer);
  } else {
    store = createStore(rootReducer, initialState, applyMiddleware(...middlewares));
  }
  return store;
}
```

Best regards

**Comment by TrySound** [comment]
@JacobSoderblom What is your build config? Also you do you use `compose` around `applyMiddleware`?

**Comment by JacobSoderblom** [comment]
@TrySound The build config is just standard Webpack, nothing fancy in there. Do you need the code?

I use `compose` around `applyMiddleware` because I'm going to apply DevTools later on. But I have tried to removed it, and it's the same.

**Comment by sacho** [comment]
Can you try to `import redux from 'redux'` and see what the exported object is? You may be importing some other module named 'redux' instead of redux itself. You could debug that by running webpack's build with  `--display-reasons --display-modules`, which should show how imports are resolved.

**Comment by JacobSoderblom** [comment]
@sacho @TrySound Thank you for your help, I found the problem. And it has nothing to do with Redux. It had to do with the Webpack build config as @TrySound said.

Sometimes you just stare at your code for too long..

**Comment by azmenak** [comment]
@JacobSoderblom any ideas what this issue ended up being? Running into the same problem now and I'm totally stumped.

**Comment by batjko** [comment]
I'm getting this error during testing. When starting the app (with webpack) it all works fine.
But when running mocha tests (with jsdom and babel-register), I get this error (`Cannot read property 'apply' of undefined`).

**Comment by se-panfilov** [comment]
@JacobSoderblom Can you say pls, what was your error? Ran into the same issue...

**Comment by trenunu** [comment]
@azmenak @se-panfilov have you two figured out what was the issue?
