### ISSUE TITLE
i can see data is there in the state but when i try to access the state it's undefined.

### ISSUE THREAD

**Issue by kishanj918** [reactjs/redux#1732]
I am using react-router and redux. I am fetching data on onEnter hook of react router.

**ISSUE**
Now the issue is very strange. When i navigate from other page to landing page event got successfully dispatched,data is there in the state (check screenshots) but when i try to log it in the componentDidMount it is undefined. I don't know what am i missing. A little help will be useful..

react router onEnter hook

```
function loadData(nextState, replace,callback) {
  Progress.show()
  if (nextState && nextState.routes.length > 0) {
    console.log(nextState)
      let data  = configureStore().dispatch(fetchLandingPageData())
    data.then((res)=>{
      Progress.hide()
      callback()

    })
  }
}

<Route path="/" component={App}>
        <IndexRoute component={LandingPage} onEnter={loadData}/>
</Route>
```
Here is my reducer
```
function LandingPageReducer (state = {}, action) {
  let cloned;
  switch(action.type) {
    case constants.FETCH_INDEX:
        cloned = _.clone(state)
      return _.merge(cloned,action.response)
    default:
      return state;
  }
}
```

my combined reducer

```
const rootReducer = combineReducers({
  landingPage
});
```

Component's code
```
componentDidMount() {
      console.log(this.props.data) //output:-  Object {}
  }

function mapStateToProps(state) {
  return {
    data: state.landingPage //my landing page's state is in state.landingPage
  };
}
```
![screen shot 2016-05-16 at 10 23 40 am](https://cloud.githubusercontent.com/assets/3994657/15280836/c26374ec-1b52-11e6-993d-3770861e4ae9.png)
![screen shot 2016-05-16 at 10 23 53 am](https://cloud.githubusercontent.com/assets/3994657/15280835/c26324b0-1b52-11e6-89af-e452bf808136.png)

**NOTE**
first screen shot is of after action got dispatched
second one is of when i log data into componentDidMount.

**Comment by gaearon** [comment]
This looks like a usage question. Please use StackOverflow for this. You are posting in the issue tracker, which is used for bugs and feature requests. 

I am closing but feel free to share a link to your question on StackOverflow! Thanks.

**Comment by gaearon** [comment]
That said `configureStore` *creates a store*. You should only create it once.

Make your route configuration a function that accepts store as an argument, and returns the routes. Then you can pass it from outside, right from the place where you really create it. I assume you do this somewhere in `index.js`. 

You should not ever need to call `configureStore` twice in a client side app.

**Comment by kishanj918** [comment]
@gaearon  Hi Dan thanks for the answer it worked. I have updated my code.. 

```
function loadData(store) {
  return (nextState,replace,callback) => {
    if (nextState && nextState.routes.length > 0) {
      let data  = store.dispatch(fetchLandingPageData())
       //error : TypeError: Cannot read property 'dispatch' of undefined  (on page refresh) 
      data.then((res)=>{
        callback()

      })
    }
  }

}
```
But what i am now facing is when i refresh the page ,i  am getting this error.
```
TypeError: Cannot read property 'dispatch' of undefined
```
 would you mind take a look into that?

**Comment by gaearon** [comment]
I think it means you are passing `undefined` instead of the `store` into `loadData`.
