### ISSUE TITLE
Documentation for testing async actions with nock

### ISSUE THREAD

**Issue by hlavacek** [reactjs/redux#1733]
Hi,

In the docs for [Writing tests](http://redux.js.org/docs/recipes/WritingTests.html) in the chapter for Async Action Creators the example uses fetch and suggests using [nock](https://github.com/node-nock/nock) for mocking http requests. But be because of https://github.com/node-nock/nock/issues/409 the example isn't really working in browser tests (at least from what I've tried). 

Would it make sense to update the docs? Maybe add an with example using [fetch-mock](https://github.com/wheresrhys/fetch-mock) (that's where I ended up after trying nock).

**Comment by gaearon** [comment]
I would recommend doing something like this instead: https://github.com/reactjs/redux/issues/1716.

**Comment by hlavacek** [comment]
It seems like a nice way to do dependency injection and to put tests for api "out of scope" for redux documentation, although might be still good to keep example around, as many people would use fetch for rest api calls and the api should be tested. 

Btw in the example of the action creator in #1716, there it is missing a return of the promise in the inner function, to be able to wait for it in the tests right?
