### ISSUE TITLE
Add favicon to the website

### ISSUE THREAD

**Issue by gaearon** [reactjs/redux#1735]
This from https://learnredux.com looks rad:

<img width="205" alt="screen shot 2016-05-16 at 15 50 06" src="https://cloud.githubusercontent.com/assets/810438/15293123/6998b6ca-1b7e-11e6-80dc-2dfc19d5bd53.png">

We should do it too!

**Comment by timdorr** [comment]
@wesbos Is it cool if we use that favicon.ico?

**Comment by wesbos** [comment]
Yep - go nuts! 

https://learnredux.com/images/redux-logo-fav.png

**Comment by preflight** [comment]
Gitbook doesn't appear to [support](https://github.com/GitbookIO/gitbook/issues/1254) custom favicons yet for the default theme. If anyone knows how to hack the `<head>` in the generated `_book/index.html` file, I can provide the icon files (for iOS, Android, Safari, Windows, etc.) and the `<link>`/`<meta>` tags.

**Comment by gaearon** [comment]
Done via #1761.
