### ISSUE TITLE
Is it OK to dispatch another actions inside action creators?

### ISSUE THREAD

**Issue by diegohaz** [reactjs/redux#1738]
I'm doing something like this:
```js
function getItems () {
  return (dispatch) => {
    api.get('/items').then((res) => {
      dispatch({
        type: 'RETRIEVE_ITEMS',
        items: res.data
      })
    })
  }
}

function createItem (item) {
  return (dispatch) => {
    api.post('/items', item).then((res) => {
      // reload data
      dispatch(getItems())
    })
  }
}
```

But I'm wondering if `dispatch(getItems())` is ok to do or could it break something.

**Comment by TrySound** [comment]
@diegohaz You can dispatch anything you want. Even not the only one. As you can see in this example https://github.com/gaearon/redux-thunk#composition it's ok.

**Comment by nvartolomei** [comment]
This is legit. I, personally, try to avoid this. Usually, I add a `didInvalidate` property to state. Now createItem can invalidate items' state tree, by dispatching a didInvalidate action or by setting didInvalidate in reducer. After that I make view/container/component responsible to fetch new data if it is invalid/old/whatever.

_It depends._

**Comment by gaearon** [comment]
>But I'm wondering if dispatch(getItems()) is ok to do or could it break something.

It’s totally fine to do. Thunk action creators can dispatch other thunk action creators.
https://github.com/gaearon/redux-thunk#composition

**Comment by Deepeshbhardwaj** [comment]
function getItems () {
  return (dispatch) => {
    api.get('/items').then((res) => {
      dispatch({
        type: 'RETRIEVE_ITEMS',
        items: res.data
      })
    })
  }
}

function createItem (item) {
  return (dispatch) => {
    api.post('/items', item).then((res) => {
      // reload data
      dispatch(getItems())
    })
  }
}

But  why can we import getItems in that action and call it directly without using dispatch?
