### ISSUE TITLE
Is there a way to pass state to action creators?

### ISSUE THREAD

**Issue by diegohaz** [reactjs/redux#1740]
I'm developing a package of reusable action creators for an API (things like `getItems`, `createItem`, `removeItem` etc.) to provide common actions to apps. So it isn't aware of reducers/store schema.

Some action creators need state information. For example: `createSession` needs to know about the `session` state, because if it is already set, it won't create another one.

Currently I'm doing this way:
```js
function createSession (username, password) {
  return (dispatch, getState, {api}) => {
    const {session} = getState()

    if (typeof session === 'undefined') {
      throw new Error('There is no session state')
    } else if (session.accessToken) {
      return dispatch({
        type: 'RETRIEVE_SESSION',
        session
      })
    }

    const auth = {username, password}

    return api.post('/sessions', {}, {auth}).then((res) => {
      dispatch({
        type: 'RETRIEVE_SESSION',
        session: res.data
      })
      return res.data
    })
  }
}
```
As you can see, I'm assuming that the state name will be `session` and this will have a `sessionToken` property. If there's no `session` in state, it will throw an error. If the app developer wants to implement session state with another schema (e.g. `{user: {token: 'token'}}`), he can't.

As you also can see, I'm passing `{api}` to the action creator, using the method @gaearon described [here](https://github.com/reactjs/redux/issues/1716). I think I can use that in some way to solve this problem, but I still can't figure it out.

**Comment by TrySound** [comment]
@diegohaz Everything fine. What's exactly doesn't work? Did you add thunk middleware?

**Comment by diegohaz** [comment]
Hi, @TrySound, maybe my question wasn't clear.

The action creator isn't aware of how the state is structured (this is a package of common actions to be used for a bunch of apps). The way I've implemented it, I'm assuming a specific state schema. If developer wants to implement this in another way, he can't. And I think this is bad.

I want to replace it by something like:
```js
function createSession (username, password) {
  return (dispatch, getState, {api, session}) => {
    if (session) {
      return dispatch({
        type: 'RETRIEVE_SESSION',
        session
      })
    }

    const auth = {username, password}

    return api.post('/sessions', {}, {auth}).then((res) => {
      dispatch({
        type: 'RETRIEVE_SESSION',
        session: res.data
      })
      return res.data
    })
  }
```

So developers can configure store by doing something like:
```js
const finalCreateStore = compose(
  someMiddewareThatPassState(),
  applyMiddleware(thunk.withExtraArgument({api})),
)(createStore)

const store = finalCreateStore(services)
```

**Comment by TrySound** [comment]
@diegohaz I can suggest you to add some adater function in your api.
```js
function createSession (username, password) {
  return (dispatch, getState, { api }) => {
    const { session } = api.getNecessaryDataFromState(getState);
    if (session) {
      return dispatch({
        type: 'RETRIEVE_SESSION',
        session
      })
    }

    const auth = { username, password }

    return api.post('/sessions', {}, { auth }).then(res => {
      dispatch({
        type: 'RETRIEVE_SESSION',
        session: res.data
      })
    })
  }
```

**Comment by sompylasar** [comment]
The helper functions that act on a state and return a slice of it are called selectors, and they should come from the same module where the reducer for that slice of state resides.

**Comment by sompylasar** [comment]
@TrySound, right, but not from `api.`, they should be imported from the `sessions` reducer module.

**Comment by sompylasar** [comment]
You'll get something like `extractSessionToken(getState())`. In that reducer module, in the selector function, you'll have to know the global state key where your root reducer puts tge data. I came uo with exporting a `STORE_KEY` constant from each reducer module, and use it in the root reducer.

**Comment by TrySound** [comment]
@sompylasar Not sure how do you want to import local modal from external library.

**Comment by gaearon** [comment]
Please use StackOverflow for usage questions. Answers get lost here.
I’m closing but feel free to post a link to the same question on SO.
Thanks!
