### ISSUE TITLE
Error when rub npm start

### ISSUE THREAD

**Issue by Stas-Buzunko** [reactjs/redux#1742]
bon@bon-K72Dr://home/bon/work/redux/examples/counter$ npm start

> redux-counter-example@0.0.0 start /home/bon/work/redux/examples/counter
> node server.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:953:11)
    at exports._exceptionWithHostPort (util.js:976:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1385:5)
    at EventEmitter.listen (/home/bon/work/redux/examples/counter/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/home/bon/work/redux/examples/counter/server.js:17:5)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)

npm ERR! Linux 3.19.0-58-generic
npm ERR! argv "/home/bon/.nvm/v6.2.0/bin/node" "/home/bon/.nvm/v6.2.0/bin/npm" "start"
npm ERR! node v6.2.0
npm ERR! npm  v3.9.0
npm ERR! code ELIFECYCLE
npm ERR! redux-counter-example@0.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the redux-counter-example@0.0.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the redux-counter-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs redux-counter-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls redux-counter-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bon/work/redux/examples/counter/npm-debug.log

**Comment by markerikson** [comment]
Well, this is the root error: `listen EADDRINUSE :::3000`.  So, presumably you have something else already running listening on port 3000.  Close any other development servers or stuff you have running, and try again.
