### ISSUE TITLE
Rename createStore() second argument from initialState to preloadedState

### ISSUE THREAD

**Issue by gaearon** [reactjs/redux#1743]
It has caused enough confusion. This argument is only meant for providing persisted state, not for putting an object literal with all app’s initial state in one place. We should make it more clear by renaming the argument both in the source and everywhere in the docs.

**Comment by gaearon** [comment]
(Arguably it’s also used for server rendering. Alternative naming suggestions are welcome. I just want to make it clear that it’s supposed to be generated and not written by hand.)

**Comment by markerikson** [comment]
`importedState`?  `preloadedState`?

**Comment by gaearon** [comment]
`preloadedState` looks better. More ideas are welcome.

**Comment by BerkeleyTrue** [comment]
defaultState

**Comment by JisuPark** [comment]
`preloadedState` looks good. Then how about `stateToSync`?

**Comment by DavidBrear** [comment]
My only argument to keep it as initialState is when referring to "currentState" it sounds more fluid to say "initial" -> "current" as opposed to "preloaded" -> "current".

**Comment by markerikson** [comment]
W00t!  Actually rather amused that my offhand suggestion of "preloadedState" worked out :)

**Comment by gaearon** [comment]
:-)
