### ISSUE TITLE
can i use es7 async function in action?

### ISSUE THREAD

**Issue by stephenkingsley** [reactjs/redux#1752]
Recently, I used redux to do a demo, in store, i used redux-thunk. If i did not use es7 async,  Chrome was not  error. But when I used es7 async, Chrom cast error. <br />
in Action
```javascript
// action.js
const API = 'https://hacker-news.firebaseio.com/v0/topstories.json?print=pretty';
async function getTopNewsId() {
  let response = await getId(API);
  console.log('---', response);
  return {
    type: 'GET_TOP_NEWS', response,
  }
}

function getId(api) {
  return fetch(api)
          .then( response => response.json())
          .then( data => data)
}

```

in react-native Component
```javascript
import {getTopNewsId} from '..action/news';
componentDidMount() {
  this.props.dispatch(getTopNewsId())
}
```

the error is `Actions must be plain objects. Use custom middleware for async actions.`
I do not know what went wrong? Please tell me.

**Comment by gaearon** [comment]
Redux does not support action promises out of the box.
You can either wait for the promise to finish:

```js
  const action = await getTopNewsId()
  this.props.dispatch(action)
```

or you can add `redux-promise` middleware:

```js
import { createStore, applyMiddleware } from 'redux'
import promise from 'redux-promise'

const store = createStore(reducer, applyMiddleware(promise))

// now you can dispatch async functions directly
this.props.dispatch(getTopNewsId())
```

Please use StackOverflow for questions in the future!

**Comment by mustafawm** [comment]
Given that all required pollyfills and plugins are in place, shouldn't this force redux to (a)wait for the promise to resolve?
