### ISSUE TITLE
How to call one action after other actions is called

### ISSUE THREAD

**Issue by mahaina** [reactjs/redux#1753]
I have several fetch actions with thunk, for example:
`function addARequest(
    return (dispatch) => {
        return fetch(blablabla).then(blablabla);
    };
)`
`function addBRequest(
    return (dispatch) => {
        return fetch(blablabla).then(blablabla);
    };
)`
`function addCRequest(
    return (dispatch) => {
        return fetch(blablabla).then(blablabla);
    };
)`

and I have a requirement to call a action after each of them above was called.
But I don't want to add a dispatch in every action...like
`
function addARequest(
    return (dispatch) => {
        dispatch(aMustCalledActionAfterEveryOtherAction);
        return fetch(blablabla).then(blablabla);
    };
)`

I want it to run like an AOP or something.
Could anyone help me...?

**Comment by DavidBrear** [comment]
Just to clear it up for myself, you're trying to call a particular method (let's call this method **fooMethod**) after each of those above methods is called? Something like this flow?: 
`addARequest does its fetch then fooMethod gets called`
`addBRequest does its fetch then fooMethod gets called`
etc.
Just trying to clear it up for myself as to what the flow is.

**Comment by gaearon** [comment]
This is a usage question rather than a bug or a feature request. Please use StackOverflow for this.
