### ISSUE TITLE
symbol-observable/index.js does not export $$observable

### ISSUE THREAD

**Issue by nverba** [reactjs/redux#1754]
Just setting up with rollup.js, and I'm getting an error when trying to build the main JS file.

`/node_modules/symbol-observable/index.js does not export $$observable (imported by node_modules/redux/es/createStore.js)`.

Are there any specific issues building with Rollup?

I currently can't use webpack, the rest of the application in Polymer components, so my options are limited.

**Comment by gaearon** [comment]
Thanks for reporting! Filed as https://github.com/blesh/symbol-observable/issues/9, let us know if you’d like to help!

**Comment by gaearon** [comment]
This should be fixed.
