### ISSUE TITLE
Updating similar attribute across multiple state branches

### ISSUE THREAD

**Issue by pbanda123** [reactjs/redux#1755]
Hello, 

If I have a scenario where I am trying to implement - adding comment - functionality on several pages in the app that are connected to different state branches. 

I created a component to display the comment form. Can some one please explain how we can manage the code in the reducers. 

Should I write functions to save comment in each of the page reducers and pass in the function to the component or can I write a reducer for the component. 

Thank you very much for the help. 

Regards,
Prasad.

**Comment by gaearon** [comment]
Please use StackOverflow or Discord chat (links in README) for usage questions.
I’ll close because we use the issue tracker for bug reports and feature requests.
Feel free to post a link to your question here!
