### ISSUE TITLE
Sealing return value of currentState

### ISSUE THREAD

**Issue by ev1stensberg** [reactjs/redux#1757]
I was looking over the source code, and wondered if we truly want to make state read-only, could we apply `object.seal` to the state in order to make it immutable and read-only? 

Here's where I was thinking about implementing it. 

[Legit link](https://goo.gl/1bdPIl)

**Comment by ev1stensberg** [comment]
> `object.freeze` could also be of interest

**Comment by onbjerg** [comment]
This would need to be a major bump if it was implemented, as it would probably break someones code.

**Comment by ev1stensberg** [comment]
`object.freeze` is a bit sketchy, since the prototype is muteable, also you can push things into, i.e an array.

**Comment by ev1stensberg** [comment]
Sure, but isn't that what is the main point of redux? preserving state as read-only? Also, `object.freeze` is not 100% the best fit, since prototype & pushing to things like arrays are allowed.

@onbjerg do you know if the source code checks if your state has prototypes/constructors of some sort?

**Comment by gaearon** [comment]
We recommend using something like `deep-freeze` in tests to ensure immutability. However we likely won’t enforce something like this in Redux itself because of potential edge cases where mutation is desired (though they are very rare), and performance implications of deep freezing everything.


You can use something like https://github.com/leoasis/redux-immutable-state-invariant to ensure you don’t mutate the state by accident.

**Comment by ev1stensberg** [comment]
Can you tell me an example of this rare use case? @gaearon 
Mutating state by accident is hard, if you allow `obj.seal` to persist and decide for things like `writable, enumerable, configurable`

**Comment by gaearon** [comment]
>Can you tell me an example of this rare use case?

Redux DevTools is one example where we mutate the state to avoid too many allocations when we know it’s safe to do.

>Mutating state by accident is hard

Then why do you wish to seal the state? For stronger guarantees, you can always use ImmutableJS or https://github.com/rtfeldman/seamless-immutable.

**Comment by ev1stensberg** [comment]
I meant in context of `object.seal`, sorry! 
>Mutating state by accident is hard 

Yes. Sealing the state will make, it hard to override the previous state with non-readable actions. If we want it immutable, then` prevState` should be different from state when passing` state` as the previous one. (Leaving state blank). I'm terrible at explaining, but if you seal the state, you'll avoid mutability on the same state object and instead you'll have to create a new one. Please, do correct me if I'm wrong.

**Comment by ev1stensberg** [comment]
Holy macaroni my English is broken asf :cry:

**Comment by ev1stensberg** [comment]
What I'm trying to say, is that you should not override your `previousState` when you have reduced it or when it has been rendered/ is outside your scope or context.

**Comment by gaearon** [comment]
I understand this. But I wrote that this has performance implications (will be slow!) so we don't want to do this by default. There are ways to enforce this as opt in if you'd like.
