### ISSUE TITLE
Confusion in docs related to react-redux

### ISSUE THREAD

**Issue by hoodwink73** [reactjs/redux#1759]
In the [Middleware](http://redux.js.org/docs/advanced/Middleware.html) section of the docs, under *Attempt -1 Logging manually*

> Note
If **you’re using react-redux** or similar bindings, you likely **won’t** have direct access to the store instance in your components. For the next few paragraphs, just assume you pass the store down explicitly.

It says, the components will **not** have access to store.
Doesn't the `<Provider />`  makes the `store` available to all components irrespective of the hierarchy?

**Comment by gaearon** [comment]
Yes, but you won’t be able to read it unless you use context directly (which we don’t recommend). Instead you’d use `connect()` from React Redux which hides talking to the store from you.

**Comment by hoodwink73** [comment]
Oh! Thats why the `mapStateToProps` and `mapDispatchToActions` methods passed to `connect`. Only these methods can access the `store.state` and `store.dispatch` respectively.

Now it makes sense. Thanks.

**Comment by gaearon** [comment]
Exactly!

**Comment by markerikson** [comment]
Nice.  Have to say it's always fun watching the lightbulb go on for someone :)
