### ISSUE TITLE
dispacth: TypeError: undefined is not a function

### ISSUE THREAD

**Issue by FuGardenia** [reactjs/redux#1767]
when I use `dispatch(fetchGoods())` 
the Wechat browser shows error
`TypeError: undefined is not a function {stack: (...), message: "undefined is not a function"} `

```
computeNextEntry instrument.js:114
recomputeStates instrument.js:144
(anonymous function) instrument.js:384
dispatch createStore.js:179
dispatch instrument.js:431
(anonymous function) index.js:208
(anonymous function) index.js:14
dispatch applyMiddleware.js:45
(anonymous function) actions.js:11
(anonymous function) index.js:11
componentWillMount index.js:31
ReactCompositeComponentMixin.mountComponent 
ReactCompositeComponent.js:210
wrapper ReactPerf.js:66
ReactReconciler.mountComponent
......
```

Chorme works well, But in Wechat

and the browser(SOGOU) version is
```
5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 Safari/537.36 SE 2.X MetaSr 1.0"
```
shows error
`TypeError: undefined is not a function {stack: (...), message: "undefined is not a function"} `
too

HELP! HELP! HELP!

**Comment by FuGardenia** [comment]
Object.assign is undefined

**Comment by deowk** [comment]
@FuGardenia I assume you know that it needs a polyfill? --> https://www.npmjs.com/package/es6-object-assign

**Comment by FuGardenia** [comment]
@deowk  Thanks for your advice. Finaly, I use  `lodash` _.assign .
