### ISSUE TITLE
External javscript in react component

### ISSUE THREAD

**Issue by uragecz** [reactjs/redux#1774]
Hi, i have problem, i wanna use external javascript - fabric.js in my component during server-side render.. any tips how do it? I still have error message fabric is not defined. Thank you so much

**Comment by gaearon** [comment]
Hi! Can you please ask this on StackOverflow? This is not really related to Redux, and we use issue tracker for bug reports and feature requests. Thank you!

**Comment by markerikson** [comment]
Maybe about time to set up an issue template for the ReactJS repos?  https://help.github.com/articles/creating-an-issue-template-for-your-repository/
