### ISSUE TITLE
Pass action to subscribe() listeners

### ISSUE THREAD

**Issue by rstacruz** [reactjs/redux#1786]
It'd be nice to be able to learn what actions trigger a subscribe() event:

```js
store.subscribe(action => {
  if (action.type === '...') {
    /* do something */
  }
})
```

This way you can create listener services that wait for a certain `action` to do something. Example use case is to send Google Analytics data when `ROUTE_CHANGE` occurs (assuming your router sends this out).

**Comment by markerikson** [comment]
This has been suggested several times, and turned down.  Use middleware to respond to actions (such as redux-saga).

See https://github.com/reactjs/redux/issues/1057 , https://github.com/reactjs/redux/issues/1243 , https://github.com/reactjs/redux/issues/347 , https://github.com/reactjs/redux/issues/1300 , and https://github.com/reactjs/redux/issues/580.
