### ISSUE TITLE
Tests do not run on shopping cart example

### ISSUE THREAD

**Issue by ttaub** [reactjs/redux#1788]
On the shopping-cart example running the npm run test command does not work and it errors out. 

The test does not run because the required babel-register dependency is not installed. I can make a PR to add the correct files. 

Side note: why do all the tests take such a long time to run

**Comment by gaearon** [comment]
>I can make a PR to add the correct files.

Please do!

>Side note: why do all the tests take such a long time to run

Please feel free to find out and let us know 😉

**Comment by gaearon** [comment]
I tried running `npm test` inside `examples/shopping-cart` and I have no issues.
If you can reproduce it please provide exact steps and help fix it!
Thanks.
