### ISSUE TITLE
TypeScript and "declare const dispatch: Dispatch<any>" - dispatch is undefined

### ISSUE THREAD

**Issue by lukaszbulzacki** [reactjs/redux#1790]
Hi,

I have a probably *bug*.

#### BUG DESCRIPTION

I'm using react and redux with TypeScript.
It is packed with webpack.
I'm using the line (from tests https://github.com/reactjs/redux/blob/master/test/typescript/actionCreators.ts)

```typescript
declare const dispatch: Dispatch<any>;
```

I'm getting in browser console error *Uncaught ReferenceError: dispatch is not defined index.tsx:8*

#### STEP TO REPRODUCE

This is the minimal project [rr-test.zip](https://github.com/reactjs/redux/files/298715/rr-test.zip)

Zero step is installing globally few dependencies:
```sh
npm install -g typescript typings webpack
```
First step is download and extract minimal project.
Second step is to install node dependencies in that project:
```sh
cd rr-test
npm install
```
Third step is running webpack dev server:
```sh
webpack-dev-server
```
Fourth step is to run localhost:8080 in browser and in console should be visibile text *Uncaught ReferenceError: dispatch is not defined index.tsx:8*

#### EXPECTED BEHAVIOR

Variable distpatch should be function.

### OTHER
os: Debian stretch 
browser: Chrome Version 51.0.2704.79 (64-bit)
npm: 1.4.21
webpack: 1.13.1
react: 15.1.0
react-dom: 15.1.0
redux: 3.5.2
ts-loader: 0.8.2
typings: 1.0.4
TypeScript: 1.8.9

**Comment by gaearon** [comment]
Please post the project code on GitHub. I don’t think people like to download ZIP attachments from an unknown source. 😉

**Comment by jwbay** [comment]
`declare const dispatch: Dispatch<any>;` is a type declaration with no runtime part. It completely disappears during compilation. In order for `dispatch` to exist during runtime you need to import it from somewhere or implement it.

Generally, do not use anything under test/typescript as an example of how to do actually use Redux. Those files exist purely to test the type definitions. All they do is throw variables at things declared in index.d.ts to make sure the right types come out.

**Comment by lukaszbulzacki** [comment]
OK.
I understand problem is in my "usage".
I will look for another solution, thanks.
