### ISSUE TITLE
[docs] redux alias info in Examples section of CONTRIBUTING.md should be removed

### ISSUE THREAD

**Issue by dryror** [reactjs/redux#1797]
The [examples documentation](https://github.com/reactjs/redux/blob/master/CONTRIBUTING.md#examples) in **CONTRIBUTING.md** makes mention of aliases that are longer present:

> For development convenience, the Webpack configs for the examples are set up so that the redux module is aliased to the project src folder when inside of the Redux folder. If an example is moved out of the Redux folder, it will instead use the version of Redux from node_modules.

The aliases were removed in [this commit](https://github.com/reactjs/redux/commit/0b9416bb8d833fa246d21e16f346e75547d86290)

**Comment by ellbee** [comment]
Good catch! Thank you.
