### ISSUE TITLE
Could not access customized property of component after using connect()

### ISSUE THREAD

**Issue by mindnova** [reactjs/redux#1809]
Say a simple example:

```
class My extends Component{
	constructor(props) {
	  super(props)
	  this.state = {}
	  this.hello=this.hello.bind(this)
	}
	componentDidMount() {
	}
	hello(){
		console.log('hello')
	}
	render(){
		return <View>
		<Text>my ....my</Text>
		<You/>
		</View>
	}
}
```
And in other components render():
```
render(){
 return <View>
 <My ref='my'/>
</View>
}
```
Then I can use 
```
this.refs['my'].hello()
```

But after connect with redux,
```
My = connect()(My)
```
There wil be an error: this.refs.my.hello is not a function.

Anybody know how to fix this?

**Comment by taurose** [comment]
Messing up refs is a known problem with higher order components. Fortunately, `connect` provides an [API](https://github.com/reactjs/react-redux/blob/master/docs/api.md#getwrappedinstance-reactcomponent) that should help here.

**Comment by mindnova** [comment]
@taurose . Thanks! Got things right. 
Thought I should always check the documentation first..
