### ISSUE TITLE
cannot call dispatch using internet explorer

### ISSUE THREAD

**Issue by michaeltheodore048** [reactjs/redux#1820]
here is my code : 

![capture](https://cloud.githubusercontent.com/assets/10736007/16183420/c96ee380-36db-11e6-8758-13a244882231.PNG)

I don't know whether I'm being silly or this method just won't work on any internet explorer other method works fine for me except dispatch. been searching for the answer for a while but I just don't get it. 

this code works completely fine on other browser, if anyone can help, I really appreciate it.
thank you so much.

**Comment by stooboo** [comment]
Just a possibility ..

setState is an asychronous operation,

so if you're expecting to get the id from the state ..

then you'll need to pass 'that' part of the code as a callback (2nd
argument) to setState
so that it will be guaranteed to execute AFTER setState completes


cheers
Stoo

**Comment by stooboo** [comment]
or .. just use the 'res.data.sysuser_id' value instead when you're creating your 'users' kwargs

If none of that is the issue then are there any 'helpful' messages in the browser's console when this 'fails' ?

**Comment by stooboo** [comment]
(p.s. prob best to ask this question on StackOverflow instead of here as it's most likely 'NOT' a redux issue)

**Comment by gaearon** [comment]
Please ask this on StackOverflow. This is an issue tracker, and the answer will get lost here. I also think it’s not enough information—you might want to create a [fiddle](https://jsfiddle.net) reproducing the problem so others can help you.
