### ISSUE TITLE
How to implement a self contained component in react redux?

### ISSUE THREAD

**Issue by eromoe** [reactjs/redux#1822]
I am building a file manager webui base on react redux(My purpose is to master react and redux through this project)

As you know, a file manager need a tree explorer.I want to build a component which can contain it self and each has self state. like below:

`TreeNode` can contain children  which are `TreeNode` too.Each `TreeNode` hold its state `{path, children_nodes, right .....}`, `children_nodes` is get from server, `path` is passed by parent. That's what I imagine.
Struct like:

    App:
    TreeNode
    --TreeNode
    ----TreeNode
    ----TreeNode
    TreeNode
    TreeNode
    --TreeNode
    TreeNode
    --TreeNode
    ----TreeNode
    ----TreeNode

----

But trouble come here, because redux `connect` store to the tree root, all node under the root receive same state...

For example, I have a `OPEN_NODE` action, which is design to trigger `getFileList fucntion` base this node's path and set this node's `state.open` to `true`.(note: `getFileList fucntion` not implement yet, just give fake data for now)
The screen shot:
[![enter image description here][1]][1]

Click each element , but `states are equal`.

My code:

containers/App.js

    import React, { Component, PropTypes } from 'react';
    import { bindActionCreators } from 'redux';
    import { connect } from 'react-redux';
    import Footer from '../components/Footer';
    import TreeNode from '../containers/TreeNode';
    import Home from '../containers/Home';
    import * as NodeActions from '../actions/NodeActions'
    
    export default class App extends Component {
    
      componentWillMount() {
        // this will update the nodes on state
        this.props.actions.getNodes();
      }
    
      render() {
        const { nodes } = this.props
        console.log(nodes)
        return (
          <div className="main-app-container">
            <Home />
            <div className="main-app-nav">Simple Redux Boilerplate</div>
            <div>
              {nodes.map(node =>
                <TreeNode key={node.name} info={node} actions={this.props.actions}/>
              )}
            </div>
    
            {/*<Footer />*/}
          </div>
        );
      }
    }
    
    function mapStateToProps(state) {
      return {
        nodes: state.opener.nodes,
        open: state.opener.open
      };
    }
    
    
    function mapDispatchToProps(dispatch) {
      return {
        actions: bindActionCreators(NodeActions, dispatch)
      };
    }
    
    export default connect(
      mapStateToProps,
      mapDispatchToProps
    )(App);

containers/TreeNode.js

    import React, { Component, PropTypes } from 'react'
    import { bindActionCreators } from 'redux'
    import { connect } from 'react-redux'
    import classNames from 'classnames/bind'
    import * as NodeActions from '../actions/NodeActions'
    
    export default class TreeNode extends Component {
    
      constructor(props, context) {
        super(props, context)
        this.props = {
          open: false,
          nodes: [],
          info:{}
        }
      }

      handleClick() {
        let {open} = this.props
        if (open) {
          this.props.actions.closeNode()
        } else {
          this.props.actions.openNode()
        }
      }
    
      render() {
        const { actions, nodes, info } = this.props
        return (
          <div className={classNames('tree-node', { 'open':this.props.open})} onClick={ () => {this.handleClick()} }>
            <a>{info.name}</a>
            {nodes &&
              <div>{nodes.map(node => <TreeNode info={node} />)}</div>
            }
            {!nodes &&
              <div>no children</div>
            }
          </div>
        );
      }
    }
    
    TreeNode.propTypes = {
      open:PropTypes.bool,
      info:PropTypes.object.isRequired,
      nodes:PropTypes.array,
      actions: PropTypes.object.isRequired
    }

actions/NodeActions.js

    import { OPEN_NODE, CLOSE_NODE, GET_NODES } from '../constants/NodeActionTypes';
    
    export function openNode() {
      return {
        type: OPEN_NODE
      };
    }
    
    export function closeNode() {
      return {
        type: CLOSE_NODE
      };
    }
    
    
    export function getNodes() {
      return {
        type: GET_NODES
      };
    }

reducers/TreeNodeReducer.js

    import { OPEN_NODE, CLOSE_NODE, GET_NODES } from '../constants/NodeActionTypes';
    
    const initialState = {
      open: false,
      nodes: [],
      info: {}
    }
    
    const testNodes = [
      {name:'t1',type:'t1'},
      {name:'t2',type:'t2'},
      {name:'t3',type:'t3'},
    ]
    
    
    function getFileList() {
      return {
        nodes: testNodes
      }
    }
    
    
    export default function opener(state = initialState, action) {
      switch (action.type) {
      case OPEN_NODE:
        var {nodes} = getFileList()
        return {
          ...state,
          open:true,
          nodes:nodes
        };
      case CLOSE_NODE:
        return {
          ...state,
          open:false
        };
      case GET_NODES:
        var {nodes} = getFileList()
        return {
          ...state,
          nodes:nodes
        };
      default:
        return state;
      }
    }

For complete code, see my github https://github.com/eromoe/simple-redux-boilerplate

I don't see an example cover such component, and google result nothing helpful.
Any idea to overcome this?

  [1]: http://i.stack.imgur.com/G6HBj.png

**Comment by sompylasar** [comment]
@eromoe You should add identifiers to your tree nodes, and include them into actions about one node (i.e. `OPEN_NODE`, `CLOSE_NODE`).

Moreover, there is a complete example how to implement a Tree View in Redux: https://github.com/reactjs/redux/tree/master/examples/tree-view

**Comment by eromoe** [comment]
Hi @sompylasar, these days, I use rest time to check `tree-view` and  solved a lot other react issue, it's  just one feet to success I think, but there is a strange problem -- my TreeNode can't get update.
Just now, after saw `Node container` in  `tree-view` again, I finally realize that, it is no need to make root container connect to store, I should connect root's child - `ConnectedNode` . 
Only connect  `ConnectedNode` can have affect to every node (but root). 
I always think the top container should be connect , that's wrong !
Maybe redux should add a tip in some page, the official example projects all  seems connect store on root, which lead me to misunderstand.

**Comment by markerikson** [comment]
The Redux FAQ does address this topic: http://redux.js.org/docs/FAQ.html#react-multiple-components .
