### ISSUE TITLE
npm install --save redux throws react-redux error

### ISSUE THREAD

**Issue by jordyvandomselaar** [reactjs/redux#1823]
**bug**

**What is the current behavior?**
When I run `npm install --save redux` I get the following error: 
>react-redux@4.4.5 requires a peer of redux@^2.0.0 || ^3.0.0 but none was installed.

Even though I'm not trying to install react-redux, I'm trying to install redux.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

Open a terminal inside of a project and run `npm install --save redux`

**What is the expected behavior?**
To install Redux

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

Version: latest
OS: Linux Ubuntu 16.04 64 bit
I don't know if it worked in previous versions as I'm just getting started.

**Comment by Aweary** [comment]
What version of npm are you running? Missing peer dependencies are only warnings in npm <3.0 If you check your `package.json` file do you see `react-redux` in there?

**Comment by gaearon** [comment]
Please run `rm -rf node_modules`, make sure you have the latest versions of `react-redux` and `redux` in `package.json` then run `npm install` again. It is not a Redux issue—something is wrong with your local npm setup, and cleaning the `node_modules` will fix it.

**Comment by jordyvandomselaar** [comment]
I don't have anything installed. I only ran npm install redux - - save

**Comment by jordyvandomselaar** [comment]
But thanks for the help, will try :)

**Comment by Githubuser108** [comment]
You need to use: "npm install --save redux".
