### ISSUE TITLE
How can i update only name in category object in reducer

### ISSUE THREAD

**Issue by chienvuhoang** [reactjs/redux#1827]
I have a object below:

```JS
categoryDetail: {
        isFetching: false,
        category: {
            id: '',
            name: '',
            publish: '',
            time_create: '',
            attributes: []
        }
    }
```
How can i update only name in category object in reducer. 
I'm trying use `return {...state, category: {name: cateName}};` and I get result:

```
categoryDetail: {
        isFetching: false,
        category: {
            name: ''
        }
    }
```

Please tell me how to update only name in category object and keeping all fields.
Thanks so much.

**Comment by mxstbr** [comment]
This will fix the issue:

```JS
return {
  ...state,
  category: {
    ...category,
    name: cateName
  }
}
```

I think this would be a case for using reducer composition and having a separate `categoryReducer`, see [this and the following lessons](https://egghead.io/lessons/javascript-redux-reducer-composition-with-objects?course=getting-started-with-redux) of Dan's redux course for information on what that means and how to do it!

**Comment by chienvuhoang** [comment]
Thanks so much @mxstbr for help :)

**Comment by chienvuhoang** [comment]
Hi @mxstbr ,
I set it but i get error : 

> Uncaught ReferenceError: category is not defined

**Comment by mxstbr** [comment]
Ah sorry, I had a typo :blush: it's

```JS
return {
  ...state,
  category: {
    ...state.category,
    name: cateName
  }
}
```

**Comment by chienvuhoang** [comment]
yeah, it work!!!. Thanks @mxstbr. Have a nice day. :)

**Comment by mxstbr** [comment]
Awesome, glad to hear! Sorry for the typo again!

**Comment by Koleok** [comment]
Could be a great time to look into lenses if you often have to write code with deeply nested object spreads. See ramda's [lensPath](http://ramdajs.com/0.21.0/docs/#lensPath) and [set](http://ramdajs.com/0.21.0/docs/#set).

**Comment by chienvuhoang** [comment]
Thanks @Koleok

**Comment by Yalhu** [comment]
Could someone figure out my error?
I want to chage chatMsg Status from 'loading' to 'error', but it doesn't return a new state with 'error'.
It is always 'loading' . 
What's more , when debug with chrome devtools, the process truly return 'error'.  At end it will log 'loading'. 
```javascript
state={
  msgId1:{status:'loading',text:'first text'},
  msgId2:{status:'loading',text:'second test'}
}
// reducer
// action:{type,msgId,msg:{status:error}}
export function chatMsgs(state={},action){
    const {msgId,msg}= action
    switch(action.type) {
        //  change msg status by msgId
        case 'SET_CHAT_MSG':
            return{
                ...state,
                [msgId]:{...state[msgId],...msg}
            }    
        default:
            return state 
    }
}

//action
export function setChatMsg(msgId=0,msg={}){
    return {type:'SET_CHAT_MSG',msgId,msg}
}
// container
function getChatMsgs(msgs={},ids=[]){
    var chatMsgs=[]
    ids.map(id=>{
        chatMsgs.push(msgs[id])
    })
    return chatMsgs
}
export default connect(state => {
    return {
        chatMsg:getChatMsgs(state.chatMsgs,state.roomChatMsgIds[state.activatedRoom]),
    }
})(Component);
```
