### ISSUE TITLE
What is the reason call assertReducerSanity in non-production environment?

### ISSUE THREAD

**Issue by dentuzhik** [reactjs/redux#1828]
While looking at the source code, stumbled upon this:
https://github.com/reactjs/redux/blob/master/src/combineReducers.js#L117

While I can understand the general reason of doing this, the reason of doing sanity check in production is unclear. I might be missing something, but it seems that there's no reason to keep this check in production env.

**Comment by ellbee** [comment]
We consider it dangerous to have behavior differences in production and development. See https://github.com/reactjs/redux/pull/1678

**Comment by dentuzhik** [comment]
Thank you!
