### ISSUE TITLE
containers in examples provided have presentational behavior

### ISSUE THREAD

**Issue by halayli** [reactjs/redux#1830]
I've noticed in the examples directory that many of the containers having presentational behavior like the one here:

https://github.com/reactjs/redux/blob/master/examples/real-world/containers/UserPage.js#L51

doesn't that break the separation of containers and components? wouldn't it be better to pass the connected components (containers) to the component and let it figure out how to present them?

**Comment by gaearon** [comment]
Don’t take this separation too seriously. It is a nice pattern but it’s not to be a dogma. In this particular case it seemed like too much hassle to separate them, so I didn’t.

**Comment by halayli** [comment]
Oh yeah it's definitely not a dogma. But my thinking was since those are examples and newcomers look at them as a pattern to copy it can be confusing as it was for me. Particularly, when the separation isn't from design necessity. I love the containers/component separation as it promotes reusability to a big extent and having examples of that will he more helpful for newcomers. From my personal experience, newcomers want opinionated patterns to follow. They aren't comfortable coming up with their own at an early stage.

I'd be more than happy to submit a PR if you want.

On a side note, while components might need to render containers passed to them, I haven't had a need for a container to render components/elements aside from the component its wrapping. But maybe I just haven't had a need to do that.

P.S Thanks for introducing redux and taking the time to write all those awesome articles and videos!

**Comment by gaearon** [comment]
If you’re up to work on it, feel free to draft up a PR! If it involves too much ceremony we probably won’t merge it though because this particular example is very demanding by itself.

**Comment by halayli** [comment]
I'll take a stab at it over the weekend, if I felt it's going to reshuffle a lot of pieces and might be controversial I'll stop. :)
