### ISSUE TITLE
Suggestion: pass the current state to the listeners/subscribers when calling `dispatch`

### ISSUE THREAD

**Issue by xareelee** [reactjs/redux#1832]
In [the `createStore.dispatch()` implementation](https://github.com/reactjs/redux/blob/master/src/createStore.js#L177):

```js
var listeners = currentListeners = nextListeners
for (var i = 0; i < listeners.length; i++) {
  listeners[i]()    // no argument
}
```

we invoke the listener callbacks without any argument.

Pass the current state to the listener will be more sophisticated:

```js
// Line 177
listeners[i](currentState);
```

Now, when we use `subscribe()`, we won't need to use `getState()` anymore.

```js
// old
store.subscribe( () => {
  var state = store.getState();
  // use state to update the views
})

// new
store.subscribe( (state) => {
  // use state to update the views
})
```

**Comment by markerikson** [comment]
This has been suggested _numerous_ times in the issues.  The short version is that Redux just provides the simplest API possible.

See https://github.com/reactjs/redux/issues/1707 , https://github.com/reactjs/redux/issues/303#issuecomment-125184409 , and also https://github.com/reactjs/redux/issues/1300.
