### ISSUE TITLE
ERR! code ELIFECYCLE on npm start

### ISSUE THREAD

**Issue by pricetula** [reactjs/redux#1836]
node v5.11.1
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! redux-universal-example@0.0.0 start: `node server/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the redux-universal-example@0.0.0 start script 'node server/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the redux-universal-example package,
npm ERR! not with npm itself.
I run into these errors whenever I try starting an example such as todos

**Comment by gaearon** [comment]
Hi! Have you ran `npm install` in that folder?

**Comment by gaearon** [comment]
Also can you generally run `node` in command line? There might be something wrong with your node installation if not.

**Comment by pricetula** [comment]
ohh i ran npm install on the root folder and not in all specific examples. yes todos works thank you. I am new in node.

**Comment by gaearon** [comment]
No problem!
