### ISSUE TITLE
react-redux sample blog

### ISSUE THREAD

**Issue by akornatskyy** [reactjs/redux#1838]
A simple blog written using react and redux (see [here](https://github.com/akornatskyy/sample-blog-react-redux)). You might consider add it to examples.

**Comment by markerikson** [comment]
Thanks for the link.  Opening this as an issue doesn't really make sense, though, and I don't see us copying the repo contents and adding it to the `examples` folder.

**Comment by akornatskyy** [comment]
There is no sense to copy content, you can just add a link.
