### ISSUE TITLE
Why Dispatch<S>?

### ISSUE THREAD

**Issue by unional** [reactjs/redux#1840]
https://github.com/reactjs/redux/blob/master/index.d.ts#L96

It doesn't seems to use type `S`.

**Comment by Fnatte** [comment]
This was discussed here https://github.com/reactjs/redux/pull/1537#discussion-diff-57125232, see Igorbek's answer.

**Comment by unional** [comment]
Thanks.

I have to masked it for my usage. I'm creating a variant that is IoC in nature. In my case the store's state is not typed.
