### ISSUE TITLE
Include optimized production builds for examples

### ISSUE THREAD

**Issue by jeongl** [reactjs/redux#1849]
Would it be too much to ask for an optimized bundle (minified) through webpack? The truth is this repo is probably used by many beginners such as myself for learning, and even used as boilerplates. The real world example in dev mode runs at 4MB.

Considering that this is a start place for learning redux / ecosystem, it would be very helpful to include some portions of tooling.

**Comment by gaearon** [comment]
Well, it was never intended to be used as boilerplates but I agree.
I might have a solution to this relatively soon so let’s keep it open.

**Comment by timdorr** [comment]
Looks like Dan was referencing [Create React App](https://github.com/facebookincubator/create-react-app), which has since been released.

**Comment by gaearon** [comment]
This is now done. All examples include production configuration with `npm run build`.
