### ISSUE TITLE
How to create reusable projects?

### ISSUE THREAD

**Issue by warrendeleon** [reactjs/redux#1858]
I have a project contact-list that lists videos and this project uses React + Redux + Sagas and Actions. I've uploaded this project in my private NPM repository.

In another project I installed this project using "npm install contact-list". But, when I try to create two instances of contact-list if I click on fetchContacts on one contact-list it fetches contacts in the other one too.

How can I create two instances of components that have it's own redux store?

**Comment by timdorr** [comment]
Just added to the docs! https://github.com/reactjs/redux/blob/master/docs/recipes/IsolatingSubapps.md

**Comment by sompylasar** [comment]
@timdorr [The docs](https://github.com/reactjs/redux/blob/master/docs/recipes/IsolatingSubapps.md) are awesome, thanks! I've been using this architecture for a while in a complex app.

**Comment by warrendeleon** [comment]
Is there any code example?

**Comment by sibelius** [comment]
u should take a look on this one 

https://github.com/threepointone/redux-react-local
https://github.com/threepointone/react-redux-saga
