### ISSUE TITLE
Testing change in redux state.

### ISSUE THREAD

**Issue by amit1911** [reactjs/redux#1859]
I have a react-redux application and I am trying to do some testing using Mocha and Chai. I just want to test the change in state after an action occurs and would like to know what is the best way to go about it.
Right now I just _deep compare_ the new state with the expected state but I also want to make sure that nothing else changed apart from some specific parts of my state. Take a look at the following example.

let's say my application's state is as follows:-
```
{
    id: 23,
    alert: {
        show: false,
        message: 'Unexpected error occured'
    },
    a: {
        ...
    },
    b: {
        ...
    },
    c: {
        ...
    }
}
```
**A simple  test case**
```
it('should show alert when "show alert" action is dispatched',
        function() {
            const oldState = getState();

            dispatch(alertShow());

            const newState = getState();

            let expectedState = oldState;
            expectedState.alert.show = true;

            expect(newState).to.deep.equal(expectedState);
        }
    );
```
So as you can see in the above example, here I am able to make sure that `alert.show === true` but I need to test that no other part of my state was modified as for this particular action I only want the 'alert' state to be modified. Now I am using _deep compare_ to match the _before_ and _after_ states, but it doesn't guarantee that other parts of my state were not modified as they could have been modified but it's just that their values were not changed. So to make sure that only 'alert' state was modified I would have to change the above test case to something like

```
it('should show alert when "show alert" action is dispatched',
    function() {
        const oldState = getState();

        dispatch(alertShow());

        const newState = getState();

        expect(newState.alert.show).to.equal(true);
        expect(newState.a).to.equal(oldState.a);
        expect(newState.b).to.equal(oldState.b);
        expect(newState.c).to.equal(oldState.c);
    }
);
```
Using the above test, I can _shallow compare_ other parts of the state and make sure that they were not modified but I still cannot make sure that the primitives like _id_ in the state were not modified. Is there a way to get only the modified state after an action? Something like
```
{
    alert: {
        show: true
    }
}
```
If the above is possible, then it will be really easy to make sure that there were no side-effects for a particular action.

**Comment by timdorr** [comment]
If your components aren't concerned with other parts of the state, it shouldn't matter if they are modified otherwise. It sounds like you would benefit from either an immutable data library, or a selector library like reselect and re-use of your selectors from your components in your tests. 

Overall, you shouldn't have to check the entire state tree any time one thing changes. That's not going to be an issue in almost all applications.

**Comment by amit1911** [comment]
My goal is not to check the entire state tree but to make sure that an action modified only the correct parts of the state tree. I want to make sure there are no side-effects of an action. For example, let's say I update certain parts of the state when an API call is successful (data is updated, some successful alerts are shown, etc). Right now, the only thing I can do is
```
expect(newState.a.b.data).to.equal(newData);
expect(newState.c.alert.show).to.equal(true);
expect(newState.c.alert.message).to.equal('api call successful');
```
But the above does not guarantee that other parts of my state tree were not modified. There could have been other state changes that maybe the tester doesn't know about or maybe some developer added by mistake or maybe a typo. Basically, I cannot guarantee what else is changing when this action is dispatched. I only know about certain things that will definitely change. To make sure that my action only modifies the expected parts of state I would have to manually check which reducers respond to this action. Now, this might seem trivial when one action is being handled by only one reducer, but in cases when an action is being handled by multiple reducers it could be useful to analyze the different parts of the state that the action is tied to.

**Comment by carnag3kid7** [comment]
I do not think this issue should be closed. This is a valid point. Testing that no unintended parts of the state tree are modified should also be implemented.

**Comment by carnag3kid7** [comment]
Perhaps you could create a helper function in your test that ensures no side effects are introduced on the function you are testing. 
```javascript
   compare(oldState, newState, ignoredProperties){
       //remove the ignoredProperties from newState and oldState
      // return boolean result of comparison between newState and oldState
   }
```
And then in the test

```javascript
   it('should show alert when "show alert" action is dispatched', () => {
           // arrange
            ....
           dispatch(alertShow());

           expect(newState.alert.show).to.equal(true); //test for modified state
           expect(compare(oldState, newState, newState.alert).isTruthy();
    });
```

**Comment by amit1911** [comment]
Thanks @carnag3kid7 ....This is what I did, but it still doesn't solve the problem completely because we still cannot know if the `primitives` changed or not. For example:- If a number in the state did not change after an action it still doesn't guarantee that it was not modified.

**Comment by carnag3kid7** [comment]
@amit1911 I see what you mean. I am also having this issue now. I think another way would be to iterate through all the properties and use [obj.watch(prop, handler)](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/watch) and just fail the test if any unwanted assignments or modifications have been made. But from the docs it says the `watch()` and `unwatch()` have performance overhead.
