### ISSUE TITLE
Docs: Fragment URLs doesn't work on docs

### ISSUE THREAD

**Issue by tugberkugurlu** [reactjs/redux#1865]
Example: http://redux.js.org/docs/basics/UsageWithReact.html#presentational-and-container-components It doesn't navigate me to `presentational-and-container-components` element inside the page.

**Comment by markerikson** [comment]
Yeah, it's an issue with Gitbook and the sidebar causing the page to snap back up to the top.  See some of the discussion in #345 .  I actually added a plugin to Redux's Gitbook config that sorta-kinda fixes things (by forcing a re-jump back to the anchor after a timeout), but looks like the last publish of the docs didn't include that plugin.

**Comment by timdorr** [comment]
Sorry about this! Looking into it via the linked PR.

**Comment by timdorr** [comment]
Updated and republished!

**Comment by markerikson** [comment]
Hmm.  Going to the original hash URL linked in the issue doesn't jump anywhere - in fact, the hash gets removed from the URL entirely.  The previous (busted) behavior was that you'd very briefly jump to the correct location, then snap back up to the top, while the hash stayed in the URL.  Definitely doesn't seem like this is working as desired.

**Comment by timdorr** [comment]
It does remove the hash, but it scrolls down for me. This link works for me: http://redux.js.org/docs/basics/UsageWithReact.html#containersfilterlinkjs

**Comment by markerikson** [comment]
Hmm.  I see the behavior you describe in Chrome (which I keep around for debugging purposes), but not in my personal FF43 instance.  Pretty annoying.
