### ISSUE TITLE
Example with flow types

### ISSUE THREAD

**Issue by sandysaders** [reactjs/redux#1866]
It would be nice to see an example of using flow with redux. I've seen a few articles that start to explain how to use flow with redux and it just seems like it would be useful for people like myself who know how to use redux but not flow and want to see both be used in an example app. [This](http://frantic.im/using-redux-with-flow) article starts to show the benefits really quickly and It would be dope if someone familiar with flow could make add an example app in the examples folder.

**Comment by jimbolla** [comment]
See #1887

**Comment by timdorr** [comment]
Oh, this was merged in. Great! 😄
