### ISSUE TITLE
zero conf redux

### ISSUE THREAD

**Issue by fibo** [reactjs/redux#1869]
I would like to share a package I wrote to have a dev environment for redux with no configuration file needed (uses budo+livereactload): [zeroconf-redux](https://www.npmjs.com/package/zeroconf-redux).

I found it really comfortable to forget about configuration and just start coding a redux App.

Is it worth to add it to some list of redux tools, maybe in sone wiki or documentation? If yes, please let me know if I can do apull request or something.

If there is any feedback to improve the package or something missing it should be added, please let me know

Thank you for giving us redux, which is for me the first time I really liked webapp development workflow.

**Comment by timdorr** [comment]
Thanks, @fibo. Looks neat! 

I would wait until you've gotten some traction. Sending users you way might cause an overload and burnout on your end, so it's best to build this stuff up organically and over time to avoid any scaling issues with the project. Feel free to submit a PR when you think it's ready!
