### ISSUE TITLE
Docs: some links ask you to download .md files

### ISSUE THREAD

**Issue by MoOx** [reactjs/redux#1870]
The screenshot is easy to understand (same behavior on Firefox Nightly and stable Chrome)

![screen shot 2016-07-26 at 14 55 08](https://cloud.githubusercontent.com/assets/157534/17138565/35a12b18-5341-11e6-96dd-315d9ea1a3f7.png)

**Comment by timdorr** [comment]
Looks like this is fixed with a rebuild.
