### ISSUE TITLE
Unable to figure out a better way of doing things with Redux

### ISSUE THREAD

**Issue by yash0087** [reactjs/redux#1879]
I have a ReactJs app which uses Redux to manage its store. My state is a complex json whose fileds can change. When i initiate  the reducers, i have to specify the initial state else when accessing it before fetching the content from server, i get 'undefined' error. Following is the example,

    //Test.jsx
    class Test extends React.Component{
        componentWillMount(){
           fetchContent({
             type: SET_CONTENT
           });
        }
        render(){ 
          return(
           <div> {this.props.header} </div>
          )
        }
        mapStateToProps(state){
           return{
             header: state.reducer1.a.b.c
           }
        }
    }
    export default (mapStateToProps)(Test);

    //reducer1.js
    export default function reducer1(state = {}, action = {}) {
      switch (action.type) {
        case SET_CONTENT:
          return Object.assign({}, action.data);
        default:
          return state;
      }
    }
      
    //reducer2.js
    export default function reducer2(state = {}, action = {}) {
      switch (action.type) {
        case SET_SOMETHING_ELSE:
          return Object.assign({}, action.data);
        default:
          return state;
      }
    }
      
    //CombinedReducer.js
    export default combinedReducers(Object.assign({}, {reducer1}, {reducer2}))

Now when the component initialises for the first time, ```state.reducer1.a.b.c``` throws undefined because the ```fetchContent()``` doesnt seems to be called at this point. 

So my question is how do i solve this issue? Is specifying the initial state in reducer the only option? like the following,

    //reducer1.js
    export default function reducer1(state = { a: { b: { c: "somedata"}}}, action = {}) {
      switch (action.type) {
        case SET_CONTENT:
          return Object.assign({}, action.data);
        default:
          return state;
      }
    }

**Comment by yash0087** [comment]
@gaearon Any help would be much appreciated :)

**Comment by carlesba** [comment]
You have to figure out the shape of your store. The simpler, the better. If your backend returns some big, ugly object you probably need to slice it to make it fit into your store.

Using actions like `SET_CONTENT` is not a good idea.

**Comment by yash0087** [comment]
@carlesba does that mean I can't store nested json data in my store workout having to face the issue?

**Comment by yash0087** [comment]
Sorry I meant "  does that mean I can't store nested json data in my store without having to face the issue"

**Comment by markerikson** [comment]
If you know you're going to be extracting nested data from the state, and that the nested data may not exist at the time a component is created, your basic choices are to either ensure that a suitable set of initial values are available instead, or handle the lookup process safely (such as checking one step of the nesting at a time and returning a default value if the next level doesn't exist).  This can be done within selector functions, within a `mapState` function, using one of the many "safe nested lookup"-type utility libraries out there, etc.

Looking at the description, it doesn't seem like it's ultimately a Redux-specific question.  It comes down to handling nested data which might not exist yet, which is a more general question.

**Comment by yash0087** [comment]
Just to clarify, should the 'mapState' function not be executed after the 'componentWillMount' is run? I am asking this because in React most of the data fetching happens in this life-cycle function. I think 'mapState' function gets executed even before the actual React life-cycle event starts and at this point the redux store needs to have an initial state without which it throws 'undefined field' kind of error.

Also in real time big projects, the json data returned from the server would be nested and complex and slicing them into tiny part and having one reducer for each of them would mean we would end up having lots of reducers which i dont think is correct?

**Comment by yash0087** [comment]
Or, Prefetching the actual data and passing it to redux store while creating the store is a better way of doing it?

**Comment by sompylasar** [comment]
@yash0087 You should handle the initial (empty, no data) state in your components, render some loading indicator. You may use various ways to detect that the store hasn't been populated yet.
