### ISSUE TITLE
Small documentation wording fix

### ISSUE THREAD

**Issue by canibanoglu** [reactjs/redux#1881]
Hello,

I've been following the advanced guide from the documentation and I've come across the following phrase:

> Each of these two moments can usually require a change in the application state ...

And I kept thinking that it should either be

> Each of these two moments can require a change in the application state ...

or 

> Each of these two moments usually require a change in the application state ...

I went over the contributing guidelines and couldn't fine anywhere else to post this. Apologies in advance if this is the wrong place.

I would be happy to create a PR for this.

Cheers,

Can

**Comment by canibanoglu** [comment]
Come to think of it, there are some other inconsistencies that I can see in the advanced guide. There are also incomplete sections but I assume you are already well aware of them. I'll come up with a list of problems that I have noticed.

**Comment by Aweary** [comment]
@canibanoglu usually it's fine just to open a PR with your documentation changes and they can be reviewed there!

**Comment by canibanoglu** [comment]
@Aweary ah, thanks a lot for the pointer :) Will prepare a PR then
