### ISSUE TITLE
combineReducers converts Immutable Map into plain JS object

### ISSUE THREAD

**Issue by sarink** [reactjs/redux#1894]
According to my reading, this should no longer happen in redux v3? Or am I doing something wrong?

myReducer.js
```
import { Map } from 'immutable';

const initialState = Map({});

export default (state = initialState, action = {}) => {
  switch (action.type) {
    default:
      // On the third run "@@INIT" the state gets converted from a Map to a plain JS object :(
      console.log('action:', action.type, 'state:', state);
      return state;
  }
};
```

output
```
action: @@redux/INIT
state: Map {size: 0, _root: undefined, __ownerID: undefined, __hash: undefined, __altered: false}

action: @@redux/PROBE_UNKNOWN_ACTION_x.5.a.b.w.u.f.k.8.3.q.b.s.5.e.e.4.5.c.d.i
state: Map {size: 0, _root: undefined, __ownerID: undefined, __hash: undefined, __altered: false}

action: @@INIT
state: Object {}
```

**Comment by markerikson** [comment]
Uh.... no, `combineReducers` only knows how to work with plain JS objects.  Not sure why you think this has changed at some point.  If you need a similar function that knows how to work with an Immutable Map, there's a number of utilities along that line listed at https://github.com/markerikson/redux-ecosystem-links/blob/master/immutable-data.md#immutableredux-interop .

There has been some discussion of making `combineReducers` configurable so it could iterate over a plain JS object, an Immutable map, or something else if needed, but that seems to be stalled at this point.  See #1792 .

**Comment by sarink** [comment]
Ah, I guess I misunderstood. Sorry and thanks for the clarification.

**Comment by sarink** [comment]
Is this still the case if my `state` is a plain object but the keys within state are Immutables?

**Comment by markerikson** [comment]
That should work okay.  The point is that `combineReducers` does:

```js
var finalReducerKeys = Object.keys(finalReducers)

// later
    for (var i = 0; i < finalReducerKeys.length; i++) {
      var key = finalReducerKeys[i]
      var reducer = finalReducers[key]
```

Which obviously only works with plain objects.  It's the iteration over the object that's the issue - if the values at each key are Immutable objects, that's fine as long as the slice reducer can handle those.

**Comment by sarink** [comment]
This is exactly how my setup is, because we're slowly transitioning to Immutable. So... This shouldn't be an error. What's wrong?
