### ISSUE TITLE
src folder in published package

### ISSUE THREAD

**Issue by hpurmann** [reactjs/redux#1902]
I just noticed that the `src` folder is included in the npm package. From the code execution point of view, this folder is just cruft, right?

Is there any specific reason not to `.npmignore` this folder to save some KBs?

**Comment by markerikson** [comment]
Haven't dealt with the packaging side, but I could see a potential use case for someone who's doing minimal amounts of transpiling to directly import the ES6 codebase files and use them as-is.

**Comment by gaearon** [comment]
It's there for folks who want to read the source to better understand it. Removing is not really going to save any meaningful size.
