### ISSUE TITLE
Docs: Add example of using createStore with just enhancer function

### ISSUE THREAD

**Issue by jrajav** [reactjs/redux#1903]
In https://github.com/reactjs/redux/blob/master/docs/api/createStore.md it's not immediately obvious that you can pass `enhancer` as the second parameter if no `preloadedState` is passed. This might be a little more clear if a something like a second signature of `createStore(reducer, [enhancer])` was added, or an example of using it with just the two parameters.

**Comment by timdorr** [comment]
A PR for this would be great!

**Comment by seriCodes** [comment]
He's right!
