### ISSUE TITLE
define.amd not defining Redux on CDN

### ISSUE THREAD

**Issue by ppalladino** [reactjs/redux#1905]
The version of redux on [cdnjs](https://cdnjs.cloudflare.com/ajax/libs/redux/3.5.2/redux.js) does not define the 'Redux' amd module. I believe line 5 should be changed from:

```js
define([], factory);
```

to:

```js
define('Redux', [], factory);
```

I am not sure who maintains the CDN build. I apologize if it is someone else....

**Comment by gaearon** [comment]
It's generated by Webpack with [these settings](https://github.com/reactjs/redux/blob/14834591ea8525e373b5ab660af406d8cc847358/webpack.config.js#L12-L15). Maybe they need some sort of tweaking?

**Comment by SimenB** [comment]
Maybe this? https://webpack.github.io/docs/configuration.html#output-umdnameddefine

**Comment by ppalladino** [comment]
@SimenB That looks like it to me!

**Comment by gaearon** [comment]
What are the upsides and downsides of doing it? There might be some reason this isn't the default.

**Comment by SimenB** [comment]
The recommend way of AMD is to have all anonymous, as this allows greater flexibility for the consumer.

But for libraries, naming themselves isn't any real problem, I think.

http://requirejs.org/docs/whyamd.html#namedmodules

**Comment by ppalladino** [comment]
I am not making an argument one way or the other, but here is a use case and I think a typical situation for a Polymer project:

- At work we use Polymer, the two way binding is a mess and we want to clean it up using Redux
- Polymer does not play well with webpack so we are pulling in Redux via bower and cdnjs
- IMD is the AMD module manager for Polymer. 
- We import IMD which sets 'define' in the global namespace.
- Then import our AMD dependencies. These will sniff for 'define' and instead of adding a global reference to themselves, register with the AMD manager
- If Redux does not give itself a name while registering with AMD, one has to import Redux prior to IMD, letting Redux add a global reference to itself, import IMD, then cherry pick Redux from the global namespace and add to 'define' manually or in a wrapper module.

**Comment by ppalladino** [comment]
After poking around a bit it probably makes sense to leave it undefined. Popular libraries seem to prefer anonymous module definitions. Lodash in particular, for good reason, allows developers to define it as the "_" module. Our project is using IMD (the AMD implementation for Polymer) and after reading the docs, it allows developers to set names on modules via:

```html
<script src="thingo.js" as="thingy"></script>
```
