### ISSUE TITLE
React view vs reducer dilema

### ISSUE THREAD

**Issue by mehrdaad** [reactjs/redux#1909]
I'm sorry to opening a new issue but I was afraid this type of  question would get closed as opinionated on SO.
I'm using React with Redux in my app and I know reducer should be pure functions.
there is an authentication system in my app.  
The only question I have is that where should take the responsibility of saving tokens.  
Should they be saved in reducer or should the action dispatch another action which would save the token or would it be saved in the view?

**Comment by markerikson** [comment]
Since this is a usage question, this _should_ be asked on SO, not in an issue tracker.  You may also want to read through the Redux FAQ for some ideas: http://redux.js.org/docs/FAQ.html .
