### ISSUE TITLE
Add store.replaceMiddlewares?

### ISSUE THREAD

**Issue by lucasconstantino** [reactjs/redux#1916]
`store.replaceReducer` is very useful for hot loading and code splitting, but this only affects reducers. What if there is the need to insert a new middleware or even some enhancer? More: could an enhancer be capable of providing such functionality?

**Comment by markerikson** [comment]
This could actually be implemented inside a custom middleware, really - no need for another enhancer.  I could totally envision a middleware that constructs its own dynamic middleware pipeline internally, and listens for actions like `ADD_MIDDLEWARE`, `REMOVE_MIDDLEWARE`, `REORDER_MIDDLEWARE`, etc.  Not entirely sure what the use case would be, but absolutely feasible.

I suppose the most effective way to use it would be to create your "custom pipeline" middleware, pass all the "real" middlewares like thunk and saga to that, and then pass the "custom pipeline" middleware as the only arg to `applyMiddleware`.

**Comment by timdorr** [comment]
I'm also not sure this would be the right thing to do. Middlewares normally handle side effects, so a simple replacement might be error prone.
