### ISSUE TITLE
todos example hot reload not working.

### ISSUE THREAD

**Issue by leedorian** [reactjs/redux#1917]
When the  ./components/Link.js is changed, the HMR is triggered on todos example of redux, I got this warning:

`[HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See http://webpack.github.io/docs/hot-module-replacement-with-webpack.html for more details.
process-update.js?e13e:89 [HMR]  - ./components/Link.js`

Then I followed the instructions of HMR, added code lines in index.js, but still got same message and changes were not applied. But the changes of reducers were applied immediatly by HMR, the changes of actions, containers, components were not applied also.
```javascript
import 'babel-polyfill'
import React from 'react'
import { render } from 'react-dom'
import { Provider } from 'react-redux'
import { createStore } from 'redux'
import todoApp from './reducers'
import App from './components/App'
// if (module.hot) {
//   module.hot.accept();
// }

let store = createStore(todoApp)
const rootElement = document.getElementById('root');
if (module.hot) {
  

  // Enable Webpack hot module replacement for reducers
  module.hot.accept('./reducers', () => {
    const nextRootReducer = require('./reducers').default;
    store.replaceReducer(nextRootReducer);

  });


   render(
      <Provider store={store}>
        <App />
      </Provider>,
      rootElement
    )
}
```

**Comment by timdorr** [comment]
It is because your React component is being told to hot reload and has not been configured too. I suggest looking into adding React Hot Loader.

**Comment by leedorian** [comment]
@timdorr , thanks, React Hot Loader works.
