### ISSUE TITLE
Why did you disable React-router links in documentation?

### ISSUE THREAD

**Issue by wzup** [reactjs/redux#1919]
What happened to `react-router`. Don't you support it anymore?

![async flow _ redux - google chrome 2016-08-30 20 53 35](https://cloud.githubusercontent.com/assets/3880497/18089723/f0ce7ee0-6ef3-11e6-8e26-ea65b71a4b14.png)

**Comment by vnctaing** [comment]
Because it is not written yet, I think : https://github.com/reactjs/redux/blob/master/docs/advanced/UsageWithReactRouter.md

**Comment by markerikson** [comment]
Yeah, there's a couple sections of the docs that were sketched out, but never actually written.  PRs totally welcome! :)

**Comment by wzup** [comment]
But there was a link. And I followed it. I read docs about `react-router`. Don't understand it.
