### ISSUE TITLE
Application States not getting update

### ISSUE THREAD

**Issue by sajumani** [reactjs/redux#1921]
Hi,

my applications states not getting update, it was working correctly, 

from now it won't work... now my complete application not running

**Comment by vnctaing** [comment]
I wish I could help you but can you provide us some code ? Maybe try to ask the question on StackOverflow, usually issues on github are for feature request, bug, enhancement for the repo itself rather than a usage problem

**Comment by sajumani** [comment]
Thanks for reply @vnctaing , it was version issue .. i fixed with latest version
