### ISSUE TITLE
Rollup build broken, fixed in master, not in npm

### ISSUE THREAD

**Issue by marvinhagemeister** [reactjs/redux#1924]
Currently, one cannot bundle redux with rollup, because of an older `symbol-observable`dependency. This is fixed in master with ab0724d09b74a5f3a11fc149508d174c09f3ce86.

Is there any chance of making a new release and publishing it on npm?

**Comment by gaearon** [comment]
@timdorr Could you take a look at this?

**Comment by timdorr** [comment]
Yeah, I've been meaning to dive into a bug fix release and then looking at the v4 stuff that's laying around. I can try to find some time this weekend.

**Comment by timdorr** [comment]
Published! https://github.com/reactjs/redux/releases/tag/v3.6.0
