### ISSUE TITLE
Testing Async Action Creators: 'fetch is not defined'

### ISSUE THREAD

**Issue by timkraut** [reactjs/redux#1925]
Hi,

I've followed closely the [guide on testing async action creators](http://redux.js.org/docs/recipes/WritingTests.html#async-action-creators). Unfortunately, I get the error 'fetch is not defined'. I know that this is not really a bug or a feature request but there seem to be other people which had the same problem. Are there any requirements besides what is noted in the docs? Like Node 6? Is Mocha a requirement or rather a recommendation?

I use the latest Redux version (3.5.2) with Jasmine 2.5.0 and Jest 15.1.1 as the task runner on Node 4.4.7.

Thank you!

P.S.: I hope that this issue doesn't fall under the Should-go-to-Stackoverflow category.

**Comment by timkraut** [comment]
Ah... too bad... I've just found the solution myself. I haven't been using the import on isomorphic-fetch in the file to test. It's in the guide for async actions but not in the testing example. I'll update the docs.

**Comment by muzidx** [comment]
hi, I met a problem similar to yours, can help me look at the reasons for mistakes, thx:

To test redux async actions, error own fetch func is not find.
error: `TypeError: Cannot read property 'post' of undefined`


actions: (as example)

```
import { Fetch, ErrorLog } from 'market-rc-utils'
import * as types from './constant'

export function loadFetch(url, code) {

  return (dispatch, getState) => {
    dispatch({ 'type': types.REDEEM})

    return Fetch.post(url, {
      'code': code
    }).then((res) => {
      let r = parseInt(res.r, 10)
      if (r === 0) {
        return dispatch({ 'type': types.LOAD_SUCCESS, res})
      } else {
        return dispatch({'type': types.LOAD_FAIL })
      }
    }).catch((err) => {
      return dispatch({'type': types.LOAD_FAIL})
    })
  }
}

```

test code:
```
import * as types from './../src/constant'
import { redeemFetch } from './../src/action'
import redeemReducer from './../src/reducer'

import configureMockStore from 'redux-mock-store'
import thunk from 'redux-thunk'

const middlewares = [thunk]
const mockStore = configureMockStore(middlewares)

describe('load:actions', () => {

  it('should handle redeemFetch', () => {
    // here need some fetch setting ...?

    const store = mockStore({r: 0, data: []})
    const url = 'api/xxx'
    const code = 'sss'
    return store.dispatch(loadFetch(url, code)).then(() => {
      const expectActions = {
        type: types.LOAD_SUCCESS
      }
      expect(store.getActions()[0]).toEqual(expectActions)
    })
  })
})
```

fetch func is my package of func, contain get, post, some else func.
I guess if need to my fetch func, get post method, or set global.fetch as nock api?
