### ISSUE TITLE
Curried reducers

### ISSUE THREAD

**Issue by rvikmanis** [reactjs/redux#1927]
The idea is to use curried "action-first" reducers like in Elm.

I propose calling them `updaters` to differentiate from regular reducers. (in Elm the reducing function is by convention called `update`)

Instead of taking the current state and action, and returning the next state,
an updater takes the action and returns a function that takes the current state and returns the next state.
```js
nextState = updater(action)(currentState)
```

Compare the signature of a normal reducer to that of an updater:

```js
type Reducer<C, A, S> = (currentState: C, action: A) => S
type Updater<A, C, S> = (action: A) => (currentState: C) => S
```

The reason why updaters are better suited for Redux, which arguably embraces functional programming, is that they can be composed with any curried "context-last" function, allowing [point-free style](https://en.wikipedia.org/wiki/Tacit_programming) and declarative reducer creation with libraries like [lodash/fp](https://github.com/lodash/lodash/wiki/FP-Guide) or [Ramda](http://ramdajs.com).

Consider this example, where we call the updating function with `state`:

```js
import { update, concat } from 'lodash/fp'

const reducer = (state, action) => {
  if (action.type === 'PUSH')
    return update('list', concat(action.payload))(state)

  return state
}
```

Same example, as a point-free updater - we return the updating function itself:

```js
import { update, concat } from 'lodash/fp'

const updater = (action) => {
  if (action.type === 'PUSH')
    return update('list', concat(action.payload))

  return state => state
}
```

---

Should `createStore` expect an updater or a reducer by default?
  
  Converting reducers to updaters and vice versa is trivial:
  ```js
  const fromReducer = (reducer) => action => state => reducer(state, action)
  const fromUpdater = (updater) => (state, action) => updater(action)(state)

  const applyReducerEnhancer = (reducerEnhancer) => (createStore) => (reducer, ...args) => {
    return createStore(reducerEnhancer(reducer), ...args)
  }
  ```
  * if the API for `createStore` is not to be altered, a store enhancer should be bundled:
    ```js
    const adaptStoreForUpdaters = applyReducerEnhancer(fromUpdater)
    ```

    Usage:
    ```js
    const store = createStore(updater, adaptStoreForUpdaters)
    ```

  * if `createStore` is to accept updaters by default, regular reducers would have to be decorated with `fromReducer` to work:
    
    ```js
    const store = createStore(fromReducer(legacyReducer))
    ```
  
---

**Is this a good idea for Redux core?**

**Comment by rvikmanis** [comment]
**Related**

* [redux-fp](https://github.com/rvikmanis/redux-fp) - helpers for dealing with updaters

**Comment by timdorr** [comment]
It sounds like your library achieves this without modification to the core. I don't think the main library needs to support this directly, as it's mainly a boilerplate reducer and there are varying opinions on how to reduce boilerplate and deal with your reducers as a whole.
