### ISSUE TITLE
Make applyMiddleware optionally support a more "Nodeish" API

### ISSUE THREAD

**Issue by dtothefp** [reactjs/redux#1932]
**Do you want to request a *feature* or report a *bug*?**  
feature

**What is the current behavior?**
```js
function someMiddleware(opts) {
  return ({ dispatch, getState }) => next => action => //do stuff
}
```

would be nice and easier to understand for those used to Node/Express/Koa to do 
```js
function someMiddleware(opts) {
  return ({ dispatch, getState }) => (action, next) => //do stuff & call `next()`
}
```
Would be trivial to do and could be made backwards compatible for current middleware style by checking middleware function argument length

```js
const [last] = chain.slice(-1);
const rest = chain.slice(0, -1);
const wrap = (fn, next) => action => fn(action, next);

const newDispatch = rest.reduceRight((next, fn) => {
  return fn.length === 2 ? wrap(fn, next) : fn(next);
}, wrap(last, store.dispatch));
```
Sorry if similar issues have been previously posted (I didn't find any in my search) and wondering if you'd be open to a PR?

**Comment by markerikson** [comment]
Yeah, variations on this have been discussed previously, and turned down.  See #534 , #922, and #1744  for prior discussion.

**Comment by dtothefp** [comment]
😢  seems like being able to provide this API while at the same time supporting `next => action` through arguments check is best of both worlds `¯\_(ツ)_/¯`

**Comment by jimbolla** [comment]
You could write your own applyMiddleware, [as it's only about 20 lines of code](https://github.com/reactjs/redux/blob/master/src/applyMiddleware.js)
