### ISSUE TITLE
Typescript: compose function should be able to accept single rest argument

### ISSUE THREAD

**Issue by Strate** [reactjs/redux#1935]
As for now, it is not possible to call `Resux.compose` like this:
```ts
declare const middlewares: Redux.Middleware[];
declare const enhancers: Redux.GenericStoreEnhancer[];
const enhancer = Redux.compose(Redux.applyMiddleware(...middlewares), ...enhancers);
```
This is broken since https://github.com/reactjs/redux/pull/1868 was merged.
I think we should have an overloading for `compose`, which covers this case.
/cc @aikoven

**Comment by aikoven** [comment]
Thanks, pushed a fix: #1936
