### ISSUE TITLE
Convert test suite to Jest

### ISSUE THREAD

**Issue by timdorr** [reactjs/redux#1944]
Since we now [recommend using Jest](https://github.com/reactjs/redux/pull/1943), we should practice what we preach 😄 

Jest 15 introduces some major improvements and makes the TDD process a heck of a lot easier and more fun. It's also faster and and has more helpful error messages. It's really awesome and there's good reason for its recommendation in the Writing Tests docs.

This is a request for a PR from the community. If you want to help out with open source development, this is a great chance to do so. Just remove `mocha` (the current test runner) and `expect` (Jest provides an `expect` function built-in), and switch out the test suite to run through Jest instead. There are hopefully only minimal changes needed to the actual test code, so this should mostly be just simple infrastructure work.

It *should* be good for beginners, but let us know if anything is particularly challenging. We can pass that along to the Jest team, who is always looking for ways to make the tool as friendly and fun as possible.

**Comment by jimbolla** [comment]
I was going to suggest the same thing

**Comment by HeinrichFilter** [comment]
I am keen to give it a try.

It will be my first contribution to a popular project. Please feel free to point out mistakes or anything that can be done better/differently.

**Comment by timdorr** [comment]
Thanks @HeinrichFilter!
