### ISSUE TITLE
Is getMappedItems an anti-pattern in mapStateToProps?

### ISSUE THREAD

**Issue by pgilad** [reactjs/redux#1948]
In all `real-world` examples (including code we use in our own work) I see the following pattern emerging in `mapStateToProps`:

```js
// action
export const getOrganizations = state => state.entities.organizations;

export const getMappedOrganizations = (state, ids) => {
    const { byId } = getOrganizations(state);
    return ids.map(id => byId[id]);
};

// view
const mapStateToProps = state => {
    const { byAll } = getOrganizations(state);
    const organizations = getMappedOrganizations(state, byAll.ids);

    return {
        isFetching: byAll.isFetching,
        lastUpdated: byAll.lastUpdated,
        organizations,
    };
};
```

This provides the view all the data it needs, but unfortunately `organizations` will always be a new array when store updates, resulting in redundant updates of the view even though nothing has changed.

This is especially noticed when you have a **popup** or **modal** that updates store as well, and the list in the background, resulting in slowness because the view is always updating.

Is this really the advised pattern? Should you modify `shouldComponentUpdate` to fit it for `non-shallow` comparison in this case? Perhaps you should pass down the functions to create the mapped items and do so in the render function instead?

**Comment by nighca** [comment]
In this case, you can use [reselect](https://github.com/reactjs/reselect) to create your selectors, so that their result can be memoized.
For example:

```javascript
import { createSelector } from 'reselect'

const organizationsSelector = state => state.entities.organizations;

const allOrganazationIdsSelector = createSelector(
  organizationsSelector,
  organizations => organizations.byAll.ids
)

const allOrganazationsSelector = createSelector(
  organizationsSelector,
  allOrganazationIdsSelector,
  ({ byId }, ids) => ids.map(id => byId[id])
)

const mapStateToProps = state => {
    const { byAll } = organizationsSelector(state);
    const organizations = allOrganazationsSelector(state);

    return {
        isFetching: byAll.isFetching,
        lastUpdated: byAll.lastUpdated,
        organizations,
    };
};
```

**Comment by pgilad** [comment]
Great answer! thanks for the help!
