### ISSUE TITLE
How to communicate between pages

### ISSUE THREAD

**Issue by jasonji** [reactjs/redux#1949]
I think react/redux doesn't have this feature:
https://stackoverflow.com/questions/39452497/how-to-communicate-between-pages

**Comment by markerikson** [comment]
This is totally out of scope for the Redux library itself.  Redux is simply a tool to store data in memory for a given application.

There _are_ a number of addons that build on top of Redux to provide persistence and synchronization of actions and store data in various ways.  See https://github.com/markerikson/redux-ecosystem-links/blob/master/store.md#store-persistence for some examples.
