### ISSUE TITLE
Error level

### ISSUE THREAD

**Issue by MrEfrem** [reactjs/redux#1956]
Hello!
I permanently receive warnings:
```
warning.js?07c3:14Unexpected key "ui" found in previous state received by the reducer. Expected to find one of the known reducer keys instead: .... Unexpected keys will be ignored.warning
```

It occurs because in the beginning I on the server fill a redux state and then I rehydrate it on the client. But before starting rendering of components I don't know what reducers is required because i register them in components.

This message to operation is finite doesn't hinder, but strongly irritates.

There are some options to disable it? Can transfer some flag, for example level of errors?

**Comment by timdorr** [comment]
Constructing your state on the fly can be fairly difficult to manage. I would try something similar to the data fetching problem, where you pre-register what reducers a particular component tree will need before rendering. That should give you the same state tree and rendered HTML on both the server and client.

**Comment by MrEfrem** [comment]
I use such approach for dynamic registration of reducers in the reused components. It reduces coding when using of the reused components. 
Your approach delivers inconveniences and I don't understand why I shall follow it.
In redux it isn't put that my approach breaks its ideology. For you control creation of a status on the fly looks difficult, for me seems not such difficult.
