### ISSUE TITLE
Connect() not notified of changed on cross-reducer store.

### ISSUE THREAD

**Issue by qualifyapp** [reactjs/redux#1962]
**What is the current behavior?**

Currently, connect() does not update props of a changed array on a nested object in the store.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

Example:

Reducer 1:
```
    state = {
         collection: {
              key: { 
                   valA: '',
                   valB: []
              }
          }
    }
```

Reducer 2:
```
    state = {
        selected: ''
    }
````

connect:

```
connect(state => {
    return {
        selected: state.reducer2.selected,
        collection: state.reducer1.collection[state.reducer2.selected].valB
    }
})(Component)
```

**What is the expected behavior?**

In this event, I would expect the `props` to be updated whenever an element is added to the nested array in the first reducer's state.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

Version 3.6.0 - Usage with react-native, iOS.

**Comment by jimbolla** [comment]
Can you show your reducer function?

**Comment by markerikson** [comment]
Yeah, the wording "an element is added to the nested array" concerns me.  That sounds as if you're doing `someArray.push(newValue)`.  Remember that `connect` does _shallow equality_ checks on the objects returned by your `mapState` function.  If that `collection` key points to the same array reference both times, `connect` will assume nothing has changed and it won't re-render.

**Comment by timdorr** [comment]
Mark is right. You need to be building a new state object every time you handle an action. If you're manipulating the existing object, then you need to refactor your reducer.
