### ISSUE TITLE
Component connected to dispatch with `mapDispatchToProps`

### ISSUE THREAD

**Issue by sniperyan** [reactjs/redux#1973]
I have only one connect in the top container.The code is below:
```javascript
const mapStateToProps = state => {
    return {
        shopmanList: state.shopmanList.shopmanList
    }
};
const mapDispatchToProps = (dispatch) => ({
    actions: bindActionCreators(Object.assign({}, shopmanAction), dispatch),
    dispatch: dispatch
});
export default connect(mapStateToProps, mapDispatchToProps)(ShopmanListApp);
```
but when i try to dispatch an action after the page is rendered,i see the bug is like that : dispatch the action trigger once , action creator trigger once , but the reducer function which is match with ActionType trigger two times .  I have debugged the code for many times and i find the question is at the linsteners of the  `createStore`  in the package of `redux` . Every time the reducer triggers two time,there must be two listeners . I try to solve this the problem and finally solved . i modify my code like that :

```javascript
const mapStateToProps = state => {
    return {
        shopmanList: state.shopmanList.shopmanList
    }
};
export default connect(mapStateToProps)(ShopmanListApp);
```
but i dont know why so !

Versions: 
"react-redux": "^4.4.5",
"redux": "^2.1.0",

**Comment by timdorr** [comment]
This is probably better discussed on the react-redux repo: https://github.com/reactjs/react-redux

Can you open up an issue over there and also show the code of how you dispatch/call the action? Nothing looks particularly wrong with what you've got, but it would be more clear if we also knew how you were using it.

**Comment by markerikson** [comment]
I'm also not clear what's meant by "dispatch the action trigger once , action creator trigger once".  Or what the exact issue is, for that matter.  Are you saying that the reducer function itself is being run twice for a single dispatched action, or that `mapState` is being run twice?
