### ISSUE TITLE
Minor fix for createStore JSDoc

### ISSUE THREAD

**Issue by FlyingDR** [reactjs/redux#1979]
Currently [JSDoc definition](https://github.com/reactjs/redux/blob/master/src/createStore.js#L31) of `enhancer` argument of `createStore` function doesn't have it marked as optional while argument's comment says that it is optional. It results into "missed argument" warning from IDE, e.g. WebStorm.

**Comment by timdorr** [comment]
Can you submit a PR to fix it? Thanks!

**Comment by FlyingDR** [comment]
@timdorr PR #1984
