### ISSUE TITLE
The probelm with redux

### ISSUE THREAD

**Issue by zhangk2000** [reactjs/redux#1981]
I 'v been researching on redux for a while,
still unable to use it in to my project.

Redux makes things more complicated, even if you just want to implement a list retrieved from server.
you have to write much more boilerplate codes , in order to get redux works.

I really doubt if all the efforts worth the cost.

 does anyone have the same doubt?

**Comment by canibanoglu** [comment]
Uh no. No one is advocating the use of Redux in simple projects where you can reason about the state easily. You can do it but Redux really shines in more complex projects where state management is a serious issue.

**Comment by alexeyraspopov** [comment]
You definitely don't need Redux if you just want to show data retrieved from a server. Check [this](https://facebook.github.io/react/tips/initial-ajax.html) article and maybe [this](https://github.com/RickWong/react-transmit) project.

**Comment by markerikson** [comment]
This is a bug tracker, and not intended as a discussion forum.  FWIW, Dan did just write a post on this topic: https://medium.com/@dan_abramov/you-might-not-need-redux-be46360cf367 .
