### ISSUE TITLE
From "http://redux.js.org/docs/basics/Actions.html" -> 'VisibilityFilters'

### ISSUE THREAD

**Issue by SeanJM** [reactjs/redux#1983]
I think that `VisiblityFilters` is a constant containing a record of constants and since it isn't a constructor it should be rewritten like this `VISIBILITY_FILTERS` <-- this is clear to me that it isn't a constructor, it is a constant.

Thank you.

**Comment by timdorr** [comment]
The `VisibilityFilters` variable isn't an action type constant itself, but a collection of those constants. 

Also, keep in mind the `const` statement in ES2015 isn't like constants in other variables. This is totally valid code:
```js
const thing = { foo: 123 }
thing.foo = 321
```
The only thing constant is that the variable points to the same thing at all times. It doesn't make those things read-only.

**Comment by SeanJM** [comment]
Yeah, if an object contains a list of types which are all UPPERCASED constants, why would it be different?

Sean

**Comment by brigand** [comment]
To clarify, the convention is PascalCase for constructors/classes and namespaces (e.g. React). This is a namespace.

**Comment by SeanJM** [comment]
Yeah, this isn’t a constructor or a class. It’s an object containing string CONSTANTS.

Sean

**Comment by SeanJM** [comment]
For me, it seems odd (and inconsistent) to look at the object which is “camelCase.STRING_CONSTANT”
