### ISSUE TITLE
Error: Unexpected property <reducer> found in previous state received by the reducer

### ISSUE THREAD

**Issue by wellyshen** [reactjs/redux#1994]
Hi Guys,

I use the async reducers to build my project. But I have encountered an error says :

<img width="1062" alt="2016-09-27 4 42 11" src="https://cloud.githubusercontent.com/assets/21308003/18866192/63e177d2-84d1-11e6-8e95-b1e0e57432bd.png">

Now my workaround is :
```javascript
export default function createReducer(asyncReducers) {
  return combineReducers({
    routing,
    home: (state = Map({})) => state,          // Add the initial reducer
    userInfo: (state = Map({})) => state,      // Add the initial reducer
    ...asyncReducers,
  });
}
```

Does anyone has great idea for it?

**Comment by timdorr** [comment]
`combineReducers` expects the object keys to be the same every time it processes a dispatch. So, if you have something that is producing keys for the object dynamically, then you need to provide that default initial set of keys for stuff that will load later. This is just a function of how `combineReducers` works. That workaround is essentially how you should be doing it.
