### ISSUE TITLE
Component not re-rendered after dispatch unless its state is changed

### ISSUE THREAD

**Issue by nuthinking** [reactjs/redux#2002]
For a prototype I registered directly the component instance to the store without having to create extra wrapping classes (note: the store is a dodgy singleton, it's a prototype after all).

    componentDidMount(){
        store.subscribe( this.render.bind(this) );
    }

The render method gets correctly called but even if the result returned is different than the previous value, the component doesn't get updated. If I bind the dispatch to a new method which updates the state and rendering based on the state instead it works.

    state = {
        open: false
    };

    componentDidMount(){
        store.subscribe( this.storeDidUpdate.bind(this) );
    }

    storeDidUpdate(){
        this.setState({open: store.getState().sessionActive});
    }

Is not possible to have dymamic rendering only based on the store state and not the component state?

Thanks!

**Comment by nuthinking** [comment]
(I find react-create-app a valid prototyping tool, just trying to find a way to quickly use redux to manage the state).

**Comment by jimbolla** [comment]
Calling `render` directly does not make React actually re-render. You'd have to do
```js
componentDidMount(){
    store.subscribe( this.forceUpdate.bind(this) );
}
```
This may be ok for prototyping, but would be absolutely horrible to do in "real code".

**Comment by markerikson** [comment]
You really shouldn't be manually subscribing to the store.  That's what the `connect` function from React-Redux does for you.  Use that instead.

And yeah, as @jimbolla said, binding `render` won't do anything meaningful anyway, since that's called by React as part of its update lifecycle.

**Comment by nuthinking** [comment]
Thanks a lot guys. All clear!

**Comment by nuthinking** [comment]
@markerikson what would be the simplest way to use connect(), for instance with a singleton store hence I guess without a Provider? (obviously just for prototyping).

**Comment by markerikson** [comment]
@nuthinking : Not sure I understand your question.  Why would you not be using `<Provider>`?

The basic pattern is to do this in your application's entry point:

```js
const store = createStore(reducer);

ReactDOM.render(
    <Provider store={store}>
        <App />
    </Provider>,
    rootDiv
);
```
