### ISSUE TITLE
invariant.js:38 Uncaught Invariant Violation: Objects are not valid as a React child

### ISSUE THREAD

**Issue by snovos** [reactjs/redux#2003]
If you have an object in class and in **render** method you have some condition
`render() {
{user && <div className="userInfo">some info</div>
}`
It will throw error.

Should convert object to boolean and then check

Affects all browsers and OS (latest version of redux)

**Comment by gaearon** [comment]
This issue has no relation to Redux as far as I can see.
Redux is a state management library, it isn’t related to React (a UI library).

Also it’s hard to say why you think it’s a bug from your example.
