### ISSUE TITLE
what allows this syntax "static propTypes = {"

### ISSUE THREAD

**Issue by keithn** [reactjs/redux#2004]
What makes that compile?

**Comment by brigand** [comment]
@keithn It's part of the "Public Class Fields" proposal. In babel it can be enabled with the state-2 preset or the transform-class-properties plugin.

**Comment by keithn** [comment]
right, seems like there's a lot of stuff in the "Examples" that use things that are not well explained / documented in terms of the build you need to setup....  which kind of defeats the purpose of examples.

**Comment by brigand** [comment]
Yeah, it's briefly mentioned in the create-react-app readme, near the bottom, but that's not obvious. If you use create-react-app, like the examples do, there's nothing you need to set up; it's included automatically.

**Comment by gaearon** [comment]
@keithn 

Examples use [Create React App](https://github.com/facebookincubator/create-react-app) for build setup.
I believe this is mentioned as the very first sentence in the README of every example:

<img width="516" alt="screen shot 2016-10-03 at 15 15 43" src="https://cloud.githubusercontent.com/assets/810438/19040514/52464822-897c-11e6-9423-efbd47de70e5.png">

Create React App takes care of all build configuration so you don’t need to configure anything if you use it. 

You can learn about Create React App in its [introductory blog post](https://facebook.github.io/react/blog/2016/07/22/create-apps-with-no-configuration.html) or [its repository](https://github.com/facebookincubator/create-react-app).

**Comment by markerikson** [comment]
I will say that we should maybe call out use of non-finalized features in the examples a bit more, for clarity.

**Comment by gaearon** [comment]
I agree. Ideally CRA docs should list supported features beyond ES6 and we should link to that list.

**Comment by keithn** [comment]
@gaearon   @markerikson   

A link to the list would be great.   While I've been pointed to various bits and pieces, I already have a webpack setup for React that I'm trying to modify so I can use redux, which in itself works ok, but the examples of using redux use language features that are hard to work out exactly how to get them to work.

**Comment by gaearon** [comment]
Would you like to help us out with that? You could look at packages/babel-preset-react-app in Create React App repository, write a list, and add this to its documentation in its user guide linked from the README.

**Comment by jonathanconway** [comment]
Was the above what you had in mind, @gaearon?
Apologies if I'm a bit off-track here. I'm new to open-source. 😸
