### ISSUE TITLE
Question: What should go in the state?

### ISSUE THREAD

**Issue by stunaz** [reactjs/redux#2021]
Hi,
Sorry this is not a but nor an issue, but really a question, perhaps I should have post this on stackOverFlow, I apologize in advance.

I am a bit new to the react world, so my question might sound a little stupid. I also been reading all the redux documentation and many posts about it.
I am trying to build a complex **web** application, (a kind of e-commerce app, where they will be product to sells, user profile, user cart, user product ....).

It's an client/server application, by that I mean that the back-end is completely separated with the front-end. The front-end which I am trying to build with react/redux communicates with the back-end via rest-services.

**Now, my question is what should be stored into the state**? for example : an anonymous user load the web application on his browser (he should see a list of public products), does that mean that all the products should be stored in the state? what if there are a lot of products and I am trying to do a pagination?

A connected user (user with session/cookie) load the web application, should I store all the public products, all his private products, all his profile information and all other related information to the state? 

Let's say I have stored his private information (first name, last name ...) to the state, the user go to edit his profile, the form took the initial data from the state, then when he presses `save`, I should call a ws to save the information in the database and then edit the state? Is that the correct flow? it feels like I do things 2 times.

I just trying to understand the flow of things.

**Comment by markerikson** [comment]
Yeah, this is a usage question, and should be asked elsewhere.

The Redux FAQ has some guidance on this topic: http://redux.js.org/docs/faq/OrganizingState.html#organizing-state-only-redux-state .  The "Structuring Reducers" section also has some relevant info: http://redux.js.org/docs/recipes/reducers/BasicReducerStructure.html#basic-state-shape .
