### ISSUE TITLE
recommend watching: typed redux store

### ISSUE THREAD

**Issue by born2net** [reactjs/redux#2023]
I love redux... but felt it needed typing.
I posted this video:
https://www.youtube.com/watch?v=bEkPEnudm7s&feature=youtu.be
it's the best of both worlds, typed redux

regards

Sean

**Comment by markerikson** [comment]
Probably not something worth opening an issue over, but that is a useful video.  Nice.

FYI, Redux does ship with type definitions for both Flow and Typescript.

**Comment by born2net** [comment]
tx, got it!
regards
