### ISSUE TITLE
The ultimate typed redux...

### ISSUE THREAD

**Issue by born2net** [reactjs/redux#2024]
I posted this video which is what I believe the best way to use redux, with typings.
https://www.youtube.com/watch?v=bEkPEnudm7s&feature=youtu.be

Dan, let me know what you think and if any of it can help in making core add-ons to redux for future built in support with typings... well that would be cool... 
just figured I put it out for thoughts / feedback,

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/ng2Boilerplate
Regards,

Sean

**Comment by markerikson** [comment]
Please don't keep opening issues, especially when they're not actually for bugs.  One is enough.

And as I said in #2023 , Redux does already ship with typings for TypeScript and Flow.

**Comment by born2net** [comment]
ok tx for the feedback!
