### ISSUE TITLE
Always undefined enhancer argument

### ISSUE THREAD

**Issue by owanturist** [reactjs/redux#2028]
`applyMiddleware` Enhancer [takes three](https://github.com/reactjs/redux/blob/master/src/applyMiddleware.js#L20) arguments now.
But `createStore` pass [two arguments](https://github.com/reactjs/redux/blob/master/src/createStore.js#L50) to enhancer.

`applyMiddleware` should take only two arguments.

**Comment by timdorr** [comment]
This is true if you use the more recent `enhancer` argument on `createStore`. For the previous API, this is still correct as-is.
