### ISSUE TITLE
Redux compose "TypeError: undefined is not an object (evaluating 'last.apply')"

### ISSUE THREAD

**Issue by igorrfc** [reactjs/redux#2033]
Hey guys. I'm just building the dependencies in a project made with react/redux. And when webpack bundle the main file, the error: "TypeError: undefined is not an object (evaluating 'last.apply')" has been shown on console log.

```javascript
function compose() {
  for (var _len = arguments.length, funcs = Array(_len), _key = 0; _key < _len; _key++) {
    funcs[_key] = arguments[_key];
  }

  if (funcs.length === 0) {
    return function (arg) {
      return arg;
    };
  }

  if (funcs.length === 1) {
    return funcs[0];
  }

  var last = funcs[funcs.length - 1];
  var rest = funcs.slice(0, -1);
  return function () {
    return rest.reduceRight(function (composed, f) {
      return f(composed);
    }, last.apply(undefined, arguments));
  };
}
```

Is there any solution for this error?

**Comment by markerikson** [comment]
That sounds as if you're passing in something invalid when creating your store.  Please check your store creation code and verify that the call to `compose` has valid enhancers as arguments.

**Comment by JoeCortopassi** [comment]
@igorrfc were you able to figure out steps to reproduce? Wondering if related to this https://github.com/reactjs/redux/pull/2145

**Comment by aniddan** [comment]
In my case caused because of Redux Dev Tools. By passing undefined to compose it generates this error
```JavaScript
createStore(
	combineReducers({ auth, missions, artworks, artists }),
	compose(...[
		applyMiddleware(promiseMiddleware),
		__REDUX_DEVTOOLS_EXTENSION__ && __REDUX_DEVTOOLS_EXTENSION__()
	]),
);
```

**Comment by ballerabdude** [comment]
I got this error from safari and I was able to fix it with this.

``` 
// Only chrome can handle the redux dev tool
// redux compose cannot handle a null or undefined middleware
if (window.navigator.userAgent.includes('Chrome')) {
  var store = createStore(
    reducer,
    initialState,
    compose(
      applyMiddleware(
        routerMiddleware(browserHistory)
      ),
      window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
    )
  );
} else {
  var store = createStore(
    reducer,
    initialState,
    compose(
      applyMiddleware(
        routerMiddleware(browserHistory)
      )
    )
  );
}
```

**Comment by Barlog-M** [comment]
const middleware = applyMiddleware(
	routerMiddleware(browserHistory),
	thunkMiddleware,
	// logger,
	authStateMiddleware
);

const composeEnhancers =
	window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;

const store = createStore(
	rootReducer,
	composeEnhancers(middleware)
);

**Comment by notgoodwithpowertools** [comment]
The above solution from @ballerabdude worked but the linter complained about store being created twice and a redundant statement. I was able to get this working to remove the linter warnings ...

```
var getComposeEnhancers = () => {
    if (window.navigator.userAgent.includes('Chrome')) {
      return redux.compose(
        redux.applyMiddleware(thunk)
        ,window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
      );
    }
    return redux.compose(redux.applyMiddleware(thunk) );
  };

  var store = redux.createStore(reducers, initialState, getComposeEnhancers() );
  return store;
```

**Comment by WebbizAdmin** [comment]
Might help someone in the future...

`const createStoreWithMiddleware = createStore(
  rootReducers,
  compose(
    applyMiddleware(thunk, logger),
    window.navigator.userAgent.includes('Chrome') ?
      window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__() : compose,
  ),
);`

**Comment by casvil** [comment]
@WebbizAdmin what does `compose` by itself?

**Comment by WebbizAdmin** [comment]
@casvil Hey, it allows to apply enhancements to the store, like the devtools above. Nice explenations are [Stackoverflow](https://stackoverflow.com/questions/41357897/understanding-compose-functions-in-redux) and [Redux docs](https://redux.js.org/api-reference/compose) .

I actually changed to this package [Redux Dev Tools Extention](https://github.com/zalmoxisus/redux-devtools-extension)

```Javascript
import { composeWithDevTools } from 'redux-devtools-extension/developmentOnly';
....
....
....
const createStoreWithMiddleware = createStore(
  rootReducers,
  composeWithDevTools(applyMiddleware(thunk)),
);
```

**Comment by iMerica** [comment]
@Barlog-M's solution worked for me. Thank you!

**Comment by alonsoJS** [comment]
@barlog-m, this workaround is clean and worked perfect for me, thank you very much
