### ISSUE TITLE
Uncaught Invariant Violation: Minified React error #130;

### ISSUE THREAD

**Issue by chuqing8086** [reactjs/redux#2036]
I build the "Real World" example from http://redux.js.org/docs/introduction/Examples.html. It can "npm start" and work well. But when "npm run build", and I copy the build/index.html and build/static to my Apache server root, it report "Uncaught Invariant Violation: Minified React error #130;" error.

In my host file: 
`127.0.0.1 app.jogooolocal.com`

In httpd-vhosts.conf file 
DocumentRoot "E:/code/app"
 ServerName app.jogooolocal.com AllowEncodedSlashes On Options Indexes FollowSymLinks AllowOverride All Require all granted

My folder structure like this: E:/code/app/index.html E:/code/app/static/js/main.8a6eb2e1.js E:/code/app/static/js/main.8a6eb2e1.js.map

I find the root cause:
Add `export default Root` to the end of file `examples/real-world/src/containers/Root.prod.js`

**Comment by jimbolla** [comment]
It does indeed look like [Root.prod.js](https://github.com/reactjs/redux/blob/master/examples/real-world/src/containers/Root.prod.js) is missing an export, while [Root.dev.js](https://github.com/reactjs/redux/blob/master/examples/real-world/src/containers/Root.dev.js) does have one. Would you like to submit a PR to add this?

**Comment by chuqing8086** [comment]
[PR2038](https://github.com/reactjs/redux/pull/2038)

**Comment by tanduong** [comment]
@chuqing8086 thank you so much. You are saving me headache.

**Comment by wv1124** [comment]
Uncaught Error: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=object&args[]=%20Check%20the%20render%20method%20of%20%60t%60. for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by ivoneijr** [comment]
@chuqing8086 , how did you find a root cause? If it happens only after build and the build output does not show nothing.. ? =/
