### ISSUE TITLE
Feature Request: subscribe functions to state subtree modifications

### ISSUE THREAD

**Issue by danajanezic** [reactjs/redux#2037]
I'm sure this has been requested before but I could not find it in the issues, but I would like to be able to subscribe functions only to a part of the subtree in the state that they care about and have them called when that portion of the subtree is modified.  If that's not doable because of greater architectural concerns, right now in my project I'm using a function that wraps my subscriber that handles this for me, could something like this be added to the project?  I'm willing to contribute the code myself, but I'm not sure how this community functions yet.

**Comment by markerikson** [comment]
Yep, this has been suggested _numerous_ times before.  Please see http://redux.js.org/docs/faq/StoreSetup.html#store-setup-subscriptions for reasoning, links to earlier discussions, and links to addons that support this functionality on top of Redux itself.

**Comment by danajanezic** [comment]
Thank you!
