### ISSUE TITLE
replaceMiddleware feature for use with lazy-loaded modules 

### ISSUE THREAD

**Issue by un33k** [reactjs/redux#2041]
**feature**  

It would be great to have a feature like replaceReducers() to replace the middlewares as well.
This is extremely handy where a lazy loaded module can register its middleware and the main app can add them to the existing middlewares and call replaceMiddlware() to activate them.

**What is the current behavior?**
The createStore() requires the middlewares upfront via applyMiddlware() in order to create the store.  This makes the main app responsible for creating a list of middleware of all modules **upfront**. 

**What is the expected behavior?**
It would be great to have the main app provide a registerMiddleware() function for modules to register their middlewares on load.  The app can register the logger middleware itself, but each app will trigger its own middleware registration when loaded.  In turn each call to registerMiddleware() will trigger a replaceMiddlware().  This way, splitting the code and lazy loading modules (Angular2) will work and load time of the first page will be much faster.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**
macOS Sierra, Node v6.0.0, "redux": "^3.6.0", angular 2.1.0

**Comment by markerikson** [comment]
That's a valid point.  That said, it should actually be possible to implement this feature as a middleware :)

As a semi-related starting point, you might want to look at a sample middleware I wrote for managing timers: https://gist.github.com/markerikson/ca96a82d6fdb29388aca4052a9455431 .  I could easily imagine a middleware that operates on similar principles, but instantiates middleware and manages a dynamic chain of them.

**Comment by un33k** [comment]
@timdorr minimally it would be nice to leave a short message of why this feature request was closed. (not feasible, not doable, no interest, ...etc)

**Comment by timdorr** [comment]
Sorry, I do that a lot :P

As @markerikson stated, this can be handled outside of Redux via a middleware. You could also use a store enhancer. I don't think it needs to be a core thing.

**Comment by un33k** [comment]
@timdorr Thanks for the info. 👍  - With the popularity & modularity of NG2, more and more people may need to do this for themselves and if this mini-feature is part of the core, it would be a nice DRY. Also thx to @markerikson for the info.

**Comment by un33k** [comment]
@markerikson How do you get access to the main middleware list in your example middleware.  How can one manipulate the main middleware list that was created when the store was created afterward?

How to update a list without affecting all in progress async operations?

A working example to shed some light on this would be appreciated as I couldn't find a single middleware that achieves something like this.  Thx

**Comment by markerikson** [comment]
@un33k : To be honest, I haven't seen an actual published middleware or enhnacer that does this yet, I'm just sort of envisioning how one might work.  And yeah, I could foresee potential problems with async behavior, theoretically.

Would love to see someone experiment with creating a working implementation of this! :)
