### ISSUE TITLE
Weird scoll position issue with real world example 

### ISSUE THREAD

**Issue by MarkMurphy** [reactjs/redux#2044]
I noticed in the real-world example that if I scroll down a list of someones repos and then visit a user page and immediately hit the browsers back button, my original scroll position in the repo list is maintained. 

However, when I removed the DevTools, from the Root.dev container, it seems scroll position is no longer maintained.  I'm taken to the top of the list of repos instead of returned to where I was previously scrolled to.

I'm a little confused as to what's going on here. This seems like a bug but I'm not sure if it's to do with redux, react-router or what.

Google Chrome Version 53.0.2785.143 (64-bit)
MacOS Sierra 10.12

**Comment by markerikson** [comment]
Given that Redux is just a state management library, it's _definitely_ nothing to do with Redux itself.  I would assume some combination of the router and browser behavior.

**Comment by GGAlanSmithee** [comment]
Not too familiar with the example, but the scroll position can be lost depending on number of factors such as navigation, data loading/unloading etc.

See if react-router's [scroll behaviour middleware](https://github.com/taion/react-router-scroll) can be of help.

**Comment by MarkMurphy** [comment]
So it looks like react-router used to handle this but then removed it and now says to use the react-router-scroll middleware as @GGAlanSmithee pointed out. 

See https://github.com/ReactTraining/react-router/issues/655#issuecomment-242361002

Thanks for pointing me in the right direction guys.
