### ISSUE TITLE
Can I add troubleshooting advice for server-side rendering issue? (docs)

### ISSUE THREAD

**Issue by savovs** [reactjs/redux#2049]
I recently resolved an error and I thought someone might find this useful but I'm not sure where to share it so I'm posting here.

When doing server-side rendering with thunks, if you're getting this error:
`Error: Actions must be plain objects. Use custom middleware for async actions.`
The problem is probably creating the store in more than one place (for instance client & server). 

My issue was creating the server-side store without middleware... It took me a long time to figure this out for some reason so I thought it might help to post it if someone is having the same problem.

**Comment by markerikson** [comment]
Yeah, might not be a bad addition to the existing "Troubleshooting" docs page.  File a PR and we'll get it worked in.

**Comment by timdorr** [comment]
Yeah, a PR is best for this. Looking forward to it!
