### ISSUE TITLE
UpdatingNormalizedData.md has case without switch

### ISSUE THREAD

**Issue by scisci** [reactjs/redux#2053]
This is just a comment about the docs which I found confusing. It shows reducers that look like this:

```
function allComments(state = [], action) {
    case "ADD_COMMENT" : return addCommentId(state, action);
    default : return state;
}
```

Not sure if that is using some plugin, but I think you need a switch statement to have a case.

**Comment by jimbolla** [comment]
Looks like a mistake. Want to submit a PR?

**Comment by markerikson** [comment]
I totally blame @jimbolla for not peer reviewing hard enough and @timdorr for just blindly merging in those docs.  Clearly the maintainers of this library should have done a better job of keeping out shoddy writing.

:)

**Comment by timdorr** [comment]
Thanks, @markerikson. But yeah, this is better as a PR. Should be simple.

**Comment by markerikson** [comment]
Just went ahead and fixed this one, so it should be taken care of now!
