### ISSUE TITLE
Markup on website is weird

### ISSUE THREAD

**Issue by gaearon** [reactjs/redux#2057]
Not sure if this was changed at some point or Gitbook version update was incompatible but:

<img width="434" alt="screen shot 2016-10-27 at 17 14 19" src="https://cloud.githubusercontent.com/assets/810438/19775596/d97a9218-9c68-11e6-823e-9ed4b1d0a820.png">

**Comment by timdorr** [comment]
Multi-line bolds must not be supported. That's not valid Markdown anyways. I just fixed it so it will pick up on the next build.
