### ISSUE TITLE
combineReducers is not composable

### ISSUE THREAD

**Issue by sheerun** [reactjs/redux#2058]
**Do you want to request a *feature* or report a *bug*?**  
bug

**What is the current behavior?**

I'm unable to combine reducer created with `combineReducers` with other reducer that adds new keys in the namespace that `combineReducers` (not properly) thinks it fully controls.

Here's how to reproduce this behavior. I try to enhance reducer created with `combineReducers` with `enhancingReducer`, that controls the "form" field of original reducer. This is particular use case comes from me wanting to write custom logic for reduxForm without using plugins.

```js
var redux = require('redux');
var reduceReducers = require('reduce-reducers');

var formReducer = redux.combineReducers({
  form: function (state, action) {
    if (state === undefined) {
      return 0;
    }

    return state;
  }
})

var enhancingReducer = redux.combineReducers({
  form: function (state, action) {
    if (state === undefined) {
      return 0;
    }

    if (action.type === 'UP') {
      return state + 1;
    }

    return state;
  },
  two: function (state, action) {
    if (state === undefined) {
      return 2;
    }

    return state;
  }
})

var finalReducer = reduceReducers(formReducer, enhancingReducer)

const store = redux.createStore(finalReducer);

console.log(store.getState());
console.log(store.dispatch({ type: 'UP' }));
console.log(store.dispatch({ type: 'UP' }));
console.log(store.getState());
```

The output is as follows:

```
{ form: 0, two: 2 }
Unexpected key "two" found in previous state received by the reducer. Expected to find one of the known reducer keys instead: "form". Unexpected keys will be ignored.
{ type: 'UP' }
{ type: 'UP' }
{ form: 2, two: 2 }
```

**What is the expected behavior?**

`combineReducers` shouldn't assume it completely controls the `state`, and do not throw a warning when extra fields are found.

**Comment by sheerun** [comment]
By the way, this is true even if `enhancingReducer` doesn't touch `form` field.

**Comment by markerikson** [comment]
A couple thoughts:

First, that warning is only given in development, in case you accidentally mismatched state shape and reducer setup.

Second, `combineReducers` is deliberately opinionated in how it behaves, and intended for very specific use cases.  Once you get past those use cases, it's often time to look at writing your own custom reducer logic.  I'd encourage you to read the new [Structuring Reducers](http://redux.js.org/docs/recipes/StructuringReducers.html) section in the docs for more on this topic.

Ultimately, this is really working as intended.

**Comment by sheerun** [comment]
@markerikson Not only combineReducers warns on extra keys, but also removes them from state...

**Comment by danielrob** [comment]
I personally solved this with: 
```
const createReducer = ({ special: specialStateReducer = noop, ...otherAsyncReducers } = {}) =>
  ({ special: specialState, ...otherState } = {}, action) => ({

    /* standard reducers */
    ...combineReducers({
      routing,
      global,
      language,
      form: reduxFormReducer.plugin({
        someForm: (state, action) => state,
      }),
      ...otherAsyncReducers,
    })(otherState, action),

    /* state-sharing slice reducers */
    special: specialStateReducer(
      specialState,
      action,
      otherState.form && otherState.form.someForm
    ),
  })
```

**Comment by bleurubin** [comment]
I'd suggest that this recipe be modified or removed from the docs than, as it doesn't take this into account: https://github.com/reactjs/redux/blob/master/docs/recipes/reducers/UsingCombineReducers.md
