### ISSUE TITLE
Components with property named store, conflicts with _this.store.getState

### ISSUE THREAD

**Issue by krismeister** [reactjs/redux#2061]
**Do you want to request a *feature* or report a *bug*?**  

This is a bug. I spent a long time debugging my issue :-(

**What is the current behavior?**

I am using ES2015 syntax in my project.
```
render(){
    // the store attribute below causes the issue.
    return <MyStoreButton store={{phone:1234,address:'123 south street'}} />
}
```

MyStoreButton is using connect to subscribe to a redux store.

Here is the stack trace:
```

loadOnServer Error:  TypeError: _this.store.getState is not a function
  
  - connect.js:133 new Connect
    [TheFreshMarket]/[react-redux]/lib/components/connect.js:133:38
  
  - ReactCompositeComponent.js:294 
    [TheFreshMarket]/[react]/lib/ReactCompositeComponent.js:294:18
  
  - ReactCompositeComponent.js:74 measureLifeCyclePerf
    [TheFreshMarket]/[react]/lib/ReactCompositeComponent.js:74:12
  
  - ReactCompositeComponent.js:293 null.ReactCompositeComponentMixin._constructComponentWithoutOwner
    [TheFreshMarket]/[react]/lib/ReactCompositeComponent.js:293:16
  
  - ReactCompositeComponent.js:279 null.ReactCompositeComponentMixin._constructComponent
    [TheFreshMarket]/[react]/lib/ReactCompositeComponent.js:279:21
  
  - ReactCompositeComponent.js:187 null.ReactCompositeComponentMixin.mountComponent
    [TheFreshMarket]/[react]/lib/ReactCompositeComponent.js:187:21
  
  - ReactReconciler.js:47 Object.ReactReconciler.mountComponent
    [TheFreshMarket]/[react]/lib/ReactReconciler.js:47:35
  
  - ReactMultiChild.js:240 ReactDOMComponent.ReactMultiChild.Mixin.mountChildren
    [TheFreshMarket]/[react]/lib/ReactMultiChild.js:240:44
  
  - ReactDOMComponent.js:661 ReactDOMComponent.Mixin._createContentMarkup
    [TheFreshMarket]/[react]/lib/ReactDOMComponent.js:661:32
  
  - ReactDOMComponent.js:528 ReactDOMComponent.Mixin.mountComponent
    [TheFreshMarket]/[react]/lib/ReactDOMComponent.js:528:29
```
  

**What is the expected behavior?**

The expected behavior is to support component properties named `store` or clear documentation it is not support. I don't see reserved words in the docs.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

Redux on the server, and browser.

Redux version `3.6.0`

**Comment by markerikson** [comment]
Hmm.  First, this is really a question about the React-Redux library, not the core Redux library.

Second, while it's admittedly not widely mentioned or used, the React-Redux docs do mention this at https://github.com/reactjs/react-redux/blob/master/docs/api.md#provider-store : 

> If you really need to, you can manually pass store as a prop to every connect()ed component, but we only recommend to do this for stubbing store in unit tests, or in non-fully-React codebases.

The relevant line in `connect` is:

```js
this.store = props.store || context.store
```

Third, this really only comes into play when you are explicitly passing a prop named `store` directly to a connected wrapper component generated by `connect`.

So, on the whole, this _is_ documented, although maybe not as obvious as it could be, and definitely not a bug.  If you'd like to submit a PR to React-Redux to clarify this in the docs, that would be great!
