### ISSUE TITLE
middlewareAPI dispatch

### ISSUE THREAD

**Issue by derjoker** [reactjs/redux#2068]
https://github.com/reactjs/redux/blob/master/src/applyMiddleware.js#L27

hi, I don't understand here, what's the difference between function `(action) => dispatch(action)` and function `dispatch`. They both accept `action` and return whatever comes from `dispatch`, right? Can we just write as following? Thanks.
```
var middlewareAPI = {
  getState: store.getState,
  dispatch: dispatch
}
```

**Comment by timdorr** [comment]
It's to establish a closure so that when [`dispatch` gets swapped out later on](https://github.com/reactjs/redux/blob/master/src/applyMiddleware.js#L30), you're referencing the right function.
