### ISSUE TITLE
Call store listeners with action in params

### ISSUE THREAD

**Issue by PredokMiF** [reactjs/redux#2081]
I can subscribe of store change and track its state.

`store.subscribe(()=>{/*State changed... or not*/})`

But the handler is called always, regardless of that, the stor changed or not. 
Call handler signals that on reducer some action walked. So why not to call handler with this action in param? #2082 

Actually I write small library which has to monitor changes of a stor, and dont wont breaking logging. It is possible only if I will get action in to store change handler.

**Comment by jimbolla** [comment]
Issue #1971 explains why this isn't part of the API.

**Comment by markerikson** [comment]
FAQ, FAQ, FAQ.... :)  

Y'know, if someone wants to tackle adding that to the FAQ, that'd be great.  My attentions on my blog post series for the foreseeable future.  My FAQ notes are in #1785 .
