### ISSUE TITLE
Wire up action results with the redux flow

### ISSUE THREAD

**Issue by pronebird** [reactjs/redux#2092]
Hi,

I am currently trying to wrap my head around a very simple use case when I need to run action and get ID of newly created item to dispatch next action to update UI.

This is pretty much covered at http://redux.js.org/docs/basics/ExampleTodoList.html. However, in the example the ID of next record is predicted, which is not the case with many real world applications.

So roughly, I have two separate reducers.

First is used for backend store and accepts actions such as `add_model`. So I give it payload and assume I use mysql backend so I will know the ID of newly added item after I execute query.

Then second store is used for UI, which dispatches actions using redux-thunk. Therefore I can dispatch two actions at once:

```js
function addItem(payload) {
  return () => {
    dispatch({ type: ADD_MODEL, payload });
    const id = ... // how do you get id?
    dispatch({ type: SELECT_ITEM_IN_UI, id });
  };
}
```

Many examples of redux-thunk or any other middleware assume that one action produces the other, however if I want to keep the clear separation between the parts of business logic and UI, then it's pretty much impossible with current redux infrastructure.

Actions and reducers are so much decoupled from each other that there is pretty much no way to know what reducer specifically did. But sometimes reducers do meaningful things we want to tell others about.

It feels like there should be something to bridge this gap or I am missing something.

What I am trying to achieve is I guess is the following compound action:

```js
function addItem(payload) {
  return () => {
   // dispatch action in StoreReducer
   // state.orm.items = [ { newItem } ];
    dispatch({ type: ADD_MODEL, payload })
      .then((newId, dispatch) => {
         // dispatch action for UI reducer
        // state.ui.selectedItem = ...
         dispatch({ type: SELECT_ITEM_IN_UI, id });
      });
   });
}
```

**Comment by markerikson** [comment]
Part of the question here is "Where is the ID coming from?".  If the ID values are already in the data, that's fine.  On the other hand, reducers should almost never generate new IDs, because that's usually non-deterministic.  

Since dispatches are synchronous, you can retrieve the updated state after the dispatch is done.  That means you can use Redux-ORM to look up the latest item of a given type, like this:

```js
function addItem(payload) {
    return (dispatch, getState) => {
        dispatch({type : ADD_MODEL, payload});
        const updatedState = getState();
        const session = schema.from(updatedState);
        const {MyModelType} = session;
        const newestItem = MyModelType.all().last();
        const itemId = newestItem.getId();
        dispatch({type : SELECT_ITEM_IN_UI, id : itemId});
    }
}
```

You could also extract the ID from the incoming data before dispatching the action.

The Redux FAQ has some thoughts on splitting logic between reducers and action creators: http://redux.js.org/docs/faq/CodeStructure.html#structure-business-logic .

**Comment by pronebird** [comment]
My reducer simply calls `let newItem = Item.create({ title: 'New item' });`. I can access the id of the record immediately, but there is no way to funnel it back. 

I want to avoid UI actions from knowing much about underlying ORM store, so I thought that returning the ID back (somehow) would be much better than polluting UI actions.

I could probably achieve that with custom middleware and instead of returning new state I could return a tuple (Item.getNextState(), function callAfterStateComposed(dispatch, newId) { ... } );

**Comment by markerikson** [comment]
I have to say that middleware idea looks rather circuitous, and I really don't see a point to it.

I'm also not sure I see a reason to put arbitrary limits on what that thunk can do.  It has access to the store, you know that after the action is dispatched that the item should be added, so you should be able to look up its details.

**Comment by pronebird** [comment]
Right, I guess my motivation is to keep interactions between different actions as tiny as possible. But then again I can move that to ORM selector and simply feed it with session.

**Comment by pronebird** [comment]
I believe I figured out a better way to handle business logic and would rather leave redux exclusively for the purpose of wiring up data to redux.

**Comment by dlefuen** [comment]
Update to the FAQ linked in the initial response above: https://redux.js.org/faq/code-structure#how-should-i-split-my-logic-between-reducers-and-action-creators-where-should-my-business-logic-go
