### ISSUE TITLE
Localize Redux docs with Locki

### ISSUE THREAD

**Issue by chikathreesix** [reactjs/redux#2093]
Hi, I am Ryo, a creator of Locki.
Thanks @gaearon for allowing me to open this issue.

Locki(https://locki.io) is a website localization tool that enables your localization community to easily translate your docs on your website. Check out [this video](https://youtu.be/c21-ac_26sk) to learn more about how it works.

Now Node.js is also considering using Locki(nodejs/node#8798) and [here is the test integration](https://locki-nodejs-test.herokuapp.com/api/) so try this out.

Feel free to ask me any questions!
We'd be happy if we can help Redux's localization challenges.

**Comment by timdorr** [comment]
I know there was a similar effort with Crowdin as well. We use GitBook for our docs, so it really just has to integrate well with that system. Unless there's any specific action we can take, I don't think there's anything here we need to track.
