### ISSUE TITLE
Note on String Interpolation Syntax

### ISSUE THREAD

**Issue by brigand** [reactjs/redux#2095]
["Note on String Interpolation Syntax"][interp] warns about usage of es6 template literals, which work in node now, but says nothing about the usage of import statements and jsx. I don't know what the right wording for this is.

[interp]: http://redux.js.org/docs/recipes/ServerRendering.html#note-on-string-interpolation-syntax

**Comment by timdorr** [comment]
We can get rid of this nowadays. A PR is probably best, but I'll just go nuke it now.
