### ISSUE TITLE
Question about middlewareAPI

### ISSUE THREAD

**Issue by davidjuin0519** [reactjs/redux#2097]
In `applyMiddleware.js`:
```javascript
export default function applyMiddleware(...middlewares) {
  return (createStore) => (reducer, preloadedState, enhancer) => {
    var store = createStore(reducer, preloadedState, enhancer)
    var dispatch = store.dispatch
    var chain = []

    var middlewareAPI = {
      getState: store.getState,
      dispatch: (action) => dispatch(action)
    }
    chain = middlewares.map(middleware => middleware(middlewareAPI))
    dispatch = compose(...chain)(store.dispatch)

    return {
      ...store,
      dispatch
    }
  }
}
```

I think we can simply pass `dispatch` instead of wrapping it in a lambda:
```javascript
export default function applyMiddleware(...middlewares) {
  return (createStore) => (reducer, preloadedState, enhancer) => {
    var store = createStore(reducer, preloadedState, enhancer)
    var dispatch = store.dispatch
    var chain = []

    var middlewareAPI = {
      getState: store.getState,
      dispatch
    }
    chain = middlewares.map(middleware => middleware(middlewareAPI))
    dispatch = compose(...chain)(store.dispatch)

    return {
      ...store,
      dispatch
    }
  }
}
```
The code above passes all the tests except for this one: 
```
applyMiddleware › passes recursive dispatches through the middleware chain
expect(received).toEqual(expected)
Expected value to equal:
  2
Received:
  1
```

So here's my question: Is there any specific concern about the original version of `middlewareAPI`? Or is it okay to improve it?

**Comment by jimbolla** [comment]
Here's the commit where that was added: https://github.com/reactjs/redux/commit/af474ba34cb3aae31c418228561f6e23a4b66bb2. Unsure why.

**Comment by davidjuin0519** [comment]
@jimbolla 
Thanks for your reply. This is not really causing any problem but just making me wonder is there any insight behind the current implementation.

**Comment by sunkai612** [comment]
@davidjuin0519 
Not sure if "[to only compose dispatch method once](https://github.com/reactjs/redux/commit/b4766b3dd1a61d969f19fd1f6ba6a1957a0f2f35)" is the reason for that lambda.

**Comment by markerikson** [comment]
This has been asked in previous issues.  I don't have a link to the specific official answer at the moment, but I believe it's to set up a closure referring to the original dispatch function.

**Comment by davidjuin0519** [comment]
@markerikson 
Thanks for your reply. I think I found the discussion #1592 which reveals that the purpose of making a thunk is to do lazy evaluation on `dispatch`. 😀
