### ISSUE TITLE
Arrow navigation elements on Redux docs pages are highly annoying

### ISSUE THREAD

**Issue by Merri** [reactjs/redux#2104]
At http://redux.js.org/ the `.navigation` elements on the sides of each document page make it very annoying to use the docs on desktop.

1. It is too easy to click these elements accidentally when making browser window active or when removing selection from text, because they take the entire height of the viewport.
2. There is no clear visual indication on hover of the existance of these buttons.
3. They appear to break the back button partially, because going back to previous page does not restore the scroll position; instead I find myself on top of the page again, losing the context I was in.

This issue has now happened to me five times today within an hour. I don't see any benefit of having these buttons on desktop, they seem like a nice mobile feature, but when using Redux docs you're much more likely to be a non-mobile user.

Also posted at [GitBook's issues](https://github.com/GitbookIO/gitbook/issues/1596) but based on quick read they seem to be lazy in addressing usability issues.

**Comment by timdorr** [comment]
We use the default template for GitBook. This is an issue with that template, so I'm closing this out here.

BTW, this is the best place to post an issue: https://github.com/GitbookIO/theme-default
