### ISSUE TITLE
[Bug] lodash-es dependency adds 94kB unminified to my bundle size through redux

### ISSUE THREAD

**Issue by vjancik** [reactjs/redux#2109]
I am using latest **Webpack 2** version, and bundling a react redux app with it.

Using the https://www.npmjs.com/package/webpack-bundle-analyzer, I discovered `lodash-es` is being bundled, seemingly in it's entirety through redux, in my bundle.

Used `npm list | grep -B 50 lodash-es` to investigate the dependency tree.

Something similar was discussed here: 
 https://github.com/reactjs/redux/issues/1544

and since you commented @gaearon that this doesn't happen in webpack, I think this may be some kind of a regression? Maybe with the upgrade to webpack 2?

**Redux version 3.6.0**
**Webpack version 2.1.0-beta.27**

**Comment by gaearon** [comment]
Since this doesn't happen with Webpack 1, could you file an issue against Webpack 2?

**Comment by timdorr** [comment]
Something to watch out for if/when we switch to Webpack 2. For now, this isn't a bug with Redux itself.

**Comment by vjancik** [comment]
It may be an issue with the way I do vendor / app code bundle splitting. I'll find out in upcoming days and let you know.

**Comment by vjancik** [comment]
I found this long time outstanding issue with webpack which explains the problem.
https://github.com/webpack/webpack/issues/1750

I am not sure what the best way to act on this is ...
