### ISSUE TITLE
Different way to organize reducers, is it right?

### ISSUE THREAD

**Issue by vadimkaD** [reactjs/redux#2117]
const mapActionToReducer = {
        [actions.SET_USERNAME]: (state, action) => {
            console.log('set username action passed to reducer:', action);
            return Object.assign({}, state, {user: Object.assign({}, state.user, {name: action.value})});
        }
    }

    const rootReducer = (state = initialState, action) => {
        if (action.type in mapActionToReducer) {
             return mapActionToReducer[action.type](state, action);
        } else {
            return state;
        }
    };

    export default rootReducer;

My question is: how valid is it? Thank you.

**Comment by vaclavbohac** [comment]
Except for using `hasOwnProperty` instead of `in` operator, redux docs leads you basically to the same structure: http://redux.js.org/docs/recipes/ReducingBoilerplate.html#generating-reducers

**Comment by markerikson** [comment]
Yep, lookup tables are a very common approach.
