### ISSUE TITLE
Best Practice: React / Redux App Deployment

### ISSUE THREAD

**Issue by Jarch09** [reactjs/redux#2119]
Apologies for the beginner question.

What do people typically do for deployment of react / redux app? Do you have one set of servers providing the frontend bundle(s), and another set providing the API then queried by the frontend?

Would appreciate some tips regarding best practices. Thank you

**Comment by vaclavbohac** [comment]
I'd say there's no such a thing as a best practice for react/redux app.

It's more likely the matter of scale. For the most apps single server is perfectly ok. For bigger apps, you'll probably have multiple servers (caches, proxies, balancers and so on).

From react/redux point of view the only thing you basically do is to build your app for the prod. environment (dead code elimination, tree shaking, splitting to bundles, minification).

Sorry for the vague answer
