### ISSUE TITLE
IDEA - Describe reducers as maps

### ISSUE THREAD

**Issue by astrauka** [reactjs/redux#2127]
# Describe reducers as maps

## Problem

Hey guys, I was thinking about how to make redux more performant.
Currently on action dispatched we iterate all registered reducers
evaluating `case` statements till we match one or in worst case return the `default` block, e.g. for reducer

```javascript
function counter(state = 0, action) {
  switch (action.type) {
  case 'INCREMENT':
    return state + 1
  case 'DECREMENT':
    return state - 1
  default:
    return state
  }
}
```

dispatching `FILTER_ACTIVE` action the code will perform two `case`
checks and return the same state evaluating `default` block. 
Sounds like 3 operations.

Let's say that `handlers(reducer)` is count of `reducer` handlers - `if` or `case` statements.
On each dispatch we are performing

```javascript
reducers.reduce((sum, reducer) => sum + handlers(reducer), 0)
```
operations. This does not sound scalable.

## Proposal

What if we organized reducer actions as maps of type => handler:

```javascript
const defaultState = 0;
const counter = new Map([
  ['INCREMENT', (state = defaultState, action) => state + 1],
  ['DECREMENT', (state = defaultState, action) => state - 1],
])
```

On app start redux could form a global map of type => handlers:

```javascript
typeHandlers = new Map([
  ['INCREMENT', [counter['INCREMENT']]],
  ['DECREMENT', [counter['DECREMENT']]],
])
```

On action dispatched it would only call the involved handlers.

```javascript
handle(action, prev_state) =>
  typeHandlers.get(action.type).reduce(
    (handler, next_state) => handler(next_state, action),
    prev_state
  )
```

This code illustrates the idea, it does not handle corner cases.

### How do we match all the actions?

Reducer types could be described as strings or as functions.
We invoke handler once the function evaluates to `true`:

```javascript
const logger = new Map([
  [(action => true), console.log(action)],
])
```

For functions there is no optimization, 
we need to evaluate them all for each dispatch.
But it is not that bad as we rarely use functions to match actions.

@gaearon what do you think about it? Does it sound valid?

**Comment by markerikson** [comment]
Three thoughts:

- This is already one of the most common ways to define reducers in Redux besides switch statements, and in fact, the Redux docs already give an example of a `createReducer` utility function that does this: http://redux.js.org/docs/recipes/ReducingBoilerplate.html#generating-reducers
- Switch statements are generally a highly performant pattern. Compilers usually generate very optimized code for switch statements.
- The Redux FAQ discusses overall performance concerns, and points out that calling a few functions is _not_ going to be a bottleneck: http://redux.js.org/docs/faq/Performance.html#performance-all-reducers
