### ISSUE TITLE
an unnecessary argument in applyMiddleware.js

### ISSUE THREAD

**Issue by HQidea** [reactjs/redux#2131]
Since there is no `enhancer` argument passed to an enhancer, so this argument can be omitted.

see: https://github.com/reactjs/redux/blob/master/src/applyMiddleware.js#L20

If this is ok, I'll send a pr later.

**Comment by jimbolla** [comment]
Duplicate: https://github.com/reactjs/redux/pull/2128#issuecomment-263581319
