### ISSUE TITLE
XSS in documentation

### ISSUE THREAD

**Issue by polkovnikov-ph** [reactjs/redux#2148]
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

["Because we have introduced more code that relies on user generated content (UGC) and input, we have increased our attack surface area for our application."](http://redux.js.org/docs/recipes/ServerRendering.html)

```
<script>
    window.__PRELOADED_STATE__ = ${JSON.stringify(preloadedState)}
</script>
```

Suppose
```
preloadedState = {deepInState: {someUserInput: "</script><script>alert(1);</script>"}};
```

**What is the current behavior?**

XSS.

**What is the expected behavior?**

No XSS.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

Documentation issue. [684 github code search results](https://github.com/search?q=window.__PRELOADED_STATE__&type=Code&utf8=%E2%9C%93), mostly with same bug.

**Comment by polkovnikov-ph** [comment]
Already [fixed](https://github.com/reactjs/redux/commit/e2bdf4ad730b3cdd4fcdd36c6f5d578e7ff761a6) in master 20 days ago. Why it is not online?

**Comment by markerikson** [comment]
The docs aren't automatically republished on commits - it's a manual process.  @timdorr 's been the one republishing docs lately.  (I did do it once or twice, but haven't tried in a while, and the current publish script makes a couple assumptions about running on Linux while I'm on Windows, so it took some effort to make it happen.)

**Comment by polkovnikov-ph** [comment]
@timdorr, could you publish new docs, please?

@markerikson With all my respect, such situations make me suspicious if I will be informed when some serious security issues will be found that do affect my code. Luckily I'm a big fan of OWASP, but there're thousands of other users that have a huge security issue, they're not informed, and their numbers are counting. I would not only fix docs the day the issue was found, but draw some users' attention. Could you ask if, for example, Dan can talk on this in his twitter?

**Comment by timdorr** [comment]
It's been published. Sorry about that!
