### ISSUE TITLE
Using deprecated filter in todo-with-undo example

### ISSUE THREAD

**Issue by kevinmccartney** [reactjs/redux#2152]
Hey guys, I was reading the [undo-with-redo example](https://github.com/reactjs/redux/tree/master/examples/todos-with-undo) & in the todos reducer, there's a deprecated filter being used on line 42.

```
/** 
 * ./src/reducers/todos.js
 */

// this is what the statement is right now, starting at line 41
const undoableTodos = undoable(todos, {
  filter: distinctState()
})

// this is the statement with the deprecated filter removed
const undoableTodos = undoable(todos)
```

The `distinctState()` filter has been deprecated [according to the redux-undo docs](https://github.com/omnidan/redux-undo#filtering-actions), as it's behavior has become default. 

I would be more happy to do a quick pull request! 😄

**Comment by timdorr** [comment]
A PR would be great!
