### ISSUE TITLE
Problems with TypeScript definitions

### ISSUE THREAD

**Issue by johnfn** [reactjs/redux#2154]
I installed Redux like so: `npm install redux --save`

Then I attempted to install the Redux type definitions: `npm install @types/redux`

However, I got the following error:

```
npm WARN deprecated @types/redux@3.6.0: This is a stub types definition for Redux (https://github.com/reactjs/redux). Redux provides its own type definitions, so you don't need @types/redux installed!
```

This error makes no sense to me. Sure, Redux has type definitions in its repo, but TypeScript and my IDE aren't intelligent enough to dig through my node modules in order to find them. The error seems to imply that the typings should have been correctly installed somehow already, but I can't discover any way in which that could have happened.

(My guess is that this error is a holdover from the days of DefinitelyTyped?)

Eventually I got it to work simply by copying index.d.ts into node_modules/@types/redux/, which is goofy. 

What does the error mean? Can we clarify it? Or better, can we have Redux install its typings via `npm install @types/blah` like a standard definitions file?

**Comment by aikoven** [comment]
Definitions are bundled with npm package, so you don't have to install them separately. That means that after
```
npm install --save redux
```
you can just import and use it in TypeScript:
```ts
import {createStore} from "redux";
```

**Comment by aikoven** [comment]
Btw, what IDE are you using? You can also try adding `"moduleResolution": "node"` to your `tsconfig.json`:
```json
{
  "compilerOptions": {
    "moduleResolution": "node",    
    /* other options */
  }
}
```

**Comment by johnfn** [comment]
Aha. `    "moduleResolution": "node",    ` is what I needed.

I'm using Visual Studio Code.
