### ISSUE TITLE
[docs] night mode css bug

### ISSUE THREAD

**Issue by Andarist** [reactjs/redux#2156]
<img width="326" alt="screen shot 2016-12-16 at 13 33 49" src="https://cloud.githubusercontent.com/assets/9800850/21262948/61a8ca68-c394-11e6-86ad-d734109b2057.png">

Thats caused because of wrongful aplication of `prism.css`, I've check on their site and `prism-dark.css` does not have this problem, however the docs suffer from this issue.

That may be gitbook issue (or may be fixed in some newer version), but Im not sure as unfortunately my v8 goes crazy when I try to run `gitbook-cli`.

**Comment by timdorr** [comment]
I have to do a rebuild soon anyways. I'll check out the CSS when I get to that.

**Comment by markerikson** [comment]
Yeah, we've had a number of docs edits merged that are waiting for a republish.

Y'know, we're programmers.  What we _really_ ought to do is automate republishing the docs after any edits...
