### ISSUE TITLE
A puzzled

### ISSUE THREAD

**Issue by XueSeason** [reactjs/redux#2157]
When learning the Redux source code, I was confused by variable `currentListeners` and `nextListeners` in createStore function. 

I think nextListeners variable is unnecessary, beacause currentListeners will always equal to nextListeners when dispatch the action. In addition, only nextListeners shallow copy could happenned in subscribe function.

Could you please tell me why set two arrray here.thx.

**Comment by markerikson** [comment]
Looks like the code was added in commit c031c0a8d900e0e95a4915ecc0f96c6fe2d6e92b .  Per Dan's commit message:

> Delay copying listeners until is necessary
> We can avoid excessive slice() calls by only copying the listeners if they are modified during dispatch()
