### ISSUE TITLE
The 'next' branch is very out of date and errors on install/build.

### ISSUE THREAD

**Issue by jimbolla** [reactjs/redux#2158]
Master branch installs/builds fine on my machine, but if I switch to the `next` branch, I get errors during install/build:

[npm-debug.log.txt](https://github.com/reactjs/redux/files/664617/npm-debug.log.txt)
```
> npm run build:commonjs && npm run build:es && npm run build:umd && npm run build:umd:min && node ./build/es3ify

module.js:472
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:17:20
    at Object.<anonymous> (E:\Projects\github\redux\node_modules\npm\node_modules\npm-registry-client\node_modules\graceful-fs\fs.js:11:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

It looks like changes in `master` haven't been merged into `next` in many months.

**Comment by jimbolla** [comment]
I can submit a PR for this. But is it better to merge `master` into `next` or rebase `next` onto latest `master`?

**Comment by gaearon** [comment]
If you want to start moving `next` forward I’d be happy to chat about what might be good to get in there! It’s stale because nobody was actively interested, and there wasn’t enough motivation from anyone to make it happen.

Either rebasing or merging is fine by me. What’s more important is that there’s someone to do it. :-)

**Comment by jimbolla** [comment]
I'm certainly willing to help. I started looking at https://github.com/reactjs/redux/issues/1342 to get an idea of the plan.

**Comment by timdorr** [comment]
The biggest thing to do is figure out subscription semantics. There was some effort on this in #1729, but it died out. If we can get that right, that's a big piece of the puzzle to 4.0. 

But yeah, let's keep the 4.0 discussion in #1342.
