### ISSUE TITLE
DOCS -- more specifics

### ISSUE THREAD

**Issue by jordyvandomselaar** [reactjs/redux#2163]
[The source code of the example to do list](http://redux.js.org/docs/basics/ExampleTodoList.html) doesn't match[ the source code in the basics tutorial](http://redux.js.org/docs/basics/Actions.html). Which can be confusing

**Comment by markerikson** [comment]
Yeah, we've had a few comments that some of the sample code in the docs don't match up with the projects in the `examples` folder.  Trying to fix that up isn't on my priority list at the moment, but if you'd like to submit a pull request to improve the docs, the examples, or both, that would definitely be appreciated!

**Comment by jordyvandomselaar** [comment]
Thanks for the reply! I'll see what I can do 😄
