### ISSUE TITLE
Update variable assignment to ES6 usage

### ISSUE THREAD

**Issue by dfrownfelter** [reactjs/redux#2168]
Currently redux uses pre-ES6 variable assignment, as shown [here](https://github.com/reactjs/redux/blob/master/src/applyMiddleware.js#L21). Per @gaearon it was [due to flow failing on let/const a long time ago](https://twitter.com/dan_abramov/status/811368841964097536). The issue is no longer relevant now.

Will be working on a PR to update all variables today. It also seemed that there is interest in adding in semicolons. I could do that as well, any thoughts?

**Comment by markerikson** [comment]
Hi, thanks for following up on this.

I'm okay with a change from var to let/const, as it's reasonable for consistency given that we're using ES6 throughout the codebase.  That said, although my own personal preference is to use semicolons, I'm also _not_ keen on touching entire codebases just to update styles.  Tends to make `git blame` rather useless.  So, at this time I'd prefer to not introduce semicolons just for the sake of having semicolons.

**Comment by dfrownfelter** [comment]
Okay thanks for letting me know. I'll skip the semicolons as of now.
