### ISSUE TITLE
Examples for replaceReducer and document how to use Redux in a code-split app

### ISSUE THREAD

**Issue by neeharv** [reactjs/redux#2170]
I haven't been able to find any meaningful examples or documentation on how to add reducers progressively in an app with code-splitting. I understand this is the job of http://redux.js.org/docs/api/Store.html#replaceReducer - it would help to have official examples + better documentation (maybe an "advanced" recipe) to show how to use redux with progressive enhancement.

Would be happy to work on it since I'm doing that for the day job anyway!

**Comment by jamesmbowler** [comment]
Check out https://github.com/mxstbr/react-boilerplate , I believe it does that.

**Comment by markerikson** [comment]
Yep.  It generally comes down to calling `combineReducers` again with the new bunch of slice reducers, and then calling `store.replaceReducer()` with that result.

@neeharv , if you wanted to add a recipe that discusses code splitting and hot reloading, that would be great!  I do have an example of using the "plain" HMR API to hot reload reducers at http://blog.isquaredsoftware.com/2016/11/practical-redux-part-3-project-planning-and-setup/ , and a few more under https://github.com/markerikson/react-redux-links/blob/master/webpack-advanced-techniques.md#hot-module-replacement .
