### ISSUE TITLE
Dispatch causes stop in code

### ISSUE THREAD

**Issue by sam-n-johnston** [reactjs/redux#2173]
**Do you want to request a *feature* or report a *bug*?**  
*bug*

**What is the current behavior?**

I dispatch a specific action and the rest of the function stops executing

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

I call my postResult function. The problem occurs during the second dispatch: "second dispatched OK" never gets printed to the console. If I replace the second dispatch with another type, rest of the function is executed correctly. 
 
```
let postResult = (tennisResultSet) => {
  return (dispatch, getState) => {
    return fetchWrapper('/api/results', 'POST', tennisResultSet.toJSObj())
      .then((response) => {
        let responseResultSet = makeResultFromResultSet(response).toJSObj()
        dispatch({
          payload: responseResultSet,
          type: actionTypes.ADD_NEW_USERS_RESULT_TO_REDUX_STORE,
        })
        console.log('first dispatched OK')
        dispatch({
          payload: responseResultSet,
          type: actionTypes.ADD_SINGLE_RESULT_TO_REDUX_STORE,
        })
        console.log('second dispatched OK')
        Actions.popTo('root')
        Actions.Feed()
        dispatch(userActions.fetchAllOpponents(getState().currentUser.toJS()._id))
      })
  }
}
```

Here is the reducer:
```
export default (state = initialState, action = {}) => {
  switch (action.type) {
    case actionTypes.ADD_RESULTS_IN_REDUX_STORE:
      return Immutable.fromJS(action.payload).concat(state)
    case actionTypes.ADD_SINGLE_RESULT_TO_REDUX_STORE:
      return Immutable.fromJS([action.payload]).concat(state)
    default:
      return state
```

If I replace this part of the reducer, it starts working again:
```
    case actionTypes.ADD_SINGLE_RESULT_TO_REDUX_STORE:
      return state
OR
    case actionTypes.ADD_SINGLE_RESULT_TO_REDUX_STORE:
      return Immutable.List() // Empty list
```

Even when I try to dispatch this is does not work, the rest of the function is not executed
```
    case actionTypes.ADD_SINGLE_RESULT_TO_REDUX_STORE:
      return { _id: 'test' } 
```

**What is the expected behavior?**

I expect the reducer to change the state and concatenate it with the new result. I have never had a problem similar to this in redux. I have tried to debug, but to no avail. The unit tests of these functions work perfectly (When I import the reducer and do tests directly on it). So I think there might be a problem elsewhere? The type `ADD_RESULTS_IN_REDUX_STORE` works perfectly, even if I send it multiple actions when the app loads, but if I change this: 
```
        dispatch({
          payload: responseResultSet,
          type: actionTypes.ADD_SINGLE_RESULT_TO_REDUX_STORE,
        })
``` 
to this:
```
        dispatch({
          payload: [responseResultSet],
          type: actionTypes.ADD_RESULTS_IN_REDUX_STORE,
        })
```
it still doesn't work. 

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

I'm using redux 3.6.0 and redux-thunk 2.1.0

**Comment by markerikson** [comment]
That's... both a good amount of information, and not enough.

Are there any error messages logged in the console?  What happens if you put a breakpoint on that reducer line and step past there?

It's highly unlikely that this is an issue with Redux itself.  That said, if you can create a repo that demonstrates this issue, it might be possible to take a look at it.

**Comment by sam-n-johnston** [comment]
I can also confirm that the object gets indeed added to the state! But the rest of the function does not get called...

**Comment by timdorr** [comment]
Do you have any middleware applied to your store? Something must be swallowing an error somewhere to be doing that. 

As Mark said, do you have any errors in the console?

**Comment by sam-n-johnston** [comment]
Sorry, I messed up. My code was throwing an error, but no information was sent to the console. This was indeed not a redux problem at all. Thanks for pointing me in the right direction!
