### ISSUE TITLE
Document middleware function names.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [reactjs/redux#2174]
Suppose I had the following middleware
```
const middleware = store => next => action => state;
```
Conceptually, it is a single thing, `middleware`.  But when I rewrote it as
```
function middleware(store) {
  return function(next) {
    return function(action) {
      return state;
    }
  }
}
```
I realized that the functions that make up `middleware` don't seem to have a name.
It's nitpicky, but I feel silly naming them `middlerware` and `middlestware`.

**Comment by markerikson** [comment]
Well, if you look at the [Middleware docs page](http://redux.js.org/docs/advanced/Middleware.html), the last example that uses full function syntax looks like this:

```js
function logger(store) {
  return function wrapDispatchToAddLogging(next) {
    return function dispatchAndLog(action) {
      console.log('dispatching', action)
      let result = next(action)
      console.log('next state', store.getState())
      return result
    }
  }
}
```

**Comment by wtgtybhertgeghgtwtg** [comment]
`logger` is middleware, but what are `wrapDispatchToAddLogging` and `dispatchAndLog`?  Do they have official names?

**Comment by markerikson** [comment]
They don't.  If anything, it's kinda like `wrapDispatchToAddThingThisMiddlewareDoes`, and `dispatchAndDoTheThing` :)

**Comment by wtgtybhertgeghgtwtg** [comment]
Alright, thank you.
