### ISSUE TITLE
Inline CSS

### ISSUE THREAD

**Issue by mtaddia** [reactjs/redux#2180]
hi,

i am new to redux and wanted to ask- does Redux always output the css inline in the page or is there a way to generate a css file for the custom css generated by the options panel?

Is there any benefit to adding the styles inline like this? Usually this is something i would avoid doing so i wanted to ask.

If adding the css inline in the page is the only way Redux works can you also let me know if other options panels work the same way?

**Comment by markerikson** [comment]
This repo is for the Redux Javascript data management library.  You're looking for the PHP website tool: https://reduxframework.com/ .
