### ISSUE TITLE
Facing issues with flow when following todos-flow example

### ISSUE THREAD

**Issue by mtford90** [reactjs/redux#2183]
Howdy - so I've just been using the `todos-flow` example as a guideline on how to use redux with flow.

Now this could be an issue with flow or a result of my own lack of understanding but I figured i'd report this anyway as it seems like it could be a potential bug or at least an issue with the examples.

Ignoring the fact that this is not working code (i.e. no state/store/reducers defined - I derived this from my project for brevity) I would have expected to see a flow type error when I attempt to dispatch an action that does not match my `Action` type:

```js
/* @flow */

import type {Dispatch as ReduxDispatch} from 'redux'
import {createStore} from 'redux'

type Action = {
  type: 'SET_SEARCH_STRING',
  searchString: string,
} | {
  type: 'CLEAR_SEARCH_STRING',
}

type Dispatch = ReduxDispatch<Action>

const store              = createStore()
const dispatch: Dispatch = store.dispatch.bind(store)

// Type error as expected
const action: Action = {
  type:         'SET_SEARCH_STRING',
  searchString: 4, // Mistake #1 - flow error
}

// No type error
dispatch({
  type:         'SET_SEARCH_STRING',
  searchString: 4, // Mistake #2 - no flow error
})
```

If you run `flow check` against this, there are no errors for mistake 2. This led me to take a look at the  code for [Dispatch](https://github.com/reactjs/redux/blob/master/index.d.ts#L96) within redux:

```js
export interface Dispatch<S> {
    <A extends Action>(action: A): A;
}
```

So I've never tried typescript so I may be misunderstanding here - but the type `S` i'm passing appears to be ignored? Could this be the reason that flow isn't picking up the error when I fire off `dispatch`?

**Comment by timdorr** [comment]
cc @gcanti or anyone else experienced with Flow. (I'm not, unfortunately)

**Comment by mtford90** [comment]
Closing this - just discovered [flow-types](https://github.com/flowtype/flow-typed). Using this I now get the error I expected.

/flownoob
