### ISSUE TITLE
Rename "container components" "connector components"

### ISSUE THREAD

**Issue by davidgilbertson** [reactjs/redux#2185]
I know this is a long shot, but I'll throw it out there. I think the term "[container components](http://redux.js.org/docs/basics/ExampleTodoList.html#container-components)" would make more sense as "connector components".

a) It is nice and clear what their job is
b) It matches the `connect` method that is central to these components

Happy to do a PR for the docs on the very slim chance that this is deemed a reasonable suggestion.

(I won't mind a no-comment-issue-close :))

**Comment by markerikson** [comment]
Yeah, the terminology on this is well established already.  The "container component pattern" is widely known in the React community.  A "container component" is simply any component whose primary job is to collect data and pass it down to another component.  The wrapper components generated by `connect()` qualify in that regard.

See https://github.com/markerikson/react-redux-links/blob/master/react-component-patterns.md#component-categories for a number of articles discussing "container/presentational" components.
