### ISSUE TITLE
Document suggestion: mention redux-pack

### ISSUE THREAD

**Issue by CodinCat** [reactjs/redux#2192]
The current document mentions redux-thunk, redux-promise and redux-saga in the advanced/AsyncActions section, I think it is worth to add [redux-pack](https://github.com/lelandrichardson/redux-pack) to the list. This library is well designed and does solve some misuses of thunk. (And [according to the author](https://twitter.com/intelligibabble/status/809092589664075776), redux-pack is now used by airbnb.)

**Comment by markerikson** [comment]
Yeah, could mention it in there.  Feel free to submit a PR adding that mention, and we can get it in.
