### ISSUE TITLE
Documenting the application state

### ISSUE THREAD

**Issue by vraa** [reactjs/redux#2195]
I am working on a React / Redux web application. In the beginning of the project, I had a very good understanding of my application state. But, as the code base grows, I tend to put more and more attributes to the application state through reducers. The problem here is, if a new person joining my project, he may not have a clear knowledge about all the attributes that are already there in the state.

Right now, I am just using a commented out Object in a file called `state.js` to describe all the attributes in the state.

    /*
        APP_STATE = {
            attribute1 : '',
            attribute2 : '',
            attribute3 : [],
            attribute4 : {
                key: ''
            },
        }
    */

  

The question is: Is there better way to document the structure of my application state so that it is easy to make sense? What approach do you guys use?

**Comment by JacobSoderblom** [comment]
Depending on your structure, I think [wp-calypso](https://github.com/Automattic/wp-calypso/tree/master/client/state) does a great job at that. They have selectors, reducers, constants, actions and a README.md file that holds most of the documentation in same dir.
```
state
  product
    reducer.js
    selectors.js
    actions.js
    constants.js
    README.md
```

Check them out!

**Comment by vraa** [comment]
@JacobSoderblom that's interesting. May be a similar approach with reduced complexity and structure will work for small scale apps. Thanks.

**Comment by timdorr** [comment]
You can always use a Redux devtool, like either [redux-devtools](https://github.com/gaearon/redux-devtools) or [redux-devtools-extension](https://github.com/zalmoxisus/redux-devtools-extension) to browse the state tree. You can also just `JSON.stringify` the state at any point (I suggest putting the store on `window` to make it accessible through your console) to see what it looks like.
