### ISSUE TITLE
Avoid constants usage and autogenerate actions & reducers from single source like Edux does

### ISSUE THREAD

**Issue by dogada** [reactjs/redux#2199]
**Do you want to request a *feature* or report a *bug*?** 

Feature

**What is the current behavior?**

It's need to add constant for each action name and define separately actions and reducers. In reducers you often need to use switches and each reducer should be able to handle all actions (to return state unchanged for an unknown actions). This leads to unnecessary boilerplate, code duplication and will slowdown reducer stage for complex states.

**What is the expected behavior?**

It's possible to define state `changes` once and generate from this single source of truth both actions and reducers fully compatible with current Redux ecosystem. For example of this approach you can see my attempt to improve this situation:

https://github.com/dogada/edux

For every action it has O(1) speed instead of Redux's O(N) where N is number of reducers.

**Comment by brigand** [comment]
This is something that should be solved in user space. If you like, send a pull request to [markerikson/redux-ecosystem-links](https://github.com/markerikson/redux-ecosystem-links); specifically [action-reducer-generators](https://github.com/markerikson/redux-ecosystem-links/blob/master/action-reducer-generators.md).

**Comment by markerikson** [comment]
Agreed.  This isn't actually a specific "feature" request, either, as it doesn't suggest any actual changes to Redux, but rather just points to an addon library.

**Comment by dogada** [comment]
Thanks. Sent a PR: https://github.com/markerikson/redux-ecosystem-links/pull/35
