### ISSUE TITLE
Q: Redux, HMR, and React Native

### ISSUE THREAD

**Issue by dsimmons** [reactjs/redux#2204]
As part of this [official React Native blog post](https://facebook.github.io/react-native/blog/2016/03/24/introducing-hot-reloading.html), it details the recommended approach using Webpack's `hot` feature. Specifically:

```Javascript

export default function configureStore(initialState) {
  const store = createStore(
    reducer,
    initialState,
    applyMiddleware(thunk),
  );

  if (module.hot) {
    module.hot.accept(() => {
      const nextRootReducer = require('../reducers/index').default;
      store.replaceReducer(nextRootReducer);
    });
  }

  return store;
};
```

I've done some diligence on this thus far, and have a very specific question that I was hoping to obtain some additional clarification around.

As part of [this issue](https://github.com/reactjs/react-redux/issues/347), @Thorbenandresen asked the following question:

> Does this mean that I just have to accept that I won't be able to hot-reload when working on my flow-control logic (thunks, sagas)?

As far as I can tell, the recommended approach is to actually call the above `configureStore` **within a component**, per @gaearon's comment:

> If you change the component that creates the store, store = createStore() will re-execute and you will get a new store. Either don’t change that component while you work on the app (do you often need to change the root component?), or create store in index.js and pass it as a prop so you can work on the component independently.

So my question is as follows: what do you do when you **additionally** need to access `store.dispatch` outside of any given/particular component?

To elaborate, I'm using one or more third-party libraries that expose observables. Accordingly, upon code initialization, in addition to providing an **instance of a store** to my root-level `Provider` component to be passed down the component tree, I also need access to **the same store instance** to wrap the observables with a corresponding `store.dispatch` invocation, when an event is emitted.

If my understanding is correct, it sounds like, for HMR to work correctly, you need to define the instantiation code such that it won't be re-executed again when the HMR process runs, as to maintain the original store and not instantiate a new one.

So I guess my question is, is it possible to keep the store from being reinstantiated if you additionally need to access it outside of a root-level component? Per my local testing, as far as I can tell, that seems to be what's happening -- if I keep the store instance in the "global scope" (as an export), it seems that HMR is recreating it every time. If I keep the instantiation local to the root-level component, I'm then unable to access it outside of the component tree.

I hope the above makes sense! 😄 Happy to provide code samples of what I'm attempting to do if the additional context it's helpful.

**Comment by steida** [comment]
That's all we need https://github.com/este/este/blob/a1f5baff53f33dfa8dc741e2110b0bb520aa7146/src/native/app/Root.js#L11

**Comment by timdorr** [comment]
You should just need to move your HMR handling up to the same level where you instantiate the store. That is so you can replace that variable (i.e., it should be `let store = createStore()` instead of `const store = createStore()`) and still maintain reference to it inside of whatever other closures you start at the top level.
