### ISSUE TITLE
npm redux.js build breaks isCrushed() check and always throws warning

### ISSUE THREAD

**Issue by alexdvance** [reactjs/redux#2210]
The following code exists in the npm build of redux:

```
	if (("development") !== 'production' && typeof isCrushed.name === 'string' && isCrushed.name !== 'isCrushed') {
	  (0, _warning2['default'])('You are currently using minified code outside of NODE_ENV === \'production\'. ' + 'This means that you are running a slower development build of Redux. ' + 'You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify ' + 'or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) ' + 'to ensure you have the correct code for your production build.');
	}
```

In the npm redux build, `process.env.NODE_ENV` has been replaced with `('development')`, causing the warning to always fire when redux is minified. This NODE_ENV variable needs to not be replaced so npm redux installers can get the warning only on development.

**Comment by jimbolla** [comment]
I'm pretty sure this is intentional. Instead of minifying `dist/redux.js`, you're expected to use `dist/redux.min.js`.

**Comment by alexdvance** [comment]
So I have to use different files on my dev and prod builds?...ok.
