### ISSUE TITLE
Remove or polyfill the use of Symbol in the examples

### ISSUE THREAD

**Issue by daannijkamp** [reactjs/redux#2217]
The  [real word example](https://github.com/reactjs/redux/blob/master/examples/real-world/src/middleware/api.js#L76) makes use of JavaScript Symbols. This doesn't work in older browsers¸ also [Create React App](https://github.com/facebookincubator/create-react-app/blob/d1250743adc2abc41d80d566c5f817e1a16da279/packages/react-scripts/config/polyfills.js) doesn't provide any polyfill for Symbols.
I believe that this should be removed from the example. Because It is only used once, and a polyfill needs some [optimizations](https://github.com/facebookincubator/create-react-app/issues/170#issuecomment-235304765) require it. 
What do you think?

**Comment by gaearon** [comment]
Sure, I don't think it's important there. Send a PR?
