### ISSUE TITLE
Importing with Webpack Produces SyntaxError

### ISSUE THREAD

**Issue by joshdmiller** [reactjs/redux#2223]
**Do you want to request a *feature* or report a *bug*?**  

Bug.

**What is the current behavior?**

The main lib of the latest (3.6.0) version of redux is not importable using babel and wepback. It produces the following error:

```
ERROR in ../~/redux/es/index.js
Module build failed: SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
```

Importing specific files (from lib) works ok; the problem also does not exist on 3.5.2.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

The following webpack config is sufficient to reproduce the error.

```js
module.exports = {
  context: __dirname + '/src',
  entry: './index.js',
  output: {
    path: __dirname + '/build',
    filename: 'bundle.min.js',
  },
  module: {
    loaders: [
      {
        test: /\.js$/,
        exclude: /(node_modules)/,
        loaders: [ 'babel-loader', 'ng-annotate-loader' ],
      },
    ],
  },
};
```

**What is the expected behavior?**

I expect the default export to be importable. :smile: 

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

3.6.0 fails; 3.5.2 works. I'm on Fedora Linux with node 6.7 and npm 3.10. Latest babel and latest webpack (though the problem persists in the last major version as well).

**Comment by timdorr** [comment]
You need to configure babel to disable the `modules` transform if you're using tree-shaking and native es modules. If you scroll down to the 3rd item on the list in this section, it'll show you how to do it: https://webpack.js.org/guides/hmr-react/#code
