### ISSUE TITLE
Possible alternative for a protected state

### ISSUE THREAD

**Issue by leodutra** [reactjs/redux#2228]
I'm a long time JavaScript developer but a new redux user.

I've read and heard about changing redux state and I've seen libs which freezes or clone the state. Most of then freezes the source state and that's already a state change by principle. 

I tinkered with some ideas and found a "proxied" solution.

As I'm new, I don't know if is interesting for redux core team, but I found it more performatic and less drastic than a deep `Object.freeze()`

The solution is very simple: it creates a proxy for the source object, which returns a new proxy for referenced objects, on every property access.

```javascript
function toImmutableProxy(any) {
    switch(typeof any) {
        case 'object':
        case 'function':
        case 'xml':
        
            return new Proxy(any, {
                set: function immutableProxySet(target, prop) {
                    throw new Error('Cannot set property "' +prop +'", this object is immutable.')
                },

                get: function immutableProxyGet(target, prop) {
                    return toImmutableProxy(target[prop])
                }
            })
    }
    return any
}
```

[Demo](https://jsfiddle.net/de2fL1m6/3)

**Comment by timdorr** [comment]
I'd probably wait on Proxys to become more prevalent, as you don't have them in most browsers and the polyfills are incomplete for now. Interesting idea though. Thanks!

**Comment by markerikson** [comment]
Yeah, this isn't something we'd bring into the core, but as you said, there are definitely a number of existing libs for freezing state during dev to help find accidental state mutations.  My Redux addons catalog lists them in the [DevTools#Linting](https://github.com/markerikson/redux-ecosystem-links/blob/master/devtools.md#linting) category.

As Tim said, Proxy availablility is a major limiting factor, but it would be interesting to see another freezing-type library that uses Proxies as the implementation.  I'd encourage you to look into publishing your approach as a library.
