### ISSUE TITLE
This cannot be real world without tests (unless you're advocating that projects with no tests is a real world situation, therefore it is right)

### ISSUE THREAD

**Issue by legacyWork** [reactjs/redux#2229]
Where are the tests?

**Comment by jimbolla** [comment]
https://github.com/reactjs/redux/tree/master/test

**Comment by gaearon** [comment]
By “real-worldiness” I mostly meant smart caching, loading indicators, pagination, and using middleware.
Maybe not the best naming in retrospect 😄

**Comment by legacyWork** [comment]
The question remains, are tests going to be written for this "real world" example?

**Comment by gaearon** [comment]
If you contribute them, maybe. 😉
