### ISSUE TITLE
redux on npm package.json doesn't have the browser field

### ISSUE THREAD

**Issue by monkindey** [reactjs/redux#2235]
### Do you want to request a *feature* or report a *bug* ?

report a __bug__

### What is the current behavior ? 

1. `npm install redux` or `yarn add redux`
2. view the package.json which didn't have the **browser** field, but the github repo have.

Sorry for the big image, which is the part of package.json file on npm, didn't found the browser field

![image](https://cloud.githubusercontent.com/assets/6913898/22836385/2101537e-eff7-11e6-8162-b728afb9ab77.png)

### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.

as above

### What is the expected behavior ?

package.json have the browser field and the [unpkg](https://unpkg.com/redux) can read the browser field to determine which file is used for browser. Now is the `lib/index.js`

### Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?

__3.6.0__

Thanks

**Comment by timdorr** [comment]
It was added in #2047. We haven't had a release since then.
