### ISSUE TITLE
Middleware - Dispatch to beginning of middleware chain?

### ISSUE THREAD

**Issue by stevenmusumeche** [reactjs/redux#2241]
I am writing a custom middleware that needs to dispatch thunk actions. The problem is that the middleware is called after redux-thunk in the middleware chain, so I get the error `Uncaught Error: Actions must be plain objects. Use custom middleware for async actions.` when using the provided `dispatch`.  

My understanding was that by using `dispatch` in the middleware, it would start the entire middleware chain again, and then `redux-thunk` could process the thunk action, but it appears to only be sending the action to the next middleware.

```
export default function createMiddleware() {
    return ({dispatch, getState}) => next => (action) => {
        if(action.type !== 'FOO') {
            return next(action);
        }

        dispatch(thunkActionHere); // this is the issue
    }
}
```

**Comment by timdorr** [comment]
If you need to pass things to redux-thunk, then make sure it comes before it in the middleware chain. Then you would simply call next. It's not a good idea to dispatch in your middleware, as that can easily lead to infinite loops.

**Comment by NE-SmallTown** [comment]
The chain order by `applyMiddleware`  is **right to left**.But called by **left to right**.For example,`applyMiddleware(middlewareA, middlewareB)` means that `redux's native store` controled by `B` controled by 'A',when you call `dispatch` at component,first it will calls middlewareA's encapsulated itself `dispatch`,and then calls middlewareB's encapsulated itself `dispatch`, and then calls `redux's native `dispatch`.
