### ISSUE TITLE
DEV code is now in production bundle in master

### ISSUE THREAD

**Issue by gaearon** [reactjs/redux#2244]
This PR broke Uglify's dead code elimination for DEV: https://github.com/reactjs/redux/pull/2030.

Uglify is not smart enough to understand that if a literal is assigned to a variable, and later that variable gets compared, it's the same as literal. As a result, DEV-only code ends up in the production bundle:

```js
{var c=t[r];"production"!==p&&void 0===e[c]&&(0,l["default"])('No reducer provided for key "'+c+'"'),"function"==typeof e[c
```

I suggest reverting #2030, at least in the current form.

**Comment by timdorr** [comment]
Yeah, not sure why I didn't give that more scrutiny. Luckily, it hasn't been released.

We may want to add a quick check of the gzipped UMD bundle size to the build scripts. We do this on react router and it helps guard against ballooning the bundle size, provided you know what a "good" size looks like. 

I'll revert this once in on desktop (since it can't be done automatically).

**Comment by gaearon** [comment]
>We may want to add a quick check of the gzipped UMD bundle size to the build scripts.

Yes, that would be great!

**Comment by Andarist** [comment]
Do you guys know by any chance how [this](https://github.com/reactjs/redux/commit/0139a9601dae810db533762c2bc4a745a37d4cf6#commitcomment-20910083) can be avoided?

**Comment by timdorr** [comment]
That sounds like a tooling problem. We don't add the polyfill ourselves, so it would seem you need to configure your tooling not to do that. It's similar to checking for a DOM with `typeof window !== 'undefined'`.

**Comment by Andarist** [comment]
yeah, u have reverted your checks to `if (process.env.NODE_ENV !== 'production') {`, but the mentioned commit tried not to only cache this value, but also guarded against lack of `process` like this:
`var NODE_ENV = typeof process !== 'undefined' ? process.env.NODE_ENV : 'development'`
this has triggered (on your previous webpack config too, i see u have switched to rollup now) `process` polyfill to be included

anyhow i'll try to explore possibilities to avoid this, from that I understand Aurelia has its own bundler which does not recognize `process` and packages that use it cannot be properly transpiled by its users

**Comment by timdorr** [comment]
@Andarist It's 50% smaller: https://github.com/reactjs/redux/pull/2283#issuecomment-284913574
