### ISSUE TITLE
Produce main bundle with Rollup

### ISSUE THREAD

**Issue by gaearon** [reactjs/redux#2245]
There are unfortunate Babel artifacts in the compiled UMD bundle.
For example:

```js
return e&&e.__esModule?e:{"default":e}}t.__esModule=!0
```

```js
// Oops, we access ["default"] in a hot path!
if(!(0,u["default"])(e))throw Error("Actions must be plain objects. Use custom middleware for async actions.")
```

We should use a better build process that doesn’t produce artifacts like this.

**Comment by timdorr** [comment]
This is due to the oldIE support stuff, right? Shouldn't be happening in next branch. Scope hoisting (aka, rollup) won't fix this by itself.

**Comment by gaearon** [comment]
I meant the Babel `default` indirection which goes away if we compile with Rollup.

**Comment by TrySound** [comment]
@gaearon Do you want a PR?

**Comment by gaearon** [comment]
Sure.

**Comment by TrySound** [comment]
@gaearon Done
