### ISSUE TITLE
Docs - Simpler "Usage With React" guide

### ISSUE THREAD

**Issue by christiannaths** [reactjs/redux#2246]
Hi all, I hesitated a lot adding this but was encouraged by the contribution guidelines, so here it goes: 

### I'd like to see if there is any interest in adding a simplified version of the "Basics/Usage with React" tutorial.

I often find it hard to remember the steps to add Redux to a React web application and every time I land on the official docs I really find the "Usage with React" page far too complicated, as I really just need the basic setup to then flesh out for my own needs. I'm thinking that I might not be the only person with this need/want.

The current page was also a hurdle for me when I was learning Redux, as I was approaching the library _because_ of React so this is the page in the documentation that I immediately gravitated towards – I sort of suspect this isn't all that uncommon.

### I'd be more than happy to contribute this in a PR, but I wanted to see if there was interest first.

A few opinions I have about how this might go:

- would fit in alongside the current "Usage with React" page – not a replacement
- would focus on the _how_, not the _why_
- just enough code to get started, and to easily extend as needed (one step beyond the current "Counter" example, but as a tutorial/guide)

I have a draft of what kind of content I'm planning, you can read it here if you like: https://medium.com/@christiannaths/from-zero-to-redux-8db779b6ed01#.sbnt0jpjo

&nbsp;

So, if you have a moment and wouldn't mind letting me know if this is something you think would be useful, I'd be happy to get started. Also welcoming any suggestions to the draft I posted (structure, code samples, etc) if that makes for a good starting point.

**Comment by markerikson** [comment]
That's definitely a reasonable idea.  The current docs have a distinct tendency towards the "walk you through all possible steps so you understand the reasoning" approach, which can be helpful, but that's not the best way for everyone to learn.  

I'm not entirely sure on exactly how the content in your draft would fit into or alongside the current page.  That said, yeah, if you have some ideas for how to improve the current content, by all means put together a PR and we can work through the changes.  

Thanks!

**Comment by christiannaths** [comment]
Ok awesome, I'll put a PR together. Thanks! 🙂

**Comment by christiannaths** [comment]
I'm going to close this since my question has been answered. I'll try to follow up with a PR soon :)
