### ISSUE TITLE
Improve the description of createStore.js

### ISSUE THREAD

**Issue by NE-SmallTown** [reactjs/redux#2249]
In the src code of [createStore](https://github.com/reactjs/redux/blob/master/src/createStore.js):

```
  // When a store is created, an "INIT" action is dispatched so that every
  // reducer returns their initial state. This effectively populates
  // the initial state tree.
  dispatch({ type: ActionTypes.INIT })
```

The word "INIT" maybe cause confusion to new people,because in the examples of official,we use the `DevTools.instrument()` enhancer and it would dispatch a action which is displayed with  `INIT_ACTION` in console or devtools and it's value is `@@INIT`.

On the contrary,the redux's init action is displayed with  `INIT` in console or devtools and it's value is `@@redux/INIT`.IMO,if people who use redux and `DevTools.instrument()` enhancer,this situation may cause them can't understand very well.

So,suggest that add some description in the src code or docs.

**Comment by timdorr** [comment]
The `INIT` action is really a private thing that doesn't concern the user of the store. If you're seeing it in redux-devtools, then it would make more sense to add documentation on the devtools side of things. Most people aren't going to see that if they aren't using devtools.

**Comment by NE-SmallTown** [comment]
Thanks for you replay.I agree that ' Most people aren't going to see that if they aren't using devtools',but now the situation is that almost everyone will using devtools and the most important is that the [redux examples](https://github.com/reactjs/redux/blob/master/examples/real-world/src/store/configureStore.dev.js#L14) use it too.So it will be friendly add something reminding in the src code.Read the src code help us to understand redux and it's the first step to think redux ecological system.

**Comment by NE-SmallTown** [comment]
@markerikson @gaearon @ellbee what's your thought about this?

**Comment by NE-SmallTown** [comment]
@markerikson @gaearon @ellbee @jimbolla @acdlite what's your thought about this?

**Comment by NE-SmallTown** [comment]
Any body wants to discuss this?
