### ISSUE TITLE
Docs -- Add a note explaining tradeoffs when using `combineReducers`?

### ISSUE THREAD

**Issue by dmitrygusev** [reactjs/redux#2250]
Currently in [Basics/Reducers/Splitting Reducers](https://github.com/reactjs/redux/blob/34b7b0650f43cfad3cb64bc700b97a511c6f57e9/docs/basics/Reducers.md#splitting-reducers) it's proposed to return JavaScript object with reducer functions:

```javascript
...
function todoApp(state = {}, action) {
  return {
    visibilityFilter: visibilityFilter(state.visibilityFilter, action),
    todos: todos(state.todos, action)
  }
}
```

Although it's the same semantically (as reducers are pure functions), it's not exactly the same as with the `switch` statement.

In above example and with `combineReducers` we still need to call the reducer functions in order to calculate the new state which involves unneeded CPU usage.

In previous steps of the tutorial the state was just copied using `Object.assign()` or the spread operator which is more efficient, as we know those parts won't be changed and we can only call the required reducers.

Am I right here?

**Comment by markerikson** [comment]
Ah... sort of.  

In that example, the `switch` statements are inside of the slice reducers.  We _know_ that we need to construct an object that looks like `{todos, visibilityFilter}`, so there's definitely no need for a switch statement there.  The only question is how we put together the contents of each slice, and the `todoApp` function is composing together the two slice reducers and delegating the decision to them.

Also, `combineReducers` still calls all the slice reducers it was given - the only real difference with the example snippet there is that `combineReducers` will check to see if all slice reducers returned the same object they did before, and if so, return the same top-level object as well.

It's also important to keep in mind that that page is just introducing the idea of reducers and combining them, not trying to define the most optimized possible way of writing them.

You may also want to read through the [Structuring Reducers](http://redux.js.org/docs/recipes/StructuringReducers.html) section, which does go into detail about more advanced usage of reducers.

**Comment by dmitrygusev** [comment]
Indeed there's already a note on this in [Structuring Reducers/Using `combineReducers`](http://redux.js.org/docs/recipes/reducers/UsingCombineReducers.html#core-concepts).

>One frequently asked question is whether Redux "calls all reducers" when dispatching an action. Since there really is only one root reducer function, the default answer is "no, it does not". However, combineReducers has specific behavior that does work that way. In order to assemble the new state tree, combineReducers will call each slice reducer with its current slice of state and the current action, giving the slice reducer a chance to respond and update its slice of state if needed. So, in that sense, using combineReducers does "call all reducers", or at least all of the slice reducers it is wrapping.

Though I still think it would be nice to mention this somewhere in the beginning. I must admit I was wrong about extra CPU usage as only one of the sliced reducers will match dispatched `action` and actually generate new state, the rest will just return the same slice via `switch/default`.
