### ISSUE TITLE
react-native Help

### ISSUE THREAD

**Issue by hirande** [reactjs/redux#2251]
Good luck with.
Friends! I get this error when I run the application in android studio, I have not figured it out for days. But the same application 'XCODE' works without problems. Android studio does not work either. ADV Emulator I need the error halves you encounter. Thank you

Examines
https://codecanyon.net/item/beostore-complete-react-native-template-for-ecommerce/17010642
=============================================
`
console.error: “You are currently using minified code outside of NODE_ENV === ‘production’. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.” t warning.js:14:18 <unknown> index.js:39:2 i require.js:130:15 n require.js:69 t require.js:53 <unknown> wrapActionCreators.js:6:21 i require.js:130:15 n require.js:69 t require.js:53 <unknown> connect.js:19:34 i require.js:130:15 n require.js:69 t require.js:53 <unknown> index.js:10:23 i require.js:130:15 n require.js:69 t require.js:53 <unknown> RootRouter.js:10 i require.js:130:15 n require.js:69 t require.js:53 <unknown> index.android.js:11 i require.js:130:15 n require.js:59:13 t require.js:53 global code require-0.js:1`

**Comment by brigand** [comment]
@hirande this is the wrong repo.

**Comment by hirande** [comment]
I do not know exactly what you mean?

**Comment by brigand** [comment]
@hirande this is the redux issue tracker, not react-native. https://github.com/facebook/react-native/issues/new

**Comment by markerikson** [comment]
Technically, the error message is related to Redux, but it's a problem with your project's build setup, not a bug with Redux.  So, it's not a valid issue to discuss here.
