### ISSUE TITLE
Add an example which does not use create-react-app

### ISSUE THREAD

**Issue by ioboi** [reactjs/redux#2261]
**Do you want to request a *feature* or report a *bug*?**  
A feature.

**What is the current behavior?**
Most examples have been rewritten using create-react-app.

**What is the expected behavior?**
Would it be possible to add one example (could be as simple as the counter example), which does not use create-react-app. If there would be one, it could be used for guides like the [Server Side Recipe](http://redux.js.org/docs/recipes/ServerRendering.html).

**Comment by gaearon** [comment]
We have one, `universal`.

**Comment by ioboi** [comment]
Ok, thanks for pointing out `universal`.

**Comment by ioboi** [comment]
I thought of using an existing example for #2211 as a guide but the only two examples are `universal` and `counter-vanilla`. The existing [SSR recipe](http://redux.js.org/docs/recipes/ServerRendering.html) guides the user through the process of setting up SSR, so I don't think I can use `universal` as a base. 
Would another example without SSR like for example the `counter` or `todos` be feasible to add to the existing examples?

**Comment by gaearon** [comment]
I'm a bit confused. Are you looking for an SSR example of the opposite?

**Comment by ioboi** [comment]
Sorry for the confusion. I would like to update the [SSR recipe](http://redux.js.org/docs/recipes/ServerRendering.html), which at the moment cannot be followed step by step as it's "out of sync" with the current state of the repository. (Issue #2211)

For the updated guide I would like to provide a sort of bare bone example, just containers, components, reducer and actions. The updated [SSR recipe](http://redux.js.org/docs/recipes/ServerRendering.html) would then guide the user in adding SSR to the bare bone example.

**Comment by timdorr** [comment]
> For the updated guide I would like to provide a sort of bare bone example, just containers, components, reducer and actions.

That's exactly what the Example in the docs does: http://redux.js.org/docs/basics/ExampleTodoList.html

>  I would like to update the SSR recipe, which at the moment cannot be followed step by step as it's "out of sync" with the current state of the repository. 

Let's keep track of that in #2211. If you have any ideas, a PR would be great!
