### ISSUE TITLE
Bad color of links in a theme, may be change?

### ISSUE THREAD

**Issue by BorodinDemid** [reactjs/redux#2262]
Hello!
I ran into a problem when I switched a theme.
This problem is only in the color scheme - "sepia".

In this color scheme, it's very hard to find links.
You can distinguish text from a link only when you are hovering.
My English is not very, so I'll put a gif.

![-23-2017 17-36-55](https://cloud.githubusercontent.com/assets/10565298/23263239/b4ac11e4-f9ee-11e6-955f-f66d11adce2b.gif)

**Comment by markerikson** [comment]
You're looking for https://reduxframework.com/ .

**Comment by naw** [comment]
Looks like he's referring to http://redux.js.org/docs/basics/Reducers.html

**Comment by markerikson** [comment]
Huh.  My bad - I saw the words "color scheme" and "themes", and assumed this had nothing to do with the Redux JS library.  Also... we have "themes" for our docs?

**Comment by naw** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/8030877/23270048/cac7b8e6-f9af-11e6-9f2c-e1c74e3ef217.png)

**Comment by markerikson** [comment]
Huh.  We do have themes for our docs.  Presumably something that's built into Gitbook.

Honestly, this isn't something I'm worried about.  If someone wants to submit a PR that modifies this in some way, I guess we could look at it, but considering the default theme is "White", I don't see this as much of ap roblem.

**Comment by BorodinDemid** [comment]
@markerikson i can change color, but need use !important, i don't found other why (but i try) :)
i can make pr, and change gitbook.css in build folder, because this css include in gitbook.

<img width="463" alt="2017-02-23 20 34 38" src="https://cloud.githubusercontent.com/assets/10565298/23271176/a46cee5c-fa07-11e6-8d0d-e70416d8f594.png">

It would be a good idea? I just don't want to look stupid if I do it)
