### ISSUE TITLE
console.log

### ISSUE THREAD

**Issue by 4knort** [reactjs/redux#2271]
somebody forgot to delete console.log from the code before production
open console on the main page to see the problem

**Comment by timdorr** [comment]
Other than the docs and a typescript test, [there aren't any `console.log`s in the codebase](https://github.com/reactjs/redux/search?utf8=%E2%9C%93&q=console.log) nor [in the final build](https://unpkg.com/redux@3.6.0/dist/redux.js). If you can point to the specific line, that would be helpful.

**Comment by 4knort** [comment]
http://clip2net.com/s/3I4h2lB

**Comment by gaearon** [comment]
This is from our documentation system (Gitbook). It doesn’t really affect anything, but feel free to send them a PR! 😉
