### ISSUE TITLE
Reducer that returns Infinity value turns value into null

### ISSUE THREAD

**Issue by hyperh** [reactjs/redux#2273]
**What is the current behavior?**
A reducer that returns the value Infinity, turns into null.

**What is the expected behavior?**
I expect the reducer to return Infinity.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**
Redux 3.6.0
Was running on OSX 10.11.6, Chrome 56.0.2924.87

**Comment by markerikson** [comment]
Please provide a repro of the issue.  Redux itself shouldn't actually do any kind of modification to a reducer return value.

**Comment by hyperh** [comment]
@markerikson Actually, it seems like it's an issue with the React Chrome devtools and Redux Chrome devtools, they both display `Infinity` as `null`. But when I do a `console.log(...)`, I get `Infinity`.

**Comment by zalmoxisus** [comment]
Yes, `Infinity` is not serializable. If you think that Redux Devtools Extension should support that, please file an issue [there](https://github.com/zalmoxisus/redux-devtools-extension). We're currently [serializing](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#serialize) dates, regex, undefined, error objects, symbols, maps, sets and functions.
