### ISSUE TITLE
More reusable reducer logic

### ISSUE THREAD

**Issue by Voronar** [reactjs/redux#2278]
According to [this issue](http://redux.js.org/docs/recipes/reducers/ReusingReducerLogic.html) I suggest improved [approach](https://github.com/Voronar/redux-multireducer).

P.S. Yes, I have found Dan [warning](https://github.com/reactjs/redux/issues/779) about symbol constants.

**Comment by markerikson** [comment]
This isn't a bug report or an actual feature request.  You're welcome to use this approach in your own code, although as you've seen already, use of Symbols will cause the DevTools to not always work as expected.  Also see this entry in the FAQ: http://redux.js.org/docs/faq/Actions.html#actions-string-constants

**Comment by Voronar** [comment]
Symbol is not a problem. Just try this [implementation](https://github.com/Voronar/redux-multireducer/blob/master/src/redux/modules/list/List.devtools.ready.js).
