### ISSUE TITLE
How to deal with one time action?

### ISSUE THREAD

**Issue by sky0014** [reactjs/redux#2285]
For example, when ACTION_UPDATE dispatched, update method should be runned.

`{type:ACTION_UPDATE} -> {shouldUpdate:true} -> update()`

That's correct.

But next time when other action dispatched, **shouldUpdate** remains **true**, and will trigger update method again.

How to deal with this kind of one time action?

I supposed to do it like this:

`{type:ACTION_UPDATE} -> {shouldUpdate:true} -> update() -> {type:ACTION_UPDATE_DONE} ->  {shouldUpdate:false}`

But will it be a little complicated? Is there any easier way?

**Comment by timdorr** [comment]
Perhaps dispatch some action in whatever looks for that state to "reset" the variable back? 

It sounds more like you need to restructure your state and application code, as temporal state doesn't really work well in redux or React. Ryan Florence gave a good talk about removing time from your state at React Rally: https://www.youtube.com/watch?v=kp-NOggyz54

**Comment by sky0014** [comment]
Thank you, I will take a look at that:)
