### ISSUE TITLE
How to integrate new React-Router (v4.0.0) with React Redux app?

### ISSUE THREAD

**Issue by wzup** [reactjs/redux#2300]
Guys from React-Router have rolled-out new version of their plugin (v4.0.0) and as they say themselves they only have a basic idea of how it should work with Redux. 

And Redux docs is about React Router `^2.7.0` (http://redux.js.org/docs/advanced/UsageWithReactRouter.html)

Will there be an update on how to use Redux with React and new React Router (v4.0.0)?

**Comment by markerikson** [comment]
PRs are welcome :)

**Comment by yogurt1** [comment]
Listen to history changes and update location state in Redux
See `react-router-redux`

**Comment by Lukeghenco** [comment]
@markerikson is this the only page with React Router instructions http://redux.js.org/docs/advanced/UsageWithReactRouter.html? I could put some time into a PR for it.

**Comment by wzup** [comment]
I have written a blog-post in Medium on how to do React server-side rendering with React-router v4

https://medium.com/@5XvYrLT7/react-server-side-rendering-with-react-router-3-x-74cf87919b3

**Comment by devserkan** [comment]
I created a PR for an 4.1.1 version update. I don't know if anything missing but I wrote and tried the updated code and it is working for 4.1.1.

**Comment by derwaldgeist** [comment]
Any news on this? I am curious if redux can be run with react-router 4. The latter seems quite promising, but I do not want to break my app.

**Comment by devserkan** [comment]
@derwaldgeist, we can use Redux with React Router 4 easily. There is not any obstacle about that. This issue is only related with the outdated documentation. You can see a working example here: https://github.com/devserkan/react-with-idiomatic-redux

**Comment by derwaldgeist** [comment]
Thanks for this info!

**Comment by sambragge** [comment]
Is anyone still having trouble with this? I have tried solutions from various forums and none have worked. I am using React Router 4 with Redux, and when my route changes my view does not. withRouter seems to do nothing.

**Comment by timdorr** [comment]
Merged in some changes on this. If anyone wants to improve it, go right ahead!

**Comment by zhoulujun** [comment]
https://github.com/zhoulujun/wepack4-react-project-template
a demo^
