### ISSUE TITLE
Real world pagination example a bit limiting? No pun intended.

### ISSUE THREAD

**Issue by MarkMurphy** [reactjs/redux#2303]
This is part example/feature request and question. Take your pick.

Say I want to keep state of `videosByUser` in my pagination reducer. Using the `paginate` method 
from the "real world" example I would do:

```
videosByUser: paginate({
  mapActionToKey: action => action.payload.userId,
  types: [VIDEOS_LIST_REQUEST, VIDEOS_LIST_SUCCESS, VIDEOS_LIST_FAILURE]
})
```

But what happens when I want `videosByUser[1].ids` to include the video id after a `VIDEOS_CREATE_SUCCESS` action?

Won't work. That's not an action the `videosByUser` pagination is listening for.

**Comment by timdorr** [comment]
The real-world example is just one possible way of doing things. If you need some other way of structuring your data, you might need to jump into more advanced techniques, such as reselect's selectors.

**Comment by markerikson** [comment]
You may also want to look at this recent article on [Advanced Redux Entity Normalization](https://medium.com/@dcousineau/advanced-redux-entity-normalization-f5f1fe2aefc5) .

**Comment by MarkMurphy** [comment]
Thanks guys!
