### ISSUE TITLE
Add a method to our requirement

### ISSUE THREAD

**Issue by Vasikaran** [reactjs/redux#2305]
Can you guys add setState() method in createStore module?

**Comment by TrySound** [comment]
@Vasikaran Nope. It's anti-pattern. State should be changed only with actions, without any other force. This makes application more predictable and safe.

**Comment by markerikson** [comment]
No.  As @TrySound  said, that is _not_ how Redux is intended to be used.  Please read the [Three Principles of Redux](http://redux.js.org/docs/introduction/ThreePrinciples.html) section in the docs.

**Comment by Vasikaran** [comment]
Okay, thank you for your replies. 👍
