### ISSUE TITLE
Redux store automatically updates by javascript reference

### ISSUE THREAD

**Issue by datpt154** [reactjs/redux#2308]
As i know Redux store is just update through reducer. But that's not correct. I meet this issue when i work on Angular2 form and Redux. **Whenever I change my component data, that mean Redux data will be changed automatically**.
Here below is my code to load redux store to angular component
```js
const initialState: IStatePage = {
  formStatus: Consts.NOT_COMPLETED,
  formData: {age: 10, b: 20}
}

this.ngRedux.select(state => state.formData)
      .subscribe(data=> {
        this.localFormData= data;
      });

<lable>Age</lable>
<input [(ngModel)]= "localFormData.age">
```
. When user changes Age from UI  
    - angular will binding two-ways to localFormData.age.
   - Because javascript is passing by reference => that will affect to Redux store

is there any solution here for this issue?

Thanks

**Comment by datpt154** [comment]
Currently my solution is using lodash cloneDeep to prevent Redux store changed. But i think cloneDeep is not good for performance. So hope to listen to new ideas

this.ngRedux.select(state => state.formData)
.subscribe(data=> {
this.localFormData= _.cloneDeep(data);
});

Thanks

**Comment by neurosnap** [comment]
There is nothing stopping a person from mutating the store, the idea is that you shouldn't do it.  This is more of a convention as opposed to some frozen object.

At my job we use https://github.com/buunguyen/redux-freeze to ensure we don't inadvertently mutate the state in  a component of selector.

**Comment by TrySound** [comment]
@datpt154 Just don't use two way data binding. Do all via unidirectional data flow.

**Comment by timdorr** [comment]
This seems like a question better answered by the ng-redux team, as it's not really specific to redux itself, but your integration with angular.

**Comment by datpt154** [comment]
I see my problem is Javascript reference by object. So when you change an object. Every variable that reference to that object will be affected automatically. 

@neurosnap Thanks for you idea. That's right we should prevent update Store except Reducer.
