### ISSUE TITLE
"examples:build" script fails

### ISSUE THREAD

**Issue by everdimension** [reactjs/redux#2321]
`npm run examples:build` script currently ends with an error:

`Error: Building examples exited with non-zero`

This happens when you do not have `webpack` installed neither locally nor globally.

Webpack is not listed in `devDependencies` though, but is used in a building script: https://github.com/reactjs/redux/blob/v3.6.0/examples/buildAll.js#L16

I'm using the `master` branch (`v3.6.0`)

**Comment by timdorr** [comment]
This works in master, as we've switched to yarn.

**Comment by everdimension** [comment]
What does this have to do with it?!

You do not have `webpack` neither in dependencies nor in the `yarn.lock` file.

The script doesn't work unless you install webpack globally or to the project.

**Comment by gaearon** [comment]
Hmm. I have no idea why we have `webpack` in there at all.

**Comment by gaearon** [comment]
It should run `npm run build` in every package. Most of these packages delegate to `react-scripts build`.

**Comment by timdorr** [comment]
Let me check on that then. I went through all of these things when switching to yarn, but may have missed something. The universal example is the only weird one, but should just need a noop script for `build`.
