### ISSUE TITLE
The "Understanding Programmatic Side Effects" link is broken

### ISSUE THREAD

**Issue by bryonchan** [reactjs/redux#2330]
**Do you want to request a *feature* or report a *bug*?**  
Bug in the documentation - http://redux.js.org/docs/recipes/reducers/PrerequisiteConcepts.html

**What is the current behavior?**
The link (http://web24studios.com/2015/10/understanding-programmatic-side-effects/) goes to a generic hosting holding page

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**
v.3.6.0

**Comment by timdorr** [comment]
Can you submit a PR to fix this?

**Comment by justincy** [comment]
It's hard to submit a PR without knowing what the original content was but perhaps this could replace it: http://c2fo.io/c2fo/programming/2016/05/11/understanding-programmatic-side-effects/

**Comment by timdorr** [comment]
Yeah, that's fair. I'm not expect omniscience 😄  That link looks like a good replacement to me. I'll swap it out now.

**Comment by markerikson** [comment]
Yes, that appears to be the same article content in a different location, thankfully.  The original domain looks to be dead.  Thanks!
