### ISSUE TITLE
Could there be a description of what Real World and Universe do? And a sample working website?

### ISSUE THREAD

**Issue by jianlin** [reactjs/redux#2333]
The current description or README.md doesn't say much about them.
Are there sample websites to see it working?

**Comment by timdorr** [comment]
The documentation lists them: https://github.com/reactjs/redux/blob/master/docs/introduction/Examples.md

You have to check out the example code to get it working. It's not possible to run them on GitHub pages, as some require server side code.

**Comment by jianlin** [comment]
I mean... after reading the description, I still don't know what it is

Real World:
This is the most advanced example. It is dense by design. It covers keeping fetched entities in a normalized cache, implementing a custom middleware for API calls, rendering partially loaded data, pagination, caching responses, displaying error messages, and routing. Additionally, it includes Redux DevTools.

Universe:
This is a basic demonstration of server rendering with Redux and React. It shows how to prepare the initial store state on the server, and pass it down to the client so the client store can boot up from an existing state.

**Comment by timdorr** [comment]
If you'd like to see it changed, a PR is the best way to do that. Just saying "make it better" doesn't offer any real guidance on what to change.
