### ISSUE TITLE
Remove References to Sanity in Combine Reducers

### ISSUE THREAD

**Issue by seanmhanson** [reactjs/redux#2334]
The file `combineReducers.js` contains language like `assertReducerSanity` and `sanityError` that is generally viewed as ableist and potentially offensive to people living with mental illness. In addition, it doesn't accurately describe what we're trying to do in this check, and using an idom like this also makes it less approachable for developers whose first language is not English.

I'll throw a PR up in a second since this is a super tiny change, but I'm proposing to call it `assertReducerShape` and describe the error as a `shapeAssertionError` so that we're more precise and more inclusive.

**Comment by timdorr** [comment]
Closing in favor of the PR you opened up. (Thanks for that!)
