### ISSUE TITLE
Reducers need to provide default value, even when using preloadedState

### ISSUE THREAD

**Issue by kengorab** [reactjs/redux#2338]
**Do you want to request a *feature* or report a *bug*?**  
Bug/unexpected behavior

**What is the current behavior?**
When the store is created, and an initial `preloadedState` is provided, reducers are called with the `@@redux/INIT` action and an `undefined` state. This causes startup to fail, unless the reducers provide default values for state. [Here's a codepen](https://codepen.io/anon/pen/yMrLzg?editors=0010) which replicates the issue.

**What is the expected behavior?**
When providing a `preloadedState`, I would expect to not need to provide a default value in my reducer, since I've already provided one in the form of `preloadedState`. I understand that this is to ensure that reducers are properly-written, in that they don't return `undefined` even when passed `undefined`. However, if a field in the store is populated using `preloadedState` and never changed, it seems silly to have to do either:

```javascript
const propReducer = (state = null, action) => state
```
or

```javascript
const preloadedState = window['__PRELOADED_STATE__']
const propReducer = (state = preloadedState.prop, action) => state
```

At the very least, I think the documentation for using preloaded state should be updated to include this, because it wasn't entirely obvious (without reading the redux source code) why I needed to provide this default when, in my mind, I already had.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**
The browser/OS/version aren't really relevant, since the unexpected behavior will occur in any scenario.

**Comment by timdorr** [comment]
> I think the documentation for using preloaded state should be updated to include this

This is the correct answer here. You always have to have a default value for a reducer's state input, such as when unit testing them individually. So, the behavior of the code is correct here, but the documentation apparently isn't.

**Comment by markerikson** [comment]
The current documentation related to handling of initial state is in http://redux.js.org/docs/recipes/reducers/InitializingState.html .  Note that this is a combination of how `preloadedState` is used, how `combineReducers` works, how reducers (and specifically slice reducers) can provide default parameters, and how Redux dispatches that `INIT` action.

**Comment by kengorab** [comment]
I think the most misleading line is this one, second paragraph under Summary on the page linked by @markerikson:

> With combineReducers() the behavior is more nuanced. Those reducers whose state is specified in preloadedState will receive that state. Other reducers will receive undefined and because of that will fall back to the state = ... default argument they specify.

I think this should include something mentioning that reducers whose state comes from `preloadedState` *still* need to provide a non-`undefined` default state.
