### ISSUE TITLE
`browser` field in `package.json`

### ISSUE THREAD

**Issue by alexfedoseev** [reactjs/redux#2345]
If next release will be published w/ [`browser` field in `package.json`](https://github.com/reactjs/redux/blob/master/package.json#L5), then webpack will be using umd build on bundling instead of `module`/`main` builds.

Webpack issue: https://github.com/webpack/webpack/issues/4674

**Comment by timdorr** [comment]
Sorry, I thought I responded to this. Must have been in my head...

But yeah, this would seem to be a problem. However, we're looking at bundling the es/cjs builds as well (#2358), so maybe it won't be an issue then?

**Comment by alexfedoseev** [comment]
> However, we're looking at bundling the es/cjs builds as well (#2358), so maybe it won't be an issue then?

@timdorr I'm afraid it's still an issue w/ default configuration of webpack. If `target` is set to `web` (default), then `browser` field takes precedence over the others.

Link: https://webpack.js.org/configuration/resolve/#resolve-mainfields

I think it makes sense to remove this field in #2358 (or I can submit another PR).

**Comment by timdorr** [comment]
I finally got rid of this. Thanks for the heads up!
