### ISSUE TITLE
Stricter typing for combineReducers

### ISSUE THREAD

**Issue by ajeffrey** [reactjs/redux#2347]
**Do you want to request a *feature* or report a *bug*?**  

Feature

Given the following code:

```ts
import {Reducer, combineReducers} from 'redux';

interface IAState {
  abc: string;
};

interface IBState {
  def: number;
};

interface IState {
  a: IAState;
  B: IBState;
};

const AReducer: Reducer<IAState> = (state: IAState, action: any) => {
  return state;
};

const BReducer: Reducer<IBState> = (state: IBState, action: any) => {
  return state;
};

const RootReducer: Reducer<IState> = combineReducers({
  a: AReducer,
});

```

**What is the current behavior?**

TypeScript does not complain about the missing `b: BReducer` in `RootReducer` because the typing for combineReducers is not strict.

**What is the expected behavior?**

The TypeScript compiler should error out because `b: BReducer` is missing.

**Solution**

If it would be possible to update the combineReducers typing to something like this:

```ts

export type ReducersMapObject<S> = {
  [K in keyof S]: Reducer<S[K]>;
}

export function combineReducers<S>(reducers: ReducersMapObject<S>): Reducer<S>;

```

... then combineReducers could be correctly enforced by the compiler. The main concern I have is that the `keyof` type is only available as of TypeScript 2.1, so it's fairly new. If there's a way to opt-in to this stricter typing, that would be super awesome as it's not possible (as far as I can tell) to override the typings set in redux's package.json without forking.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

Latest Redux, Mac OS Sierra, TS 2.2.1.

**Comment by timdorr** [comment]
Check the next branch. I believe this is already done.

**Comment by ajeffrey** [comment]
oh ok cool, I'll check it out - thanks!
