### ISSUE TITLE
Typo in documentation [../advanced/AsyncActions.md]

### ISSUE THREAD

**Issue by jamesxv7** [reactjs/redux#2351]
I just found a minor typo in the Advanced Async Actions section. Since there are a bunch of PRs in queue I would like to know if the typo can be corrected in a current PR or if a new PR is required I can work it.
![typo](https://cloud.githubusercontent.com/assets/121668/24873734/02e6de82-1df0-11e7-995e-49c82cd20170.png)

**Comment by timdorr** [comment]
A new PR is best. I don't think any open PRs overlap with that file. Even if they do, conflicts can be resolved later.
