### ISSUE TITLE
Suggested way to share state between reducers seems like an anti-pattern

### ISSUE THREAD

**Issue by JemarJones** [reactjs/redux#2356]
In the [Beyond combineReducers](https://github.com/reactjs/redux/blob/master/docs/recipes/reducers/BeyondCombineReducers.md#sharing-data-between-slice-reducers) recipe section the following is one suggested method of sharing state between reducers:

---
> Another alternative to the "shared-slice updates" issue would be to simply put more data into the action.  This is easily accomplished using thunk functions or a similar approach, per this example:

```js
function someSpecialActionCreator() {
    return (dispatch, getState) => {
        const state = getState();
        const dataFromB = selectImportantDataFromB(state);
        
        dispatch({
            type : "SOME_SPECIAL_ACTION",
            payload : {
                dataFromB
            }
        });
    }
}
```

> Because the data from B's slice is already in the action, the parent reducer doesn't have to do anything special to make that data available to `sliceReducerA`.
---

I understand this is only a suggestion, but it stands out to me as something that doesn't really reflect the methodology generally followed in Redux. As i understand it, a reducer should rely solely on the current state and an action to determine the next state. Amongst the various benefits of this methodology is that it enables us to replay actions, time travel, and remove actions from history and observe the resulting state. With the above suggestion/recipe, the ability to do this becomes fairly limited. If we were to remove an earlier action which had affected the portion of the state in `B` that we used to calculate `dataFromB`, the resulting state after `SOME_SPECIAL_ACTION` could very well differ from the state we would have if the actions had normally played in that order in the application. 

I hope my description of the issue with this suggestion is clear. I think this drawback should either be mentioned in the documentation, or the suggestion should be modified.

**Comment by timdorr** [comment]
> As I understand it, a reducer should rely solely on the current state and an action to determine the next state.

You are correct on this. But the code above is for an action creator. It runs before dispatch occurs. So, the action that results from this thunk will be replayable like normal. 

The case where it breaks on replay is actually the same thing as an async action. If you have some API you request data from that has changed it response since that action was originally dispatched, then you might end up with inconsistencies with making further actions. This is a potential problem with any time travel, as you can't know any external state at all times.

Time travel is good for debugging reducer changes, not necessarily state selection or action creator changes. That's just a fundamental limitation. What's suggested here doesn't cause any new problems, and is still a valid option for implementing your action creators.

**Comment by markerikson** [comment]
It's important to understand that the DevTools Enhancer effectively only records actions once they arrive at the reducer level, and that replaying of actions definitely occurs at the reducer level.  

Note that the `dataFromB` is being included in the action.  Therefore, by definition, if the action is being replayed, that state+action are available.  The action just contains larger amounts of information.

**Comment by JemarJones** [comment]
I suppose my point is actually more about the disadvantages of choosing to put vital state information inside of an action, rather than retrieving it from the state directly. Additionally it seems to me that `dataFromB` in this case is more about what **is** rather than what **happened**, which has always been my mental distinction between what belongs in state and what belongs in an action.

**Comment by markerikson** [comment]
This is ultimately a question of what the "right" semantics are for actions.  The Redux docs have some suggestions about that, but there's no actual rule or enforcement anywhere.  Redux doesn't care if you dispatch `"ADD_THING"` vs "`ADDED_THING"`, whether you put the entire new state in your action and spread it in the reducer or just include a couple item IDs and look up everything on the reducer side.  All Redux ultimately does is run `currentState = reducer(currentState, action)`.  

I'm actually working on a blog post that will discuss what Redux does actually require, vs what the _intended_ use of Redux is, vs what is _possible_ to do with Redux.  Pretty busy atm, so it might be a while before I can pull it together.  If you're interested, keep an eye on http://blog.isquaredsoftware.com .
