### ISSUE TITLE
dispatch() - doesn't accept object created via class

### ISSUE THREAD

**Issue by Hotell** [reactjs/redux#2361]
**Do you want to request a *feature* or report a *bug*?**  
both, kinda

**What is the current behavior?**
`dispatch` is not accepting object created via classes, because `dispatch` is using `lodash.isPlainObject` which accepts only raw `Object`s.

This is not very convenient if one want's to use Typescript powerful Discriminated Unions for reducers and create action creators as classes so we don't have to repeat definitions and implementations.

-> I'm using ng-rx patterns here, as we are using angular and react on various projects and wanna be consistent.

example:

```ts
// actions.ts
import { Book } from '../models/book';

type Action = Readonly<{
   type: string,
   payload?: any
}>
export const SEARCH =           '[Book] Search';
export const SEARCH_COMPLETE =  '[Book] Search Complete';

export class SearchAction implements Action {
  readonly type = SEARCH;

  constructor(public payload: string) { }
}

export class SearchCompleteAction implements Action {
  readonly type = SEARCH_COMPLETE;

  constructor(public payload: Book[]) { }
}

export type Actions
  = SearchAction
  | SearchCompleteAction;
```

```ts
// reducer.ts
import {Actions,SEARCH_COMPLETE} from './actions'

export interface State {
  ids: string[];
  entities: { [id: string]: Book };
  selectedBookId: string | null;
};

export const initialState: State = {
  ids: [],
  entities: {},
  selectedBookId: null,
};

export function reducer(state = initialState, action: Actions): State {
switch (action.type) {
    case SEARCH_COMPLETE:
      // action.payload will be here of type Book[] because action is narrowed to type SearchCompleteAction
      // custom logic ....
      return {/*new state*/};
}
```

then in component where I dispatch, it will fail on this error 
```js
// createStore.js
   if (!isPlainObject(action)) {
      throw new Error('Actions must be plain objects. ' + 'Use custom middleware for async actions.');
    }
```

```ts
import * as React from 'react'
import {Dispatch, connect} from 'redux'
import {SearchAction} from './actions'

type Props = {
  searchTerm: string,
  onChange: Function,
  dispatch: Dispatch
}
const Search: SFC<Props> = ({searchTerm, onChange, dispatch}) => {
  return (
    <div>
      <input value={searchTerm} onChange={{{target})=>onChange(target.value)} />
      <button 
        onClick={dispatch(new SearchAction(searchTerm))}
      >
        search
      </button>
    </div>
  )
}
export default connect()(Search)
```

**What is the expected behavior?**
Allowing objects as actions that are created via classes.

This can be fixed pretty easily 

```js
const isObject = (value) => _.isObjectLike(value) && !_.isArray(value);

 if (!isObject(action)) {
      throw new Error('Actions must be plain objects. ' + 'Use custom middleware for async actions.');
 }
```

If you're ok with that I will submit PR.

Thanks!

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**
Redux 3.6

**Comment by timdorr** [comment]
We specifically want plain objects so we don't end up passing through unintended side effects (think of passing a Proxy as an action, for instance). The reducer should get a pure input to help enforce pure functional form. There are also ancillary benefits to your tooling, including serializing actions for playback later.

Best way I can think of to approach this: Add a `toObject()` on your `Action` class and add a middleware that checks `action instanceof Action`, which returns the result of your `toObject()` method.

**Comment by Hotell** [comment]
Well my tooling benefits is strongly typed js with immutable data types.  You proposal would make things even more verbose and I don't think it would help either as the object passed to dispatch is not plain object.

What I would have to do:

```ts
class SearchAction implements Action {
  readonly type = SEARCH;

  constructor(public payload: string) { }

 // payload: string duplicate
  static create(payload: string){
     return Object.assign({},new SearchAction(payload))
  }
}
```

And dispatch like this:

```ts
dispatch(SearchAction.toObject('hello'));
```

but I understand your point of view ofc,

anyway, thx for quick response

**Comment by markerikson** [comment]
Middleware can intercept dispatched values and choose to not pass them onwards.  So, it's entirely legal to pass non-plain-object values to `dispatch`, _if_ a middleware is going to intercept them.  This is how `redux-thunk` works - it looks for functions being passed to `dispatch`, and if it sees one, executes it but does _not_ pass it onwards.

Also, by having a centralized middleware handling that process, it might be possible to write a generic "convert a class to an action" function, and only have to implement it in one place.

**Comment by Hotell** [comment]
yeah right @markerikson I will do that, thx again

**Comment by kosz** [comment]
```
dispatch({ ...new MyAction() })
```
seems to work to quickly overcome this imposed limitation :) 

I tend to agree that not using new and class is a good thing in javascript but as far as action classes go, I find the ngrx pattern quite strong

**Comment by voroninp** [comment]
I also hit this issue, so I [made middleware](https://github.com/voroninp/RandomNotes/blob/master/How%20to%20dispatch%20actions%20which%20are%20instances%20of%20classes.md) both for redux and saga.
