### ISSUE TITLE
TypeScript Reducer definition doesn't allow for undefined state

### ISSUE THREAD

**Issue by etreworgy** [reactjs/redux#2364]
**What is the current behavior?**
Currently Redux defines a Reducer as:
`type Reducer<S> = <A extends Action>(state: S, action: A) => S;`

The issue is that `undefined` is a valid/expected value to be passed in for `state` when the reducer is being initialized.  

From the docs:
> Redux will call our reducer with an undefined state for the first time. This is our chance to return the initial state of our app

This causes TypeScript compilation issues if I want to call the reducer manually with `undefined` as in this made up example:
```
const myReducerWrapper = <S>(reducer: Reducer<S>) => {
  const initialState = reducer(undefined, {type: 'INITIALIZE'});
  return (state: S, action: Action) => {
    if (state === undefined) {
      return { init: initialState };
    }
    return Object.assign({ init: initialState }, wrapReducerLogic(state, action));
  };
};
```

The compiler will give you the following error on the second line (`reducer(undefined, ...)`):
`[ts] Argument of type 'undefined' is not assignable to parameter of type 'S'.`

**What is the expected behavior?**
The definition should account for this valid usage of a reducer:
`type Reducer<S> = <A extends Action>(state: S | undefined, action: A) => S;`

**Comment by timdorr** [comment]
Already fixed on next: https://github.com/reactjs/redux/blob/next/index.d.ts#L46
