### ISSUE TITLE
Middleware logging order is wrong

### ISSUE THREAD

**Issue by pkl** [reactjs/redux#2365]
**bug**  

_Usual disclaimer:_ This could be a bug or just me being an idiot.

Dispatch calls wrapped in setTimeout (and async thunks) are logged after console.log entries in the component lifecycle methods using Chrome debugging.

**What is the current behavior?**

Redux logger middleware logs the action **after** console.log entries in the component lifecycle methods.

```
componentDidMount() {
  setTimeout(() => {
    this.props.dispatch({
      type: 'APP_NAME',
      name: 'app1',     
    })
  }, 2000);
}

componentDidUpdate() {
  console.log('Well, hello there ' + this.props.appName + ' ' + Moment().format("HH:mm:ss.SSS"));
}

const mapStateToProps = (state) => {
  return {
    appName: state.app.name,
  };
};

export default connect(mapStateToProps)(App);

```

Log (notice the timestamps are correct, but in wrong order):

```
Well, hello there app1 11:04:27.769 <<<<< componentDidUpdate
> action **APP_NAME** @ 11:04:27.759 (in 13.60 ms) <<<<< Logger middleware
```

**What is the expected behavior?**

Redux logger middleware should log the action **before** console.log entries in the component lifecycle methods.

**Redux 3.6.0 - React Native 0.43.3 - Redux Logger 3.0.1**

This also happes when I roll my own logger, so it's probably not a bug in Redux Logger.

**Comment by markerikson** [comment]
I'm sorry, but this is definitely _not_ a bug in Redux, on several accounts.

First, `redux-logger` is a separate library maintained by someone else, not part of the Redux core itself.

Second, the implementation of any given middleware is entirely up to that author.  Looking at [the relevant lines of code in `redux-logger`](https://github.com/evgenyrodionov/redux-logger/blob/385f41ce403f721212ef1cdc8d40249309fdd51b/src/index.js#L86-L107), the author chose to do logging _after_ the action has been sent onwards through the dispatch chain, when the result is on its way back out the call stack.

Third, it's entirely likely that the rendering process is synchronous, so by delaying the dispatch behavior, the entire component lifecycle is almost definitely going to execute before the dispatch happens.

I'm afraid I really don't understand what the desired intent is here, and whatever it is, it's not a bug.
