### ISSUE TITLE
Build Output totally managed by Rollup

### ISSUE THREAD

**Issue by rockchalkwushock** [reactjs/redux#2379]
## Build Implementation (Feature?)

I recently migrated my oss project from `webpack` to `rollup` just to play with this tech and was pretty impressed with it! I saw that `redux` is using `rollup` for bundling the browser scripts & `babel` handles the build/output of the `cjs` & `es` distributions. After some research and tinkering I was able to make a `rollup.config.js` that will output all of these distributions in one shot just calling `rollup -c`.

I'm more than willing to look into migrating the `redux` build process to be totally handled by `rollup` if that is something the maintainers feel would be a direction they want to go in for bundling and distributing the product.

The configuration I came up with can be found [here](https://github.com/rockchalkwushock/how-to-open-source/blob/master/rollup.config.js). Of course the config does not use `rollup-plugin-node-resolve` or `rollup-plugin-commonjs` plugins since my project has no external libraries to bundle like `redux` does; but from my reading it is not difficult to add this to the process with the aforementioned plugins.

Thanks for the wonderful product!

**Comment by TrySound** [comment]
@rockchalkwushock We are on this way [here](https://github.com/reactjs/redux/pull/2358)

**Comment by rockchalkwushock** [comment]
@TrySound thanks for the reference! Definitely learned a lot reading through the discussion. Closing.
