### ISSUE TITLE
Unify the code style of documentation

### ISSUE THREAD

**Issue by CodinCat** [reactjs/redux#2381]
Just noticed that the code style of documentation is very inconsistent.

Some indent with 2 spaces, while some use 4; some use semicolons and some not. For example:

2 spaces, no semi: http://redux.js.org/docs/basics/Reducers.html
2 spaces, semi: http://redux.js.org/docs/recipes/reducers/InitializingState.html
4 spaces, semi: http://redux.js.org/docs/recipes/reducers/ImmutableUpdatePatterns.html
...

The uses of spaces are also inconsistent. Like `colon : 'foo'` and `colon: 'foo'` etc.

It would be good to choose one style and unify the documentation. Maybe prettier can do this job, but we still need to choose something like semi and trailing comma.

**Comment by timdorr** [comment]
The docs are all in Markdown, so enforcing style in code blocks is much harder there. I don't know if there is tooling for this yet.

A PR would be the best way to get these things fixed up.

**Comment by CodinCat** [comment]
I'd be happy to send a PR. I can write a small script to apply prettier to the docs (some still need to be handled manually), but I need a style. It seems that the style which is being used most in the current docs is 2 spaces and no semi. I'll just go for this style now. If you have other ideas just let me know, thanks!
