### ISSUE TITLE
Wrong redirection to React Router API

### ISSUE THREAD

**Issue by wyeo** [reactjs/redux#2395]
Hi,

In [UsageWithReactRouter section](http://redux.js.org/docs/advanced/UsageWithReactRouter.html#) we have a redirection react-router api documentation but is not the good url

It's ok on redux documentation page but not on the site

**Comment by timdorr** [comment]
I just need to publish the gitbook again. I'll get that done after we get the prettier PRs merged in.

**Comment by wyeo** [comment]
👍🏿
