### ISSUE TITLE
[Discussion] Share your repeated patterns

### ISSUE THREAD

**Issue by brigand** [reactjs/redux#2402]
I'd like to build a library that abstracts common patterns, e.g. the variations on pagination, and simple collection reducers with loading states. It's **not** going to be primarily yet another alternative syntax for writing reducers, et al. It's about high level abstractions for repeated and/or bug prone code with reducers, thunks/sagas, and selectors.

My experience only goes so far, so I want to collect feedback from other people. Any patterns you notice in your own projects are valuable, even if it seems small.

Also any prior work in this area is appreciated.

Thanks!

**Comment by markerikson** [comment]
For prior art, check out my [Redux addons catalog](https://github.com/markerikson/redux-ecosystem-links).

In particular, see the sections for [Entity/Collection Management](https://github.com/markerikson/redux-ecosystem-links/blob/master/entity-collection-management.md), [Prebuilt Use Cases](https://github.com/markerikson/redux-ecosystem-links/blob/master/use-cases.md), [Reducers](https://github.com/markerikson/redux-ecosystem-links/blob/master/reducers.md), and [Action/Reducer Generation](https://github.com/markerikson/redux-ecosystem-links/blob/master/action-reducer-generators.md).

**Comment by TrejGun** [comment]
@brigand 
Hey man! nice idea
please take a look at this two libs
https://github.com/Versent/redux-crud
https://github.com/Versent/redux-loader
if you can take the best from them and create something that has both crud operations and smart pagination support it would be awesome

**Comment by dnutels** [comment]
Without implying that you don't need to do this: https://github.com/xgrommx/awesome-redux

**Comment by timdorr** [comment]
Looks like we have enough good links to work with. I'm going to close this out and you can browse through those (very extensive!) materials.

**Comment by brigand** [comment]
Thanks all!
