### ISSUE TITLE
Store does not detect state change and connected react component is not rerendered

### ISSUE THREAD

**Issue by mass85** [reactjs/redux#2406]
I use redux 3.5.2 and react-redux 4.4.2. It turns out that redux store detects a state change only when reducer returns completely brand new object. `Object.assign({}, state)` and object spread with later assignment do not work, although comparison of old and new state returns false.
```
import moment from 'moment';

import { getStateProto } from '../utils/toolbox';
import { TYPES } from '../actions/dateTimeActions';

const addSecond = (dateTimeJson) => {
  let time = moment(dateTimeJson);
  time.add(1, 'second');
  return time.toJSON();
};

const dateTime = (state, action) => {

  if (!state) {
    state = getStateProto();
  }

  switch (action.type) {

    case TYPES.DATE_TIME_GET_SUCCESS:
      return getStateProto(action.payload);

    case TYPES.DATE_TIME_GET_LOADING:
      return getStateProto(state.data, true);

    case TYPES.DATE_TIME_GET_ERROR:
      return getStateProto(state.data, false, true);

    case TYPES.DATE_TIME_SECOND_ELAPSED:
      //const newState = {...state};
      const newState = Object.assign({}, state);
      newState.data.currentDateTime = addSecond(state.data.currentDateTime)

      // the below works
      // newState.data = {
      //   ...state.data,
      //   currentDateTime: addSecond(state.data.currentDateTime)
      // };

      console.log(newState == state); // false
      return newState;

      // the below works
      // return {
      //   ...state,
      //   data: {
      //     ...state.data,
      //     currentDateTime: addSecond(state.data.currentDateTime)
      //   }
      // };

    default:
      return state;
  }

};

export default dateTime;
```
State object looks like:
```
{
    data: {
      currentDateTime: '2017-05-15T14:45:39.142Z',
      localTimezone: 'Europe/Warsaw'
    },
    loading: false,
    error: false
 }
```

**Comment by jimbolla** [comment]
This line:
```
newState.data.currentDateTime = addSecond(state.data.currentDateTime)
```
is mutating the original state's `data` object which is improper. Your commented out code is the correct way to do it.

**Comment by mass85** [comment]
How does redux detect state change? Does it iterate through all object properties instead of comparing objects?

**Comment by jimbolla** [comment]
The Redux store doesn't. It just updates the state to whatever your reducer gives it. The React Redux connector works like this:
On notifications from `store.subscribe` (after every action):
* Compare current store state to previous using strict equals (===).
* If different, run your `mapStateToProps` et al.
* Compare current results to previous snapshot using shallow equals.
* If different, rerender.

When you directly mutate your store state's child objects, you're also mutating the snapshots used by connect() to avoid re-renders. This prevents it from properly detecting state changes.

**Comment by markerikson** [comment]
@mass85 : you may want to read the [Redux FAQ on use of immutable data](http://redux.js.org/docs/faq/ImmutableData.html), which discusses where and why Redux relies on immutability.  I also talked about this topic some in my recent blog post [Idiomatic Redux: The Tao of Redux, Part 1 - Implementation and Intent](http://blog.isquaredsoftware.com/2017/05/idiomatic-redux-tao-of-redux-part-1/).
