### ISSUE TITLE
Is it a good practice to update the state dynamically based on the payload?

### ISSUE THREAD

**Issue by firaskrichi** [reactjs/redux#2409]
Is it a good practice to update the state dynamically based on the payload. 

Something like this : {...state, ...action.payload.data} 

Where if payload = {userName : "John"} only the userName will be changed in the store without having to specify it explicitly.

**Comment by timdorr** [comment]
Sure, you can do that. Your state shape and reducers can be whatever you want them to be, so long as they are pure functions.
