### ISSUE TITLE
Documentation "Example: Reddit API" AsyncApp's dispatch property

### ISSUE THREAD

**Issue by liushigit** [reactjs/redux#2410]
## No explicit initialization of the `dispatch` prop in `AsyncApp`

In the [`containers/AsyncApp.js`](http://redux.js.org/docs/advanced/ExampleRedditAPI.html) code listing, there's no explicit initialization of the `dispatch` property.

The component won't work without the `dispatch` property being defined.

In the doc there should be something like the following to make `dispatch` available:

    function map_dispatch_to_props(dispatch) {
      return {
        dispatch
      }
    }

Or did I miss something?

**Comment by jimbolla** [comment]
If no value for `mapDispatchToProps` is given, the default behavior is to inject `dispatch`.

**Comment by liushigit** [comment]
Oh it's mentioned here: https://github.com/reactjs/react-redux/blob/master/docs/api.md
