### ISSUE TITLE
[Questions] Is creating store inside Main component safe? 

### ISSUE THREAD

**Issue by mbm-rafal** [reactjs/redux#2412]
I'm pushing server's session state to component via properties (just to not maintain any global variable) so the case is that I want to use this.props.initialState same time creating store.

Is this safe in terms of state access / performance ? 

```
export default class __ extends Component {
  render() {
    return (
        <Provider store={createStore(combineReducers({
          intentions,
          categories,
          questions,
          fetching,
          initialized,
          saving
        }), this.props.initialState || {}, composeEnhancers(
            applyMiddleware(ReduxThunk),
            applyMiddleware(promiseMiddleware)
        ))}>
          <Manager {...this.props} />
        </Provider>
    );
  }
}
```

**Comment by timdorr** [comment]
It can be, but it's limiting. Getting access to it outside of your component tree is tough (or at least non-intuitive) and if you ever end up re-rendering that component, things will blow up in your face.
