### ISSUE TITLE
*SOLVED* dispatch action called once but handled in reducer twice

### ISSUE THREAD

**Issue by mprey** [reactjs/redux#2421]
**What is the current behavior?**

Hello, I've been trying to figure out why two different actions are being handled in the reducer while the action is only being called once. The action is being dispatched from a socket.io callback that is established in the componentWillMount function in a component, and then it is reduced twice for no apparent reason.

Here is the output of the console with redux-logger: https://i.stack.imgur.com/MWmft.png

```javascript
componentWillMount() {
  console.log('component is mounting')
  this.props.secureSocket.on('RECEIVE_CHAT', (data) => {
    console.log('got a socket message')
    this.props.receiveChat(data)
  })
}
```
^ this catches the socket's action from the api and dispatches the action accordingly, only firing one time

```javascript
componentWillUnmount() {
  console.log('unmounting')
  this.props.secureSocket.off('RECEIVE_CHAT')
}
```
^ this removes the listener from socket.io when the component is unmounted

```javascript
const mapDispatchToProps = (dispatch) => {
  return bindActionCreators({
    sendChat,
    receiveChat
  }, dispatch)
}
```
^ this is how the prop is binded to dispatch

```javascript
export function receiveChat(object) {
  console.log('action called')
  return {
    type: RECEIVE_CHAT,
    payload: object
  }
}
```
^ this is the action being dispatched

```javascript
export default function reducer(state = initialState, { type, payload }) {
  switch (type) {
  ...
  case RECEIVE_CHAT:
    console.log('RECEIVED CHAT')
    return update(state, {
      messages: {
        $push: [payload]
      }
    })
  ...
  }
}
```
^ this is how the action is being reduced, but it is being called twice

thanks for all the help. I've tried a lot of different things but to no avail.

**What is the expected behavior?**

The action should fire once and be handled in the reducer once

**Comment by Bruce-li-92** [comment]
Can you post your solution to solve this problem?

**Comment by artemik** [comment]
If it's renamed to SOLVED, where is the solution?
