### ISSUE TITLE
Add helpful console warning for dispatching an undefined action

### ISSUE THREAD

**Issue by petrgazarov** [reactjs/redux#2436]
### Feature request

Hi, great work with the library!
I worked on a bug recently where action was bound by `bindActionCreators` twice accidentally, and this produced a very strange error in the middleware where `action` was `undefined`, which was hard to debug.

I can't think of a scenario where you would want to dispatch an `undefined` action, so it would be helpful to output a warning message to console in that case.

**Comment by timdorr** [comment]
Unfortunately, this is up to your middleware to handle. [We check for this in `dispatch`](https://github.com/reactjs/redux/blob/master/src/createStore.js#L150), but that will occur after running through your middleware.

**Comment by petrgazarov** [comment]
@timdorr Makes sense. Thanks for your answer
