### ISSUE TITLE
Initializing third party plugin throwing error

### ISSUE THREAD

**Issue by apurvgandhwani** [reactjs/redux#2440]
I am trying to use third party plugins like bootstrap-tagsinout and noUiSlider in my react application. I have installed the libraries via npm to my package.json. Currently I am initializing the plugins in my componentDidMount method. This is how I do it

```
componentDidMount = () => {

        $(document).ready(function() {
            $('#tagsinput').tagsinput({
                typeahead: {
                    source: ['Smoking, Drinking, Eating']
                }
            });
        });

        $(document).ready(function() {
            // Apply the plugin to the element
            $("#noUiSlider").noUiSlider({
                start: 40,
                connect: "lower",
                range: {
                    'min': 0,
                    'max': 100
                }
            });
        });
```

But this gives me an error saying 

` Uncaught TypeError: $(...).tagsinput is not a function`

I tried 'refs' way also

 ```
var textInput;

<input id="#tagsinput" type="text"  ref={(input) => {textInput = input; }}  value="Smoking,Drinking" data-role="tagsinput"/>

textInput.tagsinput({
                typeahead: {
                    source: ['Smoking, Drinking, Eating']
                }
            });
```

**Comment by timdorr** [comment]
Sorry, but this doesn't have anything to do with Redux. It looks like you're trying to use a jQuery plugin inside of React, which isn't going to be a good combination. I would look into a React version of the same thing.
