### ISSUE TITLE
Higher Order Store

### ISSUE THREAD

**Issue by Vasikaran** [reactjs/redux#2444]
What is the Higher Order Store? Can anyone please explain it? Or you have any documentation, please share with me.

**Comment by TrySound** [comment]
@Vasikaran It's called also enhancer. Such function takes store and returns new one wrapped with some new functionality.

**Comment by laumair** [comment]
This might help: https://github.com/reactjs/redux/blob/cdaa3e81ffdf49e25ce39eeed37affc8f0c590f7/docs/higher-order-stores.md

**Comment by Vasikaran** [comment]
I can't understand what they were told. Do you have any simple example? @lacker .
Thanks @TrySound.
