### ISSUE TITLE
createLogger usage different in documentation

### ISSUE THREAD

**Issue by haani104** [reactjs/redux#2447]
Hi,

On http://redux.js.org/docs/advanced/ExampleRedditAPI.html#, below is how the createLogger is imported.
![screen shot 2017-06-11 at 3 59 14 pm](https://user-images.githubusercontent.com/6011865/27010332-d7ae849e-4ebf-11e7-8ca5-7895daa867e9.png)

If I use like above I get below error

![screen shot 2017-06-11 at 4 00 15 pm](https://user-images.githubusercontent.com/6011865/27010347-fbbd5e50-4ebf-11e7-8329-e059adc6a25b.png)

The correct way for it is 
```
import { createLogger } from 'redux-logger'
```

I went to create a PR for this, however the code on https://github.com/reactjs/redux/blob/master/docs/advanced/ExampleRedditAPI.md is already up to date with the above, i.e.
![screen shot 2017-06-11 at 4 00 38 pm](https://user-images.githubusercontent.com/6011865/27010371-694f708e-4ec0-11e7-819f-51027dbb3ba8.png)

So, I guess the latest documentation hasn't been published yet, please let me know if I am correct on this.

Thanks

**Comment by timdorr** [comment]
Yes, I simply haven't published this change yet. It was a change in their last major version.
