### ISSUE TITLE
Connect breaks react router 4

### ISSUE THREAD

**Issue by wichert** [reactjs/redux#2456]
I have a basic App component that uses a HashRouter. As soon as I wrap that with connect routing no longer works: any attempt to change the route will not trigger a render. [Here is a small codepen demonstrating the problem](https://codepen.io/wichert/pen/rwyWWQ). For the test I used a trivial connect call:

```javascript
App = connect(
  () => ({}),
)(App)
```

If I comment out those lines routing works correctly.

Relevant versions:

* React 15.4.2
* Redux 3.7.0
* React redux 5.0.5
* React router 4.1.1

Verified with Safari and Chrome.

**Comment by timdorr** [comment]
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/redux.md
