### ISSUE TITLE
bindActionCreators expected a function actionCreator for key 'SET_STRING', instead received type 'string'.

### ISSUE THREAD

**Issue by johhansantana** [reactjs/redux#2458]
I haven't got this error but I think since the new `3.7.0` release this is poping up.

```javascript
export const SET_STRING = 'SET_STRING';
/**
 * sets the string, if none is passed, it will default to the below string.
 * @param theString
 * @return {{type: string, theString: string}}
 */
export function setString(theString: string = 'the default string') {
  return {
    type: SET_STRING,
    theString
  };
}
```

This seems a pretty regular redux action no? What I'm doing wrong?

**Comment by Florian-R** [comment]
See #2279

**Comment by johhansantana** [comment]
@Florian-R I see what they explain there but I'm not sure how to fix it

in my container I have this
```javascript
import { connect } from 'react-redux';
import { bindActionCreators } from 'redux';
import * as demoActions from '!/actions/demoActions';

...

function mapStateToProps(state) {
  return {
    demoString: state.demoString
  };
}

function mapDispatchToProps(dispatch) {
  return bindActionCreators(demoActions, dispatch);
}

export default connect(mapStateToProps, mapDispatchToProps)(Home);
```

**Comment by elrumordelaluz** [comment]
@johhansantana Seems you have stuff `export`ed at `'!/actions/demoActions'`that aren't `functions`. Try importing only the _action creators_ from the file.

[Here](https://stackoverflow.com/questions/44630850/bindactioncreators-expected-a-function-actioncreator-for-key-account-login-in/44631893#44631893) is a similar question I asked on SO.

**Comment by johhansantana** [comment]
@elrumordelaluz oh I see, so instead of `import * as actions` just import specific actions and in the `bindActionCreators` do
`return bindActionCreators({action1, action2, action3}, dispatch);`

Right? a big app would be annoying to fix, maybe change it to a `warning` instead?

**Comment by Anishmprasad** [comment]
Try this

```
import { action1,action2, … } from '../action'
// component
export default connect(mapStateToProps,{
  action1,
  action2,
  …
})(component);
```

**Comment by timdorr** [comment]
This is a legit warning. You're attempting to pass in non-functions to bindActionCreators, which can have unexpected results. It's akin to React's change to not accept any unknown props on DOM-backed elements (e.g., `<div foo="bar">` will generate a warning now).

You'll need to be more explicit about your imports and input to the function. This is a good practice regardless, as you're not expecting Redux to clean up after you. Also, most type systems (TS, Flow) should catch this for you already (prior to this version too). It's just a good practice.

**Comment by CameronAckermanSEL** [comment]
I take issue with the attitude that "best practice" recommendations can just be changed willy nilly with no regard to backwards compatibility or what the tool is advertising as best practice in its own documentation. We've locked to 3.6.0 but this has just created a lot of needless work without much warning.

**Comment by timdorr** [comment]
Reverted and pushed out in 3.7.1. Thanks for the feedback everyone!
