### ISSUE TITLE
'Is not defined' errors in counter example

### ISSUE THREAD

**Issue by dimitri-a** [reactjs/redux#2459]
When I run npm start in the redux\examples\counter I get :

Failed to compile.

./src/components/Counter.js
  Line 5:   'propTypes' is not defined       no-undef
  Line 11:  'incrementIfOdd' is not defined  no-undef
  Line 17:  'incrementAsync' is not defined  no-undef

Any ideas?

**Comment by yaempioy** [comment]
1. Add constructor code follow.
```
constructor (props) {
    super(props)
    this.incrementIfOdd = this.incrementIfOdd.bind(this)
    this.incrementAsync = this.incrementAsync.bind(this)
  }
```
2. Change code function follow.
```
incrementIfOdd () {
    if (this.props.value % 2 !== 0) {
      this.props.onIncrement()
    }
  }

  incrementAsync () {
    setTimeout(this.props.onIncrement, 1000)
  }
```

**Comment by timdorr** [comment]
A PR would be best to get this fixed.

**Comment by Krizzu** [comment]
Hey,

Also, to get rid of `propTypes is not defined`, we could add prop checking to a class, like this:

```
Counter.propTypes = {
  value: PropTypes.number.isRequired,
  onIncrement: PropTypes.func.isRequired,
  onDecrement: PropTypes.func.isRequired
}
```

I can send a PR for this fix
