### ISSUE TITLE
bindActionCreators prints a console warning due to __esModule key in imported actions object

### ISSUE THREAD

**Issue by thom-nic** [reactjs/redux#2460]
**Do you want to request a *feature* or report a *bug*?**  

Bug.

**What is the current behavior?**

Since v3.7,  `bindActionCreators()` emits a warning if it is passed a non-function value.  It seems when using the es6 imports like `import * as someActions from './someModule'` the returned object includes an `__esModule: true` property when transpiled to es5 with webpack/ babel.  This triggers the console warning from `bindActionCreators()`.

One can work around the problem by not using `import * ...` however this form shows up a lot in redux's own documentation.

**What is the expected behavior?**

No console warning when passing action creators to `bindActionCreators()`

Suggest adding a `if( key === '__esModule' ) continue;` to the [for loop in bindActionCreators.js](https://github.com/reactjs/redux/blob/v3.7.0/src/bindActionCreators.js#L44)

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

v3.7.

**Comment by timdorr** [comment]
This an artifact of Babel transpilation. You should [turn on `strict` mode for modules](https://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/#optionsstrict), or select specific exports from your actions module.
