### ISSUE TITLE
bindActionCreators should support a nested object of action creators

### ISSUE THREAD

**Issue by DannyDelott** [reactjs/redux#2462]
Currently, you can import all items in a file and pass them to `bindActionCreators`.

```js
import { connect } from 'react-redux';
import { bindActionCreators } from 'redux';
import * as actionCreators from './path-to-action-creators';

export const FooComponent = props => { ... };

export default connect(null, dispatch => ({
  actions: bindActionCreators(actionCreators, dispatch),
})(FooComponent);
```

However this only works if the `actionCreators` object is a single-level deep object of functions.

**`bindActionCreators` should support a nested object tree, binding all the leaves that are functions to the `dispatch` method.** 

This gives us the flexibility to continue using the import strategy above, while using factories in our action creator files, eg:

```js
// A function that accepts an action type prefix string and 
// returns an object with a load, success, and fail action creator inside it
import { makeAsyncActionCreators } from './some-helper-file';

// This function will be bound properly via `bindActionCreators`
export function fooActionCreator() {
  return { type: 'foo' };
}

// This object causes `bindActionCreators` to throw the warning:
// "bindActionCreators expected a function actionCreator for key ‘asyncActionCreators’,
// instead received type ‘object’."
export const asyncActionCreators = makeAsyncActionCreators('asyncFoo');
// {
//    load: Function,
//    success: Function,
//    fail: Function,
//  }
```

I think it still makes sense to throw warnings on items that aren't functions, however objects containing functions should still work.

**Comment by timdorr** [comment]
Unfortunately, this would likely cause more problems than it solves. Especially for those using the "ducks" pattern of bundling types, action creators, and reducers in a single file. Or anyone that might be passing in an object to bindActionCreators unintentionally. We just reverted the warning around this because it was being hit a lot, so obviously people are doing it a lot...
