### ISSUE TITLE
[Question] About renderToggleAll

### ISSUE THREAD

**Issue by katopz** [reactjs/redux#2465]
I'm curious, What's this line for https://github.com/reactjs/redux/blob/master/examples/todomvc/src/components/MainSection.js#L69 ?

Even I delete that line, it still functional as expected, Thanks.

**Comment by markerikson** [comment]
Looking at the example, it appears to render a "Toggle All" checkbox above the main todos list.

**Comment by katopz** [comment]
@markerikson Maybe only me but I can't see any "Toggle All" checkbox there?

![screen shot 2017-06-21 at 23 29 25](https://user-images.githubusercontent.com/97060/27395295-80c3bf4c-56d9-11e7-8a15-977d8d8aa6e1.png)

Thanks

**Comment by markerikson** [comment]
I haven't tried running the example myself, I'm just telling you what the function appears to do.
