### ISSUE TITLE
Improve action and action creator logic

### ISSUE THREAD

**Issue by artalar** [reactjs/redux#2466]
Hi! Separation of "action" and "action creator" on two different entities seems strange to me.
Why (by performance and code style) not do so:

```javascript
// actions/index.js
export const setItem = item => {
  return {
    type: setItem,
    item
  }
}

// reducers/index.js
import {setItem} from '../actions'
const reducer = (state, action) => {
  switch(action.type){
    case setItem:
    return {...state, ...action.item}
}}
```
I think it looks better and is more understandable. In addition, it saves memory and reduces possible errors (by removing constants and their copypaste).

**Comment by markerikson** [comment]
This is a usage question, and not an actual bug or feature request with the library.

You are not required to use action creators, and the `type` field _can_ be anything, but types _should_ be serializable, and are generally strings for readability.

You may want to read the following articles for more information on the intent and design behind Redux and its common usage:

- http://redux.js.org/docs/faq/Actions.html#actions-string-constants
- http://blog.isquaredsoftware.com/2016/10/idiomatic-redux-why-use-action-creators/
- http://blog.isquaredsoftware.com/2017/05/idiomatic-redux-tao-of-redux-part-1/
- http://blog.isquaredsoftware.com/2017/05/idiomatic-redux-tao-of-redux-part-2/
