### ISSUE TITLE
Bug in redux-form

### ISSUE THREAD

**Issue by LilienfaLi** [reactjs/redux#2480]
**Do you want to request a *feature* or report a *bug*?**  
Report a bug.

**What is the current behavior?**
No focus is obtained for the redux-form when application is used in Firefox. Works OK in Google Chrome.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
The current behavior is a bug. When I open the page of my application, the form is not focussed in Firefox. This is not the case in Google Chrome. 

**What is the expected behavior?**
Focus on redux-form

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**
OS: Linux
Browser: Firefox 
Redux: 6.5.0 , updating to 6.8.0 did not resolve this issue.

**Comment by gaearon** [comment]
Please report this to `redux-form`: https://github.com/erikras/redux-form/issues/new
This project has no relation to Redux.
