### ISSUE TITLE
Missing commit 

### ISSUE THREAD

**Issue by alerd** [reactjs/redux#2482]
This https://github.com/reactjs/redux/commit/0de7e5bf8f451359d4ad84cdd310cac358419c24 is not in production

And also you are missing "payload?" in interface action

**Comment by alerd** [comment]
I am getting error with 
 @types/react-router-redux@5.0.3
@types/redux@3.6.31
typescript 2.4.1

**Comment by timdorr** [comment]
Yes, that hasn't been released yet. We don't push directly from master to npm. Everything is versioned.
