### ISSUE TITLE
PR #2467 breaks TS interface inheritance

### ISSUE THREAD

**Issue by lukescott** [reactjs/redux#2483]
**Do you want to request a *feature* or report a *bug*?**  

Bug

```ts
export default mapHandlers<SingleChoice>({
	select(state, {value}: SelectAction) {
		return input(state, value)
	},

	reset(state) {
		return input(state, "")
	},

	validate(state) {
		return input(state, state.value)
	},

```

```ts
import {Action, Reducer} from "redux"

export type HandlerMapObject<S> = {
	[name: string]: Reducer<S>
}

export default
function mapHandlers<S>(
	handlers: HandlerMapObject<S>,
	defaultReducer?: Reducer<S>
): Reducer<S> {
	return (state, action) => {
		const reducer = handlers[action.type] || defaultReducer
		if (reducer !== undefined) {
			return reducer(state, action)
		}
		return state
	}
}
```

<img width="222" alt="screen shot 2017-06-29 at 1 59 30 pm" src="https://user-images.githubusercontent.com/486224/27707737-a8ba06c8-5cd3-11e7-9274-19b4f8816db3.png">

**What is the current behavior?**

```
Argument of type '{ select(state: SingleChoice, { value }: SelectAction): SingleChoice; reset(state: SingleChoice):...' is not assignable to parameter of type 'HandlerMapObject<SingleChoice>'. Property 'select' is incompatible with index signature. Type '(state: SingleChoice, { value }: SelectAction) => SingleChoice' is not assignable to type 'Reducer<SingleChoice>'. Types of parameters '__1' and 'action' are incompatible. Type 'AnyAction' is not assignable to type 'SelectAction'. Property 'value' is missing in type 'AnyAction'.
```

**What is the expected behavior?**

No errors.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

master - error
3.7.1 - works

This was caused by PR #2467

**Comment by lukescott** [comment]
Looks like there is an issue with the `<A extends Action>` part, but this works:

```ts
export type Reducer<S> = (state: S, action: Action) => S
```

**Comment by timdorr** [comment]
What version of TS are you using?

**Comment by lukescott** [comment]
@timdorr 2.4.1. Sorry, I had some information incorrect. I updated the original issue.

**Comment by lukescott** [comment]
Gah, sorry. I actually got it to work with AnyAction. I broke something while trying to debug the original issue I was having, which was related to the TypeScript version.

Either of these work as well though:
```ts
export type Reducer<S> = (state: S, action: Action) => S
```

```ts
export type Reducer<S, A extends Action = Action> = (state: S, action: Action) => S
```
