### ISSUE TITLE
Typescript definition for compose is too "tight"

### ISSUE THREAD

**Issue by tomitrescak** [reactjs/redux#2484]
**Do you want to request a *feature* or report a *bug*?**  

Not sure ... neither.

**What is the current behavior?**

The compose definition expects to tightly define the input parameters of next composed function as output parameters of a previous function.

That is if I compose A, B, C ... in(B) = in(A) + out(A) and in(C) = in(B) + out(B).
While this makes a lot of sense it introduces a very tight definition that is often not desired in compositions, when I do not care for such tight relationships.

A good example is composition of graphql queries where using `react-apollo` package I can define higher order components that retrieve data for component.

Example:

```
// I define these general functions
import { graphql } from 'react-apollo';
const withData1 = graphql(...);
const withData2 = graphql(...);
const withData3 = graphql(...);
const withData4 = graphql(...);

// now anytime I need to bring the data into the component I can use composition.

const componentWithData1 = compose(withData1, withData2)(SomeView);
const componentWithData2 = compose(withData2, withData1)(SomeView);
const componentWithData3 = compose(withData1, withData2, withData4)(SomeView);
```

I hope that from this example is clear that using such tight definition of compose will just not do, as the partially composed functions will fail with in(X+1) = in(X) + out(X) condition.

Instead, how about using following constraints (sorry for the meta language):

```ts
// note the independence of composed functions
// example is for three functions only
compose(f1: (a) => B, f2: (c) => D, f3: (e) => F): (props: a & Partial<c> & Partial<e>) =>G
```

I'm not a typescript expert so probably my proposal is wrong, but I hope I explained the problem.
Thanks.

**Comment by aikoven** [comment]
I'm not sure `Partial` would work with primitives.

Also, in some cases TS allows you to pass objects with extra properties. For example, this would fail:

```ts
declare function a(arg: {a: number}): {a: number};

a({a: 1, b: 2});  // error
```

But this would work:

```ts
declare function a(arg: {a: number}): {a: number};
declare function b(arg: {a: number, b: number}): {a: number, b: number};

compose(a, b)({a: 1, b: 2})
```

Here function `b` returns an object with props `a` and `b`, which is passed to function `a` with no error.

**Comment by tomitrescak** [comment]
Since you closed this, I guess overriding manualy the compose definition is the only way to go.
