### ISSUE TITLE
Can not find completeAll checkbox in todomvc

### ISSUE THREAD

**Issue by kennylbj** [reactjs/redux#2488]
Here is the result of redux's todomvc demo comparing to todomvc official demo (http://todomvc.com/examples/react/)
![image](https://user-images.githubusercontent.com/6435874/27767086-5c370878-5f1c-11e7-97f1-15a88e090776.png)
![image](https://user-images.githubusercontent.com/6435874/27767095-cf54c5de-5f1c-11e7-8ac3-7af1d4f8c565.png)
As we can see, redux's demo is lack of checkbox.

**Comment by timdorr** [comment]
Perhaps todomvc.com updated to include that? It would be a good addition, if you want to put together a PR for it.

**Comment by markerikson** [comment]
I think the complaint is that _Redux_'s UI doesn't include that checkbox.  Someone (same person?) was asking about the function that renders it the other day, and also said it wasn't actually rendering anything visible.

**Comment by kennylbj** [comment]
@markerikson Yes, Redux's todomvc is designed to have this component. However, the 'checkbox' function dose not work correctly in the right place. 
It will appear a ugly checkbox if we remove "toggle-all" properties.
![image](https://user-images.githubusercontent.com/6435874/27778780-37b40e54-5ff0-11e7-91f6-128b0771b8ad.png)
