### ISSUE TITLE
Missing "todos example" for Typescript 

### ISSUE THREAD

**Issue by jurosh** [reactjs/redux#2489]
Hi guys,

not sure if there are some fans of TypeScript ✌️ - but definitely it's good alternative to Flow. For Redux there is already Flow todos example - but TypeScript example project is missing, and you need to search it in alternative sources.

So I thought, might be nice idea to create todos also in TypeScript! 😏

Sub-project is based on Flow example, rewritten to typescript, added required typings and changed React create app scripts to support typescript.

Hope this might be good start for new guys adopting redux in TypeScript. And for experienced TypeScript devs to get always fresh ideas from this example (maintained by redux community).

PR is here https://github.com/reactjs/redux/pull/2485

Soo.. what do you think?

**Comment by timdorr** [comment]
None of the core team are TS users or experts. Hopefully, some of the contributors that help with the TS typings can chime in there and provide some feedback.

**Comment by jurosh** [comment]
Hi guys, you did great work on Redux typescript typings, can you take a look at my PR please @DanielRosenwasser @aikoven @raineorshine @use-strict

https://github.com/reactjs/redux/pull/2485
