### ISSUE TITLE
Typescript definition for Reducer should allow `undefined` for `state`

### ISSUE THREAD

**Issue by flushentitypacket** [reactjs/redux#2491]
**Do you want to request a *feature* or report a *bug*?**  

Bug

**What is the current behavior?**

The reducer type `Reducer<S>` [does not allow `undefined` as a valid `state` arg](https://github.com/reactjs/redux/blob/c1953b04cf48b2973aa8e2197d5b46ec36adbd59/index.d.ts#L57).

This prevents something like [clearing state as suggested by Dan Abramov](https://stackoverflow.com/a/35641992).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

Self explanatory from [the source](https://github.com/reactjs/redux/blob/c1953b04cf48b2973aa8e2197d5b46ec36adbd59/index.d.ts#L57)

**What is the expected behavior?**

`undefined` should be a valid state, since that is the store's initial state in most cases.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

AFAIK all versions affected since .d.ts was added.

**Comment by timdorr** [comment]
This is already fixed on the `next` branch: https://github.com/reactjs/redux/blob/next/index.d.ts#L46
