### ISSUE TITLE
Code generated as es module produces eslint warning

### ISSUE THREAD

**Issue by BTMPL** [reactjs/redux#2493]
Currently, code generated for `es/applyMiddleware.js` is the following:

```
var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };

import compose from './compose';

/**
 * Creates a store enhancer that applies middleware to the dispatch method
 * of the Redux store. This is handy for a variety of tasks, such as expressing
 * asynchronous actions in a concise manner, or logging every action payload.
 *
```

It includes `_extends` polyfill which is added by bable to support the spread operator used in:

```
    return {   
      ...store,
      dispatch 
    }          
```

This will trigger eslint warning about import being in module body:

https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/first.md

A solution would be to replace the spread with `Object.assign` which is not transformed by bable with the configuration redux uses, but I'm not sure if this will introduce breaking changes or not (IE <= 11 has no support for Object.assign).

Another solution would be to replace the spread with a custom impleentation of the polyfill placed after import line.

**Comment by timdorr** [comment]
Well, first off, you shouldn't be linting our code, just your own. The modules you use certainly follow different linting guidelines than your own. 

But more importantly, this isn't a default rule for eslint-plugin-import. So, you would have to explicitly add it to your rules. This is very unlikely to be a problem for most projects.
