### ISSUE TITLE
Mappable reducers

### ISSUE THREAD

**Issue by philipnilsson** [reactjs/redux#2495]
Hello,

coming out of the Haskell world I'm really used to working with reducers in the style of [applicative folds](https://www.joachim-breitner.de/blog/560-The_mighty_applicative_left_fold)

Essentially we use exactly redux reducers except they are functors, meaning that we can map over them

```javascript
const nameReducer = personReducer.map(p => p.name)
```

This is useful for the same reasons reselect is useful, but this let's us stay within the reducer abstraction.

This is accomplished by storing a "presenter" function to postprocess the accumulated state. We end up getting a "backing state"  and a "view" which consumers see. (So a reducer in the style of redux is a special case of this with the presenter function being exactly `x => x`)

A typical example would be to have a set of translations exposed as the application state, while only storing the current `locale`.

```javascript
  const translationsReducer = localeReducer.map(locale => getTranslationsFor(locale))
```

We're still able to serialize and rehydrate only the backing state. We're also able to cache the "view" in order not to produce new objects spuriously so we can avoid re-renders (again, see reselect, expect we need only a single library / abstraction).

I've previously used this in production, and I've now pushed my implementation to github [here](https://github.com/philipnilsson/fantasyland-redux). It's often compatible with existing code bases, for instance it works out of the box with `react-redux` and any middlewares applied using `applyMiddleware` (though unfortunately not the redux devtools)

So my question is if there is any desire to ever take redux in this direction? I really feel like this model improves reducers e.g. in comparison to something like MobX, since we can produce essentially computed values while keeping all the advantages of Redux.

Cheers,
Philip

**Comment by markerikson** [comment]
I have 0 background in Haskell (or any other "serious" FP language) myself.  What are the actual differences in `fantasyland-redux` in both implementation and usage?  What does it mean to "map over" reducers?  What are the benefits you're seeing out of your approach?

Or, to put it another way: I'm afraid I don't understand what it is you're actually proposing or describing :)

**Comment by philipnilsson** [comment]
@markerikson I guess it's pretty hard to describe, so let's have the code do the talking :) 

 I've written down a small example here. http://fantasyland-redux.surge.sh/

Do you feel like it makes sense?

**Comment by markerikson** [comment]
Apologies, haven't had time to go through and specifically look at what you've put together.

My guess is that it's something we'd be unlikely to do ourselves, for a variety of reasons.  I'll see if I can give more specific feedback once I've had a chance too look this over.
