### ISSUE TITLE
Redux : Testing async functions

### ISSUE THREAD

**Issue by gourav-singhal** [reactjs/redux#2499]
Hi,

I am trying to test Async Action Creators as per the documentation described [here](http://redux.js.org/docs/recipes/WritingTests.html#): 

I am using 'nock' to mock my api call.

But instead of returning the mocked response, when I dispatch the action, It is calling the actual "fetch" call in my action code.

I am using the global fetch api for my api calls.

Any help will be appreciated as I am currently stuck here.

**Comment by timdorr** [comment]
Mocking globals is a bit more involved and potentially dangerous. I'd recommend using isomorphic-fetch or another polyfill that you can more safely override with nock.
