### ISSUE TITLE
redux cannot be AoT compiled by angular-cli

### ISSUE THREAD

**Issue by jkyoutsey** [reactjs/redux#2503]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
When using AoT I can't import anything from redux.
```
import Store from 'redux';
...
constructor (@Inject(AppStore) private store: Store<AppState>)
```
or
```
import * as Redux from 'redux';
...
constructor (@Inject(AppStore) private store: Redux.Store<AppState>)
```

Both of these fail with:
```
WARNING in ./src/main/ui/app/app.component.ts
77:64-75 "export 'Store' (imported as 'Redux') was not found in 'redux'
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
Create a base angular-cli project.
Add redux.
Try to AoT compile with `ng serve --prod --aot`

**What is the expected behavior?**
redux should be AoT compliant.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**
At compile time, not in the browser.
```
redux: 3.7.1
@angular/cli: 1.2.0
node: 6.10.3
npm: 5.1.0
os: darwin x64
@angular/animations: 4.2.6
@angular/common: 4.2.6
@angular/compiler: 4.2.6
@angular/core: 4.2.6
@angular/forms: 4.2.6
@angular/http: 4.2.6
@angular/platform-browser: 4.2.6
@angular/platform-browser-dynamic: 4.2.6
@angular/router: 4.2.6
@angular/cli: 1.2.0 or 1.1.1
@angular/compiler-cli: 4.2.6
@angular/language-service: 4.2.6
```

**Comment by gaearon** [comment]
Redux doesn't have an export named "Store". I'm not sure if you tried to import typings? I guess I don't know how those work.

**Comment by jkyoutsey** [comment]
@gaearon Typings are not needed per npm:

```
npm WARN deprecated @types/redux@3.6.0: This is a stub types definition for Redux (https://github.com/reactjs/redux). Redux provides its own type definitions,so you don't need @types/redux installed!
+ @types/redux@3.6.0
```

**Comment by houfio** [comment]
@gaearon [it does](https://github.com/reactjs/redux/blob/master/index.d.ts#L125)

**Comment by gaearon** [comment]
Yea, unfortunately I don’t know how our typings work. I hope co-maintainers with TS experience can shed light on this!

**Comment by timdorr** [comment]
`tsc` (under the hood) should be picking up on our typings. Have you created a `tsconfig-aot.json` file and is it configured correctly?

**Comment by jkyoutsey** [comment]
@timdorr It depends on what "configured correctly" means.  My app has been AoT'ing fine up until I add redux.  So, I'm not aware of what I might need to add to my tsconfig to ensure that it's picking up what it needs to make redux types get exposed to the app.

**Comment by timdorr** [comment]
Is this the first package you've imported bundled typings from? I.e., you have only used @types/whatever before.

We [bundle our typings](https://github.com/reactjs/redux/blob/master/package.json#L8) according to [how TypeScript says to do it](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html), so I'm unsure why it wouldn't be working. tsc and tsconfig.json aren't something I've worked with myself.

To be honest, this sounds like it could be an issue with @angular/compiler-cli. We're doing everything we're supposed to and TypeScript definitely works for others. Maybe someone reading this has some insight, but the angular team is going to have a better idea of what's going on internally and if there is any sort of bug.
