### ISSUE TITLE
Add state getter to returned object in createStore

### ISSUE THREAD

**Issue by baron816** [reactjs/redux#2518]
Would there be any disadvantage to adding an ES6 getter to the object that is returned by createStore, like so:

```
export default function createStore(reducer, preloadedState, enhancer) {
  ...implementation

  return {
    dispatch,
    subscribe,
    getState,
    get state() {
       return currentState;
    },
    replaceReducer,
    [$$observable]: observable
  }
```
That way, people can just call `store.state` instead of `store.getState()`. I would like to add it if there are no objections.

**Comment by markerikson** [comment]
Appreciate the suggestion, but I see no actual benefit to adding this.  The store API is well known, all existing code uses `getState()`, and having two separate ways to access the state that do the exact same thing isn't going to be useful.  (As a side note, I believe properties like that are a part of ES5, not ES6.)
