### ISSUE TITLE
unmet peer dependency requiring react@16.0.0-0, wich does not exist

### ISSUE THREAD

**Issue by genbag** [reactjs/redux#2519]
Hi,

While making a form, i can't seem to get redux-form to work.
I did yarn add redux, wich worked without problems.
But then , yarn add react-redux and yarn add redux-form both warn me with unmet peer dependency, requiring react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0.
After trying, it seems these packages don't exist, and when trying to run the program, i only get an error 500

**Comment by markerikson** [comment]
Whatever's going on here is not an issue with the Redux library.
