### ISSUE TITLE
Why has nextListeners in createStore.js?

### ISSUE THREAD

**Issue by MrErHu** [reactjs/redux#2524]
The Annotations is: 
1. The subscriptions are snapshotted just before every `dispatch()` call.If you subscribe or unsubscribe while the listeners are being invoked, this will not have any effect on the `dispatch()` that is currently in progress.However, the next `dispatch()` call, whether nested or not, will use a more recent snapshot of the subscription list.

so,the purpose of nextListeners is that subscribe or unsubscribe will not effect current listener invoke progress。But JavaScript is single thread, I think that will not happen.

**Comment by timdorr** [comment]
Yes, JS is single threaded, but this will definitely happen. Check the test suite.

**Comment by MrErHu** [comment]
@timdorr Thank you so much!
