### ISSUE TITLE
Compose breaks if Array.prototype.reduce is overwritten

### ISSUE THREAD

**Issue by andrewshatnyy** [reactjs/redux#2525]
**Do you want to request a *feature* or report a *bug*?**  
Feature

I am writing an SDK with redux. Last week I had to deal with a strange error `TypeError: d.apply(...) is not a function`. When creating a store with multiple enhancers / middleware `applyMiddleware(logger1, logger2)` TypedError would appear occasionally. Apparently client would load their `applicaition.js` which has ES overrides to support older IE versions.

I understand this is an edge case but It would be nice 

**What is the current behavior?**
[`compose`](https://github.com/reactjs/redux/blob/master/src/compose.js#L21) method relies on `Array.prototype.reduce` to compose middleware.
`applyMiddleware` will throw an error If `Array.prototype.reduce` has been augmented on the page by some other library (prototype.js or some other wacky lib)
It is hard to find out what exactly is the problem if you don't know what is going on underneath.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
[jsfiddle](https://jsfiddle.net/zf9o2rqc/)

**What is the expected behavior?**
I suggest using `reduce` from from `lodash` which is already in the dependency chain.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**
All recent versions with `compose.js`

**Comment by markerikson** [comment]
Appreciate the suggestion, but I don't think this is a change we want to make.  We've had lots of little tweaks suggested for `compose` over time, and there really isn't sufficient reason to make any further changes to it at this point.

I'll leave this open just for a bit to see if @timdorr or @jimbolla want to chime in, but at the moment I'm going to say that we're not going to add workarounds for built-in prototypes being overridden.

**Comment by timdorr** [comment]
Yeah, we can't be expected to handle if the underlying environment is a moving target.
