### ISSUE TITLE
Dispatching several actions in sequence for single reducer doesn't reflect changes in state for connected component

### ISSUE THREAD

**Issue by likerRr** [reactjs/redux#2532]
**Do you want to request a *feature* or report a *bug*?**  

bug

**What is the current behavior?**

When dispatching several different actions for one reducer, only the last one triggers component update. It might be better to show then explain.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

https://codesandbox.io/s/LLVGBnQA

Some notes on provided example:
1. Component reflects a history of updates of it's prop `redirectPath`. When it comes as `null` then `no redirect` string adds to history.
2. There is a reducer which returns just a plain `string` or `null` depending on action.
3. By pressing a button `Do redirect` I expect both actions (`SET_REDIRECT` and `CLEAR_REDIRECT`) provide changed state to `AppContainer` component. But only the latest one (`CLEAR_REDIRECT`) triggers render method with `null` value.
4. If we add slight delay between dispatching these actions, then both of them trigger component's render. You can check it by pressing `Do redirect with delay` button.

**What is the expected behavior?**

Both changes (provided by `SET_REDIRECT` and `CLEAR_REDIRECT` actions) in state should trigger component update without using `setTimeout` when dispatching actions.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

redux v3.7.1
react-redux v5.0.5
Ubuntu 16.04 LTS
I haven't tried this on previous versions of redux.

**Comment by jimbolla** [comment]
This is working as expected. Here's the de-reduxed version which behaves the same way: https://codesandbox.io/s/lYM9AZx9V

**Comment by likerRr** [comment]
@jimbolla your example makes sense. Can you provide any workaround or confirm that it's ok to use `setTimeout` in such case?

**Comment by jimbolla** [comment]
My advice is to make your render functions pure so that it doesn't matter how many times it's called.

**Comment by likerRr** [comment]
Not sure if I've understood you. You mean get rid of `redirectHistory.push(this.state.redirectPath || "no redirect");`? This is just an example and in my real app the case is another.

I have a component which does redirection when it gets `redirectPath` from a state. So I want to dispatch both actions in sequence in order to make redirection and clear `redirectPath`'s value in state after that.

**Comment by free-soul** [comment]
@likerRr , we could modify the @jimbolla 's de-reduxed [version](https://github.com/reactjs/redux/issues/2532#issuecomment-318394900) with:
```
this.setState({ redirectPath: "/login" }, () => this.setState({ redirectPath: null }));
```
to ensure atomic updates.

**Comment by likerRr** [comment]
@free-soul thanx, but can you suggest a redux way of that?

**Comment by likerRr** [comment]
That answer solves my issue https://stackoverflow.com/a/45369529/3647991
