### ISSUE TITLE
Feature: Allow updating currentState when calling replaceReducer

### ISSUE THREAD

**Issue by cvbuelow** [reactjs/redux#2533]
I would like to suggest adding an optional param to `replaceReducer` that would allow updating the `currentState`. This is needed when using code splitting with SSR (see use case below).

Proposed code change (in bold)
<pre>
function replaceReducer(nextReducer<strong>, nextState</strong>) {
  if (typeof nextReducer !== 'function') {
    throw new Error('Expected the nextReducer to be a function.')
  }

  currentReducer = nextReducer
  <strong>currentState = nextState || currentState</strong>
  dispatch({ type: ActionTypes.INIT })
}
</pre>
This change will allow hydrating the store with state that was inlined in the page when doing SSR but belongs to a reducer that is being loaded after the store has been initialized because of code splitting.

Use case: https://gist.github.com/cvbuelow/ea7bd4deb7824fdb65d81cd2b8c60f5e
This is based off @gaearon's [gist](https://gist.github.com/gaearon/0a2213881b5d53973514) and addresses the SSR concerns mentioned there. Look at the [latest revision](https://gist.github.com/cvbuelow/ea7bd4deb7824fdb65d81cd2b8c60f5e/revisions#diff-8b3d2f22fc7e4f74eeb25762947f7c36) in my fork to see the diff.

Let me know If this feature looks ok and I can submit a PR.

**Comment by cvbuelow** [comment]
@timdorr do you or anyone else have any feedback on this? I would like to submit a PR since I need this feature.

**Comment by timdorr** [comment]
I'm not sure if the original use case still applies, since we've drastically changed React Router in 4.0. 

But replaceReducer is a bit of a hack anyways, so what's the big deal if it's even more hacky :)

I'd go ahead and do a PR. Please make it against the `next` branch, since this feels like a notable change that would warrant living in the next major.

**Comment by cvbuelow** [comment]
@gaearon suggested an alternate solution. Updated gist: https://gist.github.com/cvbuelow/ea7bd4deb7824fdb65d81cd2b8c60f5e
