### ISSUE TITLE
State update gets undone on next action

### ISSUE THREAD

**Issue by pikzen** [reactjs/redux#2536]
I have a store made up of a few dozen keys combined through combineReducers. Some of them are plain javascript objects, other are `Immutable.Record` objects from immutable.js.
Upon dispatching an action to add some data to this reducer, the action is done properly, and the reducer returns an updated list. On the next action dispatch however, this entire update is undone (and the reducer is updated). This happens no matter the action that happens after. My UI state that is bound to this state leaf doesn't get updated, even when breaking after, which leads me to believe the state update has not been done.

The fun part is that I have other reducers that have the _exact_ same layout, yet do not suffer from this problem.

![capture d ecran de 2017-07-28 09-37-18](https://user-images.githubusercontent.com/373126/28713540-b8eae288-738f-11e7-8392-6287ca1ece46.png)
![capture d ecran de 2017-07-28 09-37-21](https://user-images.githubusercontent.com/373126/28713558-c4bdda34-738f-11e7-9650-0119fad79692.png)

This is how my reducer is defined (typescript)
```typescript
const _initialState = {
  courses: Immutable.List<Course>(),
  loading: true
};
class Courses extends Immutable.Record(_initialState) {
  courses: Immutable.List<Course>;
  loading: boolean;
}
const initialState = new Courses();
export type CoursesState = typeof initialState;

export const courses = handleActions(
  {
    ...
    [addCourses]: (state: CoursesState, action: Actions.AddCourses) => {
      return state.merge({
        courses: state.courses.concat(action.payload.courses.map(it => new Course(it))),
        loading: false
      });
    },
    ...
  },
  initialState
);
```

I unfortunately do not have steps for reproduction. I have tried a simple project, but it doesn't exhibit this behavior. I have setup a breakpoint in combineReducers.js (line 125, in `combination()`) which confirms that my state is properly updated at first, then the next action reverts it.

I have tried both with and without redux-immutable, the issue is the same. This did not happen with pure JS objects, data was kept.

Libraries: redux 3.7.2, react-redux 5.0.5, react-router-redux 5.0.0@alpha6
Affected browsers: Chrome 60.0.3112.24, Firefox 54.0.1, Firefox Nightly
OS: Debian 9.0 Stretch

**Comment by markerikson** [comment]
Unfortunately, I don't think there's anything we can do to help you here.  All Redux does is call your root reducer function, and all `combineReducers` does is call your slice reducers.  Any actual logic in your reducers is up to you.  

The only question I can come up with is, what does your `"event/LOG"` reducer case look like?

**Comment by pikzen** [comment]
It is a simple update of a totally different key in the tree. Which is what troubles me so much. Each reducer handles its own key without any issues. event/LOG will touch the `event` key, not `courses`. This behavior can be triggered by any action handled, only on this particular key. Logic is extremely simple and is only pushing/updating/deleting from an array.

**Comment by markerikson** [comment]
If you can provide a minimal repro, either as a separate repro or a CodeSandbox project, I might be able to take a look.  Beyond that, this should not be a bug in Redux.
