### ISSUE TITLE
Update docs regarding server-side hydration?

### ISSUE THREAD

**Issue by djake** [reactjs/redux#2542]
The documentation at http://redux.js.org/docs/recipes/ServerRendering.html includes this line:

```
  // Compile an initial state
  let preloadedState = { counter }
```
I am a few months into using redux and have tried very hard to understand the idiomatic way of doing things. It seems to me that this is an anti-pattern, and that @gaearon agrees:
> In general we consider initialState argument to createStore an optimization. (https://github.com/reactjs/redux/issues/1431#issuecomment-186910503)

> You can pass the whole initial state tree as a second argument when creating the store. This is useful for hydrating persisted data or data received from the server. However we never recommend building that state tree in your code. (https://github.com/reactjs/redux/issues/1189#issuecomment-168025590)

The recipe itself says:

```
* create a fresh, new Redux store instance on every request;
* optionally dispatch some actions;
* pull the state out of store;
* and then pass the state along to the client.
```
Therefore, I do not ever pass a preloadedState argument on the server, but instead initialize the store and then dispatch actions as needed before rendering a response. However, I have nagging discomfort, after just a few months working with redux, telling my team that something is an anti-pattern even though it is the approach used in the official documented recipe.

Would you be inclined to accept a pull request updating the docs, or am I misunderstanding this issue? Even if it is as simple as changing the comment to, it would put my mind at ease, and hopefully will save someone some time grappling with this issue:

```
// Compile an initial state - as always, you should only populate your store by dispatching actions, but we are skipping that here to keep this short
```

**Comment by markerikson** [comment]
@djake : got a few random thoughts on this.

First, I'll caveat things by saying that I've never used SSR myself, so I have no particular expertise or knowledge on that side of things.

There's a couple different variations in how you can set up the initial state for a store: `preloadedState`, return value of the root reducer, or some combination of the above (especially if you're using `combineReducers)`.  See http://redux.js.org/docs/recipes/reducers/InitializingState.html for an explanation of how those different pieces fit together.

I think that from Dan's perspective, the "ideal" approach is to have each slice reducer provide its own initial state, which is then brought together by `combineReducers`.  But, if building some or all of that initial state in your own code works better for your scenario, you should feel free to do that.
