### ISSUE TITLE
Error handling while updating store

### ISSUE THREAD

**Issue by isnifer** [reactjs/redux#2543]
**I want to report a *question-bug*?**  
So, redux make an update in `try` block, but doesn't handle an error in `catch`. Is there any reason don't do this?
How could I debug these errors on prod without redux-logger of course? 

**What is the current behavior?**
Error in reducer while updating state doesn't throw.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
https://github.com/reactjs/redux/blob/master/src/createStore.js#L168-L173

## Production build - clean console
![image](https://user-images.githubusercontent.com/1788245/28965209-a102f9b0-7918-11e7-9ec8-3dcbcff43e28.png)

## Development build - I see an error only with redux-logger
![image](https://user-images.githubusercontent.com/1788245/28965233-bbe0da5e-7918-11e7-968e-1c02fafdc4c6.png)

## Development build (without redux-logger) - I don't see an error
![image](https://user-images.githubusercontent.com/1788245/28965287-f6e89696-7918-11e7-8100-0a4a8cb6c9bc.png)

## Development build (without redux-logger but mentioned lines were changed)
```js
try {
  isDispatching = true;
  currentState = currentReducer(currentState, action);
} catch(e) {
  console.error(e)
} finally {
  isDispatching = false;
}
```
![image](https://user-images.githubusercontent.com/1788245/28965369-74b376ea-7919-11e7-96da-1578470ffa84.png)

**What is the expected behavior?**
Error message about an error

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**
Redux: 3.7.2
Browser: Chrome
OS: macOS

**Did this work in previous versions of Redux?**
Maybe

**Comment by timdorr** [comment]
We don't want to catch so that you can handle the error however you would like to. We only want to ensure our local state variable (isDispatching) is reset back to the correct value, which we use `finally` for. You can implement error handling in a middleware, if you want.
