### ISSUE TITLE
CJS build is always deoptimized

### ISSUE THREAD

**Issue by jmeas** [reactjs/redux#2558]
**Do you want to request a *feature* or report a *bug*?**  

A bug

**What is the current behavior?**

The CJS build will _always_ log out the "development build in minified environment" error if you minify it. Additionally, the CJS code is _always_ deoptimized.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

Correctly minify a build of Redux using CJS (this is easiest to do using Webpack v1). Observe that you get the "You are using a development build of Redux" warning. Also observe that there's no way to opt out of the slow development build.

**What is the expected behavior?**

You wouldn't see that message, and Redux would be optimized.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

Redux version 3.7+ is affected by this, due to the new Rollup config.

----

**Possible explanation**

The source code for the CJS build's warning looks like this:

```js
	/*
	* This is a dummy function to check if the function name has been altered by minification.
	* If the function has been minified and NODE_ENV !== 'production', warn the user.
	*/
	function isCrushed() {}

	if (("development") !== 'production' && typeof isCrushed.name === 'string' && isCrushed.name !== 'isCrushed') {
	  (0, _warning2["default"])('You are currently using minified code outside of NODE_ENV === \'production\'. ' + 'This means that you are running a slower development build of Redux. ' + 'You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify ' + 'or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) ' + 'to ensure you have the correct code for your production build.');
	}
```

You can also see that slow checks _always_ occur in this environment:

```js
if (true) {
  var warningMessage = getUnexpectedStateShapeWarningMessage(state, finalReducers, action);
  if (warningMessage) {
    (0, _warning2["default"])(warningMessage);
  }
}
```

You can view this by downloading any version of Redux >= 3.7.0, and checking out the source code within the `lib` directory.

This isn't good, because the "development" string is hardcoded here. A user's environment will never properly invalidate this conditional.

The reason for this is this Rollup plugin config:

https://github.com/reactjs/redux/blob/7d1cabd5fa3d04fd4a21242be721bc2a6ca58f09/rollup.config.js#L17-L19

which defaults to "development" because no NODE_ENV is set in the package.json scripts:

https://github.com/reactjs/redux/blob/7d1cabd5fa3d04fd4a21242be721bc2a6ca58f09/package.json#L22

I'm _thinking_ that this is unexpected behavior, and that the correct behavior is to remove the plugin altogether:

```diff
- replace({
-   'process.env.NODE_ENV': JSON.stringify(env)
- })
```

See #2557 for a PR that implements this solution.

---

This has likely gone unnoticed since the most typical way to reproduce it is to use Webpack v1, and it may just be that most Redux users are on Webpack v2 by now. Or people ignore the warning 😛

**Comment by sprjr** [comment]
This is far more detailed than the issues I report haha. Nice work and thanks for debugging that with me earlier. I was very confused :)

**Comment by timdorr** [comment]
Rollup isn't used on the CommonJS version (yet; nothing is on `master` or `next`). You can see the rollup config is for the UMD build above that line:

https://github.com/reactjs/redux/blob/7d1cabd5fa3d04fd4a21242be721bc2a6ca58f09/rollup.config.js#L8

You can see it's not coming out of npm like that either: https://unpkg.com/redux@3.7.2/lib/index.js

I'm not sure what's going on, but this appears to be a build tooling problem in your project. We're definitely shipping the right versions of things.

**Comment by jmeas** [comment]
Woops, sorry @timdorr . It's in the `dist` folder. Check it out [here](https://unpkg.com/redux@3.7.2/dist/redux.js).

**Comment by timdorr** [comment]
That is the development UMD bundle. It should have that code and warning message in it. It's checking if the `isCrushed` function has been mangled if NODE_ENV=production. It shouldn't ever fire, of course. But there is no DCE in the development UMD build. 

The message isn't in the production UMD build (redux.min.js).

**Comment by sprjr** [comment]
@timdorr Is webpack and other bundling supposed to automagically grab the `.min.js` file? Because `main` in `package.json` does not point to any of the min files.

https://unpkg.com/redux@3.7.2/package.json

Sorry if I'm misunderstanding how `require()` works here in concert with bundling. I'm currently using Webpack 1.x and am not getting the `.min.js` in my output bundle.

**Comment by jmeas** [comment]
Ah, alright, that makes sense. I guess I got a little confused while looking through things. But I see now that everything does seem to be in order here from Redux's perspective.

Thanks for the help, @timdorr !

**Comment by gaearon** [comment]
>Is webpack and other bundling supposed to automagically grab the .min.js file? Because main in package.json does not point to any of the min files.

No. If you use Webpack you're expected to perform envification with DefinePlugin and minification with UglifyJsPlugin yourself.
