### ISSUE TITLE
Is this change ok?

### ISSUE THREAD

**Issue by Runrioter** [reactjs/redux#2565]
https://github.com/reactjs/redux/blob/f267dd02d19c2ede88e37b8a73cc0b0b63413be2/src/applyMiddleware.js#L25-L28

Below is ok?
```javascript
const middlewareAPI = {
  getState: store.getState, 
  dispatch
} 
```

**Comment by jimbolla** [comment]
No. the `dispatch` variable is mutated later and it's important for that anon lambda to capture the mutable value.

**Comment by Runrioter** [comment]
@jimbolla  Thank you
