### ISSUE TITLE
Performance issues with Redux and Three.js

### ISSUE THREAD

**Issue by lysigk** [reactjs/redux#2566]
I am currently trying to figure out a way of using Redux for state management and event handling in a Three.js-based game.

My idea was to use a render function that dispatches an 'UPDATE' action in it's requestAnimationFrame() callback. The render function is also subscribed to the Redux store so it gets called after the state has been updated.

While this way of updating and rendering seems to work fine, some serious performance issues occur as soon as another mouse-triggered action ('CHANGE_MATERIAL' in my example) gets dispatched. Every time 'CHANGE_MATERIAL' is dispatched the framerate sinks a bit and CPU usage goes up. This doesn't go back to normal after a while, it just stays like this and gets worse with every click.

I have isolated the problem into this [gist](https://gist.github.com/lysigk/cf86b8c78ec2e18e9d1d0f42a182bdf2) and this [fiddle](https://jsfiddle.net/lysigk/82qg2n0p/).

This problem occurs with using Redux v3.7.2 and Three.js v0.86.0. 

**EDIT: After further investigation this doesn't seem to be a Redux related bug, so I'm closing this issue.**

**Comment by timdorr** [comment]
You're doing a few things incorrectly there. First, your reducers are directly modifying state objects. They should be free of side effects. 

Also, you are storing non-serializable objects into your state. I don't know the specifics of Three's object structures, but they have complex shapes that can't simply be serialized. 

You should be storing state information about the attributes of your system, but not the system objects themselves. Instead, you should be storing the material type as a simple value (wireframe: true || false). You can then `subscribe()` to state to update the system when those values change.

**Comment by lysigk** [comment]
Okay, I think I understand, thanks for your advice! So is calling a (pure?) function, that takes the current state and returns a modified copy of it, from inside the reducer genrerally considered a bad practice?

Considering the serialization issue, I should probably create some kind of function similar to `mapStateToProps()` in React-Redux, which applies the updated state to the Three.js scene object. This would also significantly reduce the size of the state tree.
