### ISSUE TITLE
Documentation Basics on Reducers: combineReducers is NOT equivalent to custom reducer

### ISSUE THREAD

**Issue by Reliot** [reactjs/redux#2567]
**Do you want to request a *feature* or report a *bug*?**  
I'd like to point out a small, but important slopiness in the documentation.

The [documentation about reducer basics](http://redux.js.org/docs/basics/Reducers.html) tells us, that the following two reducers would be equivalent. (I renamed them for sample's sake).

    import { combineReducers } from 'redux'
    
    const todoAppByCombine = combineReducers({
      visibilityFilter,
      todos
    })
    
    default function todoAppCustom(state = {}, action) {
     return {
        visibilityFilter: visibilityFilter(state.visibilityFilter, action),
        todos: todos(state.todos, action)
      }
    }

But in fact, they are not, since the custom implementation will change the state even if nothing changed.

    const undefinedAction = { type: undefined};

    var firstState = todoAppCustom( undefined, undefinedAction);
    var secondState = todoAppCustom( firstState, undefinedAction);
    
    console.log( firstState === secondState); // prints false

    var firstState = todoAppByCombine ( undefined, undefinedAction);
    var secondState = todoAppByCombine ( firstState, undefinedAction);
    
    console.log( firstState === secondState); // prints true

I think, this is quite an important detail. The documentation mentions further, that combineReducers will not yield a new object, if nothing changed, but i think it's important enough to mention, that the functions are not equivalent.

**Comment by timdorr** [comment]
I'm not sure I understand what the issue is. It's explaining the basics for building a reducer and then directing you to use combineReducers for this use case, as it handles the default case better than the simple example above.

If you have a specific suggestion for the docs, a PR is the best way to provide feedback, as it gives us something concrete to discuss.

**Comment by markerikson** [comment]
Yeah.  The docs page says:

> Redux provides a utility called `combineReducers()` that does the same boilerplate logic that the todoApp above currently does. 

That part is absolutely correct.  It just so happens that `combineReducers` also implements an optimization where it only returns a new state object reference if it looks like at least one of the child reducers actually updates its values.
