### ISSUE TITLE
Storing a File type object in store doesn't save it entirely

### ISSUE THREAD

**Issue by johhansantana** [reactjs/redux#2568]
I'm trying to upload a blob/file type object with the following information

![image](https://user-images.githubusercontent.com/9933887/29474054-0a476ffe-8428-11e7-81c1-08ec4ff51f33.png)

But when I save/store this in redux the only thing that gets saved is the `preview` property.

Is there  a way to get the whole blob/file to be saved in redux store/state?

**Comment by timdorr** [comment]
You should only keep serializable objects in your store. In particular with Files, since they behave quite differently from normal objects.
