### ISSUE TITLE
bindActionCreator should return the result of the dispatch call

### ISSUE THREAD

**Issue by hoegertn** [reactjs/redux#2577]
Currently, the bindActionCreator is not returning the result of the wrapped function. This leads to promises being swallowed and the original caller is not able to handle errors properly.

Especially for redux-form, this would be great, as the errors can then be forwarded to the Form validation.

This can be fixed by changing

```
function bindActionCreator(actionCreator, dispatch) {
  return (...args) => dispatch(actionCreator(...args))
}
```

to

```
function bindActionCreator(actionCreator, dispatch) {
  return (...args) => return dispatch(actionCreator(...args))
}
```

This happens with the latest version of redux.

**Comment by jimbolla** [comment]
`return (...args) => dispatch(actionCreator(...args))` already returns the result of `dispatch(...)` because that's how lambda functions work. Your version is not valid JS syntax.

**Comment by hoegertn** [comment]
You are right. I thought I saw {} around the dispatch.

It was another bug that seemed to have this as a reason.
