### ISSUE TITLE
Action types from passed through to subscribers would allow us to scale better

### ISSUE THREAD

**Issue by fir3pho3nixx** [reactjs/redux#2584]
**Do you want to request a *feature* or report a *bug*?**  

Submit a PR but discuss a feature first.

**What is the current behavior?**

Listeners that are subscribed to from an instance of the store don't have action types passed to them as a parameter when dispatch is called.

**What is the expected behavior?**

It would definitely be helpful to us if we wanted to scale out our listener(or make it smarter) using action types as a parameter, the reason I say this is because I believe we can re-use our current event structure to do more focused view binding updates when it comes to angular after actions are dispatched through the store. For now we only have a single listener that will trigger a rebind for everything in the view that is bound to the store, this does not feel optimal to me. I hope to partition things using action type. We also make extensive use of reselect but I think it abstracts our scaling needs to our selectors which just does not feel right because we use this in the view for things like formatting and composition. We also debounce our listener which I am hoping this feature will give us the ability to remove at some point. 

The change is here: https://github.com/fir3pho3nixx/redux/commit/764cbf5159e086417e6c09567f4099cddf7da79c

Look forward to your feedback/questions.

**Comment by timdorr** [comment]
https://github.com/reactjs/redux/issues/1971#issuecomment-248362831

**Comment by fir3pho3nixx** [comment]
@timdorr 

I get what you are saying about not having to deal nested dispatches because you basically don't want to become a message bus, but you should at least allow the meta data to flow through. Let's please just make sure we are grounded in the fact that we are still coding in javascript and not haskell.
