### ISSUE TITLE
Restructure "Ecosystem" docs page

### ISSUE THREAD

**Issue by markerikson** [reactjs/redux#2588]
The "Ecosystem" page is currently a bit of a scattershot list ([current version for reference](https://github.com/reactjs/redux/blob/ab5c9593bc304880c3089fc0bfcc2c3a28fd21d3/docs/introduction/Ecosystem.md)).  There's a mixture of random tutorial links, translations, bindings, middleware, and other addons.  

The page describes itself as "staff picks", and also that "the Redux staff has vetted them personally".  Really, at this point that's not exactly true.  We've had lots of people submit their own libs over time, and while someone did presumably approve each merged PR, I'm not sure we really "vetted" things per se.

On a similar note, there's a great quote from Andrew and Dan at https://github.com/reactjs/redux/issues/215#issuecomment-118639342:

> As @gaearon said once, (I can't remember where... probably Slack) we're aiming to be like the Koa of Flux libraries. Eventually, once the community is more mature, the plan is to maintain a collection of "blessed" plugins and extensions, possibly under a reduxjs GitHub organization.

I don't think we're going to actually maintain any additional libs at this point, but we can certainly highlight ones that are widely used or specifically interesting in some better ways.

I talked with Dan at ReactRally about revamping this page.  I don't have an absolutely specific plan in mind yet, but some rough thoughts:

- Move any tutorials to a separate page.  In fact, we really ought to have a separate "Learning Resources" docs page, and put stuff in there instead.
- Review all existing links for relevance
- Stop advertising "Awesome-Redux" at the top of the page.  It's okay to leave it in a list of "Useful Resources", but in my (very biased) opinion, it's a link dump that's insufficiently organized.  (FWIW, I think Dan actually suggested that change first, and Sindre Sorhus felt it was poor enough that he didn't accept it into his "awesome-awesome" list.)
- Rebuild the list of "blessed" addons from scratch:
  - Come up with a list of use cases or categories
  - Specifically pick out 3-5 entries for each use case that we want to highlight
  - For each one, give a description of what it is, why you might want to use it (or pros/cons), and hopefully even give a 10-line snippet of what using it looks like

**Comment by SadPandaBear** [comment]
Another rough thoughts and reviews:

I'd suggest changing "**Using Redux**" to "**Tools & Resources**" or something like that.

> Review all existing links for relevance

No broken links, but I will check it out later if any Github repositories' links can be a link to a website that was created after the **Ecosystem** file was written.

> Stop advertising "Awesome-Redux" at the top of the page. It's okay to leave it in a list of "Useful Resources", but in my (very biased) opinion, it's a link dump that's insufficiently organized. (FWIW, I think Dan actually suggested that change first, and Sindre Sorhus felt it was poor enough that he didn't accept it into his "awesome-awesome" list.)

 We actually have this "**More**" session in the end of the file... I think that by just removing it from the top should do.

**Comment by ishankbahl** [comment]
Suggestion:
The talks can be put in iframes using any plugin for gitbook (Not sure if it is possible).

This issue seems interesting, can I work on this?

**Comment by markerikson** [comment]
Got started on this task tonight.  My first step is to remove all the "learning"-type links from the Ecosystem page, and create a new "Learning Resources" page.  At the moment, I'm mostly dropping the existing links entirely, and creating a new set of links that's based off the categories and entries in my React/Redux links list.

From there, I plan to fill out the new Ecosystem page in a style that's similar to [my ReactBoston slides on the Redux ecosystem](http://blog.isquaredsoftware.com/2017/09/presentation-might-need-redux-ecosystem/).  The goal is to show some of the categories of libraries that are out there, highlight some of the "best" or most widely-used addons in each category, and give information on when and why you might want to use them.
