### ISSUE TITLE
Upgrade real-world example to new version of react-router

### ISSUE THREAD

**Issue by eranhirs** [reactjs/redux#2592]
**Do you want to request a *feature* or report a *bug*?**  
Feature

**What is the current behavior?**
This code is in `src/index.js` in `examples/real-world`:
```javascript
import { browserHistory } from 'react-router'
```
There is an error when using `react-router` with version 4 and above.
```
'react-router' does not contain an export named 'browserHistory'
```

**What is the expected behavior?**
I think it's best to update the example to use the newer version of `react-router`.

**Comment by ktrysmt** [comment]
@roth1002 Thank you update real-world example. 
And a little, would you forgot to delete this file?
* `examples/real-world/src/routes.js`
