### ISSUE TITLE
Remove the word "store" from applyMiddleware.js

### ISSUE THREAD

**Issue by kennylbj** [reactjs/redux#2600]
Since the definition
```js
let dispatch = store.dispatch
```
Could I just remove the word "store" from [applyMiddleware.js](https://github.com/reactjs/redux/blob/master/src/applyMiddleware.js)  as below?

from:
```js
dispatch = compose(...chain)(store.dispatch)
```

to:
```js
dispatch = compose(...chain)(dispatch)
```

It able to pass all the tests.

**Comment by timdorr** [comment]
No, we need it to call the original instance of the dispatch function. In the future, this won't be true: https://github.com/reactjs/redux/blob/next/src/applyMiddleware.js#L22-L27

**Comment by kennylbj** [comment]
I think variable "dispatch" is reference to original instance of the dispatch function (store.dispatch) now.

Do you mean 
```js
dispatch = compose(...chain)(dispatch)
```
can work in current code but can not in the future?


Would you please explain it in more detail
