### ISSUE TITLE
Error install redux on Ubuntu 16.04?

### ISSUE THREAD

**Issue by thiennhank9** [reactjs/redux#2609]
Hi guys,
I installed redux successfully on windows 10 64 bit.
But when I'm on Ubuntu 16.04 64bit, I can't install redux.
It shows this error.
![1](https://user-images.githubusercontent.com/18640233/30368407-4254bb4a-989b-11e7-8c28-06714cdc7317.png)

**Comment by timdorr** [comment]
This isn't a problem with Redux. You have some sort of issue with npm itself.
