### ISSUE TITLE
Using ES6 multilline string in index.js

### ISSUE THREAD

**Issue by danedavid** [reactjs/redux#2611]
Couldn't we use es6 multiline string using backtick in the parameter passed to `warning()` function in `src/index.js` ?

```
{
  warning(
    'You are currently using minified code outside of NODE_ENV === \'production\'. ' +
    'This means that you are running a slower development build of Redux. ' +
    'You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify ' +
    'or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) ' +
    'to ensure you have the correct code for your production build.'
  )
}```

**Comment by markerikson** [comment]
Template literal strings preserve whitespace inside, don't they?  If so, I don't think that's what we want here.

**Comment by timdorr** [comment]
Yup

![image](https://user-images.githubusercontent.com/17882/30446333-d3fb3036-9956-11e7-9598-c87d082c1a37.png)

So, unfortunately, we can't do that here.

**Comment by Florian-R** [comment]
> Template literal strings preserve whitespace inside, don't they? If so, I don't think that's what we want here.

Just curious to know, what problems can arise by keeping whitespaces in warning? This is maybe obvious, but I can figure it just by looking at @timdorr screenshot.

**Comment by danedavid** [comment]
I was thinking more like this:  
![image](https://user-images.githubusercontent.com/19928280/30479145-86d6f08e-9a31-11e7-8aff-885fdee7184d.png)

..or is it deprecated ?
