### ISSUE TITLE
Redux Doc's Advanced Middleware Section Wrong Order

### ISSUE THREAD

**Issue by icharlie2** [reactjs/redux#2612]
Hi guys, in reference to this particular doc page http://redux.js.org/docs/advanced/Middleware.html,

The bottom of Attempt#3 applies the patches in this order: 

```
patchStoreToAddLogging(store)
patchStoreToAddCrashReporting(store)
```

however in Attempt#4 and higher the patches are applied in the reverse order since 
applyMiddlewareByMonkeypatching reverses the array before applying each middleware.

`applyMiddlewareByMonkeypatching(store, [logger, crashReporter])`

I think that the action should run through the crashReporter prior to the logger, so I believe Attempt#3 is correct and the others are reverse. Can anyone else confirm?

**Comment by timdorr** [comment]
I wouldn't worry too much about the specifics. It's more of a thought exercise than code you should actually expect to run. Hence the docs take several attempts to get at the final result.
