### ISSUE TITLE
destructuring import fails in native mjs-file

### ISSUE THREAD

**Issue by pe3** [reactjs/redux#2614]
This doesn't work when running with Node.js 8.5 experimental modules support

```
//redux.mjs
import { createStore } from "redux"

function counter(state = 0, action) {
  switch (action.type) {
  case 'INCREMENT':
    return state + 1
  case 'DECREMENT':
    return state - 1
  default:
    return state
  }
}

let store = createStore(counter)
store.subscribe(() =>
  console.log(store.getState())
)
store.dispatch({ type: 'INCREMENT' })
store.dispatch({ type: 'INCREMENT' })
store.dispatch({ type: 'INCREMENT' })
```
I'm getting this error:
```
$ node --experimental-modules --no-warnings redux.mjs 
SyntaxError: The requested module does not provide an export named 'createStore'
    at checkComplete (internal/loader/ModuleJob.js:86:27)
    at moduleJob.linked.then (internal/loader/ModuleJob.js:69:11)
    at <anonymous>
```
I starts working if I do the destructuring after the import instead:
```
import redux from "redux"
const { createStore } = redux
```
OK. That's an experimental feature, but the same happens when importing through [@std/esm](https://github.com/standard-things/esm) and running without experimental modules so one starts to wonder if there is something wrong with the Redux module and if it only works when used through Babel :
```
// index.js
require = require("@std/esm")(module)
module.exports = require("./redux.mjs").default
```
Exactly same behavior repeats:
```
$ node index.js 
SyntaxError: Module '/private/tmp/fc1c5a2f65d756568d28afc2db4fa0ae/node_modules/redux/lib/index.js' does not provide an export named 'createStore'
    at /private/tmp/fc1c5a2f65d756568d28afc2db4fa0ae/redux.mjs
    at Object.<anonymous> (/private/tmp/fc1c5a2f65d756568d28afc2db4fa0ae/redux.mjs)
```
Again it works if the destructuring is done separately:
```
import redux from "redux"
const { createStore } = redux
```

**What is the expected behavior?**

I would expect desctructuring to work in imports since that is the format used in Redux docs.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

Versions:
- redux: 3.7.2
- node: 8.5.0
- std/esm: 0.10.1

**Comment by timdorr** [comment]
You need to use the module build, I believe. It's at [`redux/es/index.js`](https://unpkg.com/redux@3.7.2/es/index.js). 

However, this is all an experimental feature, so I'm not sure how sub-dependencies work. Perhaps at some point in the future, we can offer .mjs files in our package. But we should wait until the spec is finalized and the flag is gone from node.

**Comment by markerikson** [comment]
Yeah, I think I saw John-David Dalton say that while you can "import" CJS modules into an ESM module, you deliberately are not allowed to do named imports when you do so.

**Comment by jdalton** [comment]
> Yeah, I think I saw John-David Dalton say that while you can "import" CJS modules into an ESM module, you deliberately are not allowed to do named imports when you do so.

Correct. You can unlock it with `@std/esm` using the `"cjs"` option. There's also a [PR open](https://github.com/nodejs/node/pull/15445) on Node to enable loader hooks in ESM that allow enabling importing named exports of CJS.
