### ISSUE TITLE
IE11 error on createStore()

### ISSUE THREAD

**Issue by aptheod** [reactjs/redux#2619]
Hello, I'm getting this error on IE11:
**Actions must be plain objects. Use custom middleware for async actions.**

I figured that createStore() is causing this error. My implementation of createStore() is the one below:

```
const store = createStore(
    rootReducer,
    initialState,
    compose(
      applyMiddleware(sagaMiddleware)
    )
  )
```
I have even used the simple example here [http://redux.js.org/docs/api/createStore.html#example](url) to initialize a store, but it keeps crashing with the same error. Also In Edge it renders a blank page without JS errors. In all the other browsers it works fine, without any errors.

Redux version: "^3.7.2"

Thank you

**Comment by markerikson** [comment]
Per the error message, only plain object actions can be dispatched unless you have a middleware like `redux-thunk` installed.

This is unlikely to be an issue with Redux itself, but if you can post an example project that reproduces the issue, we might be able to take a quick look.
