### ISSUE TITLE
How to use multiple pages in react.js

### ISSUE THREAD

**Issue by vignesh25nithin** [reactjs/redux#2620]
I am a beginner to react.js, I came across react-router to set path for multiple pages but everything went in vain. If anyone could help me with steps to use multiple pages in react.js it would be of great help.
I have two file app.js and display.js which must have link to another. I have an index.js as entry point.
I don't want my app to be single page. so kindly give me guidance. Thanks in advance,

**Comment by timdorr** [comment]
This doesn't have anything to do with Redux.

**Comment by bbwstar** [comment]
Hi there..

Please help me.

I am trying to run on my local. But below is error.



events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8000
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at net.js:1404:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program
Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! candidate-apbprive@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the candidate-apbprive@1.0.0 start script 'node
server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the
candidate-apbprive package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project
with:
npm ERR!     npm bugs candidate-apbprive
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls candidate-apbprive
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\TASK\20170913\staging\Candidate-New-Front\npm-debug.log



Could you help me what is solution?

Thank you.
