### ISSUE TITLE
Standards-compliant ES module build

### ISSUE THREAD

**Issue by magnonellie** [reactjs/redux#2628]
**Do you want to request a *feature* or report a *bug*?** 

Feature

**What is the current behavior?**

Redux doesn't have a standards compliant es-module build that allows it to run in the browser as a native module without compilation from the user.

**What is the expected behavior?**

The build in the `es` directory should probably be made standards compliant by either rewriting the imports in the source or using rollup (which doesn't fix node_modules imports AFAIK) to produce a build of Redux that runs directly in the browser with a `<script type="module">` tag.

**What's missing?**

The problem right now is that browsers supporting es-modules doesn't support importing with loosely defined paths such as `./compose` or `lodash/isPlainObject`. Instead, the full actual path has to be defined with extensions and everything.

**Comment by timdorr** [comment]
Unfortunately, this stuff is so new, no one else in the ecosystem is doing this. Even if we were to update with correct URLs, our dependent packages wouldn't and would break things.

For the moment, you can use unpkg's module feature to accomplish this: https://unpkg.com/redux@3.7.2/es/index.js?module

**Comment by magnonellie** [comment]
That's a shame since I just noticed that the normal dist version doesn't work either when importing from a module. Fails with this:
```
Uncaught TypeError: Cannot read property 'Redux' of undefined
    at freeGlobal (redux.js:4)
    at redux.js:5
```
