### ISSUE TITLE
Whole stack falls down (crashes hard) on a null argument

### ISSUE THREAD

**Issue by justinrleblanc** [reactjs/redux#2629]
BUG REPORT

On <project_root>node_modules\redux\lib\combineReducers.js:113
Buggy code: ```arguments[0] !== undefined```
Fixed code: ```arguments[0] != undefined```

**What is the current behavior?**
allows null states to be passed through, resulting in a whole-page-crashing exception later down the chain (I noticed at line 132)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
get the arguments first element to be null

**What is the expected behavior?**
catch the null and assign an empty state object instead of passing along the null

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**
from package.json:
    "react-redux": "^5.0.2",
    "redux": "^3.6.0",
    "redux-saga": "^0.14.3",

**Comment by markerikson** [comment]
That is the Babel-compiled output that implements the ES6 "default values for function parameters" feature.  The original ES6 code is:

```js
  return function combination(state = {}, action) {
    if (shapeAssertionError) {
      throw shapeAssertionError
}
```

If and _only_ if the `state` argument is `undefined`, it will become an empty object.  Otherwise, Javascript itself assumes that you intentionally passed in a value, and uses it.

`combineReducers` expects that the passed-in state will be a Javascript object.  If you pass in anything other than a plain JS object, you have given it invalid input, and it will not behave as expected.

**Comment by justinrleblanc** [comment]
Please re-open, for the following reasons: 

It is reasonable to make a user-level notice that certain parts of the UI may not render as expected, it is unreasonable to fail out completely with no rendering and no user-level notice. Said another way, a low-level crash due to outside input should be considered unacceptable; rather if a value is not workable, if it is unreasonable to massage it into something workable, then any exception should occur at the end of the chain rather than the beginning.

**Comment by timdorr** [comment]
We do warn about this: https://github.com/reactjs/redux/blob/master/src/combineReducers.js#L29-L36 

Make sure you're not running with NODE_ENV=production.

**Comment by gaearon** [comment]
Redux does not "swallow" the crashes. If you don't see a crash in your browser developer tools, some other code in your app (whether written by you or from a library you use) is swallowing it. Use "break on all exceptions" feature of the browser debugger to pause when the code is thrown, and then follow the callstack up to find what's swallowing your exceptions.
