### ISSUE TITLE
Feature Request: pass `this` through bound actionCreator

### ISSUE THREAD

**Issue by Parakleta** [reactjs/redux#2638]
Is there any chance of changing `bindActionCreator` from:
```js
function bindActionCreator(actionCreator, dispatch) {
  return (...args) => dispatch(actionCreator(...args))
}
```

to:
```js
function bindActionCreator(actionCreator, dispatch) {
  return function() { return dispatch(actionCreator.apply(this, arguments)); };
}
```

The existing behaviour explicitly sets `this` to undefined so this [shouldn't](https://xkcd.com/1172/) be a breaking change.

I have some mixins/decorators that I apply to action creators by composition such that the arguments don't change but I can adjust settings in the enhancer by passing an object through `this`.  If I use some of the convenience functions like `connect` I lose the ability to pass through these objects.

**Comment by timdorr** [comment]
Can you put this together as a PR with some tests to go along with it?

**Comment by markerikson** [comment]
I'd also like to see some examples of the actual use case for the behavior.  I'm not sure if passing through `this` is something we really want to encourage.

**Comment by Parakleta** [comment]
I’m sure it isn’t something you want to encourage, but then is it the place of redux to police code quality or rather should it provide a shining example of what can be achieved and then get out of the way.  As troubled as it is and as often as it blows up for people, `this` is a valid part of the call mechanism in javascript and redux shouldn’t just swallow it.

**Comment by Parakleta** [comment]
@timdorr I haven’t any experience with your testing framework, but I’ll see if I can find some time tomorrow to set it up.
