### ISSUE TITLE
Metabox color option not inheriting parent Theme option. 

### ISSUE THREAD

**Issue by ACODA-LTD** [reactjs/redux#2640]
**What is the current behavior?**
Saving a Metabox color option overrides global option, even if it's left as the default. As soon as the page or post is saved, it no longer inherits the Theme option. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

If you set a global Theme color option, say the Header Background Color, create a new page and save with defaults, then change the Header Background Color Theme option, the page does not inherit the new color. Instead, it uses what was saved as default on the page. 

**What is the expected behavior?**

If the global Theme Header Background Color is changed, it should change on the page, unless the page was saved with a color different to the global option. 

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**
Latest

**Comment by markerikson** [comment]
This is the issue tracker for the Redux JS state management library.  You're looking for https://reduxframework.com/ .
