### ISSUE TITLE
form closer having linting error 

### ISSUE THREAD

**Issue by prashish14** [reactjs/redux#2644]
form closer has a  Linting issue in AddtoDo.js file in container comp..

Please fix it 

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

**What is the expected behavior?**

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

**Comment by timdorr** [comment]
Can you submit a PR? Thanks!
