### ISSUE TITLE
[Docs] statement about fetch function

### ISSUE THREAD

**Issue by miraage** [reactjs/redux#2648]
http://redux.js.org/docs/advanced/AsyncActions.html

> Note on fetch
> 
> We use fetch API in the examples. It is a new API for making network requests that replaces XMLHttpRequest for most common needs. Because most browsers **don't yet support it natively**, we suggest that you use isomorphic-fetch library:

http://caniuse.com/#search=fetch
Well, I think only IE11 requires a polyfill. What do you think on updating this section?

**Comment by timdorr** [comment]
Sure. Can you submit a PR? Thanks!

**Comment by miraage** [comment]
@timdorr If I will not provide a PR by a Monday, assume I was too lazy to make it. 😃
