### ISSUE TITLE
"getting started with Redux" course is broken

### ISSUE THREAD

**Issue by auval** [reactjs/redux#2656]
README.md points to:
https://egghead.io/courses/getting-started-with-redux
But it's broken (Error 500).
Please fix or upload to a mirror server.

**Comment by timdorr** [comment]
It's working fine for me. That's an external service, so we don't have any control over it.

**Comment by auval** [comment]
It was broken also a week ago when I tried, and today again when I filed the bug.
strangely, it is alive now.
