### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by paulspiteri** [reactjs/redux#2668]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
Typescript typings are out of sync with the Flow typings

```
export interface Dispatch<S> {
    <A extends Action>(action: A): A;
}
```

vs

```
declare type Dispatch<A: { type: $Subtype<string> }> = (action: A) => A;
```

in the typescript snippet above, what even is S? It's not used

Is this is a known issue?

I feel like it's supposed to be 
```
    interface Dispatch<A extends Action> {
      (action: A): A;
    }
```

**Comment by timdorr** [comment]
Check the `next` branch. It has revamped typings.
