### ISSUE TITLE
typescript: reducer function throws an error with "strictFunctionTypes" flag enabled

### ISSUE THREAD

**Issue by Lodin** [reactjs/redux#2691]
It is a bug I faced after updating Typescript to version `2.6.1` with `strictFunctionTypes` flag enabled. I have the following code: 
```typescript
interface MyCustomAction extends Action { 
    payload: string[];
}

interface MyCustomState { 
    payload: string[];
}

type MyCustomReducer = Reducer<MyCustomState>;

const reducer: MyCustomReducer = // here the problem appears: 
    (state = { payload: [] }, action: MyCustomAction) => {
        switch (action.type) {
            case 'MY_CUSTOM_TYPE':
                return { payload: action.payload };
            default:
                return state;
        }
     };
```
When I try to assign function definition to a `const reducer`, it fails with error:
```
Type '(state: MyCustomState, action: MyCustomAction) => MyCustomState' is not assignable to type 'Reducer<MyCustomState>'.
  Types of parameters 'action' and 'action' are incompatible.
    Type 'AnyAction' is not assignable to type 'MyCustomAction'.
      Property 'payload' is missing in type 'AnyAction'.
```
If I disable `strictFunctionTypes`, everything returns to normal. 

You can see the problem here: 
[Issue Example](http://www.typescriptlang.org/play/#src=interface%20Action%20%7B%0D%0A%20%20type%3A%20any%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20AnyAction%20extends%20Action%20%7B%0D%0A%20%20%2F%2F%20Allows%20any%20extra%20properties%20to%20be%20defined%20in%20an%20action.%0D%0A%20%20%5BextraProps%3A%20string%5D%3A%20any%3B%0D%0A%7D%0D%0A%0D%0Atype%20Reducer%3CS%3E%20%3D%20(state%3A%20S%2C%20action%3A%20AnyAction)%20%3D%3E%20S%3B%0D%0A%0D%0Ainterface%20MyCustomAction%20extends%20Action%20%7B%20%0D%0A%20%20%20%20payload%3A%20string%5B%5D%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20MyCustomState%20%7B%20%0D%0A%20%20%20%20payload%3A%20string%5B%5D%3B%0D%0A%7D%0D%0A%0D%0Atype%20MyCustomReducer%20%3D%20Reducer%3CMyCustomState%3E%3B%0D%0A%0D%0Aconst%20reducer%3A%20MyCustomReducer%20%3D%0D%0A%20%20%20%20(state%20%3D%20%7B%20payload%3A%20%5B%5D%20%7D%2C%20action%3A%20MyCustomAction)%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20switch%20(action.type)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20case%20'MY_CUSTOM_TYPE'%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20%7B%20payload%3A%20action.payload%20%7D%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20default%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20state%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%7D) (don't forget to enable `strictFunctionTypes` in `Options`). 

**Redux version**: 3.7.2

**Comment by timdorr** [comment]
This will likely be fixed in 4.0, when we land revamped typings. You can pull the index.d.ts from the `next` branch to test it out.
