### ISSUE TITLE
Failure in "npm run docs:prepare"

### ISSUE THREAD

**Issue by vkatsikaros** [reactjs/redux#2703]
**What is the current behavior?**

I am a nodejs noob, so this might not be a problem with the redux doc build configuration but with my environment. I apologize if here is not the right place to ask for this. 

I am on Ubuntu 16.04 with:
```
$ nodejs --version
v8.9.1
$ npm --version
5.5.1
```
I try to run this (as stated in the [CONTRIBUTING - Docs section](https://github.com/reactjs/redux/blob/master/CONTRIBUTING.md#docs)) but it fails
```
$ npm run docs:prepare

> redux@3.7.2 docs:prepare /home/vag/projects/redux
> gitbook install

You need to install "gitbook-cli" to have access to the gitbook command anywhere on your system.
If you've installed this package globally, you need to uninstall it.
>> Run "npm uninstall -g gitbook" then "npm install -g gitbook-cli"
```
I then run the suggestion
```
$ npm uninstall -g gitbook
up to date in 0.049s
$ sudo npm install -g gitbook-cli
/usr/bin/gitbook -> /usr/lib/node_modules/gitbook-cli/bin/gitbook.js
+ gitbook-cli@2.3.2
updated 1 package in 5.391s
```
but then `npm run docs:prepare` fails with the same message.

**Comment by timdorr** [comment]
You don't have to build the docs to contribute. Just submit a PR to change the markdown files.

**Comment by vkatsikaros** [comment]
@timdorr ah ok, I though I should make any build tests early (whatever these are). Thanks
