### ISSUE TITLE
Importing lodash as a dependency vs just the modules needed bloats js bundles

### ISSUE THREAD

**Issue by alaingoga** [reactjs/redux#2713]
**Do you want to request a *feature* or report a *bug*?**  Feature Request

**What is the current behavior?** Redux imports all of lodash

Not a bug. Just something that could potentially be optimized for smaller JS bundle files.

**What is the expected behavior?** Import only needed modules

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?** I see this on v3.7.2. Not sure if it's been like that from the get go.

**Comment by markerikson** [comment]
Redux 3.x currently uses a Babel plugin [that rewrites imports of `lodash` to be `lodash-es`](https://github.com/reactjs/redux/blob/e09b2d1ee4bf4be3499f05d87d57c12fa849647f/build/use-lodash-es.js).  We don't import all of Lodash in an actual build, which you can confirm by looking at [the 3.7.2 UMD build](https://unpkg.com/redux@3.7.2/dist/redux.js) and [the 3.7.2 ESM version of `createStore](https://unpkg.com/redux@3.7.2/es/createStore.js).

Also worth noting that in the 4.0 `next` branch, we're currently planning to drop the Lodash dependency and keep `isPlainObject` in-house again.  See #2599 .
