### ISSUE TITLE
update docs to use babel-preset-env

### ISSUE THREAD

**Issue by hozefaj** [reactjs/redux#2735]
**What is the current behavior?**
The current docs have example of using `es2015` as the babel preset. 

**What is the expected behavior?**
Better form would be to use [`babel-preset-env`](https://github.com/babel/babel/tree/master/packages/babel-preset-env) rather. Since this can confuse new folks to on whether to use `es2015`...`es2016`....or what?
Rather have the docs updated to use `env` instead.

Happy to send a PR, if this change is okayed.

**Comment by markerikson** [comment]
Yes, that would be a good idea - we'd definitely take a PR to update that.

**Comment by hozefaj** [comment]
Cool. Will send one later today.

**Comment by hozefaj** [comment]
The Contributing guide says to [publish](https://github.com/reactjs/redux/blob/master/CONTRIBUTING.md#publishing-the-docs) & [cleaning](https://github.com/reactjs/redux/blob/master/CONTRIBUTING.md#cleaning-the-docs) the doc, however I would assume that you would that to happen only after the PR's are merged.

@markerikson Can you please let me if I need execute those 2 commands or they are meant to be done at a time when bunch of updates are released.
