### ISSUE TITLE
real-world example is broken

### ISSUE THREAD

**Issue by arch-mage** [reactjs/redux#2738]
real-world example is broken for [src/containers/Root.prod.js][1] ([permalink][2]) file in master branch.

This snippet:

```javascript
const Root = ({ store }) => (
  <Provider store={store}>
    <Route path="/" component={App} />
      <Route path="/:login/:name"
             component={RepoPage} />
      <Route path="/:login"
             component={UserPage} />
  </Provider>
)
```

maybe should be like this:

```javascript
const Root = ({ store }) => (
  <Provider store={store}>
    <div>
      <Route path="/" component={App} />
        <Route path="/:login/:name"
               component={RepoPage} />
        <Route path="/:login"
               component={UserPage} />
    </div>
  </Provider>
)
```

[1]: https://github.com/reactjs/redux/blob/master/examples/real-world/src/containers/Root.prod.js
[2]: https://github.com/reactjs/redux/blob/ecdd163d9922893d0933efc4779551d933e63882/examples/real-world/src/containers/Root.prod.js

**Comment by timdorr** [comment]
A PR would be helpful.
