### ISSUE TITLE
Typing redux-thunk with redux v4

### ISSUE THREAD

**Issue by nenadalm** [reactjs/redux#2748]
Hi. Previously `Dispatch` had generic parameter for state, but currently it has only parameter for action. `redux-thunk` relies on the state parameter to type the action properly: https://github.com/gaearon/redux-thunk/blob/4f96ec0239453623adde857b7e7ad8c4f2897bf1/index.d.ts#L4

Maybe `Dispatch` should have 2 parameters? One for state and another for action?

**Comment by timdorr** [comment]
`dispatch()` only takes a action argument anyways. If you're redefining its signature, that's happening via middleware (like with redux-thunk). Hence, you should put the change there.

It looks like redux-thunk's typings probably need to be updated for the changes over here. They haven't been touched in years and were built in the 1.x era.

**Comment by NathanNZ** [comment]
@nenadalm https://github.com/gaearon/redux-thunk/issues/169
Discussion is ongoing here - note that the suggestion I have posted is against the version currently in master. See @Cryrivers's comment for the current redux@next typings.

Would be nice to have beta packages for both, but for now I'm just doing horrible things with my node_modules folder to get the typings working (as I have not found a way to get middleware working without allowing to assign a generic against it) :sweat_smile:

**Comment by Cryrivers** [comment]
I already created a PR for this. Please check gaearon/redux-thunk#180.

**Comment by timdorr** [comment]
Looks like this is a bug with redux-thunk's typings, not ours. Track @Cryrivers's PR for updates.
