### ISSUE TITLE
should `dispatch` wait until the next event loop to notify its listeners?

### ISSUE THREAD

**Issue by warren-bank** [reactjs/redux#2751]
Hi. Today is my first day learning about redux, so maybe this is a dumb question. I was walking through the code in `applyMiddleware` to see how it all works. It wasn't immediately obvious to me, but I understand it now.

In tracing that code, I noticed something that seemed a bit off. So I just wanted to share the observation..

```javascript
function applyMiddleware(...middlewares) {
  let chain = middlewares.map(middleware => middleware({getState, dispatch}))
  // chain is now an Array of functions: (next) => (action) => {}

  let dispatch = compose(...chain)(store.dispatch)
```

To quickly summarize the path the code takes:
* assuming `applyMiddleware` is called with: `(middleware_1, middleware_2, ..., middleware_N)`
* `dispatch(action)` calls: `middleware_1(next_1)(action)`
  * where `next_1` is a reference to: `middleware_2(middleware_3(...(middleware_N(store.dispatch))))`
* `next_1(action)` calls: `middleware_2(next_2)(action)`
  * where `next_2` is a reference to: `middleware_3(...(middleware_N(store.dispatch)))`
* this iterative process continues until the last middleware in the chain is reached: `middleware_N`
  * where `next_N` is a reference to: `store.dispatch`

So:
* `middleware_1` executes its code up until it calls `next_1(action)`
* `middleware_2` executes its code up until it calls `next_2(action)`
* ...
* `middleware_N` executes its code up until it calls `next_N(action)`
* `store.dispatch`:
  * runs the root reducer
  * notifies its listeners of any state change
  * returns
* `middleware_N` completes the execution of its code resuming from after its call to `next_N(action)`
* ...
* `middleware_2` completes the execution of its code resuming from after its call to `next_2(action)`
* `middleware_1` completes the execution of its code resuming from after its call to `next_1(action)`

The possible issue that I see is that `store.dispatch` notifies its listeners before the middleware has the opportunity to complete its execution.
* if a listener dispatches additional actions in response to the new state, then the middleware begins to execute the new action before it has the opportunity to finish executing the previous action
* imho, it seems to me that there should really be a `nextTick()` or `setTimeout(0)` before the listeners are notified

_example_:

```javascript
function dispatch(action) {
  currentState = currentReducer(currentState, action)

  setTimeout(() => {
    for (let i = 0; i < nextListeners.length; i++) {
      nextListeners[i]()
    }      
  }, 0)
}
```

Thoughts?

**Comment by timdorr** [comment]
This is intentional. It allows middleware, through ordering of operation, to have control when certain things run before or after subscribers are called. If it needs to either set up something for subscribers or tear something down after subscribers are finished, this allows it to do so. Pushing the notification to the next tick would remove this control.

**Comment by timdorr** [comment]
Also, while not disallowed, it's discouraged to dispatch in a subscriber. That could easily lead to infinite loops that are hard to track down. If anything, you could setTimeout/nextTick that dispatch yourself to prevent that from happening.
