### ISSUE TITLE
Cannot dispatch actions that are properties of an object

### ISSUE THREAD

**Issue by Nigh7Sh4de** [reactjs/redux#2752]
**Do you want to request a *feature* or report a *bug*?**  
bug

**What is the current behavior?**
In an action creator, I am importing an object that has other action creators as properties. I am then trying to dispatch an imported action creator and encounter an error: `Cannot read property 'getAll' of undefined`. However, when I import the function directly (`import { getAll } ...`) and pass it alone rather than explicitly as a property of an object it works without issue.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
For example:
*UserActions:*
```
import EventActions from './EventActions'

export function signInSuccess(user) {
  return dispatch => {
    dispatch({ type: USER_SIGN_IN_SUCCESS, user })
    dispatch(EventActions.getAll(user)) //<-- this throws an error in the file 'regenerator-runtime/runtime.js'
  }
}

```

**What is the expected behavior?**
I'd like to be able to import external action creators as properties of an object to maintain consistency in my application. I'd like to be able to `dispatch(SomeObject.someCreator(props))` without issues.

P.S: the error is never actually getting `console.error`ed, I noticed it when stepping into my code and encountering the line `return { type: "throw", arg: err };` in some form of `tryCatch` wrapper function in *regenerator-runtime/runtime.js*.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**
Here is a snippet of my *package.json*:
```
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0"
```

**Comment by timdorr** [comment]
This isn't a redux issue. It's an issue with how you're using ES module imports.
