### ISSUE TITLE
Spellcheck documentation in CI or as part of `npm run docs:publish`

### ISSUE THREAD

**Issue by tbroadley** [reactjs/redux#2778]
I've created [a command-line tool](https://github.com/tbroadley/spellchecker-cli) that checks Markdown and text files for spelling mistakes and some types of grammatical errors. I think it could be useful to run this tool on Redux's documentation during CI or as part of the `docs:publish` NPM script. If you agree, I'm happy to open a PR.

**Comment by timdorr** [comment]
I'd worry it would have too many false positives that we would have to work around. 

How about a PR with any changes you can find from running the tool on the current docs?

**Comment by tbroadley** [comment]
The tool can take a user-defined dictionary and combine it with the standard dictionary for the specified language. This would make it easy to ignore Redux-specific terminology that would otherwise be flagged incorrectly.

I'll definitely submit a PR to fix the issues I found.
