### ISSUE TITLE
Async Reddit Example is Broken

### ISSUE THREAD

**Issue by Hum4n01d** [reactjs/redux#2780]
**What is the current behavior?**

- Clone the Redux repository
- `npm install` 
- `cd examples/async`
- `npm install`
- `npm start`

Create-react-app throws an error:

```
Failed to compile
./src/containers/App.js
  Line 9:   'propTypes' is not defined           no-undef
  Line 29:  'handleChange' is not defined        no-undef
  Line 33:  'handleRefreshClick' is not defined  no-undef
```

**What is the expected behavior?**

The app should load normally.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

The problem is not with the Redux library

**Comment by asso1985** [comment]
Cannot reproduce. Works perfectly.

clone repo
cd examples/async
npm install
npm start

**Comment by timdorr** [comment]
Same here. Check your setup.

**Comment by Hum4n01d** [comment]
Interesting, could this be because I ran `npm install` on the parent redux repository first?

**Comment by timdorr** [comment]
Yes, that can interfere. Especially if you're not using npm@5.
