### ISSUE TITLE
Not Found problem

### ISSUE THREAD

**Issue by Tamerlan1993** [reactjs/redux#2782]
I first search non-github username.
this comes after searching 
[Not found correct image](http://www.imgim.com/2018-01-0513_28_24-real-world-codesandbox.png)
but when I type correct github username not found message is not disappear
[Not Found did not disappear](http://www.imgim.com/2018-01-0513_35_49-real-world-codesandbox-3.png)

**Comment by timdorr** [comment]
You're supposed to click the Dismiss button.
