### ISSUE TITLE
Observable state

### ISSUE THREAD

**Issue by tsamsiyu** [reactjs/redux#2792]
Hi, I have some thoughts inspired by mobx to provide possibility for faster comparing states of storage.

What do I think to make: add possibility to say to the redux to wrap the storage obtained from reducer by observable. By 'observable' I mean defining 'get' and 'set' properties hooks for listening its access requests. 

In process of making state observable we can specify for every property its access path in the state store object. Next, when the properties provided by `mapStateToProps` will be accessed, component will know paths of its dependencies, and, when subscribe will be called, component will be able to compare not the whole state it receives but known to it paths of dependencies. Thus we will reduce the number of comparisons. For large stores it have to significantly reduce the load.

Before trying to code this I wanted to ask you maybe you have already tried to implement this and that was not so useful as seems? Or for some reasons it's impossible to implement. I mean I just want to be sure that this approach is not investigated and I will not waste my time in vain.

**Comment by markerikson** [comment]
You can already do this.  The store objects returned by `createStore` support `Symbol.observable`, and even without that, it's easy to create an observable stream that reads `getState` with each dispatch.  See [the implementation in `createStore` for reference](https://github.com/reactjs/redux/blob/4c9cbd15839d153e4aee9f935c11ec9ca4af10b3/src/createStore.js#L219-L256).
