### ISSUE TITLE
redux/examples/shopping-cart fails to start

### ISSUE THREAD

**Issue by mprevot** [reactjs/redux#2793]
npm start fails:

> shopping-cart@0.0.1 start I:\www\redux\examples\shopping-cart
> react-scripts start

'react-scripts' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shopping-cart@0.0.1 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the shopping-cart@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\soleil\AppData\Roaming\npm-cache\_logs\2018-01-13T00_00_03_776Z-debug.log

following the pointer:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\soleil\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v8.9.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle shopping-cart@0.0.1~prestart: shopping-cart@0.0.1
6 info lifecycle shopping-cart@0.0.1~start: shopping-cart@0.0.1
7 verbose lifecycle shopping-cart@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle shopping-cart@0.0.1~start: PATH: C:\Users\soleil\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;I:\www\redux\examples\shopping-cart\node_modules\.bin;I:\IntelSWTools\compilers_and_libraries_2018.1.156\windows\mpi\intel64\bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\mpirt;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32_win\mpirt;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32_win\compiler;C:\Program Files\Microsoft MPI\Bin\;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\mpirt;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32_win\mpirt;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32_win\compiler;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files (x86)\Intel\OpenCL SDK\6.3\bin\x64;C:\Program Files (x86)\Intel\OpenCL SDK\6.3\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\6.3\bin\Pin;C:\Program Files (x86)\Intel\OpenCL SDK\6.3\bin\GTPin;I:\IntelMediaServer\Software Development Kit\bin\x64;I:\IntelMediaServer\Software Development Kit\bin\win32;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;I:\MATLAB\R2017b\bin;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\nodejs\;C:\Users\soleil\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code Insiders\bin;C:\Program Files\Handle;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.11.25503\bin\HostX64\x64;I:\IntelSWTools\compilers_and_libraries_2018.0.124\windows\redist\intel64_win\tbb\vc_mt;"I:\Nvidia\Cuda\9.1\libnvvp;I:\Nvidia\Cuda\9.1\bin;";I:\opencv\bin\Debug;I:\opencv\bin\Release;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\;C:\Python27amd64;C:\Users\soleil\AppData\Local\GitHubDesktop\bin;C:\Program Files\CMake\bin;C:\Users\soleil\AppData\Roaming\npm;C:\Program Files (x86)\Common Files\Acronis\TibMounter64;C:\Program Files\Procyon;C:\Program Files\ikvm\bin;
9 verbose lifecycle shopping-cart@0.0.1~start: CWD: I:\www\redux\examples\shopping-cart
10 silly lifecycle shopping-cart@0.0.1~start: Args: [ '/d /s /c', 'react-scripts start' ]
11 silly lifecycle shopping-cart@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle shopping-cart@0.0.1~start: Failed to exec start script
13 verbose stack Error: shopping-cart@0.0.1 start: `react-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\soleil\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\soleil\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid shopping-cart@0.0.1
15 verbose cwd I:\www\redux\examples\shopping-cart
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\soleil\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.9.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error shopping-cart@0.0.1 start: `react-scripts start`
22 error Exit status 1
23 error Failed at the shopping-cart@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by timdorr** [comment]
You need to npm install first.
