### ISSUE TITLE
Discussion: Gaining clarity on "business logic" for FAQs

### ISSUE THREAD

**Issue by Dubes** [reactjs/redux#2796]
**Where do I put business logic in Redux** is a question which still perplexes users. We do have an[ FAQ entry](https://redux.js.org/docs/faq/CodeStructure.html#structure-business-logic) for it, but with no acceptable definition of _what_ constitutes "Business Logic", it is hard to give concrete advice.

This issue is in response to this [tweet](https://twitter.com/acemarke/status/947563352481558533) . In here, we can collect some real world examples of _client side logic_ and work down that list into what could be construed as business logic. 

I am listing below the various kinds of logic I have seen/implemented in my career so far. 

**UI Visibility or behavior**
_Use Case_ : Show/Hide some sections or fields based on the users roles, permissions.
_Notes_: This can get complicated, with Attribute Based Access Control or other such complex requirements. I personally view it as a representation of UI state and handle it as such. 
I usually come across two flavors of this, Application level UI state (for e.x. user is not allowed to edit anything, or view the comments section) or Component/Screen based state (for e.x. user is not allowed to change some field, if the domain object is in state "submitted") . 

_Use Case_ : Change the sections to follow based on the data.
_Notes_ : In some BI or insights kind of applications, you may want to direct a user down a separate path based on the path they have taken and data that is coming in. Some example can be: If data quality/volume is not good enough to display a chart for user to narrow the scope further, take them directly to the next section. Or highlight some entries of significance in the incoming data in a separate section.

**Theme: Data Checks**
_Use Case_ : Form validation.
_Notes_ : Some validation can be simply field level ones, but some can get tricky, for e.x. in a data entry form with many sections, the validity of a field may depend on multiple data points contained in other sections. For e.x. you can choose any dates in section 2, but if a particular field in section 1 is set to X, then your dates may be limited to 45 days only.

**Theme: Filtering and Sorting**
In huge data tables (tables with many columns or complex columns), users may like to filter and sort in arbitrary fashion and it too can get complicated soon.

**Disclaimer**: 

- I am not using Redux at the moment, React state management is fine for me at the moment.
- This is not an exhaustive list, I will come back and add some more

**Comment by alpox** [comment]
When I hear business logic I usually think about data manipulation / transformation.

**UI Visibility or behavior**
Showing / Hiding things based on some roles or permissions belongs in my eyes to the UI representation, not really the business logic. In this case i would as example create a HOC which allows to hide or disable some component which it wraps based on some permissions which it gets from the redux store or even localStorage (If encrypted into a JWT token which is located in localStorage)

```
const PrivateComponent = withRole("admin", ROLE_EFFECT_HIDE)(SomeComponent)
```
Which is more just a matter of how to show something.


**Theme: Data Checks**
This, I believe is more on the edge to business logic because it handles form data directly, but its there for the validation of the data and not for its manipulation. Here i'm open for arguing.

As for a realworld example I can refer to some [prototypeI built.

**Comment by markerikson** [comment]
Relevant set of tweets from Francois Ward: https://twitter.com/FwardPhoenix/status/952971237004926977

> I think we need to move away from that terminology altogether. People were thought to think of "business logic" because of design patterns in the form "Rendering, Controller, Everything else", with the "everything else that doesn't fit" being the "business logic"  
> In patterns like Redux (and many others), things are split by pattern. Eg: a reducer is anything that can be done synchronously from original state and an action. It may or may not be "business logic", but it's split more by lifecycle than concept.  
> "Can it be done with just dispatch arguments?" -> action creator. "Can it be done with previous state and action?" -> reducer "Can it be done from just state?" -> probably a component. So "where does the business logic lives" -> everywhere.
