### ISSUE TITLE
Idiom for dependent async calls

### ISSUE THREAD

**Issue by steveworley** [reactjs/redux#2817]
Hi everyone, just looking for some guidance on the best approach to handle dependent async calls to build objects in the state. I've been looking around and can't seem to find anything relating directly to this use case.

We have a normalised API that follows the HAL specification, field references are returned as links which require an additional request to the server to get the data. We want to build a list of these objects in the state and update this state when we have fetched the additional information.

The data we're looking for is something like:

```
{
   1: {
      title: 'Test',
      image: 'http://test.com/path-to-image.jpg'
   }
}
```

and the API responds like

```
{ 
   1: { 
      title: 'Test',
      image: { 
         id: '123',
         links: { 
             href: 'http://api.com/field/123'
         }
    }
}
```

We're currently using an action on `componentDidMount` that dispatches two actions to instruct the component to update. It looks like (psuedo code for brevity):

```
loadApiContent() => {
    return (dispatch) => {
       return fetch('/content')
         .then(res => res.json())
         .then(json => {
             dispatch(receiveContent(json));
             const fieldRequests = [];
             Object.keys(json).forEach(item => {
                 fieldRequests.push(fetch(json[item].links.field_image.href).then(res => res.json));
             });
             Promise.all(fieldRequests)
                .then(values => {
                     values.forEach(result => {
                         json[result.id].image = result.image.value;
                     });
                    dispatch(receiveContent(json));
                });
         })
}
```
Receive content triggers passes the values returned from the API to the reducer which creates a new state like:

```
if (action.type === 'RECEIVE_CONTENT') {
   return { ...state, { data: action.data }};
}
```

The issue I keep running into is a state mutation error from the second dispatch. Neither my `mapStateToProps` nor the reducer do any direct manipulation of state and always clone the state to pass the updated object through.

The error returned is 
```
Error: A state mutation was detected between dispatches, in the path `loadContentReducer.data.1.image`.
```

In this case, is it recommended that we use two different props on the component to manage the different API return states? Should we only send one dispatch after the image requests have completed? Should we modify the returned data object to map `image` to a promise that can be resolved when it's printed?

Thanks for your time.

**Comment by markerikson** [comment]
That code does look like it's probably mutating, with the combination of the initial `dispatch(receiveContent(json))` and `json[result.id].image = result.image.value;`.  I would suggest dispatching a second action containing a lookup table of the result IDs and the result images instead, without modifying `json`.
