### ISSUE TITLE
npm format fails on Windows

### ISSUE THREAD

**Issue by sstarrAtmeta** [reactjs/redux#2828]
**Do you want to request a *feature* or report a *bug*?**  
bug

npm format fails on Windows
`[error] No matching files. Patterns tried: '{src,test}/**/*.js' !**/node_modules/** !./node_modules/**`
npm-debug.log states the following fails:
`prettier --write '{src,test}/**/*.js'`
Prettier and options appear to have been added in this pull request: https://github.com/reactjs/redux/pull/2676

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

`format` command was not present in v3.7.2. However, `build` succeeded in v3.7.2 but does not in my current version.

Current versions:
Redux version "4.0.0-beta.1"
Microsoft Windows [Version 10.0.16299.192]
node v8.9.4
npm 5.6.0

**Comment by timdorr** [comment]
Is there a cross-platform globbing tool we can use?

**Comment by eps1lon** [comment]
No need for that. The glob pattern syntax was wrong. PR is under way.

**Comment by sstarrAtmeta** [comment]
Neat, so it was a question of single quote vs double quote in the arguments?
