### ISSUE TITLE
Feature request: Pass action to each subscribe's handler

### ISSUE THREAD

**Issue by ulivz** [reactjs/redux#2833]
**Do you want to request a *feature* or report a *bug*?**  

Sure, I am requesting a feature.

As we all know, the`store.subscribe(()=>{ })` method is almost used for those conditions that we want to do some common operations after state change. 

However, usually, we still want to know which action triggered the state change, because we always want to have more privileges in the subscribe‘s handler. the `action` is the first part we think of.

**What will the API look like?**

```js
store.subscribe((action) => {
    // ... 
})
```

**Some concerns**

- If passed the whole action's plain object, the listener should be prevented from changing the action's any field value (**Readable**). a quick solution is to use `Object.freeze()` to freeze the `action`, or having better solution, welcome to give it.

**Comment by timdorr** [comment]
https://redux.js.org/docs/faq/DesignDecisions.html#does-not-pass-state-action-to-subscribers
