### ISSUE TITLE
Remove duplicate listeners

### ISSUE THREAD

**Issue by throwarray** [reactjs/redux#2834]
**Do you want to request a *feature* or report a *bug*?**  bug
**What is the current behavior?** Removes first listener found with indexof
**What is the expected behavior?** Remove duplicate listeners or don't allow them.

https://github.com/reactjs/redux/blob/master/src/createStore.js#L135

EDIT: Since the listeners are meant to be single subscriptions, it's better to just close over the original listener?.

**Comment by markerikson** [comment]
It already did close over the original listener, as passed in to `subscribe()`.  There are no "duplicate listeners".  The point of `unsubscribe()` is to remove that one listener callback.
