### ISSUE TITLE
QUESTION: Is this project done?

### ISSUE THREAD

**Issue by oriSomething** [reactjs/redux#2835]
And by that, I mean are there any plans to add features?
Or is this project considered as done, and only will receive security / bug fixes?

**Comment by timdorr** [comment]
A project is never "done". I don't think we have anything major being planned by anyone, but large changes are always welcome to be discussed.

**Comment by oriSomething** [comment]
@timdorr I've thought about adding action that doesn't dispatch anything to listeners and doesn't change anything in the store.
I know it seems weird and I can have a longer description but it can very useful with some middlewares.
I'm sorry if it's already exist in the codebase, but I didn't find. I've found some middlewares, but it seems, at least to me, as something that should be part of the Redux codebase itself

**Comment by markerikson** [comment]
@oriSomething : that sounds like something that can be handled as a middleware or store enhancer, and in fact there's already [many existing addons that can modify the store change event subscription process](https://github.com/markerikson/redux-ecosystem-links/blob/master/store.md#batching-and-notifications).

**Comment by oriSomething** [comment]
@markerikson I think you didn't read my comment. Because I said I know there are middlewares that do that

**Comment by markerikson** [comment]
Yes, and I'm saying that middlewares and the store enhancers are the correct way to handle this :)

Redux was deliberately created to be a minimal API that could be extended.  Middlewares allow intercepting and modifying dispatched actions, while store enhancers are used to provide altered versions of the store object API that wrap up the base store.  So, if you want to change dispatching or subscription behavior, you don't have to modify the Redux core - you can do it via middlewares and store enhancers.
