### ISSUE TITLE
Why doesn't Redux have a complete solution for solve itself own problem?

### ISSUE THREAD

**Issue by webvini** [reactjs/redux#2836]
Hello everyone.

I have deepest studied React and Redux and now come up an question.
We have to add **Reselect** and **redux-thunk** in our project, for example. But, I don't understand yet the real reason for I add these vendors too.

May we add all these improvements directly into Redux? Otherwise, new vendors will born.

Thank you

**Comment by johanneslumpe** [comment]
Adding things into core that not everyone needs or wants doesn’t make a lot of sense. It will bloat the core and lead to larger bundle sizes for all consumers. Thunks were originally baked into redux but got split out later into their own module.

One of the strengths of redux is its modularity and that it doesn’t prescribe how you have to write your selectors or how you want to handle asynchronous tasks.

**Comment by timdorr** [comment]
Exactly. Redux is intentionally small so as to not be prescriptive about how you build your app. Handling side effects, like async, is unique to an application's needs. We don't want to include anything that forces you to use a certain structure counter to those needs. 

https://redux.js.org/docs/introduction/CoreConcepts.html

**Comment by markerikson** [comment]
Yep. Redux was deliberately built as a small extensible core and designed to promote an ecosystem of addons.  See [my ReactBoston talk on the Redux ecosystem](http://blog.isquaredsoftware.com/2017/09/presentation-might-need-redux-ecosystem/) for more information, as well as my post [The Tao of Redux, Part 1: Implementation and Intent](http://blog.isquaredsoftware.com/2017/05/idiomatic-redux-tao-of-redux-part-1/).

**Comment by webvini** [comment]
Hi @johanneslumpe  @timdorr @markerikson

Make a sense for me now
 
Thank you so much for your feedback guys.
