### ISSUE TITLE
[discussion] combineReducers too greedy about state's shape

### ISSUE THREAD

**Issue by Andarist** [reactjs/redux#2841]
Sample code (taken from docs, slightly changed):
```js
const combinedReducer = combineReducers({
    posts,
    comments
});

const featureReducers = createReducer({}, {
    ADD_COMMENT : addToCalculatedView,
};

const rootReducer = reduceReducers(
    combinedReducer,
    featureReducers
);
```

**What is the current behavior?**

If `featureReducers` does manage other state key than posts and comments we''ll end up with a warning that the other key is unexpected.

**What is the expected behavior?**

Imho this greatly prevents some composition techniques that could be used in combination with `combineReducers`. I understand it's considered a good default as helper for beginners, but I feel removing this "limitation" would make this helper more composable in wider range of scenarios.

**Comment by markerikson** [comment]
This has come up a number of times in the past (afraid I don't have time to dig up links to prior discussion atm, but there should be several earlier issues on the same topic).  There's several trains of thought here:

- `combineReducers` is deliberately opinionated as the "default" approach
- One possible approach would be to allow `combineReducers` to take some options that turn off warnings like that, but it's already getting kind of complex
- Another approach would be to split up `combineReducers` into smaller composable pieces, and allow swapping out pieces like iterating over objects (which also relates to the often-requested "full state as third arg" kind of idea)
- The other solution is to use your own alternative to `combineReducers` instead.  If you strip out the warnings and such, it's really a trivial function.  There's numerous alternatives out there already, or you can write your own, and we _do_ encourage people to write their own custom reducer logic for their own specific needs.

This is not a particular priority for us right now, and not something we plan to work on.  If someone wants to submit a PR that adds options or implements the "split up into smaller functions" approaches, I can look at the PR as a possibility.
