### ISSUE TITLE
Allow to listen for specific parts of state / reducers in store.subscribe call

### ISSUE THREAD

**Issue by valf** [reactjs/redux#2847]
It would be beneficial to have this option, so that it can be further implemented in react-redux, which ultimately should make it more performant. 

For example:
```
const reducers = { reducer1, reducer2 };
const store = createStore(reducers, initialState);
store.subscribe("reducer1", () => {
   // is not called when reducer2 returns a new reference
});
```

**Comment by markerikson** [comment]
This or similar changes have been requested many times, and we have no plans to implement this right now.  Please see: 

- [the Redux FAQ entry on passing state or actions to subscribers](https://redux.js.org/faq/design-decisions#why-doesn't-redux-pass-the-state-and-action-to-subscribers)
- [the Redux FAQ entry on reducing React re-renders](https://redux.js.org/faq/react-redux#why-is-my-component-re-rendering-too-often)
- the [Redux Addons Catalog section of libraries for subscribing to state updates](https://github.com/markerikson/redux-ecosystem-links/blob/master/store.md#store-change-subscriptions)
