### ISSUE TITLE
Include a POST request in the real world example.

### ISSUE THREAD

**Issue by YPCrumble** [reactjs/redux#2853]
Thanks all for this great library!

Currently (as far as I can tell) the Real World Example only includes GET requests. I found it because I'm struggling with the best practice for implementing a POST request. I'd love to include a POST request (perhaps starring the redux repo?) as an example in this example.

I'm quickly learning redux and would love to contribute if it's something the maintainers would appreciate!

**Comment by markerikson** [comment]
The actual mechanics of making an AJAX call are honestly not a concern of Redux itself, in the same way that AJAX calls are not directly a concern of React either.  Also, the sequence of "make an AJAX call -> dispatch a Redux action based on the response" is the part that really matters.  That's the same regardless of whether you're doing a GET, POST, PUT, or DELETE.

I'd suggest reading through some of the articles in the [React and AJAX](https://github.com/markerikson/react-redux-links/blob/master/react-ajax.md) section of my [React/Redux links list](https://github.com/markerikson/react-redux-links).  If you have more questions, the [Reactiflux community on Discord](https://reactiflux.com) is a great place to ask for help.
