### ISSUE TITLE
Update connected components testing docs

### ISSUE THREAD

**Issue by devonJS** [reactjs/redux#2856]
I was testing some of my React components wrapped in a Redux connect and referred to your documentation [here](https://github.com/reactjs/redux/blob/master/docs/recipes/WritingTests.md#connected-components)

There seems to be another way to accomplish this without doing multiple exports of your React component (which worked better in my situation,  hopefully for others as well), covered in a [discussion](https://github.com/airbnb/enzyme/issues/208) over at Enzyme's repository.

Basically from that discussion, Enzyme's [instance](http://airbnb.io/enzyme/docs/api/ShallowWrapper/instance.html) method returns a ReactComponent and combined with [dive](http://airbnb.io/enzyme/docs/api/ShallowWrapper/dive.html), you could grab the ReactComponent that is wrapped in Redux's connect, which I've accomplished in my tests.

What do you think of this method of testing a connected component? Just wanted to share that with others who might run into the same issues that I did, would be more than happy to help write the documentation for it.

**Comment by timdorr** [comment]
Sure, that may work for a specific library that provides that feature. I'm not sure if there is an equivalent for react-test-renderer. 

If you want to add this to the docs, a PR would be the best way to get it in. We can discuss specific changes that way.
