### ISSUE TITLE
fetch JSON (http get) not working

### ISSUE THREAD

**Issue by ulisesinfante** [reactjs/redux#2863]
# fetch JSON vs simple import data.json

###  I don't like run JSON from "import data from './data.json'", I want run it using http get, but it not show nothing, Where is the error? 

`
import React, { Component } from 'react';
import { BrowserRouter as Router, Route, Link } from "react-router-dom";

class App extends Component {
  constructor(props) {
    super(props);

    this.state = {
      hits: [],
    };
  }

  componentJSON() {
    fetch('https://jsonplaceholder.typicode.com/posts')
    .then(res => res.json())
    .then(data => this.setState({ hits: data.hits }))
  }

  render() {

    const { hits } = this.state;
    
    return (
      <Router> 
        <div className="App">  
     
          {/* LOAD JSON */}
          <ul>
            {hits.map(hit =>
              <li key={hit.title}>
                {hit.title}
              </li>
            )}
          </ul>

        </div>
      </Router>
    );
  }
}

export default App;
`

**Comment by Majem** [comment]
[https://jsonplaceholder.typicode.com/posts](url) doesn't have property hits wchich you use in componentJSON method. I think you want bind all fetched data to hits state.

```
componentJSON() {
        fetch('https://jsonplaceholder.typicode.com/posts')
            .then(res => res.json())
            .then( data => this.setState({ hits: data }));
    }
```

**Comment by ulisesinfante** [comment]
Yes, I want show JSON, just it,

StackOverflow says:

1. fetch is async action, so you need correct scope of this, Use arrow function

`componentJSON = () => { // arrow function
    fetch('https://jsonplaceholder.typicode.com/posts')
    .then(res => res.json())
    .then(data => this.setState({ hits: data.hits }))
  }`

2. In your render() function you should delcare your constant like this:

`const { hits } = this.state.hits;
`

**Comment by Majem** [comment]
Yes, fetch function is written correctly but your data object doesn't have 'hits' property

You should change this

`this.setState({ hits: data.hits })`

for this
`
this.setState({ hits: data})`

And now render function should list all fetched posts

**Comment by ulisesinfante** [comment]
this.setState({ hits: data}) not working

#CONSOLE:

./src/App.js
  Line 59:  'hits' is not defined  no-undef

Search for the keywords to learn more about each error.

#STACKOVERFLOW say:

In your function you are assuming that the context is the class, but its not, its not how js works, so when you are trying to use this.setState it would not work because the context of the function doesnt have any function called setState. A simple way of solving this is binding the function to the class, by simply adding the following line in the ctor:

this.componentJSON = this.componentJSON.bind(this);

"But I dont understand it"

**Comment by Majem** [comment]
Insert the entire app.js on Git repos or another page where i can look on your code

**Comment by ulisesinfante** [comment]
```
import React, { Component } from 'react';

import { BrowserRouter as Router, Route, Link } from "react-router-dom";

class App extends Component {

    // 1.JSON
    constructor(props) {
      super(props);
  
      this.state = {
        items: [],
      };
    }
    // 2. JSON
    componentJSON() {
      fetch('https://jsonplaceholder.typicode.com/posts')
      .then(res => res.json())
      .then(data => this.setState({ items: data.items }))
    }

  render() {
    
    // fetch("https://jsonplaceholder.typicode.com/posts")
    //   .then(response => response.json())
    //   .then(data => {
    //     console.log(data);
    //     this.product = data;
    // });
    // this.componentJSON = this.componentJSON.bind(this);
    this.setState({ items: data})

     // 3. JSON
    //  const { items } = this.state;

    return (
      <Router> 
        <div className="App">  

          {/* HEAD */}
          <Route path="/" component={header} />

          {/* ROUTER */}
          <p className="App-intro">
            <Link to="/about">About</Link>
            <Link to="/contact">Contact</Link>
          </p>

          {/* LOAD JSON */}

          <ul>
            {items.map(item =>
              <li key={item.title}>
                {item.title}
              </li>
            )}
          </ul>

          <ul>
            {
              data.map((item) => {
                // KEY es la Palabra clave(id) de la posicion del json
                // que invocas. 
                return <li key={item.id}>{item.id} - {item.title}</li>
              })
            }
          </ul> 

          {/* SHOW ROUTER */}
          <Route path="/about" component={about} />
          <Route path="/contact" component={contact} />

        </div>
      </Router>
    );
  }
}

export default App;

```

**Comment by Majem** [comment]
I wrote only code which i corrected

```
import React, { Component } from 'react';


class App extends Component {
    constructor(props){
        super(props);
        this.state = {
            items : []
        };

        // You should bind this object to componentWillMount method, other setState was not working
        this.componentWillMount = this.componentWillMount.bind(this);
    }


    // This method is call before component will mounted
    componentWillMount() {
        fetch('https://jsonplaceholder.typicode.com/posts')
            .then(res => res.json())
            .then( data => this.setState({ items : data }) );
    }

    render() {

        const items = this.state.items; // in your exampl = const { items } = this.state;

        return (
            <ul>
                {items.map(item =>
                    <li key={item.title}>
                        {item.title}
                    </li>
                )}
            </ul>
        );
    }
}

export default App;
```

**Comment by ulisesinfante** [comment]
Ok, I go to try it.

**Comment by ulisesinfante** [comment]
Working!!! (**anyway REACT need do it easier like Angular 4.5/5**)

My problem was on:

1. Call this.componentWillMount = this.componentWillMount.bind(this); intro _constructor_
2. .then( data => this.setState({ _items : data_ }) ); 
3. And const items = this._state_.items;

Thank you so much!
