### ISSUE TITLE
Docs: Performance: hash links do not work

### ISSUE THREAD

**Issue by OliverJAsh** [reactjs/redux#2868]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
Hash links do not work

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
1. Go to https://redux.js.org/faq/performance
2. Visit a hash link in table of contents

**What is the expected behavior?**
Hash links should work

The hash links *do* work when viewed in GitHub: https://github.com/reactjs/redux/blob/721a5fab87071b336a2106a28a9165da3e630175/docs/faq/Performance.md

I would raise a PR to fix this but I'm not sure what the solution is. Why do they work in GitHub but not on the site?

**Comment by timdorr** [comment]
We're tracking this in #2846. Thanks for the report!
