### ISSUE TITLE
bindActionCreators should not attempt to dispatch "null" or "undefined" if/when an action creator returns it

### ISSUE THREAD

**Issue by Sushisource** [reactjs/redux#2870]
**What is the current behavior?**
If I define an action creator which returns null (a reasonable case where you might want to return null being a keypress handler that only handles certain keys), currently the bound version of it loyally dispatches null, this generally then later causes problems in middleware, etc.

Here's an example showing the important part - the `FieldsSections` react component just dumbly renders some stuff, and attaches the handleKeyPress listener to the document.
```typescript
export const FieldsSectionsContainer: React.ComponentClass =
  ReactRedux.connect(null, mapDispatchToProps)(FieldsSections);

export interface FieldsSectionsDispatchProps {
  readonly handleKeyPress: (e: KeyboardEvent) => UiAction | null;
}

function mapDispatchToProps(dispatch: Redux.Dispatch<AppAction>): FieldsSectionsDispatchProps {
  return bindActionCreators({ handleKeyPress: fieldsKeyPress }, dispatch);
}

function fieldsKeyPress(e: KeyboardEvent): UiAction | null {
  switch (e.key) {
    case 'ArrowUp':
      return fieldNavAction('Up');
    case 'ArrowDown':
      return fieldNavAction('Down');
    case 'ArrowLeft':
      return fieldNavAction('Left');
    case 'ArrowRight':
      return fieldNavAction('Right');
    default:
      return null;
  }
}
```

**What is the expected behavior?**
The null action isn't dispatched, since that would be pointless. 

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**
3.6.31 is what I'm using, haven't used older versions, but seems like it'd be a very straightforward change to this line: https://github.com/reactjs/redux/blob/87071fd4ab71acc4fdd8b3db37d2d7ff08b724a3/src/bindActionCreators.js#L3

Am happy to make a PR with the fix, if desired.

**Comment by timdorr** [comment]
That greatly expands the scope of that function's responsibility. It's just wrapping a function. The output is really the responsibility of the action creator. You cannot return null from an action creator. If you can, you need to protect against that within the action creator.

**Comment by Sushisource** [comment]
Is it really that much of a change? Wouldn't just this minor change make it work?

```js
function bindActionCreator(actionCreator, dispatch) {
  return function() {
    let res = actionCreator.apply(this, arguments);
    if (res !=null) { return dispatch(res); }
  }
}
```
I'm curious what the downside to that is, because as it stands, `bindActionCreators` can't be used for this scenario, which doesn't seem terribly uncommon. You can work around it by returning a no-op action, but that also feels less than ideal.

**Comment by markerikson** [comment]
We aren't trying to concern ourselves with what the end user is actually passing to the bound-up action creator, or what that function returns.  We're simply forwarding all those arguments through to the action creator they gave us, and calling `dispatch()` with the result.  If an action creator happens to return null, that's the end user's concern, not ours.
