### ISSUE TITLE
Where redux store state and how big is it?

### ISSUE THREAD

**Issue by hoantran-it** [reactjs/redux#2893]
I have one concern about the limitation of redux state to make it work efficiently.
- Where redux store state? Memory, web browser or somewhere?
- How big is it? I have this question because I want to store data on state when users navigate back to page that they already visited, it will load from current state first and calling rest service later to update latest content.

Thanks!

**Comment by timdorr** [comment]
It's just stored in memory, like any other JS application. It's as big as you make it. You're in control of its contents.

**Comment by markerikson** [comment]
Also see related items in [the Redux FAQ section on performance](https://redux.js.org/faq/performance).
