### ISSUE TITLE
Optimise combineReducers to avoid all reducers to be called on every action dispatched

### ISSUE THREAD

**Issue by franciscotln** [reactjs/redux#2894]
**Do you want to request a *feature* or report a *~~bug~~*?**  
This would be an optimisation for all users that define their action names as such:
`const ADD_TODO_SUCCESS = '[todo] Add todo success'` by preceding the action description with the state key name in square brackets on parenthesis `'(todo) Add todo success'`, which from what I have experienced, most user do so.

**What is the current behaviour?**
Now the combineReducers function merges all reduces in such a way that on every action dispatched, all reducers are called. Considering a big store, with say 40 keys, and suppose we have 10 actions that are dispatched within 1-2 seconds at some point, we have 400 function calls, when it could be only 10, one for each action.

**What is the expected behaviour?**
combineReducers returns a combined reducer that shortcuts the function calls if the user defines the action names by prefixing them with the store key name in parenthesis `(someStateKey)`or square brackets `[someStateKey]`

Here's an example of how to accomplish that:
```
function getStateKeyFromAction(action) {
  const actionType = (action && action.type) || '';
  const keyMatches = actionType.match(/(?:\[|\().*?([a-zA-Z]+).*?(?:\]|\))/) || [null, '']
  const key = keyMatches[1]
  return key
}
```
Inside the function combination:
```
function combination(state = {}, action) {
  // existing code here

  const stateKey = getStateKeyFromAction(action)
  if (stateKey && state.hasOwnProperty(stateKey)) {
    const reducer = finalReducers[stateKey]
    const prevSubState = state[stateKey]
    const newSubState = reducer(prevSubState, action)
    if (typeof newSubState === 'undefined') {
      const errorMessage = getUndefinedStateErrorMessage(stateKey, action)
      throw new Error(errorMessage)
    }
    return newSubState === prevSubState ? state : { ...state, [stateKey]: newSubState  }
  }

  let hasChanged = false
  const nextState = {}
  for (let i = 0; i < finalReducerKeys.length; i++) {
    // more existing code here
  }
}
```
What do you folks think about this?

**Comment by timdorr** [comment]
We've got an FAQ entry for this: https://redux.js.org/faq/performance#won't-calling-%22all-my-reducers%22-for-each-action-be-slow
