### ISSUE TITLE
Anchor tags within pages do not work

### ISSUE THREAD

**Issue by erolaliyev** [reactjs/redux#2895]
**Do you want to request a *feature* or report a *bug*?**  

Report a bug

**What is the current behavior?**

Anchor tags do not work within pages

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

![Demo of the problem](https://user-images.githubusercontent.com/23246526/37521050-96895ee0-291f-11e8-809b-55258ebaf2e8.gif)

**What is the expected behavior?**

To get to the referenced section in the page when clicked on the link

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

N/A

**Comment by timdorr** [comment]
We know. They need to be updated. If you use the links on the righthand side, those will work. We're tracking in #2846
