### ISSUE TITLE
Leave explicit file extensions in module import paths

### ISSUE THREAD

**Issue by lastmjs** [reactjs/redux#2898]
**Do you want to request a *feature* or report a *bug*?**  

Kind of both

**What is the current behavior?**

The current source code uses ES Modules without explicit file extensions. This is breaking my build process because my build process assumes anything without an extension is a `.ts` file.

**What is the expected behavior?**

I think it is more appropriate to explicitly put file extensions on import paths in the source code and the generated ES Modules distribution code. Since the source code is JavaScript, leaving out the extension has no purpose as far as I can tell. I don't believe my build system (https://github.com/lastmjs/zwitterion) is treating paths without extensions much differently than other popular build systems, by that I mean this is probably a common expected behavior outside of my use case

**Comment by lastmjs** [comment]
By the way, if the maintainers would accept it, I would be happy to do a PR to add these changes in

**Comment by lastmjs** [comment]
It looks like the bundling format used in `v4.0.0-beta.2` fixes my issues, though my opinion still stands that explicit file extensions should be used.

**Comment by timdorr** [comment]
The ECMA spec doesn't specify a file extension. In addition, most other tooling does not require this. This is based on [the Node module resolution algorithm](https://nodejs.org/api/modules.html#modules_file_modules), which will attempt to find the file with a few different possible extensions. I would mimic this behavior, as you'll run into this same issue in many other libraries.
