### ISSUE TITLE
What is PERFORM_ACTION?

### ISSUE THREAD

**Issue by LAITONEN** [reactjs/redux#2900]
**Do you want to request a *feature* or report a *bug*?**  
Neither. This is a "What is it and why it is not covered in the documentation" question.

You can see an attempt to ask this question on Stackoverflow [here](https://stackoverflow.com/questions/49436872/what-is-perform-action-action-type-inside-redux). This probably should be documented since nobody was able to give a reply and this peculiarity certainly comes from Redux itself.

**What is the current behavior?**
Inside my Redux store I recently started getting PERFORM_ACTION actions, which wrap my actual actions as follows:

    {
        type: PERFORM_ACTION,
        action: {
            type: REAL_ACTION,
            payload: 123
        }
    }

I was not able to find any answer to this pattern neither in the documentations, nor in Google. The only suggestions that Google included were just references to this type of action without any explanation of what is it and why does it appear in applications.

**Question:** 
So, what is this action?

**Comment by timdorr** [comment]
This is from [redux-devtools](https://github.com/zalmoxisus/redux-devtools-instrument/blob/master/src/instrument.js#L41), not the core of Redux.
