### ISSUE TITLE
[Proposal] Provide extraArgument for middlewares

### ISSUE THREAD

**Issue by miraage** [reactjs/redux#2904]
Hello,

Many of us know about `redux-thunk` package. It has [thunk.withExtraArgument](https://github.com/gaearon/redux-thunk/tree/v2.2.0#injecting-a-custom-argument) method which may provide smth like container/config/whatever.

I think It would be great if we had smth similar for [middlewareAPI](https://github.com/reactjs/redux/blob/v3.7.2/src/applyMiddleware.js#L25).

To make it backwards-compatible it's possible to pass this `extraArgument` as 2nd parameter to [middlewares loop](https://github.com/reactjs/redux/blob/v3.7.2/src/applyMiddleware.js#L29).
```js
const chain = middlewares.map(middleware => middleware(middlewareAPI, extraArgument));
```

What do you think?

**Comment by markerikson** [comment]
I don't think that's anything we would want to add to the core.  If you're writing your own middleware, you can create a factory function in a way that would make such an "extra argument" accessible inside the middleware.
