### ISSUE TITLE
Providing change status to subscribers 

### ISSUE THREAD

**Issue by stat92** [reactjs/redux#2905]
Hi. We are using [Polymer 2.0](https://github.com/Polymer/polymer) with [polymer-redux](https://github.com/tur-nr/polymer-redux). 

Every polymer component [subscribes](https://github.com/tur-nr/polymer-redux/blob/master/src/index.js#L74) to store and for every dispatch it changes its own state.

It seems that store publishes for subscribers on every action dispatch even if stores state doesn't changed. Yes I think it's good info for subscribers. But we have actions that doesn't directly change the state but affects redux-saga to start some process (like fetching data). And it would be great to know what type of action was dispatched.

Proposal: What if take [hasChanged](https://github.com/reactjs/redux/blob/master/src/combineReducers.js#L177) up to [dispatch](https://github.com/reactjs/redux/blob/master/src/createStore.js#L165) function and provide it to [listeners](https://github.com/reactjs/redux/blob/master/src/createStore.js#L186).

This way we can do next:
```
store.subscribe(function (changed) {
	if (changed) {
             ....
        } else {
             ....
        }
});
```

**Comment by timdorr** [comment]
This is essentially the same thing: https://redux.js.org/faq/design-decisions#why-doesn't-redux-pass-the-state-and-action-to-subscribers

And your particular proposal isn't possible, as the `combineReducers` code doesn't have access to the subscribers to be able to pass that information along.
