### ISSUE TITLE
SCRIPT5002: Function.prototype.toString: 'this' is not a Function object in Dispatch Event

### ISSUE THREAD

**Issue by hariram1975** [reactjs/redux#2912]
```js
const store = createStore(reducer, devToolsEnhancer());
window.store = store;


render(
  <Provider store={window.opener == null ? store : window.opener.store}>
      <App />
  </Provider>,
  document.getElementById('root')
)
```

I like to send store from Opener to Popup inorder to keep single Store

This works well in Chrome unfortunately in IE11. I'm having an issue

SCRIPT5002: Function.prototype.toString: 'this' is not a Function object

This issue is happening in Dispatch->LiftAction->PeformAction->IsPlainObject.

**Comment by timdorr** [comment]
It looks like something else is going on. toString shouldn't be calling `this` unless you have some other sort of thing going on. It almost looks like its something with devtools, which isn't this repo. Our isPlainObject usage (either with lodash or the built-in one on 4.0) doesn't use `this` either.

**Comment by hariram1975** [comment]
It fails in fakeNode.dispatchEvent(evt);

**Comment by hariram1975** [comment]
![redux-issue](https://user-images.githubusercontent.com/26047377/38098703-c1c4c078-3346-11e8-9d88-83393e09a4fe.PNG)

**Comment by hariram1975** [comment]
https://github.com/hariram1975/react-redux-popup

**Comment by hariram1975** [comment]
__proto__ type property is not coming from dispatch that is the reason it is failing in IE 11. I don't why?

**Comment by hariram1975** [comment]
return {
      __proto__: null,
      type: 'ADD_TODO',
      id: 1,
      text
    }
Temp work around all returns from action add __proto__
