### ISSUE TITLE
Store Issue in Popup

### ISSUE THREAD

**Issue by hariram1975** [reactjs/redux#2914]
```js
const store = createStore(reducer, devToolsEnhancer());
window.store = store;


render(
  <Provider store={window.opener == null ? store : window.opener.store}>
      <App />
  </Provider>,
  document.getElementById('root')
)
```

I like to send store from Opener to Popup inorder to keep single Store

This works well in Chrome unfortunately in IE11. I'm having an issue

SCRIPT5002: Function.prototype.toString: 'this' is not a Function object

This issue is happening in Dispatch->PeformAction->IsPlainObject.
![redux-issue](https://user-images.githubusercontent.com/26047377/38142864-0cbc7ccc-340c-11e8-8081-efda1d41949b.PNG)

**Comment by timdorr** [comment]
Please don't open duplicate issues.
