### ISSUE TITLE
`TypeError: environment.setup` is not a function while building from the examples folder

### ISSUE THREAD

**Issue by ed42311** [reactjs/redux#2916]
**Report a *bug***  

  Whether or not this qualifies as a bug is up for debate.  The bug seems to be present in the examples but not necessarily in the higher level test suite.  I pulled the repo and took a look at the examples but running them in isolation doesn't seem to work well inside the repo.

  We rebuilt the counter example from a create-react-app just to start learning the process of working through redux.  Very simple setup.  We used a TDD approach and built our tests first.  While attempting a pivot to `sinon` we discovered a library that attaches an adaptor to enzyme based on the react version. 

**What is the current behavior?**

```
$ jest
 FAIL  src/components/Counter.spec.js
  ● Test suite failed to run

    TypeError: environment.setup is not a function

      at node_modules/jest-runner/build/run_test.js:71:23
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

Setting up things from a new `create-react-app` we bypassed the react-scripts and setup `jest` with `enzyme`.  To reproduce the error we ran jest although this behavior is also represented when using `$ react-scripts test`.  Unfortunately you can't access the overrides in react-scripts test and if you try to use setupFiles in your `package.json` and the `enzyme-react-16-adapter-setup`.

You get this error ->

```
$ react-scripts test
...
  These options in your package.json Jest configuration are not currently supported by Create React App:
    • setupFiles
...
```
so back to jest.

**What is the expected behavior?**

after setting up the  npm `enzyme-react-16-adapter-setup` ->
```
"jest": {
    "setupFiles": [
      "enzyme-react-16-adapter-setup"
    ]
  }
```
or alternately manually attaching the adapter in any test using environment.setup() :
```
import Adapter from 'enzyme-adapter-react-16'

configure({
  adapter: new Adapter()
})
```
this happens ->
```
$ jest
 PASS  src/components/Counter.spec.js
  counter component
    ✓ first button should call onIncrement (9ms)
    ✓ second button should call onDecrement (2ms)
    ✓ third button should not call onIncrement if the counter is even (1ms)
    ✓ fourth button should call onIncrement after 1 second (1006ms)

```
this is built out in this repo:  [reduxExperiment](https://github.com/Timfoxtimfox/ReduxExperimentation)

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

We are currently react 16.3 and honestly I don't know this is the first time I've used setup().

**Comment by ed42311** [comment]
Like I said, don't know if this is actually a bug as these tests are in examples, but I setup a forked repo with the fix in counter and a bit about it in the readme.  [forked adapter examples branch](https://github.com/ed42311/redux/tree/adapter).

**Comment by timdorr** [comment]
I think you may have a janked up node_modules install. Make sure you're both on npm@^5.0.0 and you've run `npm install` with the example's subdirectory. It is likely pulling deps from the root of the repo. 

Just to confirm this isn't a bug on our end, our Travis build runs all the example tests on every run: https://travis-ci.org/reactjs/redux/jobs/361009535#L2037-L2054

**Comment by ed42311** [comment]
Awesome thanks @timdorr thought it might be a simpler problem that at first glance.
