### ISSUE TITLE
All the tests fails due to missing "testEnvironment" property in Jest config

### ISSUE THREAD

**Issue by burnmaniac** [reactjs/redux#2921]
**Do you want to request a *feature* or report a *bug*?**  

Bug

**What is the current behavior?**

All tests fails. More info in the next section of the issue.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

On a fresh install of Ubuntu, I have forked the repo, run `npm install`, run `npm run build` and then 
`npm run test`. All tests failed with the error message:

`SyntaxError: Unexpected token { at _load_jsdom (node_modules/jest-environment-jsdom/build/index.js:18:19)`

**What is the expected behavior?**

All tests should pass without error messages.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

Node version: v.4.2.6
NPM version: 3.5.2
OS version: Ubuntu 16.04.4 LTS

I don't know if it worked on previous versions of Redux.

**Comment by timdorr** [comment]
You need a newer version of npm (possibly node as well). You should be using npm@5.
