### ISSUE TITLE
Redux 4.0.0-rc.1 not compiling with redux-thunk 2.2.0.

### ISSUE THREAD

**Issue by guillaumep** [reactjs/redux#2930]
**Do you want to request a *feature* or report a *bug*?**  

Bug.

**What is the current behavior?**

When compiling my project with Redux 4.0.0-rc.1 and TypeScript 2.8.1, I have the following errors:

<pre>
ERROR in [at-loader] ./node_modules/redux/index.d.ts:115:18 
    TS2428: All declarations of 'Dispatch' must have identical type parameters.

ERROR in [at-loader] ./node_modules/redux/index.d.ts:161:13 
    TS2314: Generic type 'Dispatch<A, S>' requires 2 type argument(s).

ERROR in [at-loader] ./node_modules/redux/index.d.ts:283:42 
    TS2314: Generic type 'Dispatch<A, S>' requires 2 type argument(s).

ERROR in [at-loader] ./node_modules/redux/index.d.ts:283:53 
    TS2314: Generic type 'Dispatch<A, S>' requires 2 type argument(s).

ERROR in [at-loader] ./node_modules/redux/index.d.ts:302:66 
    TS2314: Generic type 'Dispatch<A, S>' requires 2 type argument(s).

ERROR in [at-loader] ./node_modules/redux/index.d.ts:302:77 
    TS2314: Generic type 'Dispatch<A, S>' requires 2 type argument(s).

ERROR in [at-loader] ./node_modules/redux/index.d.ts:303:38 
    TS2314: Generic type 'Dispatch<A, S>' requires 2 type argument(s).

ERROR in [at-loader] ./node_modules/redux/index.d.ts:384:95 
    TS2314: Generic type 'Dispatch<A, S>' requires 2 type argument(s).

ERROR in [at-loader] ./node_modules/redux/index.d.ts:389:33 
    TS2314: Generic type 'Dispatch<A, S>' requires 2 type argument(s).

ERROR in [at-loader] ./node_modules/redux/index.d.ts:391:106 
    TS2314: Generic type 'Dispatch<A, S>' requires 2 type argument(s).

ERROR in [at-loader] ./node_modules/redux/index.d.ts:396:34 
    TS2314: Generic type 'Dispatch<A, S>' requires 2 type argument(s).
</pre>

**Comment by timdorr** [comment]
We test our types and are using 2.8.1. I noticed you're using awesome-typescript-loader. Can you try clearing out your cache and seeing if that fixes it? It almost looks like something is cached incorrectly.

**Comment by guillaumep** [comment]
I seems I may have not completely configured AT Loader as I did not configure any cache directory and as such I have no cache (there is no 'cache' or '.cache' directory in my project).

Is there something else I can check?

**Comment by timdorr** [comment]
It might be that you already have a Dispatch interface defined somewhere else. Either in another lib or in your code.

**Comment by guillaumep** [comment]
This was a good insight. The issue comes from redux-thunk. Removing it clears the errors in compiling Redux (but obviouly I can no longer compile my project).

Here are the complete errors I get from redux-thunk and redux:

```
ERROR in [at-loader] ./node_modules/redux-thunk/index.d.ts:4:47 
    TS2314: Generic type 'Dispatch<A, S>' requires 2 type argument(s).

ERROR in [at-loader] ./node_modules/redux-thunk/index.d.ts:8:20 
    TS2428: All declarations of 'Dispatch' must have identical type parameters.

ERROR in [at-loader] ./node_modules/redux/index.d.ts:115:18 
    TS2428: All declarations of 'Dispatch' must have identical type parameters.

ERROR in [at-loader] ./node_modules/redux/index.d.ts:161:13 
    TS2314: Generic type 'Dispatch<A, S>' requires 2 type argument(s).

ERROR in [at-loader] ./node_modules/redux/index.d.ts:283:42 
    TS2314: Generic type 'Dispatch<A, S>' requires 2 type argument(s).

ERROR in [at-loader] ./node_modules/redux/index.d.ts:283:53 
    TS2314: Generic type 'Dispatch<A, S>' requires 2 type argument(s).

ERROR in [at-loader] ./node_modules/redux/index.d.ts:302:66 
    TS2314: Generic type 'Dispatch<A, S>' requires 2 type argument(s).

ERROR in [at-loader] ./node_modules/redux/index.d.ts:302:77 
    TS2314: Generic type 'Dispatch<A, S>' requires 2 type argument(s).

ERROR in [at-loader] ./node_modules/redux/index.d.ts:303:38 
    TS2314: Generic type 'Dispatch<A, S>' requires 2 type argument(s).

ERROR in [at-loader] ./node_modules/redux/index.d.ts:384:95 
    TS2314: Generic type 'Dispatch<A, S>' requires 2 type argument(s).

ERROR in [at-loader] ./node_modules/redux/index.d.ts:389:33 
    TS2314: Generic type 'Dispatch<A, S>' requires 2 type argument(s).

ERROR in [at-loader] ./node_modules/redux/index.d.ts:391:106 
    TS2314: Generic type 'Dispatch<A, S>' requires 2 type argument(s).

ERROR in [at-loader] ./node_modules/redux/index.d.ts:396:34 
    TS2314: Generic type 'Dispatch<A, S>' requires 2 type argument(s).
```

I suppose this issue becomes a duplicate of #2748.

**Comment by timdorr** [comment]
Yep, it's a dupe.
