### ISSUE TITLE
What is the reason containers/App.js exist in todomvc example?

### ISSUE THREAD

**Issue by bexoss** [reactjs/redux#2945]
There are 2 App.js in todomvc example. one is in components folder, and another one is containers folder. It looks like only component's app.js needed, so even though I delete app.js in container folder I can run application with no problem. Could you explain the app.js in container folder exist for what?

**Comment by timdorr** [comment]
The code has been changed over time, so it's leftovers from a previous version. A PR to remove it would be helpful.
