### ISSUE TITLE
What's up with Gitbook?

### ISSUE THREAD

**Issue by gaearon** [reactjs/redux#2949]
I noticed Gitbook added a loading state.

<img width="1180" alt="screen shot 2018-04-19 at 6 08 05 pm" src="https://user-images.githubusercontent.com/810438/39006990-a39df2e2-43fc-11e8-970c-a16f66563f4f.png">

I think it reflects badly on Redux. This is just a static website, why does it need a loading screen? I think it will give a wrong impression that this is how Redux apps behave (even though Gitbook has nothing do with Redux).

Can we please opt out of this change? Or maybe it's time we start migrating away from Gitbook.

**Comment by gaearon** [comment]
This is also not at all how it's intended to look. 

<img width="316" alt="screen shot 2018-04-19 at 6 09 27 pm" src="https://user-images.githubusercontent.com/810438/39007067-d4a5a222-43fc-11e8-9cf7-731f70461755.png">

The website looks kinda amateur because of this.

**Comment by taffapsn** [comment]
Maybe [#2846](https://github.com/reactjs/redux/issues/2846)

**Comment by gaearon** [comment]
To be clear I'm not complaining about Gitbook per se, I understand they might have other priorities and it's a free project.

But I'm concerned that we're updating to versions that degrade the user experience and leave it like this for more than a month. The badge situation looks very funny. 

The way the title changes is reflective of the worst stereotypes that people have about single-page apps:

![](https://dzwonsemrish7.cloudfront.net/items/2l2m3Z3W3O3S3O1D0D07/Screen%20Recording%202018-04-19%20at%2006.48%20PM.gif?v=ca602f27)

I think in the future we should be more intentional about upgrades and watch out for usability issues like this. Especially given that unintentionally reflect both on React and Redux despite the site having nothing to do with them.

**Comment by gaearon** [comment]
For Jest, Prettier, and a bunch of other projects we're now using Docusaurus: https://github.com/facebook/Docusaurus.

Maybe we could look into using it for Redux too? It produces static websites with a mobile-friendly layout that renders Markdown and doesn't have those issues.

**Comment by timdorr** [comment]
@gaearon We're tracking this (GitBook problems) over in #2846.

If we want to move away from GitBook, we can discuss that in a separate issue.
