### ISSUE TITLE
Parentheses in arrow functions

### ISSUE THREAD

**Issue by tomasztomys** [reactjs/redux#2960]
**Do you want to request a *feature* or report a *bug*?**  
bug

**What is the current behavior?**
```
arg => {
  aaa;
  bbb;
  return xxx;
}
```

**What is the expected behavior?**
```
(arg) => {
  aaa;
  bbb;
  return xxx;
}
```

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**
latest (since 2 years)

I think that we should add parentheses if we have multi-line body of arrow function (especially with return statement). Like in airbnb proposes (which allowed to skip parentheses only if we have sth like a single line arrow function with 1 arg) or like in Google styleguide (always use parentheses).

**Comment by timdorr** [comment]
We use [Prettier](https://github.com/prettier/prettier) on the code base, so it decides for us.

**Comment by tomasztomys** [comment]
@timdorr Prettier's added a new option in the end of 2017, because issue about parenthesis was the most commented issue in their repos. I think that we should change conf of Prettier in our repo.
