### ISSUE TITLE
[docs] Table of Contents anchor links broken in documentation

### ISSUE THREAD

**Issue by raunofreiberg** [reactjs/redux#2966]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
Table of contents links do not work in some sections (e.g FAQ)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
1) Go to https://redux.js.org/faq/immutable-data
2) Click on any of the TOC links
3) Nothing happens.

Note: clicking on the references next to the sections themselves do work. It seems like the anchors are just broken.

E.g: the first link under the TOC in the provided link is with the anchor of `#benefits-of-immutability` although the actual section link is `#what-are-the-benefits-of-immutability`

This bug happens across multiple sections.

**What is the expected behavior?**
Table of contents anchor links working.

**Comment by timdorr** [comment]
https://github.com/reactjs/redux/issues/2846#issuecomment-383398550
