### ISSUE TITLE
Object Spread Operator state

### ISSUE THREAD

**Issue by simonmeusel** [reactjs/redux#2971]
This issue is about the following docs:

https://redux.js.org/recipes/using-object-spread-operator

> Since the object spread syntax is still a Stage 3 proposal for ECMAScript you'll need to use a transpiler such as Babel to use it in production. You should use the env preset, install babel-plugin-transform-object-rest-spread and add it individually to the plugins array in your .babelrc.

It says, the the proposal is stage 3, but it actually is stage 4 (https://github.com/tc39/proposal-object-rest-spread, https://github.com/tc39/proposals/blob/master/finished-proposals.md).

It don't know what effect this has on different transpilers (like babel or webpack), just wanted to report this 😄. It seems that you can just use it, at least it works for me out of the box with https://github.com/wmonk/create-react-app-typescript.

**Comment by timdorr** [comment]
Feel free to submit a PR to have that updated.
