### ISSUE TITLE
Error: You may not call store.getState() while the reducer is executing.  The reducer has already received the state as an argument.  Pass it down from the top reducer instead of reading it from the store.

### ISSUE THREAD

**Issue by wm20111003** [reactjs/redux#2986]
![image](https://user-images.githubusercontent.com/10558850/39954590-d70e72a0-55f4-11e8-8e6b-d6b06ca5d5c2.png)

**Comment by wm20111003** [comment]
redux upgrade to 4.0, After『navigation.goBack()』mistake

**Comment by theJian** [comment]
You might call  `goBack()` at the wrong place during the store is being updated. Your issue seems more appropriate to ask in StackOverflow.

**Comment by markerikson** [comment]
Yep, closing.

**Comment by wm20111003** [comment]
ok,Thanks

**Comment by Vigneshwaran-crypto** [comment]
@theJian  Please explain `goBack()` method is only in react navigation ? ..    
i'm using `react-native-router-flux`, Im also getting this error randomly often
