### ISSUE TITLE
Gitbook adds UTF8 characters to code snippets

### ISSUE THREAD

**Issue by BTMPL** [reactjs/redux#2987]
It looks like all code snippets generated by gitbook have some invisible characters inserted on the newlines:

![image](https://user-images.githubusercontent.com/247153/39958780-04084c32-5608-11e8-9b98-37e0d650c267.png)

The top snippet is from a raw copy of https://github.com/reactjs/redux/edit/master/docs/basics/ExampleTodoList.md, the bottom one (with hilighted additional chars) is from https://redux.js.org/basics/example-todo-list#presentational-components

This looks to happen to all newlines - at least on that page.

CC @SamyPesse

**Comment by timdorr** [comment]
Yep, closing since this isn't our bug per se.
