### ISSUE TITLE
Docs need one or more diagrams

### ISSUE THREAD

**Issue by wmertens** [reactjs/redux#653]
There is no diagram explaining the flow in Redux.

I had some success explaining it with this diagram:
![redux flow](https://cloud.githubusercontent.com/assets/54934/9560826/3de78528-4e2a-11e5-8399-946824aaaaf9.png)

I'd be happy to provide this in png or svg, with any changes you would like.

**Comment by Johnius** [comment]
Awesome! Thank you!

**Comment by edge** [comment]
I like your explanation, but the shadows and gradients feel a little gaudy. Maybe you could use solid colors instead?

/2cents

**Comment by Johnius** [comment]
What is selector?

**Comment by edge** [comment]
@Johnius It's what the Connnector uses to make the state more specific and cache the previous value.

**Comment by Johnius** [comment]
@edge It's a library?

**Comment by Johnius** [comment]
@edge It's a ```connect()``` function? I didn't remember the caching possibility of it. Or it's a library?

**Comment by edge** [comment]
@Johnius It doesn't cache by itself, but React does. It implements `shouldComponentUpdate` by using the old props and doing a shallow equality check on the new props, essentially doing a cache check.

**Comment by wmertens** [comment]
Science agrees that visuals are important: https://blog.slideshare.net/2015/08/31/the-scientific-reason-why-bullets-are-bad-for-presentations/

**Comment by svnlto** [comment]
I found this one quite helpful. no mention of selectors however.
![Redux Diagram](https://pbs.twimg.com/media/CNP3kYSWwAEVrTJ.jpg:large)

**Comment by peteruithoven** [comment]
Another diagram https://voice.kadira.io/rethinking-redux-f1e96daba60c#.9zs9rp0vf

**Comment by Sigmus** [comment]
The above diagram for convenience: 

![image](https://cloud.githubusercontent.com/assets/155508/12051126/08c9bede-aee6-11e5-9882-2eb904fea57a.png)

**Comment by thongly** [comment]
Awesome diagrams! Perhaps a flux vs redux diagram would be helpful in explaining the differences between the two as well - and how the presentation components (react) are still entirely separate. Perhaps this belongs in the early parts of the motivation docs, @gaearon

**Comment by henriquesosa** [comment]
@thongly I'm working in a draft to represent both flux and redux architecture.

**Comment by Lassi** [comment]
You can find diagrams representing Flux/Redux and other unidirectional data flow architectures [here](http://staltz.com/unidirectional-user-interface-architectures.html)

**Comment by gaearon** [comment]
Courtesy of http://makeitopen.com/tutorials/building-the-f8-app/data/:

![](http://makeitopen.com/static/images/redux_flowchart.png)

**Comment by adamdonahue** [comment]
This diagram gives the impression that only the action type is passed to the dispatcher, rather than the action. 

Adam

**Comment by wmertens** [comment]
I like the f8 one, it only has three main components but shows there is more going on.

**Comment by gaearon** [comment]
Also these are really nice (from http://slides.com/jenyaterpil/redux-from-twitter-hype-to-production#/):

### Basic Flow

![](https://s3.amazonaws.com/media-p.slid.es/uploads/364812/images/2484552/ARCH-Redux2-real.gif)

### Side Effects

![](https://s3.amazonaws.com/media-p.slid.es/uploads/364812/images/2484716/ARCH-Redux2-extended-real.gif)

### Side Effects with API Middleware

![](https://s3.amazonaws.com/media-p.slid.es/uploads/364812/images/2484790/ARCH-Redux2-extended-real-declerative.gif)

**Comment by Aweary** [comment]
@gaearon I like those, with the exception of the "Dispatcher" which AFAIK doesn't exist in Redux and kind of confuses it with Flux.

**Comment by gaearon** [comment]
Yeah, it probably should’ve been “Dispatch Function”.

**Comment by josefbetancourt** [comment]
The diagram found here would fit in perfectly in a "counter" tutorial:   http://kenev.net/2015/09/06/redux-counter-sample-diagram/

**Comment by timdorr** [comment]
Rolling up into #1785 for now. Please keep an PRs with diagrams coming!

**Comment by xgqfrms-GitHub** [comment]
A picture is much more than thousands of words!

**Comment by xgqfrms-GitHub** [comment]
@gaearon 
https://camo.githubusercontent.com/60a24c585be04a70ff409224c97c40c252cb5329/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6d656469612d702e736c69642e65732f75706c6f6164732f3336343831322f696d616765732f323438343731362f415243482d5265647578322d657874656e6465642d7265616c2e676966

## Side Effects

> Content length exceeded

this image doesn't exist any more !

**Comment by imvetri** [comment]
@gaearon could  you share which tool you have used to create that animated diagram ?

**Comment by xgqfrms-GitHub** [comment]
yeah, a picture is much more than one thousand words!

**Comment by noscripter** [comment]
![](https://img.alicdn.com/tfs/TB167I2XgMPMeJjy1XcXXXpppXa-2052-1540.png)

**Comment by markerikson** [comment]
I really like this diagram:

![](https://raw.githubusercontent.com/LarngearTech/codesheep.io/master/pages/2017-01-06-redux-architecture/redux_architecture.png)

Found in this article: http://codesheep.io/2017/01/06/redux-architecture/

**Comment by yadielar** [comment]
Here's a diagram I made inspired by the one @gaearon shared from @terpiljenya slides.

![redux-diagram__1300x1434](https://user-images.githubusercontent.com/981175/36645441-e91f11b0-1a36-11e8-92ca-b2a21d51ffc2.png)

**Comment by xgqfrms** [comment]
I'm looking forward new data-flow images...

**Comment by stg101** [comment]
> Also these are really nice (from http://slides.com/jenyaterpil/redux-from-twitter-hype-to-production#/):
> 
> ### Basic Flow
> ![](https://camo.githubusercontent.com/5aba89b6daab934631adffc1f301d17bb273268b/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6d656469612d702e736c69642e65732f75706c6f6164732f3336343831322f696d616765732f323438343535322f415243482d5265647578322d7265616c2e676966)
> 
> ### Side Effects
> ![](https://camo.githubusercontent.com/60a24c585be04a70ff409224c97c40c252cb5329/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6d656469612d702e736c69642e65732f75706c6f6164732f3336343831322f696d616765732f323438343731362f415243482d5265647578322d657874656e6465642d7265616c2e676966)
> 
> ### Side Effects with API Middleware
> ![](https://camo.githubusercontent.com/9de527b9432cc9244dc600875b46b43311918b59/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6d656469612d702e736c69642e65732f75706c6f6164732f3336343831322f696d616765732f323438343739302f415243482d5265647578322d657874656e6465642d7265616c2d6465636c657261746976652e676966)

Hello, how you have made this graphics?

**Comment by imvetri** [comment]
@gaearon I really like the animation, which tool did you use ?

**Comment by xgqfrms** [comment]
@imvetri I think MS's PowerPoint animation is enough do that!

**Comment by i-mw** [comment]
Ok.. my turn .. 
Created it off flux flow diagram..

![redux-diagram (1)](https://user-images.githubusercontent.com/10008835/80897077-8c7b7a00-8cf5-11ea-91ac-b7d7acb83d9d.jpg)

**Comment by renelink** [comment]
> @gaearon I really like the animation, which tool did you use ?

I did it in pure SVG. https://codepen.io/rene-link/pen/LYLYVVR

**Comment by markerikson** [comment]
FWIW, I did both of the new animated diagrams in the Redux tutorials using PowerPoint:

- https://redux.js.org/tutorials/essentials/part-1-overview-concepts#redux-application-data-flow
- https://redux.js.org/tutorials/essentials/part-5-async-logic#using-middleware-to-enable-async-logic

**Comment by serverless-architectureh** [comment]
> I like your diagram, but the shadows and gradients feel a little gaudy. Maybe you could use solid colors instead?
> 
> /2cents





https://reacter.space/questions/what-are-the-benefits-of-changing-the-redux-state
