### ISSUE TITLE
Add “hot reloading and time travel” recipe

### ISSUE THREAD

**Issue by gaearon** [reactjs/redux#721]
We need to add a recipe covering:

* Setting up [React Transform](https://github.com/gaearon/react-transform-boilerplate)-like configuration (Done via #690)
* Adding [`module.hot` and `replaceReducer()` calls](https://github.com/rackt/redux/blob/0e723bdbb7840092167d23f3e1d575adbd1d7e39/examples/todomvc/store/configureStore.js#L7-L13)
* Bonus: adding [Redux DevTools](https://github.com/gaearon/redux-devtools)

Anybody would like to work on this?

**Comment by aulizko** [comment]
I'll try to implement this as one ;)

**Comment by timdorr** [comment]
We should get #690 merged in then :smile:

**Comment by gaearon** [comment]
@timdorr I'd appreciate if you could review #690. I just want to make sure all examples are running correctly.

**Comment by timdorr** [comment]
Yep, I've been sick with a cold the whole weekend, so none of my grand plans got done. Will do soon!

**Comment by gaearon** [comment]
Thanks.
