### ISSUE TITLE
Examples not working in IE / Edge

### ISSUE THREAD

**Issue by FredyC** [reactjs/redux#808]
It's because of this ... https://github.com/glenjamin/webpack-hot-middleware/issues/11

Question is if including [polyfill](https://libraries.io/search?platforms=NPM&q=eventsource+polyfill) is way to go. Do people even want to run examples in these browsers? I just tried out of curiosity :)

**Comment by gaearon** [comment]
cc @glenjamin — what should we do / recommend? Given that hot reloading setup is easy to get wrong, the less parts the better, and if you could include a polyfill that would be great. That said I see you reverted the change where you included it. What do you think is a reasonable solution?

**Comment by glenjamin** [comment]
Current conclusion was that bundling a polyfill wasn't reliable, so instead we added a note a to the docs to say one is needed.

I'm happy to expand this note to be more obvious, or to include a runtime warning that points users in the right direction.

**Comment by gaearon** [comment]
Can you expand a bit on what reliability problems you experienced? Just so we better understand the issue.

**Comment by glenjamin** [comment]
https://github.com/glenjamin/webpack-hot-middleware/issues/11#issuecomment-140299353 is the most detail.

The main thinking is that as most people will never use this, it wont get enough exposure.

**Comment by gaearon** [comment]
If we include the polyfill in examples, does that shift the potential reliability issues to us?

**Comment by glenjamin** [comment]
Added a warning and released `v2.2.1`

**Comment by glenjamin** [comment]
> If we include the polyfill in examples, does that shift the potential reliability issues to us?

I'd be fine with that, it wouldn't affect me :)

The question is: do enough people develop on browsers which don't support it to be worth potentially messing up other users?

http://caniuse.com/#feat=eventsource

**Comment by gaearon** [comment]
I think there is an important use case for hot reloading on IE: tweaking output to fix IE rendering errors. It's not meant to be primary dev env, but if it doesn't work out of the box, people might assume it isn't supposed to work at all. Can we just include polyfill when we *know* it isn't available?

**Comment by glenjamin** [comment]
The polyfill itself no-ops when `EventSource` already exists, but the issue reported was because the polyfills don't work seamlessly with webpack without some config tweaks. As I don't include any webpack config in the middleware, it's difficult to avoid this - with an example or a boilerplate project you may be able to avoid this.

**Comment by gaearon** [comment]
Oh, I see. Maybe we can make a project wrapping the polyfill but tweaking it to work with Webpack, and you can depend on that instead. Thanks for explaining.

**Comment by FredyC** [comment]
So there is runtime error in webpack-hot-middleware which essentially turns off the hot reloading when EventSource isn't available. I am wondering if it's enough for this case of examples. People might want to try it and complain that hot reloading doesn't work. What about writing some general README and putting into examples folder?

**Comment by glenjamin** [comment]
More docs can't hurt.

The only thing I could do to make it more obvious would be to use `alert` instead of `console.warn` - which is probably going too far :)
